### PR TITLE
Enable custom meta description for custom pages

### LINKED ISSUE #751: Add <meta /> "description" tag
### Is this a bug report?

Yes (more of a feature request).

It was mentioned in a PR comment (https://github.com/facebook/Docusaurus/pull/745#issuecomment-396055556) that we are missing a `<meta name="description" content="" />` tag.

There are probably some other things about the `<head />` tag we could add and clean up.  Here is a good resource to review:
https://github.com/joshbuchea/HEAD

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

(Docusaurus version via `npm outdated docusaurus` or `yarn outdated docusaurus`, OS, Node, npm, yarn)

### Steps to Reproduce

1. View a site generated with docusaurus
2. Confirm there is no `<meta name="description" content="" />` tag

### Expected Behavior

1. View a site generated with docusaurus
2. Confirm there is a `<meta name="description" content="" />` tag

### Actual Behavior

N/A

### Reproducible Demo

N/A

### PR DESCRIPTION
**Pull request by endiliey**
## Motivation

1. Fixes #751
2. Enable user to set their own description (Inspired from #704)

### For Your Information
`<meta name="description" content="" /> `
Search engines show the meta description in search results mostly when the searched for phrase is contained in the description. Optimizing the meta description is a very important aspect of on-page SEO 

`<meta property="og:description" content="" />`
This is used for Open Graph description meta. Usually used by crawler of social media like Facebook / Twitter

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Changes
Previously, all custom pages description will always be `tagline` because we never pass `description` props.

https://github.com/facebook/Docusaurus/blob/18c01327a3082962165263c37b4a49d5426fbf53/lib/core/Site.js#L31

Adding custom description for your custom pages is as simple as adding description class property to your React component.

Example:
```js
class Index extends React.Component {
  // ... some code
}
Index.description = 'Endilie is an undergraduate student at Nanyang Technological University (2019). He likes to write & code in his free time';
```

## Test Plan

Facebook URL Linter
https://developers.facebook.com/tools/debug/

Before
before-og-description-fb

After
after-og-description-fb

https://totheweb.com/learning_center/tool-test-google-title-meta-description-lengths/

Before
before

After
after

### CODE REVIEW

**Comment by JoelMarcey** [comment]
Nice catch. We only had `og:description`. 

> Enable user to set their own description (Inspired from #704)

So, by default, we just use the `tagline` from `siteConfig.js` for setting th description. Do we need to document anything that says that they can override that per custom page? Or is that self-explanatory?

**Comment by endiliey** [comment]
@JoelMarcey this is only for custom pages like `index.js`, `versions.js`. Docs & Blogs had their own algorithm for description. Unless we want to add `description` header on markdown to set a custom description.

https://github.com/facebook/Docusaurus/blob/18c01327a3082962165263c37b4a49d5426fbf53/lib/core/DocsLayout.js#L43-L47

https://github.com/facebook/Docusaurus/blob/18c01327a3082962165263c37b4a49d5426fbf53/lib/core/BlogPostLayout.js#L101-L106

You can try Facebook URL Linter to crawl & check open graph description 😄

**Comment by JoelMarcey** [comment]
> Adding custom description for your custom pages is as simple as adding description class property to your React component.

I just didn't know of most people who use Docusaurus realized that they could do the above by adding the class property. 😄

**Comment by endiliey** [comment]
Oh this is actually a new feature. I should document it like https://github.com/facebook/Docusaurus/pull/712

**Comment by endiliey** [comment]
Docs updated. Feel free to modify 👍 

http://localhost:3000/docs/en/next/api-pages
updated

**Pull request merged**
