### PR TITLE
docs(v2): add FoalTS to showcase page

### PR DESCRIPTION
**Pull request by LoicPoullain**
## Motivation

The documentation of FoalTS has migrated from Gitbook to Docusaurus v2. It could be great to add it in the showcase page.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Run `yarn run start:v2` and check that the page `http://localhost:3000/showcase` is rendered properly.

## Related PRs

No docs to update.

### CODE REVIEW

**Comment by slorber** [comment]
Thanks @LoicPoullain , that looks great

can you sign the CLA please? I can't merge without it

**Comment by LoicPoullain** [comment]
Hmm, this is weird. I signed it 10-15minutes. I'll try again.

**Comment by LoicPoullain** [comment]
I've signed again. Maybe there's a lot of traffic now.

>  *If you already submitted a pull request before signing the CLA, then we will add a confirmation comment on that pull request (this might take several minutes).*

**Comment by slorber** [comment]
yes sometimes the bot takes time :) will wait and see thanks

**Pull request merged**
