### PR TITLE
feat(v2): add notifications for commands

### PR DESCRIPTION
**Pull request by taylorallen0913**
## Motivation

I found this really cool library for dealing with notifications, so I thought why not implement it here. I've implemented notifications for `start`, `swizzle`, `build`, and `deploy` so far.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

yes

## Test Plan

Start:

start

Swizzle:

swizzle

Build:

build

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by anshulrgoyal** [comment]
I find notification a bit annoying. May be adding  config to enable it might be good.

**Comment by slorber** [comment]
@taylorallen0913 tell me if you are interested to update the PR, and making this feature optional.

**Comment by taylorallen0913** [comment]
I would be willing to continue this feature, but I am not sure what config you are intending to hold this in. Where would you suggest putting the setting?

**Comment by anshulrgoyal** [comment]
> I would be willing to continue this feature, but I am not sure what config you are intending to hold this in. Where would you suggest putting the setting?

I think adding a flag to each command is a good place.
eg: `yarn build --notify`

**Comment by slorber** [comment]
I'd rather have a notification: true/false (false by default) in site config than a new cli option. People can use env variables if they want it to be dynamic anyway.

**Comment by slorber** [comment]
Hi @taylorallen0913 , I'm closing for now but if you want to do the changes I'll re-open

**Pull request closed without merging**
