### PR TITLE
chore: update @svgr/webpack to version 6

### PR DESCRIPTION
**Pull request by ludofischer**
* svgr changelog https://github.com/gregberge/svgr/releases
* SVGO 2 changelog https://github.com/svg/svgo/releases/tag/v2.0.0

## Motivation
* depend on maintained svgo version
* although svgr 6 is in alpha, it fixes a few issues
  with webpack 5 (https://github.com/gregberge/svgr/commit/1a8cc98) 
  and React (https://github.com/gregberge/svgr/commit/3700aba)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan
Existing tests since behaviour should stay the same.

## Related PRs
https://github.com/facebook/docusaurus/pull/5703

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
Thanks, fixed the webpack config breaking changes

I honestly don't know what the state of #5703 is and whether we plan to upgrade SVGR in that PR instead... I also don't know if it's good to send an Alpha version down to all the users because we put it in the init template, but overall after #5872 I think we feel a much stronger compelling force to upgrade.

**Comment by Josh-Cena** [comment]
For some reason E2E tests are failing because it's still trying to pull the old SVGR v5 ㄟ(▔,▔)ㄏ

**Comment by slorber** [comment]
What are good reasons to ship an alpha? 

What is the benefit for the Docusaurus users in particular?

**Comment by ludofischer** [comment]
> For some reason E2E tests are failing because it's still trying to pull the old SVGR v5 ㄟ(▔,▔)ㄏ
 
From what I can see,  Yarn 1 on Node.js 17 fails,  Yarn 1 on Node.js 16 fails but Yarn berry on Node.js 14 succeeds and Yarn 1 on Node.js 14 succeeds. Why do you think the cause is that it is still trying to pull SVGR 5? I do notice that if you run `yarn examples:generate', the generated examples use `@svgr/webpack: '6.0.0-alpha.4`  do end up with two different major versions of `@svg/webpack` in `yarn.lock`. They seem to use the `template` from the repository  but depend on the published Docusaurus version. If something similar happens when the integration tests run, that could explain conflicting dependencies. But I doubt the integration tests run on the published Docusaurus version, it would not make much of a test.

**Comment by slorber** [comment]
> But I doubt the integration tests run on the published Docusaurus version, it would not make much of a test.

We publish the docusaurs on a locally hosted Verdaccio npm repository, and then install the published version (not from global npm registry). 

Not sure why it happens exactly but we must figure this out for sure.

We have a `yarn test:build:website` to test that locally (requires Docker to setup Verdaccio) if you want to take a look at it

**Comment by ludofischer** [comment]
> What are good reasons to ship an alpha?
> 
> What is the benefit for the Docusaurus users in particular?

As a user myself, I prefer to depend (transitively) on an updated svgo version. As many packages that deal with parsing and XML tend to be fairly security-alert prone. Of course, most of these alerts do not apply to the usage in Docusaurus, but it is a burden to always have to explain this. From looking at the issues in the svg repository I have the impression that svgr has few breaking changes (or changes at all) planned. We can ask @gregberge if using the alpha is recommended.

**Comment by gregberge** [comment]
Yeah it is safe enough, I think I will release the final this weekend. The core is done, I just need to update docs.

**Comment by ludofischer** [comment]
> Yeah it is safe enough, I think I will release the final this weekend. The core is done, I just need to update docs.

Thanks for the heads up!

**Comment by ludofischer** [comment]
> Not sure why it happens exactly but we must figure this out for sure.
I am not sure what you mean. From the log I think the CI is 's publishing the state of the checked-out repository to the Verdaccio instance as `current-version.NEW`. For example `2.0.0-beta.9.NEW`. Then it installs the newly published version:
https://github.com/facebook/docusaurus/blob/ac1df888aef8e18795fbb90ca67dbf852c6b8b01/admin/scripts/test-release.sh#L51
> We have a `yarn test:build:website` to test that locally (requires Docker to setup Verdaccio) if you want to take a look at it

When I have tried running `yarn examples:generate` the script tried to access my SSH private keys and assumed I was the user `slorber` ;-) I don't know if I will have the time to reproduce the build pipeline on my machine.

**Comment by Josh-Cena** [comment]
> What are good reasons to ship an alpha?

There are multiple deprecation / security warnings for SVGR v5 -> SVGO v1. Also #5144. Also in the wake of #5872 we should think about using a more robust dep version.

> I think I will release the final this weekend.

Cool, then let's wait till the weekend👍 Glad we don't have to ship alpha 

> When I have tried running `yarn examples:generate` the script tried to access my SSH private keys and assumed I was the user `slorber` ;-) I don't know if I will have the time to reproduce the build pipeline on my machine.

You don't need to run `yarn examples:generate`, just the e2e test workflow which runs `admin/scripts/test-release.sh`

**Comment by Josh-Cena** [comment]
fwiw, I hand-modified the bootstrapped test-website's package.json to use `2.0.0-beta.9.NEW` instead of `2.0.0-beta.9` as passed from the init template, and svgr v6 is correctly installed. I guess it has something to do with setting the correct version...

**Comment by Josh-Cena** [comment]
Fixed. Also cleaned up the workflow a little bit

**Comment by slorber** [comment]
Thanks @Josh-Cena that makes sense

Thanks @gregberge , I think we can wait for the final release then ;)

**Comment by gregberge** [comment]
> Thanks @Josh-Cena that makes sense
> 
> Thanks @gregberge , I think we can wait for the final release then ;)

Yeah I am sorry it takes time but it will happen!

**Comment by Josh-Cena** [comment]
@gregberge Thanks! Good job with the release. I've been following https://github.com/gregberge/svgr/pull/629 as well. Happy to see v6 finally going stable

**Comment by slorber** [comment]
👍

**Pull request merged**
