### PR TITLE
fix(algolia): add insights property on Algolia Theme Config object TS definition

### PR DESCRIPTION
**Pull request by Virgil993**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation
I was working with the Docsearch integration and i noticed that the Algolia Theme Config object defined in `@docusaurus/theme-search-algolia` did not have the `insights` property that allows Docsearch to send click events to the Algolia Dashboard

## Test Plan
I added an optional attribute to the Algolia Config Object called `insights`. Because there is no strict validation on the object. This change should allow the user to add the `insights`
 option and because the props are passed to the docsearch modal it should work as intended. i already tested it on my project and even though i get an IDE error regarding the type, the events are sent to the algolia Dashboard 
 

### Test links
The link to the `insights` property as described by docsearch
https://docsearch.algolia.com/docs/docsearch-v3/#sending-events
The link to the documentation where the algolia object is defined
https://docusaurus.io/docs/search#connecting-algolia

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

### CODE REVIEW

**Comment by slorber** [comment]
Unfortunately your prettier format probably didn't use the right config 😅 all those are unexpected changes

**Comment by Virgil993** [comment]
Is there any way I can help with this Lint AutoFix workflow?

**Comment by slorber** [comment]
Thanks, I'll handle the rest 👍

**Comment by Virgil993** [comment]
Thank you, hope I could be of help

**Pull request merged**
