### PR TITLE
docs(v2): suggest Surge for quick deployment

### PR DESCRIPTION
**Pull request by fakela**
## Motivation
My motivation was to include how Surge can also be used to deploy docusaurus project in a matter of minutes.
 I thought it would be a good idea to have Docusaurus users take advantage of this, so I added it to the docs.
**Steps:**
`npx @docusaurus/init@next init my-website classic`
`surge build/`
**if you have a domain name**
`surge build/ yourdomain.com`

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan
usage described in the section above. pretty easy. Also, an example of a docusaurus app deployed using surge 
(http://panicky-observation.surge.sh/)

### CODE REVIEW

**Comment by fakela** [comment]
This is a much cleaner PR _without some confusing changes_ .  I made edits to the docs and also focused on the changes you requested

**Comment by fakela** [comment]
@lex111 I would love to know why if you don't mind, maybe something is wrong with the way I wrote it that needs to be corrected, would love to get your feedback.

**Comment by lex111** [comment]
@fakela because only fixes should be made to versioned docs, not a new info.

**Comment by fakela** [comment]
Thanks @lex111 for explaining why I have removed the fixes from the versioned docs and only left it in website/docs/deployment.md

**Comment by slorber** [comment]
FYI, we are going to clean up our existing Docusaurus docs deployment page in favor of a GitHub discussions category. 

This means your platform won't appear anymore on this page: https://docusaurus.io/docs/deployment

If you want your hosting / CI / CDN platform to remain documented for Docusaurus users, please submit an entry at: https://github.com/facebook/docusaurus/discussions/categories/deployment-platforms

This will be your responsibility to keep it up to date over time.

**Pull request merged**
