### PR TITLE
fix(v2): scripts should allow unknown values

### PR DESCRIPTION
**Pull request by slorber**
## Motivation

See https://github.com/facebook/docusaurus/issues/3378

It should be possible to apply data attributes to the scripts tags

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Tests

### CODE REVIEW

**Comment by alexfornuto** [comment]
Hi friends. I came across this PR for the same reason as the original issue. Should the documentation be updated so users know what additional attributes they can pass to scripts in `docusaurus.config.js`?

**Comment by slorber** [comment]
yes if it's missing you can add it in our doc, just send a pr

**Comment by alexfornuto** [comment]
I would, if I felt I understood it well enough to properly document it.

**Comment by Josh-Cena** [comment]
No worries, I can do it. Thanks for bringing this up!

**Comment by Josh-Cena** [comment]
@alexfornuto Included as part of https://github.com/facebook/docusaurus/pull/7519

**Pull request merged**
