### PR TITLE
Move Docusaurus 1 files into directory

### PR DESCRIPTION
**Pull request by yangshun**
## Motivation

Better separation of projects.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

1. Run site locally and navigate around.
1. Build site locally and load using local webserver.
1. `yarn lint` and `yarn prettier` commands pass.
1. Test via CI.

## Related PRs

NA

## Next Steps

- Fix Netlify preview path
- Set up CI for v2

### CODE REVIEW

**Comment by yangshun** [comment]
@endiliey I have fixed the tests. See if they're ok. 

I found the OC message spammy and I thought it was a bad idea to make users download an entire project just to show one message. I could add it back 🤣

**Comment by endiliey** [comment]
Haha, I think we can remove it since it downloads an entire package for that.

Maybe we can be evil 😈 in the future and modify the Docusaurus CLI message such that it will show the Open Collective message and only stop if your email is registered as contributor. 🔥 🔥🔥🔥🔥🔥🔥🔥

**Comment by endiliey** [comment]
Feel free to merge whenever you're ready

**Comment by yangshun** [comment]
Thanks, please help to test it if possible 😄

**Comment by endiliey** [comment]
Sure. Now I'm more concerned on how we are going to manage different version in one repo. 
I know how to manage multiple packages in monorepo, but not multiple versions (same package) in repo 😭 

Kinda unsure on how we manage PR going forward as well. I'm assuming we are continuing v1 and v2 work in parallel ?

**Comment by endiliey** [comment]
Upon investigation:

We should not delete this, 
Since this is what triggers husky
```
// package.json
"precommit": "lint-staged"
```

Then there is no `lint` command in root directory `package.json`
```
`"linters": {
      "{v1,v2}/**/*.js": ["yarn lint --fix", "yarn prettier", "git add"]
    }
```

**Comment by yangshun** [comment]
My bad, the removal wasn't intentional. Will add it back.

**Pull request merged**
