### PR TITLE
fix(v2): update pageviews for Google Tag Manager

### LINKED ISSUE #3047: Google Tag Manager - Doesn't recognize blog page change
### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Setting up a blog only website (Mentioned here: https://v2.docusaurus.io/docs/blog#blog-only-mode)
2. Adding google tag manager
``` 
gtag: {
      trackingID: 'GTM-OOOOOO',
      // Optional fields.
      anonymizeIP: true, // Should IPs be anonymized?
    },
```
3. It only logs the first page of the landing when the tag manager is loaded. After that if I nevigate to other blog posts or back to the home page, no page views are being tracked in the Google Analytics with Google Tag Manager.

## Expected behavior

It should track all the pages being visited, not only the one on which the page was initially loaded. 

## Actual Behavior

It only tracks the first page's URL. 

## Your Environment

- Docusaurus version used: v2.0.0-alpha.58
- Environment name and version (e.g. Chrome 83.0.4103.116, Node.js v14.5.0):
- Operating system and version (desktop or mobile): Desktop

## Reproducible Demo

Will not be able to share the google analytics account details and a hosted website here. If you really want, I would setup on sample repo and share the screenshot or screen recording.

### PR DESCRIPTION
**Pull request by govardhan-srinivas**
Closes #3047 

## Motivation

Was following Facebook open-source immersion program, recently did my PR to the [Material UI](https://github.com/mui-org/material-ui) repo, So thought to give a try.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Followed the [Google Analytics document](https://developers.google.com/analytics/devguides/collection/gtagjs/pages) while implementing pageviews.

Demo site with this change: https://govardhan-srinivas.github.io/docusaurus-blog-mode/
Screenshot of pageviews in google analytics
image

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by govardhan-srinivas** [comment]
While I was debugging few minutes back I found out that adding the parameter '**send_page_view**' to existing config would also send page views to Google analytics.
Here I have created a [gist](https://gist.github.com/govardhan-srinivas/642651a46bba36dee0e11696b2a5ba4a#file-gtag-js-L28) for it.

@slorber @yangshun Please let me know how we should proceed?

**Comment by slorber** [comment]
@govardhan-srinivas I don't know gtag unfortunately and don't even have an account.

What do you feel is the right solution, and have you actually tested it live on a real Docusaurus site and GTM account to ensure it works?

Also if you hesitate between solutions, please help me help you by linking to the relevant parts of the docs

**Comment by govardhan-srinivas** [comment]
@slorber I was refering this [link](https://developers.google.com/analytics/devguides/collection/gtagjs/pages#manual_pageviews), I find 2 ways of capturing pageviews:
1. Automatically captured with this [snippet](https://gist.github.com/govardhan-srinivas/642651a46bba36dee0e11696b2a5ba4a#file-gtag-js-L28)
2. Manually capture it when there is a location change[Existing implementation in the pull request].

Both does the same functionality but I feel second one has more advantage over the first, As we can set manual break points when to trigger the page view event. 
Eg: when we have SPA and infinite scrolling content[like facebook posts], then we can add manual trigger event considering each section as a virtual page within.

If we agree on above thing, we can merge this PR.

**Comment by slorber** [comment]
Thanks, this solution looks fine

**Pull request merged**
