### PR TITLE
Fix margin for right-aligned images

### PR DESCRIPTION
**Pull request by rickhanlonii**
## Motivation

@cyan33 found this bug and submitted it to the Jest repo, I thought I'd put in a quick fix

Closes https://github.com/facebook/jest/issues/5299
Closes https://github.com/facebook/Docusaurus/issues/397

## Test Plan
Tested using the `website/` within this project

Before: 

After:

### CODE REVIEW

**Comment by rickhanlonii** [comment]
Sorry @cyan33, just saw https://github.com/facebook/Docusaurus/issues/397, didn't mean to step on your toes

**Comment by cyan33** [comment]
@rickhanlonii It's alright! Happy to see this get fixed! 😄

**Comment by cyan33** [comment]
On second thought tho, I think it's better to separate the `imageAlignSide` into `imageAlignLeft` and `imageAlignRight`. Because it seems that only adding an `imageAlignRight` makes the logic across those two components somewhat duplicated and not that intuitive.

**Comment by rickhanlonii** [comment]
I had the same thought, I'll update

**Comment by rickhanlonii** [comment]
Updated, that's much cleaner thanks @cyan33

**Comment by JoelMarcey** [comment]
@rickhanlonii Thank you so much for taking the time to fix this. Looks good to me.

And thanks @cyan33 for raising the issue too.

**Comment by cyan33** [comment]
@JoelMarcey No problem! 😄

**Pull request merged**
