### PR TITLE
misc: check doc page by Lighthouse CI

### PR DESCRIPTION
**Pull request by lex111**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Since the doc page represents the main functionality of Docusaurus, Lighthouse should check it instead of the landing page. For example, the a11y error with the home page in the breadcrumbs could have been detected earlier.

### CODE REVIEW

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
Can we check both?

The landing page's performance is still important, like FCP

**Comment by Josh-Cena** [comment]
Why does it always only check one URL😢 When you check the actions log for https://github.com/facebook/docusaurus/pull/7300/commits/3a5d4d43e435d9dcfa11d798eb6af99e7e993515 and https://github.com/facebook/docusaurus/pull/7300/commits/ea22edd6f032f3740bfd9ee39cbbdb2dc78bc87d, they seem to still stick with the old config

**Comment by lex111** [comment]
Perhaps need to merge this change so that the config for CI is updated?

**Comment by Josh-Cena** [comment]
Theoretically, the action should be using the config on this branch, especially since this is not in a fork. At least that's how I tested my config changes. My main worry is how audits on multiple URLs will be formatted, so I'd need to see at least what the output looks like.

**Comment by Josh-Cena** [comment]
@lex111 From our `actions/github-script`, we only take the first check's manifest and post it as comment. Can you add the second one's as well? We can simply add another column to the table.

**Comment by lex111** [comment]
I don't quite understand you, it will be for each of the checked pages by a separate table?

**Comment by Josh-Cena** [comment]
I'm suggesting it to be

```md
| Category | Landing page score | Doc page score |
| --- | --- | --- |
| Performance | 🟠 57 | 🟠 57 |
| Accessibility | 🟢 100 | 🟢 100 |
| Best practices | 🟢 92 | 🟢 92 |
| SEO | 🟢 100 | 🟢 100 |
| PWA | 🟢 90 | 🟢 90 |
```

So instead of using `[0]` index, we just use a `map` instead.

**Comment by lex111** [comment]
I have another idea how visualize data that should work, but it is problematic to test these changes.

**Comment by Josh-Cena** [comment]
Yeah, I can understand. Do you want to merge this so we can test it?

**Comment by lex111** [comment]
Yes, let's check it out in action.

**Pull request merged**
