### PR TITLE
💅 hover - selected effect for the doc links in the sidebar

### PR DESCRIPTION
**Pull request by albinotonnina**
## Motivation

I would add some basic transitions for the rollover and the active state of a doc in the sidebar.
### Before
hover1

### After
hover3

## Test Plan

No tests 😳

### CODE REVIEW

**Comment by neilsutcliffe** [comment]
Why does it go to the left rather than the right?

**Comment by albinotonnina** [comment]
@neilsutcliffe to mimic a sort of magnifying effect on hover, looked better to me :)

**Comment by JoelMarcey** [comment]
@albinotonnina Thank you for this pull request.

1. Will you please sign the CLA so that we can review and possibly merge it? https://code.facebook.com/cla

2. I wonder if this would be best enabled by a flag in `siteConfig.js`? You can turn off or on those animations. I need to think about that.

**Comment by albinotonnina** [comment]
Hi @JoelMarcey, I did sign the CLA yesterday :)  Since you mention the config file, I would then go a step further in a future PR and implement some more transitions, what do you think? I’d like to share them with you anyway

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by neilsutcliffe** [comment]
@albinotonnina 

If you fancy being super ambitious, do you want to be the creator/contributor to the very first theme for Docusaurus?

There is an issue #77, which is more than this pull request is at the moment, but there is no point adding custom theme support if we have no themes :)

I've been thinking of adding theming support, and have a few ideas of how it would work. What would make this a theme is.

- A cool dinosuar related name
- Custom colours
- Custom animations for all elements
- A cohesive design vision

**Comment by albinotonnina** [comment]
That's what I would love to do @neilsutcliffe. I found Docusaurus a little restrictive at the moment in terms of theming/style authoring. Superb in terms of intentions though.
Consider me onboard, I will now quantify/qualify the effort and come back to you with proposals.

**Comment by JoelMarcey** [comment]
@albinotonnina Hi. I am getting back to reviewing some pull requests now. Sorry for the delay.

Btw, if you want to join our Discord for Docusuarus chat, we are at https://discord.gg/docusaurus.

You and @neilsutcliffe can head into the #docusaurus-dev channel to discuss theming.

**Comment by yangshun** [comment]
@albinotonnina They look great, but this is probably not something that all Docusaurus users would want. It would be preferable if users had the choice to opt-in this behavior instead. Alternatively, users can also add this behavior via overriding the CSS. As discussed in the thread, this would be better as a theme/plugin which you have opened in #422.

Closing this for now so that we can shift the discussion there.

**Pull request closed without merging**
