### PR TITLE
docs(v2): Added drone.io publish docs #3491

### PR DESCRIPTION
**Pull request by aakhtar3**
## Motivation

Added support for drone.io

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

**Comment by aakhtar3** [comment]
CLA has been signed

**Comment by slorber** [comment]
Thanks. CLA bot takes time sometimes ;)

@aakhtar3 you modified the docs of v1, not v2 (https://github.com/facebook/docusaurus/edit/master/website/docs/deployment.md). It seems like your intention was to modify v2 doc, as it's the most "future-proof" version.

**Comment by aakhtar3** [comment]
@slorber Made the change

**Comment by slorber** [comment]
That seems not exactly what you want right? Looks like your instructions are related to GH pages, not Netlify

https://deploy-preview-3492--docusaurus-2.netlify.app/classic/docs/deployment/#deploying-to-netlify

image

**Comment by aakhtar3** [comment]
@slorber Its moved up under the GH pages
https://deploy-preview-3492--docusaurus-2.netlify.app/classic/docs/deployment/#using-drone

**Comment by slorber** [comment]
LGTM thanks :)

**Comment by aakhtar3** [comment]
@slorber Where could I make this change for v1?

**Pull request merged**
