### PR TITLE
Added support for Codesandbox

### PR DESCRIPTION
**Pull request by sammychinedu2ky**
## Motivation

I saw an issue on adding Codesandbox config for Docusaurus which would enable the creation of Codesandbox templates for Docusaurus.
So I decided to work on that.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

**Comment by slorber** [comment]
Hi @sammychinedu2ky 

That looks nice, but can you help me figure out how to test your code to be sure it's correct to be merged? (assuming I don't know much about CodeSandbox?)

**Comment by sammychinedu2ky** [comment]
Code Sandbox is a popular code editor that lets people spin up a vscode-like editor on their browser.
The link for code sandbox can be found here: https://codesandbox.io/
So since this pull request hasn't been merged. I created a template on codesandbox using my forked version: https://github.com/sammychinedu2ky/docusaurus.
The template can be seen here: https://codesandbox.io/s/github/sammychinedu2ky/docusaurus-test/tree/master/
With this template, a user can easily fork it and create a document on the fly in a seamless manner on codesandbox

**Comment by sammychinedu2ky** [comment]
I have an issue using this. I'm sorry about that. 
Codesandbox doesn't allow more than 500 modules in a sandbox.
But funny enough it allows me to make use of the cli tool to create a template. 
The issue I face with this is that making a template update won't be automatic

**Comment by sammychinedu2ky** [comment]
Is it okay for me to add a GitHub workflow that creates a template folder for any merge or commit made to the repo
With this integration I would be able to add an automatic support for codesandbox to read a template from the generated template folder in the Docusaurus repo
So I want to know if that is okay to add.

**Comment by slorber** [comment]
As explained on Discord, you should:
- create a yarn script `examples:generate` to init all the available templates and create those folders: `./examples/classic`, `./examples/bootstrap`, `./examples/facebook`
- commit these folders
- add `examples/*` in yarn workspace folders (in root package.json)
- add the codesandbox config in `./examples/classic`
- see if you can import the repo on CodeSandbox
- add `./examples/classic` on Netlify deploy previews for easy review

We'll figure out later how to automate the process so that `examples:generate` is run automatically, but for now, the goal is to have something working on CodeSandbox

**Comment by sammychinedu2ky** [comment]
Ok thanks .. would work on that

**Pull request closed without merging**
