### PR TITLE
Fix(theme classic) sidebar layout and announcement bar fixed height

### LINKED ISSUE #8789: announcementBar height and sidebar conflicts.
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io.
- [x] I have read the console error message carefully (if applicable).

### Description

AnnouncementBar has fixed height which cuts content inside itself.

I guess they kept the height fixed so that it'll not mess up sidebar bottom which heavily depends on fixed annoucementBar height with it's `margin-bottom: var(--docusaurus-announcement-bar-height)` property. 

### Reproducible demo

_No response_

### Steps to reproduce

1. Open browser and visit Docusarus official website.
2. Inspect the page and set `--docusaurus-announcement-bar-height` to `auto`
3. Check bottom of sidebar with full content inside.

### Expected behavior

Shouldn't be fixed height or at least must respect content inside itself.

### Actual behavior

Stays 30px no matter how much content it has.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [X] I'd be willing to fix this bug myself.

### PR DESCRIPTION
**Pull request by azeek21**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

* [This issue](https://github.com/facebook/docusaurus/issues/7815)
* [This unfinished PR](https://github.com/facebook/docusaurus/pull/8493)
* [This issue from Auth.js](https://github.com/nextauthjs/next-auth/issues/6934)
* [This hardcoded fix which I am not really a fan of](https://github.com/nextauthjs/next-auth/pull/6975)

## Test Plan
No yet.

### Test links

[deploy-preview-8790--docusaurus-2.netlify.app/docs/sidebar/items](https://deploy-preview-8790--docusaurus-2.netlify.app/docs/sidebar/items)

[deploy-preview-8790--docusaurus-2.netlify.app/tests/docs/toc/toc-_-5](https://deploy-preview-8790--docusaurus-2.netlify.app/tests/docs/toc/toc-_-5/)

## Related issues/PRs #8493 #8789 
Should fix #8789

### CODE REVIEW

**Comment by azeek21** [comment]
this should end #8567 and all other issue/pr related to this, if my solution is acceptable of course.

**Comment by azeek21** [comment]
@Josh-Cena , I am sorry for bothering. Is it ok if I ask for some feedback on this PR. I would love to work on improving this if needed. Anything can help, thanks. :)

**Comment by slorber** [comment]
Does not work as it's supposed to, and the implementation looks hacky to me (do we want. a 400ms magic delay value?)


[deploy-preview-8790--docusaurus-2.netlify.app/docs/sidebar/items](https://deploy-preview-8790--docusaurus-2.netlify.app/docs/sidebar/items)

[deploy-preview-8790--docusaurus-2.netlify.app/tests/docs/toc/toc-_-5](https://deploy-preview-8790--docusaurus-2.netlify.app/tests/docs/toc/toc-_-5/)

CleanShot 2023-04-07 at 11 36 08@2x

CleanShot 2023-04-07 at 11 38 21@2x

**Comment by slorber** [comment]
Thanks for giving it a try.

For now I'm going to close all the pending PRs trying to solve this issue, see https://github.com/facebook/docusaurus/issues/8370

**Pull request closed without merging**
