### PR TITLE
chore(plugin-docs): expose all lib files through exports

### LINKED ISSUE #7961: Making getSlug available from outside of the packages
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

We are trying to generate slugs / paths inside a remark plugin and wanted to rely on the way how docusaurus are doing these. We came across this function: https://github.com/facebook/docusaurus/blob/bf1513a3e357025ab1cf4cdb4c09f21316b31cfd/packages/docusaurus-plugin-content-docs/src/slug.ts#L24-L31

Which seems to generate the correct slugs and paths based on the input. The thing is that this function is not exported in the package.json: https://github.com/facebook/docusaurus/blob/bf1513a3e357025ab1cf4cdb4c09f21316b31cfd/packages/docusaurus-plugin-content-docs/package.json#L7-L12

Would it be alright to also add the entire lib in the `package.json` to get access to internal (e.g. adding `"./lib/*": "./lib/*", ` to the `package.json`? Or move `getSlug` to `@docusaurus/utils`? 

### Self-service

- [X] I'd be willing to do some initial work on this proposal myself.

### PR DESCRIPTION
**Pull request by JPeer264**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [x] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #7961) and the maintainers have approved on my working plan.

## Related issues/PRs

I hope that is OK that I deleted half of the template, as it would mostly duplicate #7961. 

---

@Josh-Cena This would be out of scope of this PR, but I noticed that there are `exports` in `theme-common` and `theme-search-algolia` as well, to make it consistent should we add this line there as well?

### CODE REVIEW

**Comment by Josh-Cena** [comment]
> but I noticed that there are `exports` in `theme-common` and `theme-search-algolia` as well, to make it consistent should we add this line there as well?

Everything in `theme-common` is already exported—same as `theme-search-algolia`.

**Review by Josh-Cena — APPROVED** [review]
Thanks!

**Comment by JPeer264** [comment]
@Josh-Cena general question. Is there some general release plan or roadmap when new releases are coming out? Or is this just based on specific new features?

**Comment by slorber** [comment]
We wrote about our release process here:
- https://docusaurus.io/community/release-process
- https://docusaurus.io/blog/2022/08/01/announcing-docusaurus-2.0

If you have any question after reading that, please submit and we'll improve our release process doc

**Comment by JPeer264** [comment]
@slorber thanks for these links they helped a lot. Also recently `docusaurus@2.1.0` has been deployed, but it seems that these changes were not part of the retro compatible commits. I was just wondering if there is a reason if this is not backwards compatible or not. Would it be possible by any chance to add this to some release? For now we use the nightly builds, which work fine, but still for me it feels a bit unsafe to use them in the long(er) run. Sorry for bringing this little thing up again.

**Comment by slorber** [comment]
@JPeer264 added the tag to backport for next stable release ;)

**Pull request merged**
