### PR TITLE
refactor: add missing translations in fa.json

### PR DESCRIPTION
**Pull request by farshidinanloo**
fix Persian translation

## Motivation

there is repetitive word in translation:

the correct one is like this:
image

### CODE REVIEW

**Review by lex111 — COMMENTED** [review]
@farshidinanloo do you have a desire to provide a missing translation for other messages in this file? Maybe you could do that in this PR?

**Comment by slorber** [comment]
@massoudmaboudi can you help review this change?

**Comment by farshidinanloo** [comment]
@lex111 @massoudmaboudi 
I try to add other translations and there is an issue the date it shows is wrong it's about 3 years before the current date.

**Comment by slorber** [comment]
Thanks 👍 

Please take a look at this other PR, suggesting to use slightly different fa translations: https://github.com/facebook/docusaurus/pull/5434

**Comment by slorber** [comment]
About the calendars, thanks, I was able to figure out the problem and opened a dedicated issue: https://github.com/facebook/docusaurus/issues/5440

**Comment by massoudmaboudi** [comment]
@slorber 
Sorry for the late reply. 
Yes, the changes are correct and you can merge them.

**Pull request merged**
