### PR TITLE
fix(core): forward ref to Link's anchor element

### PR DESCRIPTION
**Pull request by koistya**
## Motivation

Make it possible to use `Link` component with 3rd party libraries that rely on forwarding `ref` when using it as the base:

```jsx
<Button component={Link} href="/me">Click me!</Button>
```

At the very least, it will be possible to call `ref.current.focus()` from under the parent component using `Link` as the base. This also eliminates console errors in the browser when using `Link` with 3rd party libraries as in the example above.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

**Comment by slorber** [comment]
> Make it possible to use `Link` component with 3rd party libraries that rely on forwarding `ref` when using it as the base:
> 
> ```js
> <Button component={Link} href="/me">Click me!</Button>
> ```

Not against this change, but I don't understand the use case and this example. 

Why does this Button need a ref to the link exactly and what is the button implementation?

How, as a reviewer, can I see that this feature works as intended? Unless you want to write tests, we have a `_dogfood` folder where you can at least provide an example page where both internal/external links are used with a ref.

**Comment by koistya** [comment]
> Not against this change, but I don't understand the use case and this example.
> Why does this Button need a ref to the link exactly and what is the button implementation?

@slorber at the very list being able to call `ref.current.focus()` from under the parent component. Otherwise, you get console errors when trying to use `Link` as the base with 3rd party components (and they may not function fully as expected).

This is a commonly used pattern, no breaking changes. Take a look into `NavLink` from `react-router-dom` as an example.

**Review by Josh-Cena — COMMENTED** [review]
I see the point of this change, but would be cool if we can have some dogfooding examples on our website, like a `ref.current.focus()` as you mentioned

**Review by lex111 — APPROVED** [review]

**Review by Josh-Cena — APPROVED** [review]
Tested, can confirm that it works now and not before

**Pull request merged**
