### PR TITLE
docs(v2): showcase user questdb

### PR DESCRIPTION
**Pull request by mpsq**
## Motivation

Hello,

We develop an open-source time-series database called QuestDB. We built our first website using Docusaurus v1 and we fully migrated to v2 (with brand new designs :lipstick:) recently. We simply love it, great ecosystem, nice community, it brings everything we need and the flexibility of v2 is awesome!

Thanks to all the people involved for your hard work.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

I ran the tests + viewed changes locally + verified that links work.

## Related PRs

N/A

### CODE REVIEW

**Comment by yangshun** [comment]
Please sign the CLA before we can merge this :)

**Comment by mpsq** [comment]
Thanks @yangshun!
I already signed the CLA, it does not seem to update the PR tough. Do you think I did something wrong or the bot simply takes time?

**Comment by mpsq** [comment]
Thanks @yangshun!
I already signed the CLA, it does not seem to update the PR tough. Do you think I did something wrong or the bot simply takes time?

2020-07-30-121120_grim

**Comment by yangshun** [comment]
It just takes time. I'll merge this when the bot updates the PR. Thanks again for the wonderful addition!

**Pull request merged**
