### PR TITLE
feat(v2): bootstrap layout navbar

### PR DESCRIPTION
**Pull request by fanny**
## Motivation

Add the nav component for boostrap theme

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

yep

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)
[Imgur](https://i.imgur.com/qIGZjZ7.mp4)
go to home page

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by fanny** [comment]
Agreed. Is any problem add an external react library, for example they use [`react-transition-group`](https://reactcommunity.org/react-transition-group/transition) for collapse? Is ok to add?

**Comment by yangshun** [comment]
We allow it if it makes sense. Actually maybe you can consider using reactstrap in the theme directly, that way you might not even need to use Bootstrap's CSS classes.

**Comment by fanny** [comment]
I didn't starting using the [react-bootstrap] (https://github.com/react-bootstrap/react-bootstrap) or [reactstrap] (https://github.com/reactstrap/reactstrap/blob/master/ src / Collapse.js), because I saw that docusaurus usually use your own solutions, and because we always have a trade-off using an external library, since it can stop to provide the support for example, and we can suffer. I know that replicate the logic used for these libraries can be a little complicated, but I'm insegure if is a good idea start to apply the components from these libraries.

**Comment by fanny** [comment]
I changed to Reactstrap, I'll change the old ones soon

**Pull request merged**
