### PR TITLE
docs: add Massoud Maboudi's portfolio to showcase

### PR DESCRIPTION
**Pull request by massoudmaboudi**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Another RTL website from @massoudmaboudi 😁

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

### CODE REVIEW

**Comment by massoudmaboudi** [comment]
> This is a very, very awesome website! However it leaves me very ambivalent, because while it's highly designed, it doesn't showcase much docs feature of Docusaurus😟 I'm open to add it to the favorites, but I'm afraid it doesn't represent a typical use-case... Do you have plans to add more docs-related pages to this site in the future?

Thanks, man,
Yes, the blog is on the way. not this week but very soon.

**Comment by Josh-Cena** [comment]
Good to know! 👍 Looking forward to it, then

**Comment by massoudmaboudi** [comment]
> Good to know! 👍 Looking forward to it, then

Sure things.
I am not sure about docs section though as its a portfolio website but a different design of blog can help to make it glow.

**Comment by massoudmaboudi** [comment]
> Ye I'll be equally happy if it ends up a personal blog! We've never had a personal blog in the favorites, so it's always meaningful to add one

Yes, working on https://iammassoud.ir and my other website which is https://datagit.ir already added to the favorite before.

btw, check a preview of my new design for https://datagit.ir as below:
https://pythonbeginnercourse--datagit-preview.netlify.app/

**Comment by massoudmaboudi** [comment]
Hi @Josh-Cena 
I didn't understand why the PR is closed

**Comment by Josh-Cena** [comment]
@massoudmaboudi Did you accidentally delete your branch?

**Comment by massoudmaboudi** [comment]
my fork was on the time the main branch name was master.
Seems my fork is updated. not sure, but reapply for this change shortly. Hope my other PR is active still

**Pull request closed without merging**
