### PR TITLE
docs: add GeekyWeb to showcase

### PR DESCRIPTION
**Pull request by Designatory**
## Pre-flight checklist

- [ ] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

### CODE REVIEW

**Comment by Josh-Cena** [comment]
@Designatory Could you grant me push access? I need to make some modifications in order to merge this.

**Comment by Designatory** [comment]
> @Designatory Could you grant me push access? I need to make some modifications in order to merge this.

How to give permissions?

**Comment by Josh-Cena** [comment]
On the right sidebar, towards the bottom, there should be a "allow edits by maintainers" checkbox. Do you have it checked?

image

**Comment by Designatory** [comment]
Done Now

**Review by Josh-Cena — APPROVED** [review]
Thanks!

I like the dark mode 👍

**Comment by Designatory** [comment]
Yo! Thanks

**Pull request merged**
