### PR TITLE
Update doc2.md

### PR DESCRIPTION
**Pull request by ppatel221**
## Motivation

(Write your motivation here.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by neilsutcliffe** [comment]
Doesn't seem to be documented too well, but makes sense.

Are all markdown links relative to the root of the doc folder? There was a request to allow folders, but for now it is just a completely flat structure correct?

**Comment by ppatel221** [comment]
I've checked through the other docs and the links are relative to the root of the doc folder.

**Comment by JoelMarcey** [comment]
@ppatel221 Hi. Thanks! Can you please sign the CLA so we can merge this pull request?

**Comment by JoelMarcey** [comment]
@neilsutcliffe Yes, right now we allow the docs in any folder you want, but they have to be in a flat file structure. There is a request to allow docs in a staggered structure, but we have some considerations to take into account before doing that.

I probably could update https://docusaurus.io/docs/en/doc-markdown.html to talk about links to other docs.

**Comment by ppatel221** [comment]
I've just signed the CLA!

**Comment by JoelMarcey** [comment]
I documented inter-document referencing in https://github.com/facebook/Docusaurus/pull/394

**Pull request merged**
