### PR TITLE
refactor(v2): update tabs to follow WAI-ARIA spec

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

After some research, I realized that the current implementation of the Tabs component is not entirely correct. We should better follow the WAI-ARIA Tabs Pattern, which is described at https://www.w3.org/TR/wai-aria-practices/#tabpanel.

The main difference is that pressing on tabs list with Tab key will not switch tab, but instead move focus to the corresponding tabpanel (if necessary). This is useful if the tab content contains a focusable element like a link.

References (with automatic activation):

- https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html 
- https://reakit.io/docs/tab
- https://react-bootstrap.github.io/components/tabs/#rb-docs-content
- https://reach.tech/tabs/

In addition, I also decided to refactor the code - when rendering each tab item, we use the same functions instead of creating new ones. It seems to me to improve performance a little.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Now the link in the tab content is available for navigating from the keyboard by pressing the `Tab` button (previously there was a switch to the next tab).

| Before   | After    |
| -------- | -------- |
| ezgif com-gif-maker (14) | ezgif com-gif-maker (13) |

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by slorber** [comment]
As looks fine to me, also see this behavior on ReachUI demo.
However I don't see this behavior on Reakit page.

@Mythra do you want to give us some thoughts?

**Comment by lex111** [comment]
> However I don't see this behavior on Reakit page.

What do you have in mind? Reakit makes the tab panel **always** focusable, it seems unreasonable to me, so I did not adopt this behavior.

**Comment by slorber** [comment]
> What do you have in mind? Reakit makes the tab panel always focusable, it seems unreasonable to me, so I did not adopt this behavior.

I don't say Reakit does the right thing, just highlighting that some of your refs are doing things differently 😅 

Wouldn't we benefit from including comps like ReachUI tabs directly instead of implementing our own? As they are small and isolated that may be useful?

**Comment by Mythra** [comment]
This is definitely a good change, I didn't have any tabs on the site I was testing, but yes this is the way tabs are expected to work. 

One note I may mention is usually if a contents of the tab list are lazy which you seem to have a prop for, it's recommended a user manually hit "space", or "enter" to activate the tab as to not potentially slow down a user. A user who may be using the arrow keys to scroll, don't want them accidentally getting stuck on a tab list if there's going to be a delay.

**Comment by lex111** [comment]
Dah, you caught me :smile:,  but actually this is just a list of examples that follow the pattern noted above.

Since we already have a large JS bundle, and we are not using tree-shaking correctly, for now wise to use our own component implementations. Maybe after migrating to webpack 5 and loadable components, we should switch to using third-party UI components, but no sure about this.

**Comment by slorber** [comment]
thanks for the review

let's merge this for now

> Since we already have a large JS bundle, and we are not using tree-shaking correctly, for now wise to use our own component implementations. Maybe after migrating to webpack 5 and loadable components, we should switch to using third-party UI components, but no sure about this.

I don't think it's related, we don't need treeshaking for libs that have multiple packages like `@reachui/tabs`, as you won't import anything else from ReachUI that you don't use. Also treeshaking should work already for libs that emit ESM modules 

But yeah we can postpone that choice for now, just think that it could save us some time in the future

**Pull request merged**
