### PR TITLE
docs: correct plugin example filename

### PR DESCRIPTION
**Pull request by mxhdx**
The file name inside the my-plugin folder is index.js .

### CODE REVIEW

**Comment by Josh-Cena** [comment]
@mxhdx Please remember to sign the CLA. It's required for us to merge. PRs without CLA will be closed in two weeks.

**Comment by slorber** [comment]
@mxhdx can you sign the CLA please?

**Comment by mxhdx** [comment]
> @mxhdx can you sign the CLA please?

Done.

**Review by Josh-Cena — APPROVED** [review]
Thanks👍

**Pull request merged**
