### PR TITLE
docs(v2): Add wasp to showcase

### PR DESCRIPTION
**Pull request by matijaSos**
## Motivation

Adding a project (Wasp) that is built with Docusaurus v2.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

**Comment by slorber** [comment]
Thanks

I think you interverted Wasp and Wisdom no?

The PR is failing but it's not your fault, will fix this asap.

**Comment by slorber** [comment]
The PR issue on our side should be fixed.

However still seem to have interverted 2 sites's data, and the uploaded filename is wrong

image

**Comment by slorber** [comment]
Just updated your PR, now ready to merge

**Comment by matijaSos** [comment]
@slorber thanks a lot for fixing it! I was just about to do it and then noticed you've just done it :)

**Pull request merged**
