### PR TITLE
feat: sub-categories in sidebar.json

### LINKED ISSUE #410: sidebar.json does not allow for subcategories
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

yes

### Environment

OS: MacOS High Sierra
Node: 8.6.0
npm: 5.6.0

### Steps to Reproduce

1. Create an app following docusaurus docs
2. Try creating a subcategory using the `sidebar.json`:
```

{
  "docs": {
    "Docusaurus": ["doc1"],
    "Category 1": {
        "Subcategory": ["doc2", "doc3"]
    },
    "Category 2": ["doc4"]
   },
  "docs-other": {
    "First Category": ["doc5", "doc6"]
  }
}
```

3. Launch the website and access documentation

### Expected Behavior
I would expect to see the documentation page with a sidebar that contains subcategories.

### Actual Behavior
Site blows up with the following error:

```
Error: Improper sidebars.json file, document with id '[object Object]' not found. Make sure that documents with the ids specified in sidebars.json exist and that no ids are repeated.
    at _loop (/Users/pedro/Workspace/fsort-website/website/node_modules/docusaurus/lib/server/readCategories.js:58:17)
    at readCategories (/Users/pedro/Workspace/fsort-website/website/node_modules/docusaurus/lib/server/readCategories.js:34:53)
    at DocsSidebar.render (/Users/pedro/Workspace/fsort-website/website/node_modules/docusaurus/lib/core/DocsSidebar.js:18:26)
    at /Users/pedro/Workspace/fsort-website/website/node_modules/react-dom/lib/ReactCompositeComponent.js:793:21
    at measureLifeCyclePerf (/Users/pedro/Workspace/fsort-website/website/node_modules/react-dom/lib/ReactCompositeComponent.js:73:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Users/pedro/Workspace/fsort-website/website/node_modules/react-dom/lib/ReactCompositeComponent.js:792:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Users/pedro/Workspace/fsort-website/website/node_modules/react-dom/lib/ReactCompositeComponent.js:819:32)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/pedro/Workspace/fsort-website/website/node_modules/react-dom/lib/ReactCompositeComponent.js:359:30)
    at ReactCompositeComponentWrapper.mountComponent (/Users/pedro/Workspace/fsort-website/website/node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
    at Object.mountComponent (/Users/pedro/Workspace/fsort-website/website/node_modules/react-dom/lib/ReactReconciler.js:43:35)
```

### Reproducible Demo

Here is a link to a demo that demonstrates the issue. Simply copy, run `npm i` on the website folder and you are ready to go:

https://github.com/Fl4m3Ph03n1x/docusaurus-bug-report

### LINKED ISSUE #948: Meaningful name to represent 1000
## 💥 Proposal

Can we add a meaningful name to represent what 1000 is?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Can we add a meaningful name for what 1000 is, its not super clear why the check (i++ < 1000) is needed and also this function seems to be doing a lot of things. Would be better to split this out into multiple functions

https://github.com/facebook/Docusaurus/blob/master/lib/server/readCategories.js#L89

### PR DESCRIPTION
**Pull request by WillBrock**
## Motivation

Close #410 
Close #948 

Some users would like to be able to specify sub categories in the sidebar as discussed in #410.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Added unit tests for the functions that were modified and visually verified existing sidebars function the same as well as the new sub categories.

sub-category-sidebar

Example sidebars:

```js
{
  "docs": {
    "First Category": {
      "Sub Cat One" : ["doc2", "doc3"],
      "Sub Cat Two" : ["doc4", "doc5"]
    },
    "Second Category" : ["doc8"]
  }
}
```

```js
{
  "docs": {
    "First Category": {
     // Empty key will display no header
      "" : ["doc1"],
      "Sub Cat One" : ["doc2", "doc3"],
      "Sub Cat Two" : ["doc4", "doc5"]
    },
    "Second Category" : ["doc8"]
  }
}
```

First attempt at implementing this, let me know if some things should be changed. I changed a couple of the functions around to make them easier to write tests against. In the future we could add tests to the rest of the functions in readMetadata.js as well.

Note: We could maybe do some type of accordion for the sub categories if wanted.

### CODE REVIEW

**Comment by endiliey** [comment]
Thanks for the PR and sorry for getting back so late. This is quite a huge change so it will take a while but rest assured it is now within the radar for review.

**Comment by ricardokdz** [comment]
+1

**Comment by markerikson** [comment]
Hi.  I see the comments about "less likely to accept v1 PRs".  I'm a Redux maintainer, and we're currently investigating switching our docs site at https://redux.js.org to Docusaurus.  We've already set it up for the new React-Redux docs page at https://react-redux.js.org .

The Redux docs have multiple levels of nesting in some places.  While we're planning on restructuring the docs content itself in the near future, it would be really helpful if we could keep the existing structure for now as part of a switch to Docusaurus.

Would it be possible to get this PR merged in soon (like, the next few days)?

**Comment by markerikson** [comment]
@yangshun : sure, there's several reasons:

- We're working on completely rewriting the React-Redux docs ( https://github.com/reduxjs/react-redux/issues/1001 ), and are also looking at heavily revamping the main Redux docs ( https://github.com/reduxjs/redux/issues/2590 )
- Since React-Redux didn't have any published docs yet, only the Markdown files in the repo, we just tried setting up Docusaurus for it and it looks good so far ( https://github.com/reduxjs/react-redux/issues/1031 )
- Meanwhile, I'm not terribly happy with the Gitbook publishing flow and some other bugs and limitations we've seen ( https://github.com/reduxjs/redux/issues/3161 ), so I'm asking for other options.  Since we just set up Docusaurus for React-Redux, it makes sense to use it for Redux as well.

**Pull request merged**
