### PR TITLE
feat(core): plugin postCompile lifecycle

### PR DESCRIPTION
**Pull request by gabrielcsapo**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [x] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #5616) and the maintainers have approved on my working plan.

## Motivation

Adds the ability for plugins to decide when to do additional steps during a dev build, since there is no postStart just postBuild. This enables plugins to do more with dev builds.

## Test Plan

I didn't see a strategy for testing plugin life cycle events, this is a TBD before we merge it needs to have a test for sure.

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

## Related issues/PRs

#5616

### CODE REVIEW

**Comment by slorber** [comment]
Hey

After taking a look I find it confusing that this lifecycle would only apply to dev and not prod, because in the end both compile?

Don't you want to create an index also on prod builds?

Also, it looks to me that you can achieve this in userland through webpack plugins, without introducing a new lifecycle

```js
  function myPlugin() {
    return {
      name: 'my-plugin',
      configureWebpack(config) {
        config.plugins?.push({
          apply: (compiler) => {
            compiler.hooks.done.tap('done', async () => {
              console.log('create index');
            });
          },
        });
      },
    };
  },
```

Isn't that solution good enough?

**Comment by gabrielcsapo** [comment]
@slorber ideally it would internally check if an index was created already and choose not to reproduce it based on some conditions like time since last generation or something similar.

Yes this could be implemented as a webpack configuration in the plugin itself, though it does couple that plugin to expecting webpack when that could change in the future. Having a stable API regardless of the internal implementation does lend better to a healthier plugin ecosystem.

**Comment by Josh-Cena** [comment]
> Having a stable API regardless of the internal implementation

If we migrate off Webpack we'll have a much much bigger mess to fix than making a new lifecycle.

**Comment by gabrielcsapo** [comment]
Totally agree, I think having a webpack hook to utilize makes sense, will try that out. Does it make sense to have a postStart hook? Given the workaround here, that seems to also handle postStart requirements.

**Comment by Josh-Cena** [comment]
I have yet to see a `postStart` use-case, though. Also, does it run immediately after <kbd>Ctrl</kbd> + <kbd>C</kbd>, or immediately after the dev server is prepared, or every time after it's reloaded? I do feel like having a lifecycle after and only after the dev server is prepared is worth it, provided a strong non-workaroundable use-case exists.

**Comment by gabrielcsapo** [comment]
I think it would be after the dev server is prepared. It would happen once at startup and not get called again when rebuilding occurs. 

The use case for me is to build the local search index when the dev server starts, similarly when the production build occurs via `postBuild`.

**Comment by Josh-Cena** [comment]
Could you open a feature request first? We can investigate if it can be done with `configureWebpack().devServer` first.

**Comment by gabrielcsapo** [comment]
This is the discussion for postStart https://github.com/facebook/docusaurus/discussions/5616 which led me to try and implement postCompile. I can create a feature request and link the discussion.

**Comment by gabrielcsapo** [comment]
I created the feature request @Josh-Cena https://github.com/facebook/docusaurus/issues/7749

**Pull request closed without merging**
