### PR TITLE
docs: removing community resource docusaurus-plugin-relative-paths

### PR DESCRIPTION
**Pull request by ShahriarKh**
Removing docusaurus-plugin-relative-paths from resources since the plugin no longer exists.

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

### CODE REVIEW

**Comment by slorber** [comment]
The plugin still exist on npm though: https://www.npmjs.com/package/@someok/docusaurus-plugin-relative-paths

@ohkimur why did you delete it?

**Comment by ohkimur** [comment]
> 

@slorber It didn't provide enough value to be worth the time invested to maintain it.

**Comment by slorber** [comment]
Thanks, up to you but in this case you can simply archive the repo, which makes it easier for others to take your work over

**Comment by slorber** [comment]
@ShahriarKh I will need you to sign the Facebook CLA to be able to merge. I know this is annoying but this is mandatory, repo settings do not allow me to merge without it

**Comment by ShahriarKh** [comment]
> @ShahriarKh I will need you to sign the Facebook CLA to be able to merge. I know this is annoying but this is mandatory, repo settings do not allow me to merge without it

Done

**Pull request merged**
