### PR TITLE
chore: minor refactor and prettify code

### PR DESCRIPTION
**Pull request by jamesgeorge007**
- Eliminate code redundancy.
- Format code as per prettier standards.

### CODE REVIEW

**Comment by endiliey** [comment]
Deploy preview for *docusaurus-2* failed.

Built with commit b12ab8a1f4313603dd6bc99092d72bed1fb6aa12

https://app.netlify.com/sites/docusaurus-2/deploys/5d1719ab49f2ee00075f5022

**Comment by endiliey** [comment]
Deploy preview for *docusaurus-preview* failed.

Built with commit b12ab8a1f4313603dd6bc99092d72bed1fb6aa12

https://app.netlify.com/sites/docusaurus-preview/deploys/5d1719ab9942570007d6b5bf

**Comment by jamesgeorge007** [comment]
I'm not sure if this check here actually comes into play :thinking: 
https://github.com/facebook/docusaurus/blob/b12ab8a1f4313603dd6bc99092d72bed1fb6aa12/packages/docusaurus/src/commands/init.ts#L64

**Comment by jamesgeorge007** [comment]
@yangshun It is due to the prettier-diff.

**Comment by yangshun** [comment]
That means the prettier format you're using is different from the one we use in our CI. Shouldn't we stick with the existing format?

**Comment by jamesgeorge007** [comment]
I shall revert those changes ASAP.

**Comment by jamesgeorge007** [comment]
cc @yangshun

**Pull request merged**
