### PR TITLE
feat(v2): report port number when starting dev server

### PR DESCRIPTION
**Pull request by wgao19**
## Motivation

Report port number so that users know which port Docusaurus is run.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

[Video](https://www.dropbox.com/s/yutr04uheu781r3/report-port.mov?dl=0)

## Related PRs
NA

### CODE REVIEW

**Comment by wgao19** [comment]
Hey @endiliey are you OK with this one merged?

**Comment by yangshun** [comment]
What's left to be done in this PR? It looks good to me. I'm inclined to merge this if it's ok, after the conflicts are resolved.

**Comment by endiliey** [comment]
iirc the log doesnt appear because of progress bar. I dont think the ascii looks good as well

**Comment by wgao19** [comment]
The port number is showing. Maybe you didn’t build the latest version?

I’m ok with this one closed or dropping the dino (it’s not ascii anymore, is a colored digits, just so we’re discussing the same version).

Anyway I think displaying the port number is a desired experience. You’re welcome to make whichever changes you find necessary. Feel free to close this one and open another PR for the feature as well.
2019年6月24日 10:31 +0800、Endi <notifications@github.com>のメール:

**Comment by endiliey** [comment]
havent tried it locally yet. Maybe i tried it ouf too early back then. Mind to send screenshots ? lgtm actually if the port is showing

**Pull request merged**
