### PR TITLE
fix(website): resize showcase images, tighten CI check

### PR DESCRIPTION
**Pull request by armano2**
## Motivation

PR created as requested in: https://github.com/facebook/docusaurus/pull/6042#issuecomment-985711743

```sh
mogrify -filter Triangle -define filter:support=2 -resize 640 -unsharp 0.25x0.25+8+0.065 -dither None -posterize 136 -quality 100 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB -strip website/src/data/showcase/*.png
```

## Related PRs

#6042

### CODE REVIEW

**Comment by armano2** [comment]
there seem to be artifact :(

**Comment by Josh-Cena** [comment]
image

Just picking up a random image. The original screenshot must have been optimised a lot🧐

**Comment by armano2** [comment]
> image
> 
> Just picking up a random image. The original screenshot must have been optimised a lot🧐

yes, they used 8b colors (256) in it, and due to anti-aliasing we have to use 16b, we could update some of them manually, but i'm not sure if that's desired, i also noticed that there is one jpg image in this folder

**Comment by Josh-Cena** [comment]
Just jumping in—there's also https://github.com/facebook/docusaurus/issues/3185. Does that one make sense? I'm not a big fan of WebP (not supported by every image viewer) but guess it could be more optimised?

**Comment by armano2** [comment]
by changing format to webp we can save up 5 more mb (across all images), tho some of them are bigger

**Comment by Josh-Cena** [comment]
Oh, just realized that the ideal image plugin we use probably doesn't support WebP... We can only apply WebP to other images until we fix that on the ideal image side

**Comment by armano2** [comment]
for reference command for webp (executed on original images)

```
magick mogrify -filter Triangle -define filter:support=2 -resize 640 -unsharp 0.25x0.25+8+0.065 -dither None -posterize 136 -quality 100 -define webp:lossless=true -interlace none -strip -format webp website/src/data/showcase/*.png
magick mogrify -filter Triangle -define filter:support=2 -resize 640 -unsharp 0.25x0.25+8+0.065 -dither None -posterize 136 -quality 100 -define webp:lossless=true -interlace none -strip -format webp website/src/data/showcase/*.jpg
```

**Comment by slorber** [comment]
Thanks, will look at this later

Just a reminder: the goal is not necessarily to have the best-optimized format for source images, because those are not the images that end up being deployed on the website anyway. The goal is a format that is faster to load/resize multiple times. 

Formats like AVIF may be good for some use-cases but afaik are not the fastest to load and require more CPU usage. Just reducing the source image size should be enough, we don't need to aim for maximum compression but good enough read/resize speed. Using advanced techniques that shrink the size more can actually make the situation worst for the use-case that we are trying to solve.

**Comment by Josh-Cena** [comment]
No resizing method can make this file's size smaller... Can't imagine how it was originally encoded...

image

**Comment by Josh-Cena** [comment]
There isn't a way for us to conveniently push to a fork in an action, so I decided to just let the check fail if the image's aspect ratio is not good.

**Comment by slorber** [comment]
What about requiring size > 640?

We could do one big resize PR every month instead of fixing PRs independently, as long as the resize is now easy and remains possible it should be good enough to accept larger images temporarily.

Why are many images smaller in width but larger in kb? Isn't it supposed to become smaller as we reduce their width?

**Comment by Josh-Cena** [comment]
> Why are many images smaller in width but larger in kb? Isn't it supposed to become smaller as we reduce their width?

Apparently, the optimization in #4901 was so good that any resizing just makes the file bigger😄 See my screenshot above.

I guess the optimization deleted some metadata, since I don't know how PNGs can be optimized otherwise... But I can't use that tool since my M1 mac forbids me to build that binary 🤦‍♂️ I would fight against it later

**Comment by Josh-Cena** [comment]
Great, optimized the images so that all have a size reduction. Will merge this now

**Pull request merged**
