### PR TITLE
[WIP] Fixes for Internet Explorer 11

### PR DESCRIPTION
**Pull request by ahmadalfy**
## Motivation

Cross browser compatibility sets good example in open source project. There are few issues happening in Internet Explorer 11 that blocks the usage of the website for its users.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

This PR will mostly be about UI changes that would affect CSS only. Plans for testing would be testing the UI on IE11 and another major browser (like Chrome) to ensure the updates doesn't break the new browsers as well as testing on mobile device.

## Related issues

https://github.com/facebook/Docusaurus/issues/585

### CODE REVIEW

**Comment by ahmadalfy** [comment]
Before:

image

After:
image

The reason:

`flex: 1` on IE11 automatically set the `flex-basis` value to `0` without units on IE11. This leads to the collapse of the element and disallowing it from expanding and taking the size it should. This is a known issue on IE11 and usually countered by using `flex: 1 1 auto` in order to prevent that behavior

**Comment by ahmadalfy** [comment]
My bad @yangshun 

Should I remove the project and fork it again to avoid having the other PR commits on this one as well?

**Comment by yangshun** [comment]
@ahmadalfy From your screenshots, the font looks bad. The screenshot in #585 doesn't look that bad. We want to use the system font if possible. Could you help to look into it and fix it if possible? Ideally we want to emulate GitHub, which also uses system fonts.

**Comment by yangshun** [comment]
@ahmadalfy It's fine, I rebased and it's ok now. You'll have to branch off latest master for your new PRs or rebase on master in future.

**Comment by ahmadalfy** [comment]
Yes I already fixed that and it is coming on the next commit ;)

**Comment by yangshun** [comment]
Please title your PRs according to the specific fix you are making 😄

**Comment by zenflow** [comment]
Great work @ahmadalfy .. much appreciated!

**Comment by ahmadalfy** [comment]
@zenflow most welcomed <3

**Pull request merged**
