### PR TITLE
I added docs description about using netlify CMS

### PR DESCRIPTION
**Pull request by kaustubhk24**
There was no support for Netlify CMS, So I added a description so that users can use netlify cms with docusaurus

## Motivation

[#5090](https://github.com/facebook/docusaurus/issues/5090)
[#5015](https://github.com/facebook/docusaurus/issues/5015)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?
yes

## Test Plan

No codes changed only changes in documentation

## Related PRs

None

### CODE REVIEW

**Comment by kaustubhk24** [comment]
Reopened after completing https://code.facebook.com/cla

**Comment by slorber** [comment]
Hi

I'm sorry but NetlifyCMS is not a deployment platform, it is a CMS, and does not really belong there.

Also as explained we don't necessarily have doc about NetlifyCMS in the official doc. 

Unless you commit to maintain it up-to-date over time for the next decade, it will become our burden. Please document this, but outside the official site, as a blog post or whatever. We'll be happy to link to it and reference it.

**Comment by kaustubhk24** [comment]
Ok I will add on my blog, Please add link atleast

**Comment by slorber** [comment]
We have a resources section in our doc on which we can link to such articles: https://docusaurus.io/community/resources

**Comment by stouch** [comment]
Is there any official method to integrate Docusaurus with Netlify CMS on a private gitlab self managed repo for example ?

**Pull request closed without merging**
