### PR TITLE
docs: consistently use sidebars.js filename

### PR DESCRIPTION
**Pull request by leedom92**
## Motivation

sidebar.js should be modified to sidebars.js in some files

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes!

### CODE REVIEW

**Comment by Josh-Cena** [comment]
@leedom92 Why closing this?

**Comment by leedom92** [comment]
> @leedom92 Why closing this?

I thought the PR was not accepted，I reopen it right now.

**Comment by Josh-Cena** [comment]
Just waiting for CLA. Have you signed it?

**Comment by leedom92** [comment]
> Just waiting for CLA. Have you signed it?

oh，thx! I had signed it just now.

**Review by Josh-Cena — APPROVED** [review]
Thanks!

**Pull request merged**
