### PR TITLE
perf(v2): lazy collapsibles, reduce html output and build times

### PR DESCRIPTION
**Pull request by slorber**
## Motivation

Allowing collapsibles (ie sidebar categories) to be "lazy" can reduce significantly the HTML markup.

Fix https://github.com/facebook/docusaurus/issues/4753

Many sites have very large sidebars and the sidebar markup is responsible for a huge part of the HTML content + build time.

We should avoid rendering collapsed items on the server, and delay rendering until the first expansion.

Note: this can have an SEO impact, as crawlers won't see the whole sidebar anymore, but I believe it's fine because crawlers can still navigate the site through direct sidebar siblings and the next/previous buttons. I also believe crawlers would understand better that certain pages are related together and form "semantic cocoons" because only sidebar siblings/ancestors are rendered now.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

yes

## Test Plan

preview

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by slorber** [comment]
This can have huge impact on sites with very large sidebars, and a good impact on smaller sites too!

image


Note some very large sites already use a trick to avoid rendering the sidebar on SSR and can save up to 12min build time!: https://github.com/demisto/content-docs/pull/616#issuecomment-826973273

```js
function DocSidebarBrowser(props) {
  return (
    <BrowserOnly
      fallback={<div>Sidebar...</div>}>
      {() => {
        // Something that should be excluded during build process prerendering.
        return <DocSidebar {...props} />
      }}
    </BrowserOnly>
  );
}
```

I think current PR is a good compromise to avoid delaying the visibility of the sidebar and keep acceptable perfs. Obviously it will remain faster to simply not render the sidebar on the server.

**Comment by slorber** [comment]
@jdevalk may I ask you what you think about the potential SEO impacts of server-rendering only a subset of the full sidebar?

**Comment by jdevalk** [comment]
The risk is that search engines won't follow the links in the parts of the sidebar that aren't rendered immediately. So pages deeper are more clicks away from the main page. Whether that's a problem depends on how many links point to that documentation, but I've seen some docusaurus sites that have such hideously long menu's that that's not ideal either. So in all, especially as it'll make pages faster, I think this is a smart change to make.

**Comment by slorber** [comment]
Thanks 😜 let's use this by default then and maybe we'll add a config
option later if it's requested.

Note later we'll make category index pages/doc so crawlers will be able to
more easily navigate down the tree

Le ven. 9 juil. 2021 à 19:44, Joost de Valk ***@***.***> a
écrit :

**Comment by slorber** [comment]
👍 this seems to work fine!

**Pull request merged**
