### PR TITLE
fix(v2): tweak colors for announcement bar

### PR DESCRIPTION
**Pull request by yangshun**
## Motivation

Make the announcement more prominent.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Screen Shot 2020-04-02 at 2 26 35 PM

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by lex111** [comment]
See also https://github.com/facebook/docusaurus/pull/2504

**Comment by yangshun** [comment]
@lex111 what do you think of using the default primary color?

**Comment by lex111** [comment]
It doesn't go well with bg color, IMO.

**Comment by yangshun** [comment]
I changed the color to be black

**Pull request merged**
