### PR TITLE
Remove outdated restriction regarding docs nesting

### PR DESCRIPTION
**Pull request by yangshun**
## Motivation

@endiliey shipped a feature to allow doc nesting. This PR removes the outdated restriction in siteConfig regarding docs nesting.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

NA. Doc change.

## Related PRs

#705

### CODE REVIEW

**Comment by yangshun** [comment]
@endiliey On a side note, I have the following questions:

1. Does nested docs dirs work for custom doc path?
1. Could we try to convert the existing docs dir to nested? So as to dogfood the feature 😄

**Comment by yangshun** [comment]
How about writing a script to migrate the current and versioned docs to nested? 

1. Split each filename by hyphen.
1. Take the first word and create a dir.
1. Shift filenames with the same first word into the dir.
1. Rename the filename and strip off the dir.

I can try doing that tomorrow 👍

**Comment by endiliey** [comment]
@yangshun appreciate it if you could help me on that. I'll be out of reach of my laptop in the next few hours for a week. No wifi & laptop at hospital 😢

**Comment by yangshun** [comment]
No problem, I'll take care of it. Rest well! Take care 😄

**Comment by endiliey** [comment]
On a side note, note that we have to basically replace all markdown linking

Example:
```
[Installation guide](getting-started-installation.md).
```

to
```
[Installation guide](getting-started/installation.md).
```

**Comment by JoelMarcey** [comment]
I thought moving `admin` to its own folder under docs would gives the least friction way to have this running on Docusaurus -- which I definitely think we should.  I do not mind moving our docs to their own folder as well.

Or #whynotboth 😄 

> Split each filename by hyphen.
> Take the first word and create a dir.

@yangshun I don't think this works for `getting-started` though, which we would want as the directory name. Not `getting` 😄

**Pull request merged**
