### PR TITLE
refactor: migrate from react-loadable to @react-loadable/revised

### LINKED ISSUE #3841: Migrate from react-loadable to loadable-components (or other alternatives)
Currently, with `react-loadable`:
- react-loadable doesn't seem maintained anymore, just take a look at the "issues" list (open PRs for multitudes of fixes) dating back to 2018 https://github.com/jamiebuilds/react-loadable/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc
- react-loadable does not support React 17.X.X due to it still referencing the deprecated and now removed/to-be-removed `componentWillMount`:
	```
	react-dom.development.js?61bb:67 Warning: componentWillMount has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

	* Move code with side effects to componentDidMount, and set initial state in the constructor.
	* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

	Please update the following components: LoadableComponent
	```

## 💥 Proposal

I haven't dived too deep into the Docusaurus codebase but it seems like even according to the official React docs here https://reactjs.org/docs/code-splitting.html#reactlazy, the recommended loadable in React with code-splitting support and SSR is `loadable-components` https://github.com/gregberge/loadable-components, which seems like something that should be moved towards to allow easy support of newer React versions.

Perhaps there are also other alternatives if the above mentioned one isn't ideal for whatever reason. Opening this issue for conversation on this topic.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### PR DESCRIPTION
**Pull request by Josh-Cena**
## Motivation

Continuation of #6306. Close #3841

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

TODO

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Not sure if it even works... There are API changes between the revised version and the original version, and we have an addon that I have no idea if is impacted by this migration.

**Comment by seyoon20087** [comment]
Try modifying these lines:

https://github.com/facebook/docusaurus/blob/8f69f633e66228b129de4965b1b0d3148514b3b4/packages/docusaurus/src/client/theme-fallback/Loading/index.tsx#L8-L15

To this:

```diff
diff --git a/packages/docusaurus/src/client/theme-fallback/Loading/index.tsx b/packages/docusaurus/src/client/theme-fallback/Loading/index.tsx
index 761c9c3a7..97cbac153 100644
--- a/packages/docusaurus/src/client/theme-fallback/Loading/index.tsx
+++ b/packages/docusaurus/src/client/theme-fallback/Loading/index.tsx
@@ -5,14 +5,17 @@
  * LICENSE file in the root directory of this source tree.
  */
 
+/* eslint-disable @typescript-eslint/ban-ts-comment */
+/* eslint-disable @typescript-eslint/explicit-module-boundary-types */
+
 import React from 'react';
-import type {LoadingComponentProps} from 'react-loadable';
 
 export default function Loading({
-  error,
-  retry,
+  // @ts-ignore
+  error, // @ts-ignore
+  retry, // @ts-ignore
   pastDelay,
-}: LoadingComponentProps): JSX.Element | null {
+}): JSX.Element | null {
   if (error) {
     return (
       <div

```

Let me know if something needs to be fixed

**Comment by Josh-Cena** [comment]
@seyoon20087 Adding `ts-ignore` will surely make things "work" 😄 I will try to make them actually "work" or figure out if this setup will work at all

**Comment by slorber** [comment]
@Josh-Cena do we even still need a lib with React 18?

I'd like to figure out how to remove this.

React.lazy() now has support for Server-Side-Rendering

- https://reactjs.org/docs/code-splitting.html#reactlazy
- https://17.reactjs.org/docs/code-splitting.html#reactlazy

The v17 warning + suggestion to use loadable components was removed, so I guess our setup could be simplified 🤷‍♂️ 

image

The doc is not so clear about the behavior of React.lazy() with server-side-rendering behavior though, but I guess it will not show suspense placeholders and just load appropriately the lazy components? Will try to get answers

**Comment by Josh-Cena** [comment]
React.lazy doesn't work with SSG. See https://loadable-components.com/docs/loadable-vs-react-lazy/

**Comment by slorber** [comment]
React.lazy did not work with SSG, but in React 18 it does (loadable components doc has probably not been updated since)

Confirmed by React itself :D https://twitter.com/reactjs/status/1511755578716028928

**Pull request closed without merging**
