### PR TITLE
docs: add Pearl UI website to showcase

### PR DESCRIPTION
**Pull request by agrawal-rohit**
## Motivation

Adding another example website to the Docusaurus showcase

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Thanks, nice site, just remember to sign the CLA

**Comment by Josh-Cena** [comment]
Friendly ping @agrawal-rohit we would definitely close PRs without a CLA after two weeks of inactivity.

**Comment by Josh-Cena** [comment]
Hi @agrawal-rohit we are closing this PR because we can't merge PRs without CLA. If you are back, feel free to sign the CLA and reopen the PR, and we will happily merge it :D

**Comment by agrawal-rohit** [comment]
Hey, sorry about that. I have signed the CLA, which should be reflected in your systems after an hour or so.

Could you reopen this PR and merge it now?

**Comment by Josh-Cena** [comment]
Yep! @agrawal-rohit It's all good now. 👍 Thanks!

**Pull request merged**
