### PR TITLE
feat(V2): change the style of a  live codeblock

### PR DESCRIPTION
**Pull request by jhoneybee**
## Motivation
2021-02-26 16-05-27屏幕截图

change to 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

yes i read 
## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by jhoneybee** [comment]
This will look more beautiful. Can it be modified like this? 

@lex111 @slorber

This is not a complete implementation, I just wrote an example.  If there is no problem with this style, I will finish it

**Comment by lex111** [comment]
@jhoneybee thanks for your efforts, but the new design is very non-obvious to the end-user; I mean, most likely the user will not be able to understand there is actually a live editor. Therefore, hiding live editor is a bad idea.

**Comment by jhoneybee** [comment]
@lex111 Thank you very much for your reply. 

hiding live editor is a bad idea. but lt will reduce layout space. 

I will think of other ways to solve. it won't take much time

**Comment by jhoneybee** [comment]
@lex111 



```
```jsx live expand
```

if have `expand` , show code editor .

**Comment by jhoneybee** [comment]
@lex111  Is there any progress?

**Review by lex111 — COMMENTED** [review]
I don't really like the proposed design, but that's just my opinion, so let's get wait a feedback from @slorber.

Moreover, I don't want to complicate the `Playground` component via introducing such fields as title/desc. I rather think this is not necessary.

BTW I accidentally found a Docusaurus site that made the live code editor collapsible, if we want the same feature (I'm not sure about that), then I would prefer this option. You can check it out at https://cloudioinc.github.io/statex/docs/#demo

**Comment by jhoneybee** [comment]
@lex111

this did not make you like this design, I am very sorry.  can you tell me the shortcomings of the design?  I will avoid this design

**Comment by lex111** [comment]
@jhoneybee I have provided example from Statex (see link in my previous comment). It seems to me that this is a more suitable option without significantly changing our existing design (which has already become familiar to many people).

**Comment by jhoneybee** [comment]
> @jhoneybee I have provided example from Statex (see link in my previous comment). It seems to me that this is a more suitable option without significantly changing our existing design (which has already become familiar to many people).

I understand.  thank you very much.

**Pull request closed without merging**
