### PR TITLE
refactor: update imagemin and its dependencies

### PR DESCRIPTION
**Pull request by ahmadalfy**
Greetings,

I introduced imagemin to compress the images in an earlier versions. Currently the versions used have security issues as noticed by `npm audit`.

> found 9 vulnerabilities (1 low, 8 moderate) in 30578 scanned packages
  7 vulnerabilities require semver-major dependency updates.
  2 vulnerabilities require manual review. See the full report for details.

The problem happens because of a dependency on a package called [tunnel-agent](https://nodesecurity.io/advisories/598)

## Motivation

Getting rid of insecure packages.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Run build script and check the output. It should compress the images

## Related PRs

https://github.com/facebook/Docusaurus/pull/654

### CODE REVIEW

**Comment by SimenB** [comment]
This moved it from `dependencies` to `devDependencies`, is that on purpose?

**Comment by ahmadalfy** [comment]
@SimenB I think because they are not a part of the final output, it just modify the files so yes. I could be wrong.

**Comment by SimenB** [comment]
It's just supposed to minimize the images of docusaursus itself, not those of sites using docusaurus?

**Comment by ahmadalfy** [comment]
No it is supposed to optimize the images of the user as well. I saw what I did here 😅 I can revert it back to be in dependencies then.

**Comment by merlinnot** [comment]
Please revert to dependencies. Builds of websites are failing after a clean install.

**Comment by ahmadalfy** [comment]
Submitted

**Pull request merged**
