### PR TITLE
feat(content-docs): sidebar item type "html" for rendering pure markup

### LINKED ISSUE #6389: Pure HTML sidebar item
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

Sidebar items shouldn't always be links. We should allow thinks that are purely decorative.

### Has this been requested on Canny?

https://docusaurus.io/feature-requests/p/label-in-sidebar

### Motivation

We have several needs:

- Pure text titles;
- Sidebar dividers;
- Logos;
- Carbon ads?

While we can work around the first with a `collapsible: false` sidebar category, the other three are currently not achievable, and swizzling can be intractable as well. 

### API design

A new sidebar item `type: 'html'` which allows the developer to pass arbitrary HTML code.

```js
module.exports = {
  sidebar: [
    {
      type: 'html',
      value: '<div class="divider" />',
    },
    {
      type: 'html',
      value: '<span class="sidebar-heading">Section title</span>',
    },
  ],
};
```

### Have you tried building it?

No

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

### PR DESCRIPTION
**Pull request by jodyheavener**
## Motivation

We would like to be able to render custom HTML sidebar items. These items should render only the supplied HTML defined in the sidebar config, they don't need to be links or be associated with any pages, etc.

To achieve this I added a new sidebar item type, `"html"`. It accepts three configuration properties:

- `value` (string, required) is the HTML to be rendered.
- `defaultStyle` (boolean) will, when `true`, apply the styles that a standard menu item receives (i.e. spacing)
- `className` (string) is a class name to be applied to the outer menu item `<li>`

Note: this item's HTML is still rendered inside an `<li>` tag. This is required because sidebars are rendered inside inside `<ul>` tags, and no other element is a valid child element of it, therefor rendering "unwrapped" custom HTML is disallowed. Additionally, because menu items can be nested, custom HTML menu items will inherit horizontal spacing when nested.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

To test this feature, you can use the following sample code.

<details>
  <summary>📃 Example HTML sidebar items</summary>
  <div>

```javascript
// Divider
{
  type: 'html',
  value: '<span class="sidebar-divider" />',
},
// Section title
{
  type: 'html',
  className: 'sidebar-title',
  value: 'Core concepts',
  defaultStyle: true,
},
// Image
{
  type: 'html',
  defaultStyle: true,
  className: 'powered-by-banner',
  value: `
    <span>Powered by</span>
    <img src="/img/docusaurus.png" alt="Docusaurus Logo" />
  `,
},
```

  </div>
</details>

<details>
  <summary>🎨 CSS for HTML sidebar items</summary>
  <div>

```css
.sidebar-divider {
  border-top: 1px solid var(--ifm-color-gray-200);
  display: block;
  margin: 0.5rem 0 0.25rem 1rem;
}

html[data-theme='dark'] .sidebar-divider {
  border-top: 1px solid var(--ifm-color-gray-800);
}

.sidebar-title {
  font-size: 0.8rem;
  letter-spacing: 0.05rem;
  text-transform: uppercase;
  font-weight: 600;
  color: var(--ifm-color-gray-600);
}

html[data-theme='dark'] .sidebar-divider {
  color: var(--ifm-color-gray-200);
}

.powered-by-banner {
  margin-top: 0.5rem;
}

.powered-by-banner span {
  font-size: 0.6rem;
  letter-spacing: 0.05rem;
  text-transform: uppercase;
  font-weight: 600;
  color: var(--ifm-color-gray-600);
}

.powered-by-banner img {
  display: block;
  max-width: 70px;
  margin-top: 0.25rem;
}

@media only screen and (max-width: 998px) {
  .sidebar-title,
  .powered-by-banner {
    margin-left: 1rem;
  }
}
```

  </div>
</details>

Add this code to your Docusaurus sidebar config and CSS file, and it should render nicely as pictured below:

Screen Shot 2022-01-30 at 18 36 21

Additional screenshots:

- [Dark theme, mobile](https://user-images.githubusercontent.com/6392049/151731712-7c260399-35d9-4102-83c7-d3d2cb2abeac.png)
- [Light theme, nested](https://user-images.githubusercontent.com/6392049/151731781-46408631-cd2f-46d8-aadf-b83ec0e6a644.png)
- [Light theme, mobile, scrolled](https://user-images.githubusercontent.com/6392049/151731825-c6151190-8f71-4d1c-923b-54b27436d297.png)

## Related PRs

Closes #6389

---

⚙️ I took a quick stab at trying to get JSX rendering inside in these menu items, but I ran into CJS issues. Could be a nice followup issue.

### CODE REVIEW

**Review by slorber — APPROVED** [review]
LGTM thanks 👍 

Just fixed a little bug in another hook

We have an internal docs plugin instance for testing so added some of your examples to it:

http://localhost:3000/tests/docs

**Comment by slorber** [comment]
@Andarist I guess it's not exactly the same use-case as your sidebar carbon ads right? (https://github.com/facebook/docusaurus/discussions/5468#discussioncomment-1714434)

**Comment by SuperOleg39** [comment]
@jodyheavener Hello! Is there any way to use `html` type for full autogenerated sidebar?

**Comment by slorber** [comment]
no way for now but we'll try to allow it later by providing your own sub-items through _category_.json

**Comment by SuperOleg39** [comment]
Thanks a lot)

**Pull request merged**
