### PR TITLE
Update getting-started-site-creation.md

### PR DESCRIPTION
**Pull request by coreygans**
Removed extra comma

## Motivation

(Write your motivation here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by yangshun** [comment]
@coreygans That change seems fine, what made you close the PR?

**Comment by coreygans** [comment]
@yangshun Don't have time to review and don't want to sign the CLA.

**Comment by JoelMarcey** [comment]
@coreygans 😞 

Thanks for catching it - we can make the update ourselves if you do not want to sign the CLA.

**Comment by yangshun** [comment]
I made the change in https://github.com/facebook/Docusaurus/commit/ca7c3cebc1348119bae682122a0b6f2419333ff8, along with some content improvements.

**Pull request closed without merging**
