### PR TITLE
Update page url of obtaining access token of crowdin.

### PR DESCRIPTION
**Pull request by lyricat**
## Motivation

The page url that to obtain access token has been changed. The old url is not accessible. 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

Test it manually.

## Related PRs

No.

### CODE REVIEW

**Comment by slorber** [comment]
You closed because you were wrong right? maybe you were not logged in?

This works for me: https://crowdin.com/settings#api-key

**Comment by lyricat** [comment]
> You closed because you were wrong right? maybe you were not logged in?
> 
> This works for me: https://crowdin.com/settings#api-key

No.
Because I have multiple crowedin accounts logged in. The correct URL base is <organization>.crowedin.com.

I find that I need to change a lot of the article if I want to it satisfy the situation of multiple accounts. I don’t have time to do that so I close it.

**Comment by slorber** [comment]
I see, good to know.

Our doc is for simple Crowdin usage and you'd better read Crowdin doc if you have more advanced use-cases like multi-org. As far as I understand it may not be possible to provide a good link that works in all cases so we'd rather keep it simple and make it work for 90% of users than 10%.

**Comment by lyricat** [comment]
Yes, I agree with you.

**Pull request closed without merging**
