### PR TITLE
Make DocSidebar menus collapsible without any JS

### PR DESCRIPTION
**Pull request by utkarsh867**
## Motivation

Issue #3030 

The docs in the DocSidebar component have collapsible menus however they do not work without JS. This fix makes use of the `details` and `summary` HTML tags to implement the collapsible menus.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan
Review

## Related PRs
(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by utkarsh867** [comment]
@slorber This fix is only been made in the classic theme as of now. 

Also, I still have not figured out how to make the arrow rotate along with the collapsible menu in this approach. I have hidden the arrow that comes with `details` HTML tag but the Infima arrow, that is a part of the theme, does not animate.

image
image

**Review by lex111 — COMMENTED** [review]
Many things are broken:

- Mobile view
- Collapsible categories functionality
- CSS transitions
- Semantic HTML issues (using `p` as button)

Definitely the current solution is not at all what we need.

**Comment by sarthakkundra** [comment]
@lex111 Can you please explain what's wrong with the following : 

- Mobile View

- Collapsible categories functionality

The CSS transitions in the arrows is something we're aware of and we'll try to fix it.

**Comment by lex111** [comment]
You removed a lot of JS code responsible for the specified features. In general, I think that the solution with `details` will not work in our case.

**Comment by slorber** [comment]
Hi,

The code in this PR should not impact in any way the current behavior for almost all users that have JS enabled.
It should only improve the experience for users with JS disabled.

You can compare these 2 URLs side by side, on mobile + desktop, and you'll easily notice the large number of differences.
- https://deploy-preview-3642--docusaurus-2.netlify.app/classic/docs/
- https://v2.docusaurus.io/docs/

This PR should make the 2 URLs look exactly the same when JS is enabled (including the accessibility properties, ie you are not free to refactor the HTML tags as you want).

I suggested trying to use `:focus-within` to solve this problem, and this is for good reasons. I'd like that you try my suggestions first, before trying to do more impactful refactors.

**Comment by slorber** [comment]
Here is an example I made of focus-within with a recursive structure like we have on the sidebar: https://codepen.io/sebastienlorber/pen/MWemKJe

You should be able to apply something similar to our sidebar and obtain a similar result.
I prefer that you try this technique first, before refactoring to checkbox/label or details/summary view.

**Comment by utkarsh867** [comment]
@slorber I tried to use the `:focus-within` to solve this issue and came across this issue where opening one category, or clicking away from the sidebar would close the currently open category. I could not think of a way to prevent this from happening without using JS. Hence, after trying a couple of things, using `details` seemed to be a simple approach.

But I do agree that multiple things are broken as @lex111 pointed out. I will be working on fixing those issues as well.

I think I will rollback these changes, and try to work fresh.

**Comment by utkarsh867** [comment]
> Here is an example I made of focus-within with a recursive structure like we have on the sidebar: https://codepen.io/sebastienlorber/pen/MWemKJe
> 
> You should be able to apply something similar to our sidebar and obtain a similar result.
> I prefer that you try this technique first, before refactoring to checkbox/label or details/summary view.
> If this is too hard to do, we might as well postpone this issue for now, so let me know.

Exactly what I am talking about in my last comment. Is that acceptable behaviour for the dropdown?

**Comment by slorber** [comment]
@utkarsh867 that seems acceptable that unfocused categories collapse. Remember that we are only trying to enhance existing UX for users without JS, and current state is that they can't navigate at all. If we can make the site usable without JS, even if the UX is not awesome, it's already a win

**Pull request closed without merging**
