### PR TITLE
Windows compatibility fix

### PR DESCRIPTION
**Pull request by zenflow**
Simple fix for simple problem causing errors on Windows machines, where Git by default converts line endings from \n to \r\n when checking out code and back to \r when checking it in.

### CODE REVIEW

**Comment by yangshun** [comment]
Hi @zenflow what's the current behavior on Windows machines without this fix?

**Comment by yangshun** [comment]
Hi @zenflow what's the current behavior on Windows machines without this fix?

**Comment by zenflow** [comment]
Sorry for the delay.. I can answer this tomorrow probably

**Comment by zenflow** [comment]
I remember that (on Windows) the header is parsed incorrectly as being empty, and some error is thrown later on because of that.

Reminder that it's not simply a matter of using \n line endings because Git on Windows is typically configured to change line endings to /r/n when code comes out and back to /n when it goes back in.

**Comment by zenflow** [comment]
@yangshun I can give it a go tomorrow. But I'm a little confused.. Are the new .gitattributes and .editorconfig files in that PR copied to projects when you do `$ docusaurus-init`? (because that is what I'll try)

**Comment by yangshun** [comment]
Oh hmm I was just fixing it on local development. I think you are right, this needs to be copied upon `docusaurus-init` too. Could you try my PR and build the site locally? If that works, then this is a feasible solution and we can add these files as into the scaffolded files when `docusaurus-init`-ing. Would you be interested in making a PR to do that?

**Comment by zenflow** [comment]
@yangshun 

> Could you try my PR and build the Docusaurus site locally by cloning this repo?

Yeah for sure I'll give it a test and review. I think it will help for local development.

But I don't think it's a good idea to copy the files when `docusaurus-init`-ing.. .editorconfig doesn't always help because it will only ensure proper line endings once the individual files get opened in your IDE.. and .gitattributes needs to be in the root directory of the repo in order to work, and it's possible a project already has a file there that would be overwritten. Also we can include this in the scaffolding, but that becomes end-user-level configuration.. wouldn't it be considered more robust for Docusaurus to handle things properly without requiring more specific configuration in the app?

I've seen the /\r?\n/ pattern used a number of places (Next.js, Pino) without code comments and did not consider that it would be unfamiliar to linux-only developers.. but we can make this more clear I think... what if I extract that regex into a `const` with a short code comment like "this pattern matches \n (unix line endings) and \r\n (windows line endings)"?

**Pull request merged**
