### PR TITLE
fix(v2): deprecate docs homePageId in favor of frontmatter "slug: /"

### PR DESCRIPTION
**Pull request by slorber**
## Motivation

`homePageId` is not the best solution, as it is global across all versions. If we want to update the id of the home docs of current version, this will break the homepage for former version.

Frontmatter `slug: /` is more reliable, quite intuitive, and allows to set a different homepage for each version independently. Versions become more easily "sandboxed"

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Tests + Dogfooding

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
Will this be added to categories @slorber ? We would like to avoid using frontmatter for certain docs we are generating.

**Comment by slorber** [comment]
@gabrielcsapo I don't understand what you mean by "added to categories" here.

About frontmatter, I plan to add a generic `createFrontMatter` option that will allow you to provide doc frontmatters "from the outside" (ie the md file does not need to have any frontmatter)

**Comment by gabrielcsapo** [comment]
That would be awesome @slorber! This would be similar to editUrl function in the config?

**Comment by slorber** [comment]
Not sure what you mean by "similar", but in a sense yes it will also be a callback giving you additional control to inject/replace/enhance the frontmatter of any doc

**Pull request merged**
