### PR TITLE
chore: upgrade dependencies

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Just another update of our dependencies without BC.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Preview/tests

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by lex111** [comment]
@slorber let's enable Renovate bot according to this instruction? https://github.com/facebook/docusaurus/issues/3552#issuecomment-763623781

**Comment by slorber** [comment]
LGTM thanks 👍

**Comment by lex111** [comment]
What about setting up bot to automatically update deps?

**Comment by slorber** [comment]
@HonkingGoose created a Renovate config afaik and we want to add it someday, unfortunately it's not been my big focus and I can't even do it myself due to permissions. I keep this in my mind though and it's still planned

**Comment by HonkingGoose** [comment]
> @HonkingGoose created a Renovate config afaik

You can see the proposed Renovate config here: https://github.com/rarkins/docusaurus/blob/master/renovate.json 😉 

I'm really looking forward to seeing the bot work on this repository! I hope it will help you get updates in a more convenient way!

Remember, you're always free to ping me when you need help. If I can't figure out how to fix it, I'll call in the troops that do know how to fix it... 😉

**Pull request merged**
