### PR TITLE
Add open in browser functionality

### PR DESCRIPTION
**Pull request by yangshun**
## Motivation

Improve developer experience

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

- `yarn start`
- Browser opens to localhost:3000

Also tested with a running server, it opens in localhost:3001, which is correct.

## Related PRs

NA

### CODE REVIEW

**Comment by yangshun** [comment]
Yep it uses the user's default browser setting.

**Comment by yangshun** [comment]
@JoelMarcey Yep it uses the user's default browser setting! Saves me a few seconds of typing each time I start the server.

**Comment by JoelMarcey** [comment]
Got it. I wanted to play around this a bit before putting in an official release, that's why it will go in the next version. Hope that is cool.

One more rebase?

**Comment by yangshun** [comment]
Done! I think you are able to rebase the PR too. There's an "Update branch" button which I use to rebase other contributors' PRs before merging. Does that work?

**Comment by JoelMarcey** [comment]
I guess you are right, I can just update the branch 😄

**Comment by yangshun** [comment]
Thank you! 😍@JoelMarcey

**Comment by ahmadalfy** [comment]
I love this PR 😍

**Pull request merged**
