### PR TITLE
chore: Upgrade clsx to 2.0.0

### PR DESCRIPTION
**Pull request by harryzcy**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Upgrading clsx to 2.0.0 doesn't seems to effect anything.
According to their [release note](https://github.com/lukeed/clsx/releases/tag/v2.0.0), the breaking change is "Add "exports" map for native ESM support", which shouldn't effect docusaurus.

### Test links

`clsx` v2.0.0 release note: https://github.com/lukeed/clsx/releases/tag/v2.0.0

Deploy preview: https://deploy-preview-9464--docusaurus-2.netlify.app/

### CODE REVIEW

**Comment by harryzcy** [comment]
@slorber Hi, is there any updates to this?

**Review by Josh-Cena — APPROVED** [review]
I remember I had problems before with upgrading, but since it builds fine, I guess it is fine :)

**Comment by slorber** [comment]
Missed it but an unfortunate result of this upgrade is that we now have twice the lib in our client bundle. Wondering if we'll backport this? 🤔 

CleanShot 2023-11-21 at 19 37 08@2x

@carloskelly13 any plan to upgrade clsx in prism-react-renderer?

**Comment by Josh-Cena** [comment]
clsx is extremely small so not a huge deal. Upgrading would certainly be better, though.

**Comment by carloskelly13** [comment]
@slorber Yeah, we'll get @harryzcy's PR merged in and we'll publish a build. Thanks for getting that in.

**Comment by carloskelly13** [comment]
@slorber Prism React Renderer 2.3.0 with clsx 2.0 is published. https://github.com/FormidableLabs/prism-react-renderer/releases/tag/prism-react-renderer%402.3.0

Thanks @harryzcy for the PR!

**Comment by slorber** [comment]
thanks ❤️

**Pull request merged**
