### PR TITLE
fix(v2): increase stability of hideable navbar

### LINKED ISSUE #2907: Anchor links go to a scroll position that is slightly lower
## 🐛 Bug Report

Anchor links move to a scroll position that is slightly lower. 

**When using the url directly:**
(e.g. Directly access https://docusaurus-anchor-repro.now.sh/docs/doc1#images)
image

**When using anchor link:**
(e.g. Click the "go to images" link on https://docusaurus-anchor-repro.now.sh/docs/doc2)
image
The link also references `doc1#images`. However, we end up at a lower position. It is lower by the width of a navbar. 

## To Reproduce

1. Create a docusaurus site using the classic template 
1. In doc2, add a link to any anchor (e.g. `doc1#images`) in doc1
1. Start the website and click the link you added

## Expected behavior

After clicking the anchor link, I should go to the same scroll position as I would if I used the direct url (like the first screenshot above)

## Actual Behavior

After clicking the anchor link, I go to a scroll position that is lower by the width of a navbar.
The header is hidden by the navbar. (like the second screenshot above)

## Your Environment

- Docusaurus version used: 2.0.0-alpha.56
- Environment name and version (e.g. Firefox 77.0.1, Node.js 13.11.0):
- Operating system and version (desktop or mobile): Desktop Windows Build 2004

## Reproducible Demo
Repo: https://github.com/teikjun/docusaurus-anchor-repro
Website: https://docusaurus-anchor-repro.now.sh/docs/doc2

## Additional Remarks
This is not an issue if auto-hide sticky navbar is enabled

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Another attempt to get the hideable navbar to work well and in a predictable way.

Earlier, I did not take into account the initial (zero) position of the scroll, because of which navbar was not hidden the first time when it was expected. Technically, replacing `useState` with `useRef` fix this use case.

Fixes #2907

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Preview

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by slorber** [comment]
When I refresh the page after scrolling a bit, the page is rendered with the navbar, but then that navbar hides, producing a distracting animation

Not totally sure this is related to your change, but I can't reproduce it in production while it's visible in the preview.

Also it seems to appear more when there's the announcement bar visible

**Comment by lex111** [comment]
> Not totally sure this is related to your change, but I can't reproduce it in production while it's visible in the preview.

This behavior has been around before.

> Also it seems to appear more when there's the announcement bar visible

What do you mean, can you demonstrate it as a GIF?

**Comment by slorber** [comment]
I see this behavior in the preview, with the announcement bar enabled

Nov-17-2020 11-27-37

**Comment by lex111** [comment]
> I see this behavior in the preview, with the announcement bar enabled

Fixed this, and also removed some parts of the code.

**Pull request merged**
