### PR TITLE
feat(theme-classic): add social icons for mastodon and bluesky

### PR DESCRIPTION
**Pull request by cemerick**
## Pre-flight checklist

- [X] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [X] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.

## Motivation

Allow blog authors to display mastodon & bluesky social icons without swizzling. Pre-PR discussion @ https://github.com/facebook/docusaurus/discussions/10762

Note that this does not do anything fancy re: generating the actual social URL from anything shorter than an actual URL, since bluesky and mastodon profile links can have ~arbitrary domains, etc.

## Test Plan

These are just icons, so no tests added here. Tweaks made to a dogfooding page and the authors file there to make sure the new icons show up. I also did do a sanity check with my own site. :+1:

### Test links

Deploy preview: https://deploy-preview-10764--docusaurus-2.netlify.app/tests/blog

### CODE REVIEW

**Comment by cemerick** [comment]
I see some "lint" failures, but it seems it's just complaining about unknown terms ("bluesky", etc). I was about to update project-words.txt (where it seems such things are enumerated), but it's apparently a CI-generated file?

Let me know if there's anything I should do here to address this.

**Comment by Josh-Cena** [comment]
You can run the command `yarn lint:spelling:fix` locally to update this file!

**Comment by cemerick** [comment]
> You can run the command `yarn lint:spelling:fix` locally to update this file!

I've been incrementally resolving the problems reported by the linter(s), most recently `prettier` formatting. However, it looks like I've updated the PR more times than github likes before it's forcing a maintainer's approval to re-run those workflows again. 👉👈

**Comment by GingerGeek** [comment]
Hey @cemerick I see we both wanted the same thing 😅 

I have a similar PR in #10768 which also includes link handling for new social sites as well the icon inclusion

**Comment by cemerick** [comment]
@GingerGeek You've got more (very reasonable IMO) social sites added, so I'm happy to have yours taken instead :+1:

**Comment by slorber** [comment]
Thanks, I'm closing in favor of https://github.com/facebook/docusaurus/pull/10768 and will credit you as a co-author

**Pull request closed without merging**
