### PR TITLE
Added Stackery logo and site

### PR DESCRIPTION
**Pull request by bildungsroman**
## Motivation

Added Stackery to users.js as requested by @JoelMarcey 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

It just works!

## Related PRs

None

### CODE REVIEW

**Comment by yangshun** [comment]
@bildungsroman Could you sign the CLA first?

**Comment by bildungsroman** [comment]
@yangshun Do I need to sign it just for just this? I don't really want to go through the whole process of doing a corporate CLA for my company, and I'm not sure they'd be comfortable with that.

**Comment by yangshun** [comment]
@bildungsroman I'm afraid you have to sign it. Is the PR made under personal account? If so it's a pretty quick process. Otherwise, I could duplicate the PR on your behalf, that way you don't have to sign anything.

**Comment by bildungsroman** [comment]
Ok, it is made under a personal account so I'll go with the personal version. I just didn't want to have to bother anyone higher up at work :)

**Pull request merged**
