### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ishaan28malik**
Added yarn support to the **lqip-loader** ```package```

### CODE REVIEW

**Comment by lex111** [comment]
I see no point in cluttering the README file in this way, besides your yarn command is incorrect.

Please try to make more meaningful PRs, not create a few similar and simple ones.

**Comment by Ishaan28malik** [comment]
@lex111 thnx for correcting me

**Comment by yangshun** [comment]
> Please try to make more meaningful PRs, not create a few similar and simple ones.

Perhaps an attempt to hit the Hacktoberfest PR quota. Will be adding "invalid" tag to the PRs to discourage such behavior - https://hacktoberfest.digitalocean.com/details

**Comment by Ishaan28malik** [comment]
@yangshun I wil try to make more meaningful contributions from now.

**Pull request closed without merging**
