### PR TITLE
feat: Show icon-only for small devices

### LINKED ISSUE #2699: alpha-54: Site title no longer wraps - search box moves
## 🐛 Bug Report

In alpha-0.49 and previous (I believe but I'm struggling to get these to build now), longer site titles would wrap at the search in the header bar. This was especially important on mobile browsers where the width is obviously limited. As of alpha-54, the title is not wrapping and search box is being pushed out of the header.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce
1. Install Docusaurus and set up with a multi-word site title (total length more than 12 characters or so)
2. Enable the search plug in
3. Visit site on a mobile browser

## Expected behavior

Words should wrap to ensure proper placement of search box

## Actual Behavior

Title is shown on one line and search is moved
iOS:
IMG_0993

Pixel 4 (on BrowserStack)
image

## Your Environment

- Docusaurus version used: alpha-54
- Environment name and version: Chrome and Safari on iOS, 
- Operating system and version (desktop or mobile): iOS on iPhone XS. Using browser stack I see it on other devices, including android, depending on screen size/resolution

### PR DESCRIPTION
**Pull request by marcosvega91**
## Motivation
fix #2699 

Show icon-only search bar for devices under 768px.
This fix is useful to solve an issue with long app name causing a rendering problem with search

I hope to make something right :)

Regards 
Marco

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### CODE REVIEW

**Comment by marcosvega91** [comment]
I did in a different way because in that way the input field was not clickable. Let me know

**Comment by lex111** [comment]
But what if you completely remove the `.search-icon` element and show the magnifier icon of search input, as shown below?

ezgif com-video-to-gif

**Comment by marcosvega91** [comment]
Hi @lex111 I have applied the fix.

I removed the icon, but now I have a doubt about accessibility because in this case I made the div as button to expand the input in small devices. The div has always a button role but for large screens and when the input is already expanded the click on the div is disabled.

**Comment by lex111** [comment]
Hmm, currently I click on the magnifier icon, the search input expanded  and collapsed immediately.

**Comment by marcosvega91** [comment]
You mean that with code in master branch, removing only the search-icon it will work?

**Comment by lex111** [comment]
ezgif com-video-to-gif (2)

**Comment by marcosvega91** [comment]
this is my diff 
```diff
+++ b/packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js
@@ -104,16 +104,6 @@ const Search = (props) => {
 
   return (
     <div className="navbar__search" key="search-box">
-      <span
-        aria-label="expand searchbar"
-        role="button"
-        className={classnames('search-icon', {
-          'search-icon-hidden': props.isSearchBarExpanded,
-        })}
-        onClick={handleSearchIcon}
-        onKeyDown={handleSearchIcon}
-        tabIndex={0}
-      />
       <input
         id="search_input_react"
         type="search"
```

I only removed the `.search-icon` but it doesn't work. I think that I don't understand what you mean

**Comment by lex111** [comment]
You have made more changes, which is why the first time you tap to the search input on mobiles, it immediately collapsible. You can easily see this incorrect behavior for yourself if you open the preview website on your mobile.

**Comment by yangshun** [comment]
Thank you for this PR! As #2791 is more robust, we'll go with that. We'll definitely credit you in our next release as a collaborator of #2791 :)

**Pull request closed without merging**
