### PR TITLE
fix(typings): missing `Link` component attributes

### PR DESCRIPTION
**Pull request by kripod**
## Motivation

To evade TypeScript error messages like:

image

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### CODE REVIEW

**Comment by kripod** [comment]
@yangshun Yep, that’s possible, but I didn’t have much time to look into this deeper right now, sorry.

**Comment by kripod** [comment]
I'm not quite sure why the build is failing on CI. This looks very weird to me, so manually clearing the build cache might help:

image

**Comment by lex111** [comment]
@kripod I am currently experienced these errors too.  Apparently this is a common issue. https://github.com/facebook/react/issues/13686

**Comment by slorber** [comment]
This should be fixed now

**Pull request closed without merging**
