### PR TITLE
docs: remove exclusive language

### PR DESCRIPTION
**Pull request by ericcarboni**
## Motivation
Similar to https://github.com/facebook/jest/pull/9040 by @carolstran, I wanted to take a stab at removing some language (_easy, simply, of course, etc_) to continue creating a more inclusive and friendly community.

It was difficult, however, because a lot of Docusaurus' goal is...
>Easy to maintain open source documentation websites

...so there were a lot branding references with the word "easy", so I kept those and also did not touch old blog posts.

Let me know what you think!

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes!

## Test Plan

N/a no code changes

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by lex111** [comment]
@ericcarboni why did you changes numbered lists?

**Comment by ericcarboni** [comment]
Whoops, my editor might have done that. Good catch!

**Comment by lex111** [comment]
@ericcarboni can you revert these changes?

**Comment by ericcarboni** [comment]
Yeah, doing that now. Any idea why some lists are `1...2...` and then others are `1...1...1...`?

**Comment by lex111** [comment]
> Any idea why some lists are 1...2... and then others are 1...1...1...?

I do not know this, but I would leave only one notation `1..1`. Such lists are easier to maintain. But this already needs to be fixed in the new PR and it may be worthwhile to set linting MD files to avoid such a problem in the future.

**Comment by ericcarboni** [comment]
One instance even had `1..1..3` 🤷‍♂

**Comment by ericcarboni** [comment]
CLA signed! ✍️

**Comment by yangshun** [comment]
> One instance even had 1..1..3 🤷‍♂

That's probably because there was a code block or something between the second 1 and the 3. Doing 1..1..3 will result in 1, 2, 3. Using 1 instead of 3 will cause it to become 1, 2, 1 instead.

**Pull request merged**
