### PR TITLE
Add Reaction Commerce to users

### PR DESCRIPTION
**Pull request by machikoyasuda**
## Motivation

Add Reaction Commerce to users

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

☑️

## Test Plan

- Look at the Netlify deploy branch: https://deploy-preview-869--docusaurus-preview.netlify.com/en/users
- Click on the Reaction Commerce logo: https://docs.reactioncommerce.com/docs/intro.html
- Make sure it works
- 💯

## Screenshot

screen shot 2018-07-23 at 5 08 14 pm

## Related PRs

none

### CODE REVIEW

**Comment by yangshun** [comment]
Thanks @machikoyasuda! The logo icon is a 404 for me in the preview. Could it be a caching issue? I'll check again in a while.

**Comment by machikoyasuda** [comment]
@yangshun Nah.. it was my issue! Fixing + testing now.

**Comment by machikoyasuda** [comment]
Thank you @yangshun! Love working with Docusaurus + it's great to see so many new users with all sorts of new designs and use cases.

**Comment by JoelMarcey** [comment]
@machikoyasuda Thanks for using Docusaurus!

I noticed on your landing page that the images seem to be missing from the 6 boxes there. Just wanted to let you know.

**Comment by machikoyasuda** [comment]
@JoelMarcey Thank you for the heads up! All fixed now :D

**Pull request merged**
