### PR TITLE
chore(v2): prepare v2.0.0-beta.11 release

### PR DESCRIPTION
**Pull request by slorber**
chore(v2): prepare v2.0.0-beta.11 release

### CODE REVIEW

**Comment by Josh-Cena** [comment]
The CLA bot is not well today 🙈

**Comment by slorber** [comment]
😅 can't merge

**Comment by Josh-Cena** [comment]
@slorber maybe release before merging this?

**Comment by slorber** [comment]
Already released 😉

**Comment by pranabdas** [comment]
@slorber released version is not playing nice :(

```console
$ npm i @docusaurus/core@latest @docusaurus/preset-classic@latest
npm WARN ERESOLVE overriding peer dependency
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @docusaurus/utils-common@2.0.0-beta.11.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxx/.npm/_logs/2021-12-10T11_06_00_381Z-debug.log
```

**Comment by MateuszDabrowski** [comment]
Yep, have the same error as well, mixed with:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @docusaurus/plugin-ideal-image@2.0.0-beta.11.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by Josh-Cena** [comment]
@slorber 
looks like npm is broken? The release was incomplete

**Comment by slorber** [comment]
This is weird 😅 

image

image

**Comment by MateuszDabrowski** [comment]
Just tried once more - it went fine. So either you fixed it, or it was just a delay on the npm server.

**Comment by MateuszDabrowski** [comment]
Just tried once more, and still the same error:

```
[md:~/Documents/Code/JS/md]$ npm install --legacy-peer-deps
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @docusaurus/plugin-ideal-image@2.0.0-beta.11.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xx/.npm/_logs/2021-12-10T12_39_41_525Z-debug.log
```

**Comment by Josh-Cena** [comment]
@slorber Can you just re-run `npm publish` in those package directories? If the version isn't in the registry it will get published.

**Comment by slorber** [comment]
🤷‍♂️ 

image

I'll try to release a beta.12 and see

**Comment by Josh-Cena** [comment]
image

Hahaha

**Comment by MateuszDabrowski** [comment]
Same error on new beta file.

```
 npm install --legacy-peer-deps
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @docusaurus/cssnano-preset@2.0.0-beta.13.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by Josh-Cena** [comment]
@MateuszDabrowski There still are some packages not published. No idea what's going on with npm.

**Comment by slorber** [comment]
should be fixed now
https://status.npmjs.org/incidents/n4s34mwsdsp2

**Comment by MateuszDabrowski** [comment]
Fix confirmed! :)

**Pull request merged**
