### PR TITLE
feat(content-docs): allow custom props through _category_.json

### LINKED ISSUE #6690: Allow custom props through _category_.json
### Have you read the Contributing Guidelines on issues?

We used it docusaurus for our documentation. It's excellent.
I want to  customizae generated-index catalog, e.g. show filenames link of directory.
Is there a scheme that can be realized only by setting _category_.json?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

image

image

### Has this been requested on Canny?

_No response_

### Motivation

dd

### API design

_No response_

### Have you tried building it?

_No response_

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

### PR DESCRIPTION
**Pull request by taejs**
## Motivation

Close #6690 
Resolve [Feature Request: allow-customizing-category-description-in-generated-index-cards](https://docusaurus.canny.io/feature-requests/p/allow-customizing-category-description-in-generated-index-cards)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?
yes. but I have no idea how to test it.

### CODE REVIEW

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
Sorry, we don't want to add more root config fields for categories. Could you please just make `categoryMetadata.customProps` be passed to the final item? The idea is that the user can swizzle `DocCard` and implement whatever design through custom props.

**Comment by slorber** [comment]
Agree with @Josh-Cena : we want to enable users to bring their own customization abilities, not add just 2 new premade and unflexible attributes

**Review by slorber — CHANGES_REQUESTED** [review]
Agree with @Josh-Cena : we want to enable users to bring their own customization abilities, not add just 2 new premade and unflexible attributes

**Comment by taejs** [comment]
Also agree. Thanks for the feedback. After addressing the review I'm trying to resolve this error.
`The docs sidebar category metadata file path=${filePath} looks invalid`

CustomProps are not acceptable even though I added sidebar validation.

**Comment by taejs** [comment]
Addressed reviews:
make categoryMetadata.customProps be passed to the final item.

**Review by Josh-Cena — APPROVED** [review]
Thanks, that looks great!

**Pull request merged**
