### PR TITLE
[WIP] Add missing alt attribute to image tags for improved a11y

### PR DESCRIPTION
**Pull request by amyrlam**
## Motivation

🚨This PR is a WIP, will update PR summary here when complete! 🚨

Will resolve: https://github.com/facebook/Docusaurus/issues/462

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by amyrlam** [comment]
@yangshun First added some missing alt text from https://github.com/facebook/Docusaurus/issues/462 manually. 

Then was a little confused by some of the React syntax. Had some trouble adding an alt to the images `Powered by Markdown`, `Built Using React`, `Ready for Translations` in index.js.

So, I was thinking may be a bit faster to do trial and error without Live Reload if I added https://github.com/evcohen/eslint-plugin-jsx-a11y. Took the first step in adding eslint via https://eslint.org/docs/user-guide/getting-started#local-installation-and-usage but I get this:

```
alam@tesla Docusaurus (amyrlam/a11y) $ ./node_modules/.bin/eslint website/pages/en/index.js
-bash: ./node_modules/.bin/eslint: No such file or directory
```

Any ideas?

**Comment by yangshun** [comment]
@amyrlam Great work! 

 My thoughts:

1. What I would recommend is to submit **one PR** per a11y fix. Not sure if that's the intention of this PR, but the title of this PR suggests that it fixes all a11y fixes. Hence I would suggest you retitle this PR to be specific about what a11y issues you are fixing (alt attr to img tags?)
2. Remove the ESLint stuff for now. Integrating ESLint (adding it to `devDepenencies` and also integrating it into the dev and CI workflow) is considered an intermediate task. We can do that later but we first need buy-in from the project maintainer as it is making a change to the development process and is beyond the scope of a11y fixes. cc @JoelMarcey 

I'll look into the other issues tonight.

**Comment by amyrlam** [comment]
Ok, noted, will do. I was thinking it would be easier to debug the ones I had trouble adding an `alt` to with a linter versus restarting the app each time. But I realize that is getting too much in the weeds for this PR. I'll take a look at what you said re: the other `alt`s and report back

**Comment by amyrlam** [comment]
Thanks for the feedback, opening a new branch

TIL props...

**Pull request closed without merging**
