### PR TITLE
fix(mdx-loader): support nested admonitions

### LINKED ISSUE #8302: support nested admonitions
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

When nesting admonitions, the first seen stop-word (Line starting with `:::`) exits the first admonition block.

### Reproducible demo

_No response_

### Steps to reproduce

1. Add the following snippet with nested admonitions to a markdown page

```md
:::info Weather
On nice days, you can enjoy skiing in the mountains.

:::danger Storms
Take care of snowstorms...
:::

:::
```

### Expected behavior

expected

### Actual behavior

current

### Your environment

- Docusaurus version used: 2.2.0

### Self-service

- [X] I'd be willing to fix this bug myself.

### PR DESCRIPTION
**Pull request by lebalz**
# Pre-flight checklist
- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] If this is a code change: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] If this is a new API or substantial change: the PR has an accompanying issue (closes #8302) and the maintainers have approved on my working plan.
## Motivation
See #8302 - support nested admonitions
## Test links

- https://deploy-preview-8303--docusaurus-2.netlify.app/docs/markdown-features/admonitions#nested-admonitions
- https://deploy-preview-8303--docusaurus-2.netlify.app/tests/pages/markdownPageTests#admonitions

Related issues/PRs
#8302

### CODE REVIEW

**Comment by slorber** [comment]
Hey

Thanks for the PR

As part of the migration to MDX 2.0 (WIP - https://github.com/facebook/docusaurus/pull/8288) we will likely replace all this code with [remark-directive](https://github.com/remarkjs/remark-directive) so I'm not sure we are going to merge this PR for now. I'll keep it open but the goal is to get rid of the code. I guess it should be possible to support nested admonitions with the remark plugin.

**Comment by slorber** [comment]
> I think it's still a valuable fix to get into 2.x? I won't anticipate 3.0 to ship in a few weeks, not to mention its wide adoption.

We'll see. 

I'd like to see how to implement this in 3.x / MDX 2 before adding such new feature. In case it's complex or impossible to implement in 3.x, I'd rather not introduce a new feature to remove it later, nor to block / delay 3.x because of this new feature.

**Comment by slorber** [comment]
As part of https://github.com/facebook/docusaurus/pull/8288 we want to use the more flexible and generic [remark-directive](https://github.com/remarkjs/remark-directive) system to provide such features.

The nesting is possible, but works similarly to code blocks by adding more : for parent elements.

Here's a preview:
https://deploy-preview-8288--docusaurus-2.netlify.app/docs/markdown-features/admonitions/#specifying-title

```md

:::::note{title="Your title"}

Some **content** with _Markdown_ `syntax`.

::::note[Your nested Title]

:::note Your very nested Title (does not work yet :s)

Some **content** with _Markdown_ `syntax`.

:::

Some **content** with _Markdown_ `syntax`.

::::

hey

:::::
```

If we add this feature in v2 I'd rather have the exact same syntax instead of always using `:::`

That way users do not have to change anything when upgrading and there's no extra breaking change to explain.

Can you update the code to support 4/5+ colons please?

**Comment by lebalz** [comment]
Thanks for the review and the suggestions. I changed the algorithm which keeps track of the nesting level. Now it handles nested admonitions the way remark-directive does, e.g. with 4/5/+ colons...

**Comment by slorber** [comment]
LGTM thanks 👍

**Pull request merged**
