### PR TITLE
fix: MDX transclusion from outside `docs/`

### PR DESCRIPTION
**Pull request by kripod**
## Motivation

Make it possible to import `.md(x)` files from outside `website/docs/`. This can be used for referencing files like `../CONTRIBUTING.md` and `../CODE_OF_CONDUCT.md`.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Related issue

Partial fix for #2618.

### CODE REVIEW

**Comment by kripod** [comment]
@yangshun I tried building the upstream's `master` branch but encountered the same build issue. Unfortunately, I'm not sure about the cause.

**Comment by kripod** [comment]
I managed to fix the issue by only allowing imports from immediate parents. E.g.:

```
../file.md ✔
../../../file.mdx ✔

../dir/file.md ❌
../../../dir1/dir2/file.mdx ❌
```

**Comment by kripod** [comment]
May I help with anything to advance the state of this PR?

**Comment by yangshun** [comment]
After putting in more thought, I think this is going to cause more issues than not due to the "features" of the docs plugin approach of converting every markdown file to a corresponding doc page. It's really unintuitive to have files outside of the base docs dir also have pages created for them, and it'll lead to nasty surprises. Sorry about that.

**Pull request closed without merging**
