### PR TITLE
chore(deps): upgrade outdated transitive dependencies

### PR DESCRIPTION
**Pull request by rmkanda**
Few of the transitive dependencies are out of date. This PR upgrades to the lasted minor version available.

### CODE REVIEW

**Comment by rmkanda** [comment]
@lex111 Could you please review this?

**Comment by rmkanda** [comment]
@yangshun The conflicts are resolved. 

How this PR is created.
```
rm -rf node_modules yarn.lock
yarn install
```

One the yarn.lock is created, it locks to the specific version of transitive dependency. We can upgrade the direct dependencies by changing the version in package.json. But for transitive dependencies we need to touch the yarn.lock file.
Instead of updating the yarn.lock, Deleted the file and recreated it using yarn install.

**Comment by yangshun** [comment]
Seems like this can be easily done by the maintainers. We'll do it on your behalf as now there's merge conflicts again because we merged another PR which touched `yarn.lock`.

**Comment by rmkanda** [comment]
Thanks @yangshun

**Pull request closed without merging**
