### PR TITLE
chore(internal): add yarn deduplicate script, cleanup lock

### PR DESCRIPTION
**Pull request by Simek**
## Motivation

This small PR deduplicates yarn lock file using [`yarn-deduplicate`](https://github.com/atlassian/yarn-deduplicate) package. It also adds the deduplicate script as `lock:update` command. Let me know if you would like also to see this in [`postinstall`](https://docs.npmjs.com/misc/scripts) (to automatically optimize lock on every dependency change).

You can read more about what the script does and why it's important in the Readme section:
* https://github.com/atlassian/yarn-deduplicate#duplicated-packages

This might also fix the problems with the old, pinned packages, which are lately emerging in the repository (see related PRs).

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

Successful build and run of Docusuaurus V2 website on my local machine.

## Related PRs

* #3727 
* #3734

### CODE REVIEW

**Comment by slorber** [comment]
thanks, I'm ok to have this on postinstall

**Comment by slorber** [comment]
can it messup with yarn 2 users?

**Comment by slorber** [comment]
yarn lock conflict now :)

**Comment by Simek** [comment]
Conflict has been created after the merge of  #3716.

**Pull request merged**
