### PR TITLE
feat(v2): Added OG Image Api Support

### PR DESCRIPTION
**Pull request by FocalChord**
## Motivation

This is a draft for how we will be integrating Docusaurus with the backend for OG Image which @Drewbi will be hosting

Addresses issue #2968 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

**Comment by FocalChord** [comment]
@slorber thoughts on this?

**Comment by slorber** [comment]
that seems like a good first draft, but the thing is, to make this feature configurable, we need the user to be able to provide his custom function for `createOGImage`, instead of a hardcoded one. If he adds a fn in site config, we can only run this fn in node, not in client-side/layout.

I see 2 possible solutions:
- createOGImage in config + run it in node + inject the generated image as route props (requires integrating in each plugin)
- OgImage theme comp, used by Layout, with a default (but configurable with config) impl to generate the og image url. Users could then use swizzle to customize it to their needs


The 1st solution seems more work to me, but could also be more convenient, as it would be a global conf fn, and does not require swizzling

The 2nd solution would make this feature theme-specific, and would be more simple to implement. But maybe people implementing their own themes would like to benefit from this system as well?

Not sure which solution is best one yet.

**Comment by slorber** [comment]
Hey everyone. Just wanted to know if everything is fine on your side or if you need some help.

Please keep me posted about your  work on this feature :)

**Comment by Drewbi** [comment]
Hey thanks for checking in. I've gotten a basic api setup with only a few css issues but I think the part I have the least idea about is how to run the custom function provided by the user. You said we can run it in node but I'm not quite sure how that interaction would work/where the relevant files we would need to add are.

**Comment by Josh-Cena** [comment]
Closing due to inactivity

**Pull request closed without merging**
