### PR TITLE
fix(v2): specify own CSS class for code tabs

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Tabs must have its own CSS class so that the end user can customize it.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

image

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by lex111** [comment]
Hmm... I'm sharing my problem, maybe this will clarify the situation.

In the screenshot below, I need to stylize the code block that follows **after** the code tabs (added icon, an arrow is indicated on it). In the first version, code tabs had their own CSS class - `.tabs`, now just a `div` without anything attrs.
That is, I need to swizzle component for _simply_ add a CSS class to the root element of the code tabs?

image

Or do you propose to create a special JSX component for the second block code and use it? I would like to follow the easier way.

P.S. Moreover, I don’t see anything bad, so that the built-in components of Docusaurus have their CSS classes defined (at least root elements for sure!). So what will happen next is the responsibility of the end user, but CSS classes for _identifying_ such elements should be, IMO.

**Comment by yangshun** [comment]
Your goal is to add something below all the `<Tabs>`. I think the proper thing to do here is to create a new component that contains the `<Tabs>` component and the extra thing. There's no need to add a class.

> P.S.S. It’s strange then why you don’t use CSS Modules for Docusaurus components, because end-user can change styles!

The intention is for common UI elements to use the CSS framework styles, and one-off occurrences to use CSS modules (e.g. pages).

I agree there's some disconnect in the CSS approach here. I'll mull over it for a bit.

**Comment by lex111** [comment]
> Your goal is to add something below all the <Tabs>. I think the proper thing to do here is to create a new component that contains the <Tabs> component and the extra thing. There's no need to add a class.

Well, not really, I have to follow a certain “agreement” - https://github.com/T-Regx/T-Regx.github.io/commit/5b013b5cc53a8cc4be543feef5e2e76d74528d6a#diff-9f9d4d3c55af026e1ce4d7be1c66

Although it looks somewhat strange, it’s good for me, that's why I created this PR, because I need to create a separate component, then rewrite all the examples (and there are a lot of them in current docs :cry: ).

**Comment by lex111** [comment]
Closing because this PR did not attracted support.

**Pull request closed without merging**
