### PR TITLE
Update Deploy to Vercel guide

### PR DESCRIPTION
**Pull request by samsisle**
## Motivation

Hello from the Vercel team!

Just submitting an update to the [Deploy to Vercel](https://v2.docusaurus.io/docs/deployment#deploying-to-vercel) docs.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Will simple Doc fixes require signing a CLA?

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by slorber** [comment]
Thanks, LGTM.

Not sure about the CLA, will give you an answer soon, but I think it is required.

**Comment by slorber** [comment]
Yes the CLA is required.

Is it a problem for you?

**Comment by samsisle** [comment]
@slorber I have signed the CLA under my personal GitHub account!

**Comment by slorber** [comment]
thanks :)

**Pull request merged**
