### PR TITLE
fix(v2): render correct syntax theme for current website theme

### LINKED ISSUE #2149: [v2] theme syntax highlighting doesn't display properly on initial render
Reported by @endiliey:

> Go to https://v2.docusaurus.io/docs/installation or any link, set dark mode and refresh, it will still be light theme on first page reload.

bug

### PR DESCRIPTION
**Pull request by yangshun**
## Motivation

Fixes #2149

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

1. Go to Netlify preview's /docs/introduction
2. Set to dark mode if it's not already dark mode
3. Refresh page, see code block syntax theme is dark

## Related PRs

https://github.com/facebook/docusaurus/pull/1984

### CODE REVIEW

**Comment by wgao19** [comment]
I also noticed this, thanks for fixing!

Meanwhile, I noticed that the new theme renders dark text on top of dark background for code block in light mode which isn't very friendly

image

**Comment by yangshun** [comment]
> Meanwhile, I noticed that the new theme renders dark text on top of dark background for code block in light mode which isn't very friendly

Yes there's quite a bit of follow up work to do. Our highlighting colors now are just hardcoded without awareness of the current theme.

**Comment by yangshun** [comment]
Oh cool. Should I use it? Was thinking of making the codeblocks more standalone 🤔

**Comment by endiliey** [comment]
we can leave it as it is i guess. Not really sure on the perf benefit gain, probably only the fact that it does not rerender on every mount (?) cos context is on main bundle and we alrd consume context for themeconfig too. 


But its safe to leave it. If web performance is concerned, we are still lacking on making the first contentful paint & meaningful content paint faster (need smaller css for non render blocking evaluation 😉)

**Pull request merged**
