### PR TITLE
Fix sticky footer to work on index page

### PR DESCRIPTION
**Pull request by NoamELB**
## Motivation

As discussed in https://github.com/facebook/draft-js/issues/1765, index page is missing implementation for a sticky footer.
Docs page got it already: https://github.com/facebook/Docusaurus/pull/637

The solution was to add "justify-content: space-between", since the class of the first element under navPusher is unknown (defined by the site creator). I also removed the flex-grow/shrink that it replace.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

yes

## Test Plan

Testing the latest version on all modern browsers.

Before:
before

Draft.js before:
draft js before

After:
after

Draft.js after:
draft js after

Docusaurus site with change (looks the same):
screencapture-localhost-3000-2018-05-18-22_47_19 1

## Related PRs
https://github.com/facebook/Docusaurus/pull/637
https://github.com/facebook/draft-js/pull/1759

### CODE REVIEW

**Comment by ahmadalfy** [comment]
The rule `flex-shrink: 0` is required to make it work correctly on IE11

**Comment by yangshun** [comment]
@ahmadalfy Could you help see if the current PR state vs adding that line back works on IE11? For futureproof-ness, we should start adding in comments to explain why certain CSS have to be written that way. 

It works well for me on Chrome! Unfortunately, it's hard to test on IE11 for me, will defer to @ahmadalfy.

**Comment by NoamELB** [comment]
@ahmadalfy I reverted the shrink/grow. You are right, should've looked on the Docs as well.
The problem now is that the index page doesn't have a className like docMainWrapper to set the flex-grow on (it's `this.props.children` provided by the author of the site).
I don't think we should add another wrapper element there. So we can do something like:
```
.navPusher > :first-child {
    flex-grow: 1;
  }
```
What do you think?

**Comment by JoelMarcey** [comment]
I will leave @yangshun to stamp this given I trust his UI knowledge way more than mine, but this looks reasonable to me.

**Comment by yangshun** [comment]
LGTM. Shipping it!

**Pull request merged**
