### PR TITLE
feat: Created copycode button in live code block based on legacy button.

### PR DESCRIPTION
**Pull request by hugofovargue**
## Motivation

I've migrated the copy code button from `website-1.x` to `live-code-block` package.

### RFC

* I converted `<CodeBlock />` into a class component in order to use lifecycle methods with the clipboard library. I though about refactoring it back into a sfc with hooks, but I haven't used the hooks API yet.
* I'd also consider moving the `<button>` JSX into its own component.
* Anything wrong with using `<Fragment />` inside <Highlight />? https://github.com/facebook/Docusaurus/commit/8d81436afb5c043adbac1d118b76eaa9571b4326?diff=unified#r33938022
* Anything wrong with using an setTimeout method to set the state? https://github.com/facebook/Docusaurus/commit/8d81436afb5c043adbac1d118b76eaa9571b4326?diff=unified#r33938067

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

```shell
# In project root
yarn install

# In website/
yarn start
```

Navigate to any code block in the application.

## Related PRs

Support copy codeblock button for Docusaurus 2 - #1578.

### CODE REVIEW

**Comment by hugofovargue** [comment]
> Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla. **If you are contributing on behalf of someone else (eg your employer)**, the individual CLA may not be sufficient and your employer may need the corporate CLA signed.
> 
> If you have received this in error or have any questions, please contact us at [cla@fb.com](mailto:cla@fb.com?subject=CLA%20for%20facebook%2FDocusaurus%20%231606). Thanks!

Signed the CLA.

**Comment by endiliey** [comment]
Before i review the code

This broke https://deploy-preview-1606--docusaurus-2.netlify.com/docs/writing-docs

Please use react hooks api as well.

**Comment by hugofovargue** [comment]
> Before i review the code
> 
> This broke https://deploy-preview-1606--docusaurus-2.netlify.com/docs/writing-docs
> 
> Please use react hooks api as well.

Thank you. Will make changes.

**Comment by hugofovargue** [comment]
I understand the problem. I've neglected to create a ref (or even elements) for an input and button in `<Playground />`. Exceptions are being thrown when clipboard is being passed undefined instead of the refs, and subsequently clipboard cannot be destroyed on the unmount. 

I'll refactor `<CodeBlock />` back into an SFC and learn hooks.

**Comment by endiliey** [comment]
Friendly ping. This is still not working btw :)

**Comment by hugofovargue** [comment]
Closing because I've struggled to implement the copy button into the playground component.

**Pull request closed without merging**
