### PR TITLE
docs: add pincman site to showcase

### PR DESCRIPTION
**Pull request by pincman**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [x] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Add my site to showcase

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

### CODE REVIEW

**Comment by Josh-Cena** [comment]
@pincman I have a question: what editor is it that adds a `.history` directory? Could you add it to `.gitignore`?

**Comment by pincman** [comment]
@Josh-Cena I think I forgot to add this, I will resubmit

**Comment by pincman** [comment]
@Josh-Cena I have deleted .history in the repository

**Comment by slorber** [comment]
LGTM thanks 👍

**Comment by slorber** [comment]
Should we merge the `.history` gitignore? Still not clear to me what's the purpose of it

**Comment by Josh-Cena** [comment]
It's _some_ IDE that adds it. Not a problem to be part of the PR.

**Pull request merged**
