### PR TITLE
chore(v2): run Jest tests on Windows workflow

### PR DESCRIPTION
**Pull request by Simek**
## Motivation

Currently many Jest tests fails on Windows due to paths issues. 

This PR adds additional test run step to Windows workflow **(and it is expected to fail)**.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

N/A

## Related PRs

* #3460

### CODE REVIEW

**Comment by Simek** [comment]
Test run results (https://github.com/facebook/docusaurus/pull/3481/checks?check_run_id=1159491792#step:7:5827):
Screenshot 2020-09-24 at 11 19 33

**Comment by slorber** [comment]
oh, that's unfortunate, didn't know that tests weren't passing on Windows, and it seems a bit of work to get this fixed. 

Unfortunately, I don't even have a Windows computer here 😅 not sure what I can do. I know we had windows related fixes recently using `path.posix()` method and we also have our own `posixPath()` fn in `@docusaurus/utils`

For now, we'd better keep this PR as a draft unless someone is willing to actively work on this issue.

**Comment by slorber** [comment]
Closing for https://github.com/facebook/docusaurus/pull/3540

**Comment by slorber** [comment]
https://github.com/facebook/docusaurus/pull/3959

**Pull request closed without merging**
