### PR TITLE
fix(docs): Update README.md

### PR DESCRIPTION
**Pull request by iamdarshshah**
## Motivation
It's good to just include the logo at the top of the docs. 
> These are just the changes that make it look more cleaner.
### Changes
- [x] Replaced the introducing-image with docusaurus logo
- [x] Changed the alignment of Title and Logo

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?
Yes

### CODE REVIEW

**Comment by slorber** [comment]
Hi,

Sorry but I don't agree with this, it's quite subjective and I'm pretty sure having a h1 has benefits for accessibility

**Comment by iamdarshshah** [comment]
Hey @slorber 

Thanks for reviewing it and providing your feedback. Yes, `h1` has benefits for accessibility. (It basically reflects the `Heading` for any Organisation docs & Headings are useful for labeling page regions)

I have a few questions on this, that I would like you to explain just to get a better understanding:

1. Why we can't just place a logo in README.md? (Is there any specific rules docusaurus is following, which I might not know)
2. Why didn't you agree with these changes? (Just to know, what I am missing out with)

Looking forward to know your thoughts on this.
Thank You! 👍

**Comment by slorber** [comment]
Apart from accessibility I think this change is subjective. 

I personally prefer the current version, but if you can convince any maintainer that your proposal is better, or try to poll people on Discord and they agree with you, I'd be fine merging this.

**Comment by iamdarshshah** [comment]
I agree with what you just said. Need to make a proposal for this but before that, I would create a poll for people on Discord and through that, I would like to know their views on this.

Resizing the logo for now and Will update you on the poll results in the next 24 to 36 hours.

Thanks 👍

**Comment by iamdarshshah** [comment]
Sorry for updating late. It looks like people are supporting the current version. Will support this decision!! Thanks @slorber  👍 

> Screenshot
Result

**Pull request closed without merging**
