### PR TITLE
docs(showcase): remove sites not using Docusaurus anymore

### PR DESCRIPTION
**Pull request by GatienBoquet**
## Pre-flight checklist

- [X] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

This PR addresses the issue of non-compliant entries in the `users.tsx` file by removing links that are not using Docusaurus.
Twelve non-compliant entries were identified and removed.

I am aware of the ongoing PR adding a showcase plugin to check links, but as of now, there are incorrect links in the showcase, including some that direct to sites with potential malware. 

I can address additional links problems in this PR if it's okay for you.

## Test Plan

The changes were tested by verifying that each removed link no longer appears in the `users.tsx` file. 
Additionally, I've ensured that the remaining links are correctly listed.

## Related issues/PRs

#9967 

## Not Using Docusaurus

| URL                                       | Issue                                    |
| ----------------------------------------- | ---------------------------------------- |
| <https://benthos.dev/>                     | Using Antora 3.1.2                      |
| <https://docs.quantcdn.io>                  | Using Astro v4.12.2                     |
| <https://codesweetly.com/>                  | Using Astro v4.12.3                     |
| <https://miroiu.github.io/nodify/>          | Using Astro v4.5.9                      |
| <https://outerbounds.com>                   | Using Framer 04e0834                    |
| <https://cipp.app>                         | Using Hugo 0.111.3                      |
| <https://wiki-power.com/>                   | Using mkdocs-1.6.0, mkdocs-material-9.5.27 |
| <https://wiki.7wate.com/>                   | Using Quartz                            |
| <https://callstack.github.io/react-native-testing-library/> | Using Rspress v1.20.1                   |
| <https://docs.tuist.io/>                    | Using VitePress v1.3.1                  |
| <https://k3ai.in/>                         | Using WordPress 6.6.1                   |

## Malware Link - DO NOT CLICK

| URL           | Description                                
| --------------|--------------------------------------------|
| <https://axioms.io/> | Axioms Developer Hub and Documentation Portal |

### CODE REVIEW

**Comment by slorber** [comment]
Thanks for the maintenance help 👍 

Let me know if there are others you want to remove before merge

**Comment by Josh-Cena** [comment]
I know that Hermes is no longer using Docusaurus (AFAIK), since their website just redirects to their GH.

**Comment by GatienBoquet** [comment]
All done.

**Review by Josh-Cena — APPROVED** [review]
Way to go—thanks a bunch!

**Pull request merged**
