### PR TITLE
polish(create-docusaurus): the starter template should use a navbar item "docSidebar" instead of "doc" (less fragile on updates)

### PR DESCRIPTION
**Pull request by biplavmz**
## Motivation

Fix https://github.com/facebook/docusaurus/issues/8696

Using a docSidebar item is less fragile for new Docusaurus users: they can delete/rename the intro doc without having an immediate error because the sidebar still exists

## Test Plan

locally + CI

### Test links

Deploy preview: https://deploy-preview-8712--docusaurus-2.netlify.app/

### CODE REVIEW

**Comment by slorber** [comment]
thanks for trying but unfortunately this is not the solution, the "docSidebar" item doesn't even exist yet, the feature request was about creating it first 😄

**Comment by Josh-Cena** [comment]
@slorber https://docusaurus.io/docs/api/themes/configuration#navbar-doc-sidebar?

**Comment by slorber** [comment]
oh my bad 😅 forgot we already had this sidebar item type

@biplavmz that looks like a good change, but not in the right place. You shouldn't modify example projects but instead modify init templates here:

docusaurus/packages/create-docusaurus/templates


Part of issue https://github.com/facebook/docusaurus/issues/8696

**Review by slorber — APPROVED** [review]
Thanks

Did the changes and tested locally, it works but it was `sidebarId` not `sidebarName` 🤪

**Pull request merged**
