### PR TITLE
Add InfraQL product docs website

### PR DESCRIPTION
**Pull request by jeffreyaven**
## Motivation

Big fan and advocate for Docusaurus, amazing project!  I am using this for my personal blog (already in the showcase), adding the docs site for my open source project, InfraQL - includes docs (alot of them) and a blog

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes!

## Test Plan

N/A showcase only

## Related PRs

None

### CODE REVIEW

**Review by Josh-Cena — APPROVED** [review]
Nice site :D

**Comment by jeffreyaven** [comment]
> Nice site :D

Thanks @Josh-Cena !

**Comment by Josh-Cena** [comment]
Are you sure you want this page instead of, say, the landing page where you have a bigger title?

**Comment by jeffreyaven** [comment]
> Are you sure you want this page instead of, say, the landing page where you have a bigger title?

This page will be alright, wanted to show a typical doc page @Josh-Cena

**Comment by Josh-Cena** [comment]
I see

**Pull request merged**
