### PR TITLE
chore(v2): update Prettier config

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Update config Prettier so that it is consistent with the latest version of ESLint config Airbnb , where you now **always** need to write parentheses :cry: 

https://github.com/airbnb/javascript#arrows--one-arg-parens

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

N/A.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by yangshun** [comment]
According to https://prettier.io/blog/2020/03/21/2.0.0.html, it's turned on by default right?

**Comment by yangshun** [comment]
When I upgraded Prettier just now in #2538 I think all the arrow parens were updated. So I think it's the default option now without us having to do anything.

**Comment by lex111** [comment]
Yes, but my code editor does not know about :)

**Comment by yangshun** [comment]
Ok let's merge this since it's relatively harmless. But I think if your IDE is using your project's Prettier or has an upgraded Prettier, this wouldn't be an issue.

**Pull request merged**
