### PR TITLE
feat(v2): allow home page for docs

### LINKED ISSUE #1973: [V2] Handle /docs route
## 🚀 Feature

Currently navigating to `/docs` will result in a not found page being shown (unless `pages/docs/index` exists). I'm proposing that we handle this gracefully by redirecting to the first doc page.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Showing a not found page isn't very helpful to a user that's likely searching for the documentation.

In most cases, I can imagine the user wanting to be redirected to valid documentation.

## Pitch

* Better UX for the end-user.
* Can link to `/docs` instead of a specific page which allows us to change or remove that page without breaking the links.
* Looking at the existing V2 showcase, they all link to the first page of docs anyway.

If we agree on a solution, I'd also be happy to implement it and open a PR.

### LINKED ISSUE #2507: feat(v2): home page for docs
## 🚀 Feature

> When I navigate to https://v2.docusaurus.io/docs, I see empty page, not even a sidebar on the left. It would be great if we have a way to define content for this page e.g. docs/index.md

Refer to https://v2.docusaurus.io/feedback/p/home-page-for-docs

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Pitch

This can be specified via an option on the docs plugin.

### LINKED ISSUE #2567: Allow marking a documentation page as the landing page
## 🚀 Feature

Allow maintainers to configure a documentation page as their landing page.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Currently, Docusaurus allows users to setup in a 'docs only' mode, which requires setting your `routeBasePath` to an empty string and redirecting visitors by altering the `/src/pages/index.js` file so it points to your desired destination.

However, this means you're (needlessly) redirecting a visitor to a different URL and thus are leaving the original 'landing page' that you'd expect to see when visiting `https://myawesomedocs.com/`, for example. Manually recreating the layout of your documentation pages in the `index.js` file is also an option, but seems cumbersome.

## Pitch

Allowing maintainers to mark a particular documentation page as their landing page, would get rid of having to change the settings/files I mentioned before and make it easier for people to get a 'docs only' site up and running. Additionally, I believe it could also benefit in terms of SEO, as you aren't redirecting people "for no reason".

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

I am really excited to close all three of the listed PRs, finally this issue, which our users constantly mention, will be closed! 😝

Resolve #2507
Resolve #2567
Resolve #1973 

Related issue on Canny - https://docusaurus.canny.io/admin/board/feature-requests/p/home-page-for-docs

Yes, indeed, although there are not many changes, the complexity of the code increases, but this is all because to cover all use cases:

- Docs without versioning
- Docs with versioning
- Docs-only mode
- Using existing document as home page
- Using special-purpose document (default is "_index") as home page
- Possibility to have the own docs page (thereby  override the default home page, this may be useful in versioning docs)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

See docs and preview (eg. https://deploy-preview-2652--docusaurus-2.netlify.app/docs/)

P.S. You can see in snapshots diff that the sorting of routes has been changed, that's actually how it should be (so you don't have to worry about that). 

https://github.com/facebook/docusaurus/blob/1f00d15c7439fdbfb37d57f0cafdaedb2b34ef41/packages/docusaurus/src/server/plugins/index.ts#L103-L105

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by lex111** [comment]
It is strange why Travis CI fails, I have everything OK on my local machine.
@yangshun  could please you force it to restart?

**Comment by lex111** [comment]
Again, there seems to be a problem with snapshots being different in local (dev) and test (CI) environments. I take it this is due to the asynchronous processing of routes, perhaps it is worth sorting routes to achieve the same result?

**Comment by lex111** [comment]
Even in my fork, tests with changes to this PR successfully pass. I can’t understand why in this (original) repo does not pass the tests.

```
Test Suites: 47 passed, 47 total
Tests:       267 passed, 267 total
Snapshots:   123 passed, 123 total
Time:        134.669s
Ran all test suites.
Done in 136.01s.
```

**Comment by lex111** [comment]
Hell yeah, I added sorting for child routes and tests began to pass for CI. Now we have the same result on all environments.

**Comment by benmccann** [comment]
Thanks for this! Just FYI, this PR will need a rebase

The other thing that will help us a lot with the homepage is https://github.com/facebook/docusaurus/issues/2537

**Comment by lex111** [comment]
> Should we add this feature into the examples too?

Do you mean init template?

**Comment by yangshun** [comment]
Oh yes the templates. I think we should add useful defaults to the templates.

**Pull request merged**
