### PR TITLE
fix(theme-classic): adjust shadow on code block

### PR DESCRIPTION
**Pull request by chernodub**
Changed a `border-radius` on code-block container in order for it to match the inner code element, this way `box-shadow` outlines the code-block properly.

## Motivation

The code-block looked broken
image

Now it's fine
image

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Served the app locally and checked it manually

### CODE REVIEW

**Comment by Josh-Cena** [comment]
cc @lex111 This will revert part of your changes in #6987

**Comment by lex111** [comment]
Good catch, thanks, could you please also replace current value with `inherit` one in `box-shadow` property for `.codeBlockContent` in this case?

**Comment by chernodub** [comment]
Thanks for the suggestion @lex111. I've updated the code 🙂

**Comment by Josh-Cena** [comment]
Super nit but setting shadow on the content actually causes regression on code blocks with title. It's more prominent if you use a tall shadow:

image

**Comment by lex111** [comment]
Oh yes, then we will have to duplicate these properties in two these elements.

**Comment by chernodub** [comment]
Guys, I've reverted the last changes. But I wonder, do we really need a `box-shadow: inherit` on `codeBlockContent`? This causes the shadow to be applied twice, so looks inconsistent with other stuff (like callout).

Without `inherit`:
image

With `inherit`:
image

**Comment by lex111** [comment]
Sorry for misleading, I meant `border-radius` of course in my previous comment. So in `.codeBlockContent` we can use `inherit` value for `border-radius`. This should work well.

**Comment by chernodub** [comment]
Thanks for clarification, changed it as you suggested.

**Review by lex111 — APPROVED** [review]

**Comment by lex111** [comment]
@chernodub thanks!

**Pull request merged**
