### PR TITLE
fix(v2): add support dark theme for version badge

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Currently in dark mode, the version badge looks very light.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

| Before   | After    |
| -------- | -------- |
| image | image |

### CODE REVIEW

**Comment by lex111** [comment]
I meant that in dark mode should use dark shades of colors, right?
In this case, we need to add dark theme support for Infima components...

ср, 18 дек. 2019 г. в 14:27, Endi <notifications@github.com>:

**Comment by endiliey** [comment]
> I meant that in dark mode should use dark shades of colors, right?
In this case, we need to add dark theme support for Infima components...

Not really sure but do you agree with me this should be in infima ? Like infima is not gonna patched with this if its merged here. 

On another note this is just my opinion. gonna cc the right guy @yangshun

**Comment by lex111** [comment]
Yes, of course I agree, but I just need confirmation that it support will
be in Infima (because it is not fast to implement).
Although, as a workaround, we can take this PR, it is unlikely that in the
near future something will change, or we can use hard-coded value.

ср, 18 дек. 2019 г. в 15:08, Endi <notifications@github.com>:

**Comment by wgao19** [comment]
Can we pr infima for this change?  I do not see this as an urgent change, we should do this properly.

And agree we should select colors for dark mode that satisfy accessibility requirements.

**Comment by lex111** [comment]
Fine, closing this PR :eyes:

**Pull request closed without merging**
