### PR TITLE
refactor(v2): better docs metadata

### PR DESCRIPTION
**Pull request by endiliey**
## Motivation

This PR is an attempt to make our docs data structure to be more efficient while achieving the same functionality. This should solve scalability problem #1782

- Delete useless metadata
- Colocate related metadata better
Previously, we have something called `docsMetadata` that contains all the metadata of all docs pages. It is used as a lookup table for certain doc page to convert `id` into its corresponding `metadata` like `title` and `permalink`. This poses a huge problem because as the number of docs grow bigger, the client bundle size will increase linearly. 

Current docu v2 docs for example, the `docsMetadata` itself is alrd ~15kb
before2

With this PR, the docsMetadata is just ~2kb 
after2

 In fact, this PR makes our build time much faster and consume less memory as well

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

yes

## Test Plan

- Website `prev` and `next` button is working properly
- The docs sidebar is still working like previously
- Changed test passes

### CODE REVIEW

**Comment by endiliey** [comment]
> that's why I added legacy to the name. Do you think that approach is necessary?
i think it will be hard to maintain two plugins with different component

> see whether we can improve the sidebar with this also.
actually the sidebar has been improved also. instead of doing the lookup table client side, we do it server side (at build time) instead. The sidebar component will only receive a very-easy-to-digest props

**Comment by yangshun** [comment]
> i think it will be hard to maintain two plugins with different component

I don't intend to maintain the legacy one, just keep it there. But I guess we could just move things now. Only users who swizzled the doc components need to re-implement their doc components because the data structure has changed. No that many people swizzled I think.

> actually the sidebar has been improved also.

Ah I meant the React component, to collapse categories if the page is not active, expand when item is active. I could tackle this later :)

**Comment by endiliey** [comment]
> Ah I meant the React component, to collapse categories if the page is not active, expand when item is active. I could tackle this later :)

Sure thing. To find current page you might want to pass `location` props to the sidebar as well.

https://github.com/facebook/docusaurus/blob/e7ba8af6d9e83b89f967acaa53a218a8efdfa31d/packages/docusaurus-theme-classic/src/theme/DocLegacyPage/index.js#L27

```diff
- <DocLegacySidebar docsSidebars={docsSidebars} sidebar={sidebar} />
+ <DocLegacySidebar location={location} docsSidebars={docsSidebars} sidebar={sidebar} />
```

The sidebar content data structure will look like this. It's only either `category` or `link` type
```json
[
      {
        "type": "category",
        "label": "Guides",
        "items": [
          {
            "type": "link",
            "label": "Creating Pages",
            "href": "/docs/creating-pages"
          },
          {
            "type": "link",
            "label": "Styling and Layout",
            "href": "/docs/styling-layout"
          },
          {
            "type": "category",
            "label": "Docs",
            "items": [
              {
                "type": "link",
                "label": "Markdown Features",
                "href": "/docs/markdown-features"
              },
              {
                "type": "link",
                "label": "Sidebar",
                "href": "/docs/sidebar"
              }
            ]
          },
          {
            "type": "link",
            "label": "Blog",
            "href": "/docs/blog"
          },
          {
            "type": "link",
            "label": "Analytics",
            "href": "/docs/analytics"
          }
        ]
      }
    ]
```

**Comment by yangshun** [comment]
I'm working on it now, have a PR almost up!

**Pull request merged**
