### PR TITLE
docs(v2): i18n doc + polish

### PR DESCRIPTION
**Pull request by slorber**
## Motivation

Write the initial i18n doc

Entry point: https://deploy-preview-4014--docusaurus-2.netlify.app/classic/docs/next/i18n/introduction

### CODE REVIEW

**Comment by clairefro** [comment]
Excellent write-up and tutorial, thank you! :pray:

Some suggestions: 
1. In `Introduction` or `Tutotrial`, it would be very helpful to **include an example project filetree structure for a basic FR/EN site** à la [this](https://deploy-preview-4014--docusaurus-2.netlify.app/classic/docs/next/docs-introduction#document-id). Doc location is crucial in this framework.

2. In `Use Crowdin` or `FAQ`, regarding CI it may be helpful to share that **Crowdin has integrations with Github** and other version management sites. 

To setup Github + Crowdin integration: 
- As admin in Crowdin project dashboard, go to "Integrations" tab 
- Click "Github" and follow the instructions for setup. A wizard helps you specify the directories/docs you want to be subject to translation, and creates `crowdin.yml` and puts it in your project for you
- Your project is now synced. Translations made in Crowdin are automatically PRed to Github Repo, and changes to source documents are automatically picked up by Crowdin for re-translation. 

image

You can edit the sync settings
image

You can also manually trigger a sync by visiting "Integrations" > "Github" > "Sync Now"
image

**Comment by clairefro** [comment]
P.S. - are there any SEO considerations to be aware of?

**Comment by slorber** [comment]
Thanks.

Will include a project tree example

For now I just put a simple note about the github integration here: https://deploy-preview-4014--docusaurus-2.netlify.app/classic/docs/next/i18n/crowdin#automate-with-ci

Unfortunately, and after talking with Crowdin support, it does not work if the crowdin.yml is not at the root of the repo (ie `website/crowdin.yml` does not work, as I use this in the tutorial). Don't really understand why but unfortunately that's the current state 😅 I may need to adapt the tutorial 

About SEO, I don't think there's much to be said apart from that I'll add support for `hreflang` meta headers + an option to disable the headers. Let me know if you think about something else that could be useful.

**Comment by clairefro** [comment]
> Unfortunately, and after talking with Crowdin support, it does not work if the crowdin.yml is not at the root of the repo

strange! if you'd like a working example, we have github crowdin integration working fine in this repo:
https://github.com/redwoodjs/learn.redwoodjs.com

**Pull request merged**
