### PR TITLE
chore(v2): upgrade dependencies

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Bump deps. There is a slight decrease in all website bundles from 2.41 MB to 2.34 MB.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Starting dev server and building website works correctly (tested with [this](https://github.com/facebook/docusaurus/blob/master/admin/publish.md#2-build-and-test-the-project) script)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by slorber** [comment]
thanks, that looks safe to upgrade

**Comment by Simek** [comment]
@lex111 @slorber - It looks like this dependencies bump breaks the V1 build on CI - https://github.com/facebook/docusaurus/pull/3730

**Comment by HonkingGoose** [comment]
I have a problem with my syntax highlighting in code blocks breaking on `@mdx-js/react v1.6.21` where it was working before on `1.6.19`. Are you not having this problem with your update?

See https://github.com/mdx-js/mdx/issues/1320 for a full report of this problem.

**Comment by lex111** [comment]
I ran into this problem, but it turned out that one more dependency had to be updated to set things right (it seems it was related to `loader-utils` dep, I don't remember exactly).

**Comment by HonkingGoose** [comment]
Well I managed to fix my problem by upgrading other dependencies as well. That was a good tip! Thank you @lex111! :smile: 

I really don't know what the specific troublemaker is for my problem. But it's fixed for now at least. :+1:

**Pull request merged**
