### PR TITLE
add documentation regarding usage of nested docs + git ignore .idea

### LINKED ISSUE #855: Document the possibility to namespace markdown docs
## 🚀 Feature

Currently the approach is to stuff every doc inside docs folder and if the docs grows on an on, it's a bit hard to find the needed doc. What I've seen works but it's nowhere documented is to omit the id from markdown document and have them placed inside directories. Then later reference them as `/dir/doc`

Document the possibility of structuring the docs across directories aka name spacing them. Currently if placing a document inside a folder then referencing it by id will break. However if placing it inside a directory and omitting the id it can be referenced such as `directory/document-name`

## Motivation
It is important to outline this because otherwise stuffing markdown documents inside root docs becomes a mess real quick for large documentations

## Pitch

This is not really a feature, yet an enhancement of better structuring. As far as I've seen it's already implemented it's just not documented yet.

Thanks for this awesome tool guys and sorry for throwing proposals at you 🗡

### PR DESCRIPTION
**Pull request by steevehook**
## Motivation
Glad to contribute to such a nice project 🥇

## Test Plan

Added changes to `api-doc-markdown` then created a new version in order to be able to test

## Moderator Edit:
Close #855

### CODE REVIEW

**Comment by endiliey** [comment]
Thanks for the PR @steevehook 

1. There is no need to cut version 1.3.3 for this. All changes in docs will be reflected in `next`. So it is available for example at: https://deploy-preview-860--docusaurus-preview.netlify.com/docs/en/navigation#adding-documents-to-a-sidebar
2. I've moved it to `navigation` document instead and simplified the wording

I will let @yangshun or @JoelMarcey see the wordings one more time before merging this

**Comment by steevehook** [comment]
My pleasure contributing ❤️  @endiliey. Was nice to have a look in the project source, and sorry for the rework. Guess I'll need to familiarize myself with the project to know better where's what. If any other contribution needed I'll be around

**Comment by endiliey** [comment]
@JoelMarcey because this is supposed to be documented for >= 1.2.0 when subdirectories were implemented

**Comment by JoelMarcey** [comment]
Ok - fair enough. That may be the first time we retroactively added docs for previous versions.

**Pull request merged**
