### PR TITLE
docs(v2): Indent code example to improve readability

### PR DESCRIPTION
**Pull request by rluvaton**
## Motivation
Hard to understand without the indentation

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

**Comment by rluvaton** [comment]
For some reason the indentation are not displayed 🤔

**Review by slorber — APPROVED** [review]
thanks 👍

**Comment by rluvaton** [comment]
> thanks 👍 

Happy to help, but the indentation are not working, do you know why?

**Comment by Josh-Cena** [comment]
@rluvaton They are showing up; remember to check under `docs/next/` (for `beta-4`) rather than `docs/`.

**Comment by rluvaton** [comment]
> @rluvaton They are showing up; remember to check under `docs/next/` (for `beta-4`) rather than `docs/`.

Ahhhh, I got it, thanks 👍🏻

**Pull request merged**
