### PR TITLE
Fix edit button

### PR DESCRIPTION
**Pull request by chenglou**
Before:
screen shot 2018-06-30 at 7 28 35 pm
After:
screen shot 2018-06-30 at 7 28 57 pm

### CODE REVIEW

**Comment by chenglou** [comment]
Hold on for the search box

**Comment by chenglou** [comment]
Np. I'll revert the search bar vertical alignment change for now. It's correctly aligned in safari and off by one pixel in chrome. So if I adjust chrome it'll break safari instead.

**Comment by yangshun** [comment]
Is this good to merge?

**Comment by chenglou** [comment]
Yes

**Comment by chenglou** [comment]
Quick question: at e.g. 1200px, the headerWrapper left/right padding are different on the main page than on the docs page now. Is that intentional?

**Comment by yangshun** [comment]
Do you have an example? Which rule are you referring to?

**Comment by chenglou** [comment]
https://github.com/facebook/Docusaurus/blob/97eaaad7440b7d45ab428c4e4019796e1e9f8664/lib/static/css/main.css#L463 and https://github.com/facebook/Docusaurus/blob/97eaaad7440b7d45ab428c4e4019796e1e9f8664/lib/static/css/main.css#L1942

Main page:
screen shot 2018-06-30 at 7 59 47 pm

Doc page:
screen shot 2018-06-30 at 8 00 41 pm

For other sizes, the transition from main page to doc page doesn't move the header around

**Comment by yangshun** [comment]
Oh yes that's intentional. The header will be wider when we have the `onPageNav` (right side nav) in the main container.

**Pull request merged**
