### PR TITLE
chore: Bump webpack-dev-server to resolve DOS vulnerability

### PR DESCRIPTION
**Pull request by bo-carey**
## Pre-flight checklist

- [ ] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

### CODE REVIEW

**Comment by slorber** [comment]
Going to close this as a possible supply chain attack attempt @bo-carey 

CleanShot 2024-07-03 at 18 25 37@2x

I'll report your account in 24h to GitHub unless you clearly explain what this PR is about, and explain what is this URL "https://nexus.use1.infra-pure.cloud/"

**Comment by bo-carey** [comment]
Oh, sorry that is due to my npm settings resolving to my own registry. Completely unintentional. I'll close the PRs and run them again from the default registry.

**Comment by slorber** [comment]
I understand the mistake, but can't just trust your words considering the possible harm this PR could do. 

I'll also ask you to explain what vulnerability is fixed by upgrading what dependency.  Please give external links to each 3 vulnerabilities you attempt to fix and give your motivations to get them fixed. How did you find about these vulnerabilities. 

Otherwise I still have to report you.

We just added Socket security to the repo to prevent such possible issues in the future.

**Comment by Josh-Cena** [comment]
@bo-carey: there's absolutely no need to try to fix these issues. The ones you are fixing are dev dependencies and don't have actual attack vectors.

**Comment by bo-carey** [comment]
> I understand the mistake, but can't just trust your words considering the possible harm this PR could do.
> 
> I'll also ask you to explain what vulnerability is fixed by upgrading what dependency. Please give external links to each 3 vulnerabilities you attempt to fix and give your motivations to get them fixed. How did you find about these vulnerabilities.
> 
> Otherwise I still have to report you.
> 
> We just added Socket security to the repo to prevent such possible issues in the future.

Totally understand. I was just trying to be proactive to help with vulnerabilities marked by snyk, which is what I'm personally using as a security monitor. The vulnerabilities are documented on their site, but I'll link them here for posterity:

- `micromatch` - https://security.snyk.io/vuln/SNYK-JS-MICROMATCH-6838728
- `webpack-dev-middleware` - https://security.snyk.io/vuln/SNYK-JS-WEBPACKDEVMIDDLEWARE-6476555
- `ws` - https://security.snyk.io/vuln/SNYK-JS-WS-7266574

I realize that consumers can resolve these issues themselves. Sorry for the misunderstanding! I'll be sure to double check my changes in the future.

**Comment by slorber** [comment]
Thanks for the explanations

This looks like a legit mistake, I won't report it 👍

**Pull request closed without merging**
