### PR TITLE
Showcase Submissions: Please add our site in showcase

### PR DESCRIPTION
**Pull request by Ajay-Dhangar**
## Pre-flight checklist

- [X] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [X] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

I propose adding CodeHarborHub to the Docusaurus showcase to provide users with access to high-quality, free educational resources in technology, akin to platforms like W3Schools, GeeksforGeeks, and LeetCode. CodeHarborHub offers comprehensive DSA tutorials, interactive coding challenges, and expert-led courses, making it an invaluable resource for learners at all levels to develop and enhance their skills.

## Test Plan

To ensure the quality and functionality of this PR, I have conducted the following tests:

1. **UI Testing**: Verified the visual changes on different devices and browsers.
2. **Functionality Testing**: Tested all interactive elements and functionalities.
3. **Performance Testing**: Checked the page load times and optimized where necessary.

### Screenshot of my testing

 image

### Test links

Deploy preview: https://deploy-preview-10283--docusaurus-2.netlify.app/showcase/?name=codeharborhub

## Related issues/PRs

N/A

### CODE REVIEW

**Comment by slorber** [comment]
Hi

I think we already discussed this in DM, showcase submissions should be sent here https://github.com/facebook/docusaurus/discussions/7826

**Comment by Ajay-Dhangar** [comment]
> Hi
> 
> I think we already discussed this in DM, showcase submissions should be sent here #7826

Hi @slorber,

I wanted to ask if my site, Codeharborhub, would be a good fit for your showcase. Codeharborhub is a dream project of mine, aimed at helping beginners build their careers in tech. Your open-source project, Docusaurus, has provided invaluable setup and plugins for my site, and I'm excited to share my work with you and the community. Thank you for your contributions and support!

Best regards,
@Ajay-Dhangar

**Comment by slorber** [comment]
@Ajay-Dhangar thanks for your feedback, but please stop submitting your site everywhere

We'll consider it once we are ready to do so

**Comment by Ajay-Dhangar** [comment]
Okay, and thanks for your feedback. I apologize for any inconvenience caused.

**Pull request closed without merging**
