### PR TITLE
docs: showcase user Testing Library

### PR DESCRIPTION
**Pull request by Hongarc**
### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

**Comment by Hongarc** [comment]
> Thanks @Hongarc, have you asked them for permissions to show case? Could you link the issue here?

Sorry, I forgot.

Issue #1080

**Comment by kentcdodds** [comment]
You have a 👍 from me!

**Comment by yangshun** [comment]
Wow that was a fast reply, thanks @kentcdodds!

**Comment by Hongarc** [comment]
I asked testing-library/testing-library-docs#96 and wait for the response

**Comment by Hongarc** [comment]
@yangshun They accepted.

**Pull request merged**
