### PR TITLE
docs(v2): update sidebar migration from v1 to v2 guide

### LINKED ISSUE #1841: [v2] update v1-v2 migration guide docs on sidebars category
## 📚 Documentation

In v1, we only allow 1 nested level sidebar depth. It's infinity in v2

Compare
https://docusaurus.io/docs/en/navigation#adding-subcategories
and
https://v2.docusaurus.io/docs/sidebar#category

Turns out that v1 subcategories type 'category' is named `subcategory` and `items` is named 'ids'.

Update the migration guide https://github.com/facebook/docusaurus/edit/master/website/docs/migrating-from-v1-to-v2.md
### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

### PR DESCRIPTION
**Pull request by ThakurKarthik**
This change is regarding an issue opened at here 
Fix #1841 

## Motivation

Helps users in migrating from v1 to v2 of docusaurus.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### CODE REVIEW

**Comment by ThakurKarthik** [comment]
@endiliey Is this what you meant earlier

correction

**Comment by endiliey** [comment]
yes. but u dont need to show duplicates.

```diff
+ a
- b
+ a
- b
```

is not as good as
```diff
+ a
- b
```

**Comment by ThakurKarthik** [comment]
Showing one example in the json body.
correction2

**Comment by endiliey** [comment]
Just push your update. I'll patch it later on 😂

**Pull request merged**
