### PR TITLE
fix(v2): evaluate code in live editor on client only

### LINKED ISSUE #2986: Live editor render twice times on page first mount
## 🐛 Bug Report

Live editor render component twice times

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. Paste code below into .mdx file

```
	```jsx live
	function Demo() {
    	React.useEffect(() => console.log('mount'), [])
    	return null
	}
	```
```

## Expected behavior

<!--
  How did you expect your project to behave?
  It’s fine if you’re not sure your understanding is correct.
  Write down what you thought would happen.
-->

log 'mount' one time

## Actual Behavior

<!--
  Did something go wrong?
  Is something broken, or not behaving as you expected?
  Describe this section in detail, and attach screenshots if possible.
  Don't only say "it doesn't work"!
-->

```
mount
mount
```

## Your Environment

<!-- Include as many relevant details about the environment you experienced the bug in -->

- Docusaurus version used: 2.0.0-alpha.58
- Environment name and version: Chrome 83
- Operating system and version (desktop or mobile): macOS

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

<!--
  What happens if you skip this step?

  Someone will read your bug report, and maybe will be able to help you,
  but it’s unlikely that it will get much attention from the team. Eventually,
  the issue will likely get closed in favor of issues that have reproducible demos.

  Please remember that:

    * Issues without reproducible demos have a very low priority.
    * The person fixing the bug would have to do that anyway. Please be respectful of their time.
    * You might figure out the issues yourself as you work on extracting it.

  Thanks for helping us help you!
-->

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Attempt to fix #2986 without much large changes.  

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Page with demo example - https://deploy-preview-4318--docusaurus-2.netlify.app/classic/examples/markdownPageExample#test

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by lex111** [comment]
@slorber this PR does not solve the problem that we currently performing twice rendering (in order to define the proper Prism theme on the client-side during the initial rendering).

For a more detailed I recommend you checkout these links:

- Description of bug with dark Prism theme (FOUC), for the solution of which it was necessary to create the [`isClient` state in the root App](https://github.com/facebook/docusaurus/blob/master/packages/docusaurus/src/client/App.tsx#L25-L29) whice causes re-renders: https://github.com/facebook/docusaurus/pull/1984#issuecomment-569015188 ([PR with implementation](https://github.com/facebook/docusaurus/pull/2069))
- https://github.com/facebook/docusaurus/pull/2057#issuecomment-559813720
- https://github.com/facebook/docusaurus/pull/2150

Well, perhaps there is a better solution for this case?

**Comment by slorber** [comment]
Perhaps there is a better solution, but this one seems to solve the problem without side effect for now so let's use that

**Comment by lex111** [comment]
Yes, my previous comment was a challenge for the future to make you aware of why the `isClient` state was added, which causes a side effect as double rendering.

**Comment by slorber** [comment]
thanks :) didn't know about these issues

**Pull request merged**
