### PR TITLE
docs: make tutorial code block directly copyable

### PR DESCRIPTION
**Pull request by samgutentag**
## Motivation

Sample code block could not be copy/pasted as the tutorial mentions with the lines that appear to be from a diff tool.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes! this is so small, wasn't sure if it should be an issue or a PR

## Test Plan

None

## Related PRs

None that I could find

### CODE REVIEW

**Review by Josh-Cena — APPROVED** [review]
I'm okay to change this to make the tutorial less confusing, but please do note that:

> with the lines that appear to be from a diff tool.

The `diff` code block is a common technique for documentation to show a "user change". It's not the verbatim output from any tool. For example, here it's telling you to delete the existing `items`, and add `items: ['hello'],`. You will see this used in other places as well.

**Comment by samgutentag** [comment]
oh! ill admit i don't think I have ever seen that syntax before but it makes a ton of sense.

Thanks for taking the time to explain!

**Comment by slorber** [comment]
> oh! ill admit i don't think I have ever seen that syntax before but it makes a ton of sense.

You can see this on every single PR 😅 

image

**Comment by samgutentag** [comment]
oh well yea I see it in diff tools all the time! I meant more that I had not seen it in a sample code block like that 😄

**Pull request merged**
