### PR TITLE
fix(website): use react-lite-youtube-embed for lazy YouTube video

### PR DESCRIPTION
**Pull request by matkoch**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

As discussed with @Josh-Cena. This is recommended in the lighthouse docs:

https://web.dev/third-party-facades/?utm_source=lighthouse&utm_medium=devtools#youtube-embedded-player

### Test links

Deploy preview:

- https://deploy-preview-7390--docusaurus-2.netlify.app/
- https://deploy-preview-7390--docusaurus-2.netlify.app/docs/

## Related issues/PRs

https://github.com/facebook/docusaurus/pull/6746

### CODE REVIEW

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
There's another video on `/docs/` as well. Could you take some time to migrate that?

**Comment by Josh-Cena** [comment]
@matkoch Besides the change requested above, I need to make some refactors as well. Please give me write access to your PR.

**Comment by matkoch** [comment]
Not sure how to resolve this in `introduction.mdx` (previously `.md`):

```
<div className="video-container">
  <LiteYouTubeEmbed
    id="Yhyx7otSksg"
    params="autoplay=1&autohide=1&showinfo=0&rel=0"
    title="Docusaurus: Documentation Made Easy"
    poster="maxresdefault"
    webp
  />
</div>
```

From commit:

```
CSpell: Files checked: 1, Issues found: 2 in 1 files
/Users/matt/code/docusaurus/website/docs/introduction.mdx:57:9 - Unknown word (Yhyx)
/Users/matt/code/docusaurus/website/docs/introduction.mdx:57:16 - Unknown word (Sksg)
```

**Comment by Josh-Cena** [comment]
91 perf score! Haven't seen that in quite a while... Awesome!

**Comment by slorber** [comment]
Not a big deal but I'd rather create our own "YoutubeEmbed" component (using this lib) in "website/src/theme/components" rather than importing a third-party lib everywhere directly

**Pull request merged**
