### PR TITLE
Remove dead code in sitemap.js

### PR DESCRIPTION
**Pull request by sufuf3**
## Motivation

I removed three variables which are not used.
```
const blogFolder = path.resolve('../blog/');
const blogRootURL = siteConfig.url + '/blog';
const jestImage = siteConfig.url + siteConfig.headerIcon;
```

## Related Issue
#429 

Thank you. :)

### CODE REVIEW

**Comment by JoelMarcey** [comment]
@sufuf3 Hi. Thanks for this PR. 

I was curious - did you test to make sure that the Docusuarus site ran locally without any errors after you made this pull request?

https://github.com/facebook/Docusaurus/blob/master/admin/testing-changes-on-Docusaurus-itself.md#testing

**Comment by JoelMarcey** [comment]
I am pretty sure the PR is safe and the code isn't used; just trying to figure out a way for you to test or verify that is the case.

**Comment by sufuf3** [comment]
@JoelMarcey Thank you for your guidance.
I follow `testing-changes-on-Docusaurus-itself.md#testing` and run `npm run start` everything looks fine.
My environment is `node v8.9.4`, `npm v5.6.0`, `nodejs v4.2.6`.
Thank you.

**Comment by JoelMarcey** [comment]
Excellent! Merging now.

**Comment by sufuf3** [comment]
Thank you :)

**Pull request merged**
