### PR TITLE
Handle build-files promise error & exit properly

### LINKED ISSUE #805: Build script returns zero exit code due to unhandled promise rejection, non-zero exit code expected
It's possible for `docusaurus build` to encounter an error during a build, but the process returns a zero exit code. This causes systems like Circle CI to consider the build a success, and if your CI process happens to deploy automatically when tests are green, it could cause your [website to go down](https://twitter.com/RaphaelKats/status/1011724264146329600).

### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

`"docusaurus": "^1.3.0"`

### Steps to Reproduce

1. In an existing Docusaurus website, go ahead and delete an arbitrary markdown file from `versioned_docs`. To reproduce with https://github.com/facebook/react-native-website, delete `versioned_docs/version-0.5/removing-default-permissions.md` from master.
2. Run `docusaurus build`

### Expected Behavior

Docusaurus throws error due to improper sidebars file, returns non-zero exit code.

### Actual Behavior

Docusaurus returns zero exit code, with the following output in the console:

```
Site built successfully. Generated files in 'build' folder.
(node:170) UnhandledPromiseRejectionWarning: Error: Improper sidebars file for version 0.56-RC, document with id 'version-0.56-RC-removing-default-permissions' not found. Make sure that all documents with ids specified in this version's sidebar file exist and that no ids are repeated.
    at _loop (/home/circleci/react-native-website/website/node_modules/docusaurus/lib/server/readCategories.js:58:17)
    at readCategories (/home/circleci/react-native-website/website/node_modules/docusaurus/lib/server/readCategories.js:34:53)
    at DocsSidebar.render (/home/circleci/react-native-website/website/node_modules/docusaurus/lib/core/DocsSidebar.js:18:26)
    at processChild (/home/circleci/react-native-website/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2204:18)
    at resolve (/home/circleci/react-native-website/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2061:5)
    at ReactDOMServerRenderer.render (/home/circleci/react-native-website/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2380:22)
    at ReactDOMServerRenderer.read (/home/circleci/react-native-website/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2354:19)
    at renderToStaticMarkup (/home/circleci/react-native-website/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2737:25)
    at renderToStaticMarkupWithDoctype (/home/circleci/react-native-website/website/node_modules/docusaurus/lib/server/renderUtils.js:16:30)
    at /home/circleci/react-native-website/website/node_modules/docusaurus/lib/server/generate.js:199:17
(node:170) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:170) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 36.38s.
```

### Reproducible Demo

See `yarn test` in https://circleci.com/gh/facebook/react-native-website/1513

### PR DESCRIPTION
**Pull request by endiliey**
## Motivation

Fix #805 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Try with https://github.com/facebook/react-native-website, delete versioned_docs/version-0.5/removing-default-permissions.md from master.

Run docusaurus build

Before
before3

After
after3

Try with Docusaurus, delete first doc from versioned_docs version-1.0.11 and `yarn build`
Before
before4

After
after4

### CODE REVIEW

**Comment by JoelMarcey** [comment]
@endiliey @yangshun Should we release 1.3.1 given this and other fixes?

**Comment by yangshun** [comment]
Yes we should! Would you like me to do it since you're on PTO? I can do it tonight.

**Comment by JoelMarcey** [comment]
I am on PTO starting Tuesday -- but you can still do it tonight, if you would like 👍 Just let me know.

**Comment by hramos** [comment]
Sweet! I love it when I come back to check on an issue, but a PR has already been sent, reviewed, and merged. <3

**Comment by yangshun** [comment]
Ok I'll do it

**Pull request merged**
