### PR TITLE
Migrate to React 16

### PR DESCRIPTION
**Pull request by gedeagas**
## Motivation
Sadly Docusaurus is still using the old React 15 :(. With many major improvement and features that react v16 offers, I think this is the right time to update.

Fixes https://github.com/facebook/Docusaurus/issues/539

### Have you read the [Contributing Guidelines on pull requests]
Yes

### CODE REVIEW

**Comment by yangshun** [comment]
Thanks for doing this @gedeagas! I wanted to wait till we had some tests in place before upgrading to React 16, but I guess it if builds it should be fine 😄 

Just to be clear, Docusaurus generates static output in the build step using React and is more of a website rather than a web app, so we don't really benefit too much from the perf improvements in React 16.

I'll do a little more extensive testing before approving.

**Comment by JoelMarcey** [comment]
Wow - that is all it takes to upgrade? I thought it would have taken a bit more 😄

**Comment by gedeagas** [comment]
Hi @yangshun I know, we use react renderToStaticMarkup right? I am planning to change the function to renderToStaticNodeStream but I guess it outputs the same thing and we don't need to change it. 

Maybe any of the guys here want to use fragments or other feature that would be available in the next release ?. I know for our use case upgrading to v16 doesn't offer us many features or improvements.

Btw I didn't do much research on this but isn't renderToStaticMarkup on v16 is a bit faster than on v15?

**Comment by gedeagas** [comment]
@yangshun please test it, That is the reason why I tag this as WIP. If you guys find something fishy or wrong I will be happy to work on it.

**Comment by yangshun** [comment]
Tested it locally and it worked great. Thanks for the help!

**Pull request merged**
