### PR TITLE
fix(v2): remove Markdown syntax from excerpt

### LINKED ISSUE #2607: Meta description not formatting/removing markdown
## 🐛 Bug Report

I don't know if this is 100% a bug or not, but the meta description created for blog posts includes unformatted markdown.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Write a blog post where markdown is used in the section that will become the meta description.

## Expected behavior

I'd expect markdown to be stripped out.

## Actual Behavior

Markdown does not get stripped out.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.50
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Firefox 74.0.1
- Operating system and version (desktop or mobile): Arch Linux (desktop)

## Reproducible Demo

https://github.com/protoncr/tourmaline

You can also open https://tourmaline.dev/blog/another-day-another-release and check the meta description tag using the inspector. You'll see that the link is formatted as markdown still.

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Resolve #2607

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

See preview and tests.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by lex111** [comment]
Ok, I used Remark for these purposes, but I noticed that there was a slight decrease in performance compared to the previous solution that uses regular expressions. I commented lines related to the previous solution so that you can see for yourself which option is better.

**Comment by lex111** [comment]
I did not understand which of the solutions we use in the end?

**Comment by lex111** [comment]
cc @yangshun

**Comment by lex111** [comment]
Personally, I like a solution using regular expressions. We can opt out of using the npm strip-markdown package, and instead choose the regexps we really need to solve current issue.

**Comment by yangshun** [comment]
Ok let's do your way then. Introducing a perf regression for this isn't really worth it.

**Comment by lex111** [comment]
Done :heavy_check_mark: 

Time building on my laptop:
Before 54.65s
After 55.22s.

Probably not bad, although I think we need a more accurate way to comparing than just starting the building website with a cleared cache.

**Pull request merged**
