### PR TITLE
Docusaurus v2: fix i18n url error

### PR DESCRIPTION
**Pull request by start940315**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [x] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Thanks for the PR, but without a linked issue or a detailed motivation, I'm not really sure what you are achieving. I'll assume you are doing the same as https://github.com/facebook/docusaurus/pull/6731. I'm going to close this, but feel free to send an issue detailing what's wrong with the current behavior

**Comment by start940315** [comment]
> Thanks for the PR, but without a linked issue or a detailed motivation, I'm not really sure what you are achieving. I'll assume you are doing the same as #6731 (i.e. fixing #6462). I'm going to close this because the code obviously doesn't always work as intended, but feel free to send an issue detailing what's wrong with the current behavior.

No, I'm fixing a bug. When I use the framework, after I chose a language, the locale added to the url one by one. I assumed it to be replaced. For example, my locales is ['en', 'zh-Hant', 'zh-Hans'], the initial url is `http://localhost:3000/docu/docs/intro`, after I chose zh-Hant then chose zh-Hans, the url became `http://localhost:3000/zh-Hans/zh-Hant/docu/docs/intro`. And I found currentLocale is not updated. So I fixed it locally and submited a pr.

**Comment by slorber** [comment]
@start940315 please create a repro showing the problem you are trying to solve: use docusaurus.new for that. We can't check your localhost URLs and inspect what's wrong.

I suspect you have a trailing slash issue leading to this bug, and fixing the trailing slash issue could fix your bug at the same time.

**Comment by Josh-Cena** [comment]
@slorber The bug is https://github.com/facebook/docusaurus/issues/8652

**Pull request closed without merging**
