### PR TITLE
polish(theme): MDX images should use async decoding

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
This pull request adds the `decoding="async"` attribute to the `` HTML tag, enhancing image loading performance. This implementation is inspired by the default implementation of the Next.js image component, which prioritizes efficient and fast image loading.

### CODE REVIEW

**Comment by sanjaiyan-dev** [comment]
https://nextjs.org/docs/app/api-reference/components/image#other-props

**Comment by sanjaiyan-dev** [comment]
👀

**Comment by slorber** [comment]
thanks

I read on the subject and this seems like a reasonable change
Many interesting refs here: https://core.trac.wordpress.org/ticket/53232

Note: this PR took time to merge not because the code was bad, but because you didn't really justify the change and explained the tradeoff. We don't do changes because Next.js use them bindly, we make our own judgement ;)

**Comment by sanjaiyan-dev** [comment]
> thanks
> 
> I read on the subject and this seems like a reasonable change Many interesting refs here: https://core.trac.wordpress.org/ticket/53232
> 
> Note: this PR took time to merge not because the code was bad, but because you didn't really justify the change and explained the tradeoff. We don't do changes because Next.js use them bindly, we make our own judgement ;)

Welcome, and I apologize for not providing the correct explanation.

**Comment by slorber** [comment]
Unfortunately this change leads to flakiness in our Argos visual tests (https://github.com/facebook/docusaurus/issues/9805)

I hope we'll not have to revert it

**Comment by sanjaiyan-dev** [comment]
> Unfortunately this change leads to flakiness in our Argos visual tests (#9805)
> 
> I hope we'll not have to revert it

Hi @slorber, I am sincerely sorry for the inconvenience. I will do my best to find a solution for this from my side.

**Comment by slorber** [comment]
no problem, that was worth trying 😄 we'll find a solution

**Pull request merged**
