### PR TITLE
docs: try to make plugin/preset config less confusing

### PR DESCRIPTION
**Pull request by slorber**
## Motivation

Make it easier to understand that there are 2 ways to configure content plugins, and most users should use the preset config.

See confusion here: https://github.com/facebook/docusaurus/discussions/5246#discussioncomment-1087287

Preview: https://deploy-preview-5313--docusaurus-2.netlify.app/docs/next/api/plugins/@docusaurus/plugin-content-docs/

### CODE REVIEW

**Comment by slorber** [comment]
@lex111 @Josh-Cena any opinion on this doc structure?

**Comment by lex111** [comment]
@slorber looks good to me, that's much better!

**Comment by Josh-Cena** [comment]
@slorber LGTM!

**Comment by slorber** [comment]
thanks 👍

**Pull request merged**
