### PR TITLE
docs: add Gulp to users

### PR DESCRIPTION
**Pull request by thecodechef**
## Motivation

My motivation is simple **GulpJS** uses **Docusaurus** for its website enough said

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

No Tests Yet

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by phated** [comment]
@yangshun yep!  I haven't had a chance to submit it myself so big props to @thecodechef! 

Would we be able to become "pinned"?  That would be super awesome.

**Comment by yangshun** [comment]
> Would we be able to become "pinned"? That would be super awesome.

@phated Yes definitely! I noticed that the link submitted in this PR is going to the landing page, which if I'm not mistaken, is not built using Docusaurus. That's fine but would it be better to direct to the docs page instead?

**Comment by phated** [comment]
We use a custom `index.html` in our docusaurus setup.

The 2 "landing" pages for the actually docusaurus template are https://gulpjs.com/docs/en/getting-started/quick-start and https://gulpjs.com/docs/en/api/concepts

I'm not particular and what you'd like to link to 😄

**Comment by thecodechef** [comment]
@yangshun I just signed the **CLA** so it's ready to be merged now thanks

**Comment by yangshun** [comment]
@thecodechef Many thanks!

**Pull request merged**
