### PR TITLE
bump react-json-view package version to remove peer-dep issue with Re…

### PR DESCRIPTION
**Pull request by homotechsual**
…act 18

## Pre-flight checklist

- [X] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [X] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

## Related issues/PRs

#9486

### CODE REVIEW

**Comment by yanni4night** [comment]
Expected to merge ASAP

**Comment by slorber** [comment]
@homotechsual I could merge but I'm not sure it would solve https://github.com/facebook/docusaurus/issues/9486 ?

The problem is not in the dependency itself but in a transitive dependency flux

**Comment by homotechsual** [comment]
Ah yeah ok - they bumped their node version requirement but that won't alter the flux transitive dep. Looks like we'll need a replacement JSON viewer for the debug plugin?

**Comment by mcrstudio** [comment]
I think we're good to close this PR in favour of #9566

**Pull request closed without merging**
