### PR TITLE
fix: adjust spacing for custom search properly

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Adjustment styles must be applied equally to all search blocks, not just from the Algolia one. Otherwise, the lack of proper styling in other custom search bars will lead to the following result:

image
https://nomicon.io/ as example

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Preview (no visual changes, it just adds search wrapper to all search bars)

### CODE REVIEW

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
~~I think this won't work as soon as we use the `type: "search"` navbar item, right?~~ Nvm, looked at it again, search items are respected as well, but the point below still stands

IMO the goal is to _reduce_ coupling between navbar items and navbar layout instead of hardcoding more special items, because it's in our plan to make every navbar item configurable (see also #7154 for one such confusion)

What about unifying the padding/margin for every navbar item? We have a similar problem for the color mode toggle as well.

**Comment by lex111** [comment]
Since SeachBar implementation comes from third-party plugins, we need put it in wrapper to set proper spacing by analogy with other navbar items. I don't know any other way to achieve this without introducing extra component.

**Comment by Josh-Cena** [comment]
Oh, I see where you are coming from. Can this wrapper be made generic? e.g. a `<NavbarItem>` wrapper with a margin that wraps all kinds of links?

**Comment by lex111** [comment]
No, because the search bar requires extra wrapper, not only to adjust the spacing, but to proper positioning on mobiles (see styles.css file).

**Comment by slorber** [comment]
👍 looks like a useful extra wrapper

Agree we can still improve things more and having something like `NavbarItemWrapper` could be useful in the future, open to further improvements

**Review by slorber — APPROVED** [review]

**Comment by JPeer264** [comment]
I totally understand the extra wrapper und support it, but is there a way of adding extra styles on these modules? Adding an extra `className` property is [not supported](https://docusaurus.io/docs/api/themes/configuration#navbar-search) when having `type: 'search'`. The reason why I ask this is, because we had some extra styles on `.dsla-search-wrapper` and is breaking it a little as we have another wrapper on top of it.

Screenshot 2022-05-05 at 08 30 30

**Comment by slorber** [comment]
that seems reasonable to me that we allow a className attribute like other navbar items

Do you want to send a PR ?

**Comment by JPeer264** [comment]
Sure I can add a PR there.

**Pull request merged**
