### PR TITLE
feat(v2): add option to toggle sidebar category open by default

### LINKED ISSUE #2354: [v2] Option to toggle docs category open by default
## 🚀 Feature

Add a new property on the `@docusaurus/plugin-content-docs` `SidebarItemCategory` to set the default state as opened. This should affect only to that one category, no all the categories on the docs.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

Improve UX.

## Pitch

Imagine docs with just two root elements:

- Introduction
- Reference v

Where `Reference` is a category with few other documents inside. This would allow to have this `Reference` category open by default which would be easier for the user to navigate/explore.

### PR DESCRIPTION
**Pull request by jsjoeio**
This PR adds the ability to toggle sidebar categories open by default.

## Changes
- update sidebar category to take collapsed prop 
- add extra sidebars collapsed test
- only mutate `item.collapsed` if necessary
- update docs for SidebarItemCategory

## Motivation

Fixes #2354 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

I wrote extensive notes on the issue: https://github.com/facebook/docusaurus/issues/2354

Here's how I tested my changes:
1. Built project: `yarn build`
2. Published to `verdaccio` locally: `yarn lerna publish --registry http://localhost:4873 --no-git-tag-version` 
3. Created a new website: 
```shell
# set the registry to verdaccio
npm set registry http://localhost:4873/
# install @docusaurus/init globally
npm i -g @docusaurus/init
# run the binary from the location directly
/Users/jprevite/.nvm/versions/node/v10.15.1/lib/node_modules/@docusaurus/init/bin/index.js init test-joe
```
4. Modified the `sidebars.js` file:
```js
module.exports = {
  someSidebar: 
     [
      {
        "type": "category",
        "label": "Introduction",
        "items": ["doc1"],
        "collapsed": true
      },
      {
        "type": "category",
        "label": "Powering MDX",
        "items": ["doc2"],
        "collapsed": false
      }
    ]
  }
```
5. Tested if changes worked (and they did 🎉). You can tell because "Powering MDX" is **not collapsed** (because it's set to `false` in the `sidebars.js` file. 
image

## Screenshots

Here are a few other screenshots of it in action:

### Before

This is what happens before I made any changes. (note: I load the page, "Powering MDX" is collapsed). 

### After

I made the change and now it loads and is expanded (not collapsed) like I want! 

And, if I'm on the "Powering MDX", it should be expanded (because it's the current page), which still works as expected.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by jsjoeio** [comment]
The following tests are failing:
- docsVersion
  - first time versioning
  - not the first time versioning
- loadSidebars
  - sidebars with known sidebar item type
  - sidebars shortand and longform lead to exact same sidebar
  - sidebars link
- versioned website
  - content

Any guidance on how to fix these would be awesome!

**Comment by jsjoeio** [comment]
Additional suggestions (out of the scope of this work:
- we should link to the `local-third-party-project-testing.md` in the `CONTRIBUTING.md`
- the swizzle section of the docs should have an example:
```shell
yarn swizzle @docusaurus/theme-classic DocSidebar
```

**Comment by lex111** [comment]
@jsjoeio if I understand correctly, you just need to update snapshots, run `yarn test -u`.

**Comment by jsjoeio** [comment]
> if I understand correctly, you just need to update snapshots, run `yarn test -u`.

That worked for the snapshot tests! Now I just have to fix the actual test that I broke 😂 Thank you @lex111 🎉

**Comment by yangshun** [comment]
@jsjoeio We should also update the docs to tell people about this cool new feature :)

**Comment by jsjoeio** [comment]
> We should also update the docs to tell people about this cool new feature :)

@yangshun Yes! Agreed :) I updated the example [here](https://github.com/facebook/docusaurus/blob/6c6f4204a5134a104fa57ab13c23e1868864fdb0/website/docs/docs.md#category) in this PR. 

I'll open a separate PR and add a short paragraph to that section of the docs!

**Comment by yangshun** [comment]
@jsjoeio seems like there was a bug, found by @lex111. We have to resubmit this PR.

**Comment by jsjoeio** [comment]
@yangshun Oh no! Okay. Do you want me to do that? (i.e. open a new PR with this work?)

**Comment by jsjoeio** [comment]
@yangshun actually, I'd like to propose moving this conversation to #2354 so it's easier to keep track of

**Pull request merged**
