### PR TITLE
Rephrased TeamProfileCard as Class instead of Function

### PR DESCRIPTION
**Pull request by AdvaitDhingra**
## Motivation

I have used React for a couple months now and have found that Classes are easier to use than just functions. Terribly sorry if this is not the case, I am just a beginner and wanted to contribute to this open-source project. Please don't get mad.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

I merely changed the layout/ rephrased the code. I tested it with node.js (npm start) and it works just fine. 

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by lex111** [comment]
We only use function components.

**Comment by AdvaitDhingra** [comment]
Oh ok. Sorry for wasting your time

**Comment by AdvaitDhingra** [comment]
Quick question, where can I find the footer files? I found an error in the footer.

**Comment by lex111** [comment]
What kind of error exactly?

**Pull request closed without merging**
