### PR TITLE
feat(v2): autoprefix css

### PR DESCRIPTION
**Pull request by shakcho**
## Motivation

Automatically add vendor prefix for CSS

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan
 
In the root directory execute the following command 

```
yarn 
yarn start
````
go to http://localhost:3000/docs/introduction 
Open chrome devtools, we should see the position sticky should get vendor prefixed with 
-webkit-sticky to work on Safari Browser as shown in the image below.
Screenshot 2019-06-19 at 1 53 51 AM

Try the URL in Safari browser, now the left sidebar should not scroll while scrolling.

## Related PRs

I'm not aware of any

### CODE REVIEW

**Comment by shakcho** [comment]
@endiliey Thanks for your support. I will read about all the things you mentioned. And do the necessary changes. If needed I will ask you for help. Thanks

**Comment by shakcho** [comment]
@endiliey Updated the pull request 
But I still have doubt about how to solve the below mentioned issue.

1. Allow users to update browserslist 
- My idea is to, let the project use browserslist conf from the package.json itself. If someone wants to update the browserslist, they can use **browserslist-config-mycompany** .

Let me know if you have something else in mind.

2. I don't know how to setup SSR, so unable to test this, please help me to test this.

**Comment by shakcho** [comment]
@endiliey @yangshun please check this

**Comment by endiliey** [comment]
dont have a safari to test it out. overall lgtm but not sure if we want to compile postcss just for autoprefixer

cc @yangshun @wgao19

**Comment by wgao19** [comment]
i'd go for it because autoprefixing css counts as a chore that people will most likely have to deal with or  may not even be aware that their projects already have it set up

**Comment by endiliey** [comment]
Thanks a lot @shakcho

Sorry for the delay, was sick

**Comment by shakcho** [comment]
@endiliey @yangshun @wgao19  Thanks for the opportunity to allow me to work on this issue.

**Pull request merged**
