### PR TITLE
fix(core): make webpack HMR always listen to current location

### PR DESCRIPTION
**Pull request by jeengbe**
See https://github.com/facebook/docusaurus/issues/7912 for explanation as to how these changes fix the problem. This does not have any side effects that I am aware of.

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

## Related issues/PRs

Closes https://github.com/facebook/docusaurus/issues/7912

### CODE REVIEW

**Comment by slorber** [comment]
> This does not have any side effects that I am aware of.

Can you backup your claim with some reference to other projects using a similar setup? 
If nobody uses this by default, there must be a reason 🤷‍♂️ 

I'd rather align to the behavior others are already using if we were to merge something not easy to double-check is correct.

For example CRA has env variables, but does not use such default:
https://github.com/facebook/create-react-app/blob/main/packages/react-scripts/config/webpackDevServer.config.js

**Comment by jeengbe** [comment]
> > This does not have any side effects that I am aware of.
> 
> Can you backup your claim with some reference to other projects using a similar setup? If nobody uses this by default, there must be a reason 🤷‍♂️

I cannot, I just can't come up with a situation in which the new behaviour would be unwanted. As the websocket runs on the same domain + port the rest of the website is on, it always ought to be accessible on the same domain + port.
The only environment in which this would cause an issue is a reverse proxy that does not work with websockets, and the original port still exposed, and I do not see that happening in any dev envionment I can think of.

**Review by Josh-Cena — COMMENTED** [review]
Not familiar with the dev server architecture at all, so more of a question: does this change the experience with remote developing, like on GitHub codespaces? Right now we have to recommend `--host 0.0.0.0`.

**Comment by jeengbe** [comment]
It does change the experience in that it fixes HMR for when Docusaurus is launched on a different address/port is is being used with. `--host 0.0.0.0` is still necessary for the server to work at all, but this pr eliminates issues with the socket connection (for HMR) being made to a different address/port (since setting to 0 makes it use the current `location`'s)

**Review by Josh-Cena — APPROVED** [review]
The current configuration looks sensible to me (sounds like a no-op in most cases). I'll be willing to give it a try.

**Comment by slorber** [comment]
Let's try this and we'll see if anyone complains

For now I won't backport it in 2.x

**Comment by zevisert** [comment]
I for one would like to see this backported to 2.x! I brought up a question in discord that was likely solved by this PR. https://discord.com/channels/398180168688074762/867060369087922187/1012096405780844594

My use case is the same as #7912 -- it's that we want to run the docusaurus dev server on eg minikube locally. One of our requirements is to have TLS enabled in development for secure-context only JS features, like `navigator.clipboard` - and we plan on doing that with an ingress that terminates the TLS connection. We can get our SSL certs by proving a domain like `local.example.com` that points at `127.0.0.1`. 

Problem is that when deployed behind a reverse proxy ingress, the HMR websocket tries (and fails) to connect to the internal port like `wss://local.example.com:3000/ws` instead of `wss://local.example.com/ws`. I confirmed that `@docusaurus/core@canary` (0.0.0-5272 as of time of writing) solves this.

**Comment by slorber** [comment]
@zevisert we could backport it but I'd prefer to have more user feedback first. For example, if nobody complains on any 3.0 upcoming alphas, it becomes safer to backport it

**Comment by slorber** [comment]
@zevisert we could backport it but I'd prefer to have more user feedback first. For example, if nobody complains on any 3.0 upcoming alphas, it becomes safer to backport it

**Comment by jeengbe** [comment]
Until the backport fix is out, remember that you can always put PR diffs in your patches folder and run [patch-package](https://www.npmjs.com/package/patch-package).

[https://patch-diff.githubusercontent.com/raw/facebook/docusaurus/pull/7951.diff](https://patch-diff.githubusercontent.com/raw/facebook/docusaurus/pull/7951.diff)

**Comment by masad-frost** [comment]
I noticed this never made it to 2.2.0, why?

**Comment by slorber** [comment]
because we don't have a lot of feedback on potential side-effects due to v3.0 canaries not being widely, and I decided to not backport this:

https://github.com/facebook/docusaurus/pull/7951#issuecomment-1219760865

If you want to use it, wait for 3.0, use a canary release, or this temp workaround: https://github.com/facebook/docusaurus/issues/7912#issuecomment-1212954898

**Pull request merged**
