### PR TITLE
fix(v2): use absolute path to manifest file

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

If you visit any page other than the home page, for example https://v2.docusaurus.io/docs/, then you can see the following error in the console:

> Failed to load resource: the server responded with a status of 404 ()   manifest.json

Or something like this:

> Manifest: Line: 1, column: 1, Syntax error.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Preview (see motivation section).

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by slorber** [comment]
Hmmm that's annoying 😅 

I tried to keep relative paths because I wanted the PWA to work in deploy previews, using baseurl. Seems it does not work on the deploy preview now :'(

**Comment by lex111** [comment]
I don't get what you mean. Right now the browser cannot find the manifest file because a relative URL is specified.

**Comment by slorber** [comment]
I mean, we want the (+) icon to be there in all cases

image


Currently, it only works on the homepage (which is the problem your PR fixes, as it will work from /docs/ too)

 But your PR breaks the (+) on deploy previews: https://deploy-preview-3554--docusaurus-2.netlify.app/classic/

image

While it used to work on PRs. (but only on PR classic homepage 🤪 ):

image

---

The ideal solution should make it work:
- for all subpaths: / or /docs/myDoc
- for deploy previews: /classic/ or /classic/docs/myDoc

This way it's easier to review PWA issues in deploy previews

**Comment by lex111** [comment]
Aha, I figured it out now, so I changed to use `baseUrl` const, it should be OK, I guess.

**Comment by slorber** [comment]
LGTM, we'll see if main site still works after :D

**Pull request merged**
