### PR TITLE
feat(v2): add before and after dev server implementation

### PR DESCRIPTION
**Pull request by RDIL**
- `beforeDevServer` & `afterDevServer` have been removed
- `configureDevServer` has been added

## Motivation

It was on the todo list.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

It works just fine in my testing.

## Related PRs

n/a

### CODE REVIEW

**Comment by slorber** [comment]
Thanks,

Do you have a concrete use case in mind that gets solved by this new API?

I don't have much context about this TODO in the code and why we need this 😅 maybe @yangshun knows why it can be useful?

If we do need more customizations to the dev server, wouldn't it be preferable to let the user change whatever he wants from the default config we provide, instead of adding a new API for each devserver config.

**Comment by RDIL** [comment]
I believe this is for cases like where users want to add custom middleware, for example if they use the service worker plugin they may want to add react-dev-utils's `noopServiceWorkerMiddleware`.

**Comment by slorber** [comment]
What if we had a "configureWebpackDevServer" instead? 

That would also allow that usecase and yet be a more future-proof API?

**Comment by RDIL** [comment]
Going to close this until there is an exact feature request for it.

**Pull request closed without merging**
