### PR TITLE
feat(v2): Add @theme-init components to user theme

### PR DESCRIPTION
**Pull request by edno**
## Motivation

Swizzled components currently do not have access to `@theme-init` components as it has been introduced in PR[#2464](https://github.com/facebook/docusaurus/pull/2464) for Docusaurus components.

Having access to initial theme components allows overriding default components without having to rewrite the entire component.

This PR extend the initial PR for providing access to `@theme-init` components for custom components.

The point has been raised on the Discord channel [#docusaurus-2-dogfooding](https://discordapp.com/channels/398180168688074762/567414046073159701/718010716527001690).

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Tested with a local instance and a custom code block:
```jsx 
import React from 'react';
import CodeBlock from '@theme-init/CodeBlock'; // access to initial theme Codeblock

const TryQueryLink = ({ gql, text }) => {
  const graphiQLPath = "/graphiql?query=";
  const encodedQuery = encodeURIComponent(gql || "");
  return <a href={`${graphiQLPath}${encodedQuery}`}>{text}</a>;
}

const graphiQLCodeBlock = (Component) => {
  const WrappedComponent = (props) => {
    let tryMe;
    const language = props.className && props.className.replace(/language-/, '') || "";
    if (props.withgraphiql && language == "graphql") {
      const match = props.metastring && props.metastring.match(/withgraphiql/, RegExp.$1);
      tryMe = <TryQueryLink
 gql={props.children} text="Try Query"/>;
    }

    return <>{tryMe}<Component {...props}/></>
  };

  return WrappedComponent;
};

export default graphiQLCodeBlock(CodeBlock);
```

Screenshot 2020-09-25 at 17 44 35
## Related PRs

- #2464: refactor(v2): add @theme-init alias to give access to initial components

### CODE REVIEW

**Review by lex111 — COMMENTED** [review]
Let's create a separate function for this purpose to avoid code duplicating?

**Comment by edno** [comment]
> Let's create a separate function for this purpose to avoid code duplicating?

@lex111 - I've put the full iterator logic into a separate function.

**Comment by slorber** [comment]
thanks, LGTM

**Comment by slorber** [comment]
Hi @edno 

I've tried to write some doc for these aliases here https://github.com/facebook/docusaurus/pull/3502, I'd appreciate a review to see if the doc make sense for you

**Comment by edno** [comment]
Hi @slorber 

The documentation looks good to me. I even learn something new with `@theme-original`. 😁

**Comment by slorber** [comment]
thanks :)

**Pull request merged**
