### PR TITLE
chore: update FB template headers

### PR DESCRIPTION
**Pull request by yangshun**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Our internal copyright header requirements have changed.

## Test Plan

Run Eslint in the facebook template

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

### CODE REVIEW

**Comment by slorber** [comment]
Shouldn't we change all the other headers as well?

**Comment by Josh-Cena** [comment]
In hindsight this looks really sus 🤔 This means the template is for non-open-source sites by default? Should we at least keep the original header somewhere for reference?

**Comment by yangshun** [comment]
> Shouldn't we change all the other headers as well?
Yes but since this is within the code, it's not as urgent. It's more urgent to update the template as this is being flagged as a violation for new projects (we have internal lint rules which conflict).

> In hindsight this looks really sus 🤔 This means the template is for non-open-source sites by default? Should we at least keep the original header somewhere for reference, for open-source ones?
Hmm I didn't really consider the contents lol, was just trying to make the internal linter happy. The new internal website I was trying to change this for actually is meant to be open sourced eventually.

 @zpao do you have any advice here?

**Comment by zpao** [comment]
This should get reverted. The headers here are intended for public code and I updated those in #7639. If we want a template for non-public headers then we can consider that but since the intent here is primarily public projects, this was already right.

> was just trying to make the internal linter happy. 

We'll talk elsewhere. There are better ways to do that :)

**Pull request merged**
