### PR TITLE
misc: add TypeScript linting to root & pre-commit hook

### PR DESCRIPTION
**Pull request by strtw**
## Motivation

Resolve issue [2192](https://github.com/facebook/docusaurus/issues/2192)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

#### Considerations
Rule sets need to be added to make exceptions for the errors, or the errors need to be fixed. 

## Test Plan

Modified `package.json` and `.eslintrc` to include TypeScript linting on pre-commit and when running `yarn lint`. To test I attempted a commit and it was prevented by successful running of the linter which logged TS errors. Same result when I ran `yarn lint`.

```console

$ yarn lint
yarn run v1.17.3
$ eslint --cache "**/*.{js,ts}"

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/client/exports/__tests__/useBaseUrl.ts
  13:23  error  Use 'as jest.Mock' instead of '<jest.Mock>'  @typescript-eslint/consistent-type-assertions

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/commands/build.ts
   15:1   error    '@docusaurus/types' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
   25:52  warning  Unexpected any. Specify a different type                                                 @typescript-eslint/no-explicit-any
   48:1   error    Prefer default export                                                                    import/prefer-default-export
  128:7   error    Expected an assignment or function call and instead saw an expression                    no-unused-expressions

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/commands/deploy.ts
  19:1  error  Prefer default export  import/prefer-default-export

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/commands/external.ts
  12:1  error  Prefer default export  import/prefer-default-export

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/commands/start.ts
   23:1   error    '@docusaurus/types' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
   42:1   error    Prefer default export                                                                    import/prefer-default-export
   54:18  warning  Missing return type on function                                                          @typescript-eslint/explicit-function-return-type
   61:30  warning  Missing return type on function                                                          @typescript-eslint/explicit-function-return-type
  161:5   error    Expected an assignment or function call and instead saw an expression                    no-unused-expressions

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/commands/swizzle.ts
  17:1   error    Prefer default export                     import/prefer-default-export
  22:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/server/client-modules/__tests__/index.test.ts
   8:8   warning  'path' is defined but never used                @typescript-eslint/no-unused-vars
  12:21  error    Require statement not part of import statement  @typescript-eslint/no-var-requires
  13:22  error    Require statement not part of import statement  @typescript-eslint/no-var-requires
  14:26  error    Require statement not part of import statement  @typescript-eslint/no-var-requires

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/server/client-modules/index.ts
   9:1   error    '@docusaurus/types' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
  11:1   error    Prefer default export                                                                    import/prefer-default-export
  11:51  warning  Unexpected any. Specify a different type                                                 @typescript-eslint/no-explicit-any

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/server/config.ts
  12:1   error    '@docusaurus/types' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
  34:20  warning  Unexpected any. Specify a different type                                                 @typescript-eslint/no-explicit-any
  37:20  warning  Unexpected any. Specify a different type                                                 @typescript-eslint/no-explicit-any
  50:1   error    Prefer default export                                                                    import/prefer-default-export

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/server/html-tags/__tests__/index.test.ts
   8:8   warning  'path' is defined but never used                @typescript-eslint/no-unused-vars
  12:21  error    Require statement not part of import statement  @typescript-eslint/no-var-requires
  13:27  error    Require statement not part of import statement  @typescript-eslint/no-var-requires
  14:24  error    Require statement not part of import statement  @typescript-eslint/no-var-requires
  15:28  error    Require statement not part of import statement  @typescript-eslint/no-var-requires

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/server/html-tags/htmlTags.ts
   9:1   error    '@docusaurus/types' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
  13:37  warning  Unexpected any. Specify a different type                                                 @typescript-eslint/no-explicit-any
  26:1   error    Prefer default export                                                                    import/prefer-default-export
  26:54  warning  Unexpected any. Specify a different type                                                 @typescript-eslint/no-explicit-any

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/server/html-tags/index.ts
   9:1   error    '@docusaurus/types' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
  25:46  warning  Unexpected any. Specify a different type                                                 @typescript-eslint/no-explicit-any

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/server/index.ts
  11:1  error  '@docusaurus/types' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/server/loadSetup.ts
   9:1  error  '@docusaurus/types' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
  13:1  error  Prefer default export                                                                    import/prefer-default-export

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/server/plugins/index.ts
  11:1   error    '@docusaurus/types' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
  20:8   warning  Missing return type on function                                                          @typescript-eslint/explicit-function-return-type
  33:21  error    Do not nest ternary expressions                                                          no-nested-ternary
  38:12  error    Do not nest ternary expressions                                                          no-nested-ternary
  49:19  warning  Unexpected any. Specify a different type                                                 @typescript-eslint/no-explicit-any
  53:25  warning  Unexpected any. Specify a different type                                                 @typescript-eslint/no-explicit-any

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/server/plugins/init.ts
  10:1   error    '@docusaurus/types' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
  12:1   error    Prefer default export                                                                    import/prefer-default-export
  18:12  warning  Unexpected any. Specify a different type                                                 @typescript-eslint/no-explicit-any
  19:25  warning  Unexpected any. Specify a different type                                                 @typescript-eslint/no-explicit-any
  30:9   error    Use array destructuring                                                                  prefer-destructuring
  39:27  warning  Unexpected any. Specify a different type                                                 @typescript-eslint/no-explicit-any

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/server/presets/__tests__/index.test.ts
  10:9  warning  'DocusaurusConfig' is defined but never used  @typescript-eslint/no-unused-vars

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/server/presets/index.ts
  10:1   error    '@docusaurus/types' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
  17:1   error    Prefer default export                                                                    import/prefer-default-export
  33:7   error    Use array destructuring                                                                  prefer-destructuring
  39:25  warning  Unexpected any. Specify a different type                                                 @typescript-eslint/no-explicit-any
  45:5   error    Expected an assignment or function call and instead saw an expression                    no-unused-expressions
  46:5   error    Expected an assignment or function call and instead saw an expression                    no-unused-expressions

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/server/routes.ts
  11:1   error    '@docusaurus/types' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
  19:26  warning  Unexpected any. Specify a different type                                                 @typescript-eslint/no-explicit-any
  41:1   error    Prefer default export                                                                    import/prefer-default-export
  41:8   warning  Missing return type on function                                                          @typescript-eslint/explicit-function-return-type
  79:5   warning  Missing return type on function                                                          @typescript-eslint/explicit-function-return-type

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/server/themes/alias.ts
  12:1  error  '@docusaurus/types' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
  14:1  error  Prefer default export                                                                    import/prefer-default-export

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/server/themes/index.ts
   8:1  error  '@docusaurus/types' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
  11:1  error  Prefer default export                                                                    import/prefer-default-export

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/webpack/base.ts
   15:1   error    '@docusaurus/types' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
   22:8   warning  Missing return type on function                                                          @typescript-eslint/explicit-function-return-type
  109:19  error    Identifier 'ascii_only' is not in camel case                                             @typescript-eslint/camelcase

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/webpack/client.ts
  11:1  error  '@docusaurus/types' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
  16:1  error  Prefer default export                                                                    import/prefer-default-export

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/webpack/plugins/ChunkAssetPlugin.ts
  13:3  warning  Missing return type on function                                                                                                                                            @typescript-eslint/explicit-function-return-type
  23:9  error    iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations  no-restricted-syntax

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/webpack/plugins/CleanWebpackPlugin.ts
  122:5  error    Do not use "// @ts-ignore" comments because they suppress compilation errors  @typescript-eslint/ban-ts-ignore
  192:3  warning  Missing return type on function                                               @typescript-eslint/explicit-function-return-type
  241:3  warning  Missing return type on function                                               @typescript-eslint/explicit-function-return-type
  251:3  warning  Missing return type on function                                               @typescript-eslint/explicit-function-return-type
  316:3  warning  Missing return type on function                                               @typescript-eslint/explicit-function-return-type

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/webpack/server.ts
  13:1  error  '@docusaurus/types' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
  18:1  error  Prefer default export                                                                    import/prefer-default-export

/Users/stu/Workspace/docusaurus/packages/docusaurus/src/webpack/utils.ts
   20:20  warning  Unexpected any. Specify a different type        @typescript-eslint/no-explicit-any
   55:18  warning  Missing return type on function                 @typescript-eslint/explicit-function-return-type
   56:11  error    Unexpected require()                            global-require
   56:11  error    Require statement not part of import statement  @typescript-eslint/no-var-requires
  132:22  error    Unexpected require()                            global-require
  157:21  warning  Unexpected any. Specify a different type        @typescript-eslint/no-explicit-any

/Users/stu/Workspace/docusaurus/packages/docusaurus-init/src/index.ts
  29:48  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  37:1   error    Prefer default export                     import/prefer-default-export

/Users/stu/Workspace/docusaurus/packages/docusaurus-plugin-content-blog/src/__tests__/generateBlogFeed.test.ts
  34:33  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  65:33  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/stu/Workspace/docusaurus/packages/docusaurus-plugin-content-blog/src/blogUtils.ts
  13:1   error    '@docusaurus/types' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
  16:8   warning  Missing return type on function                                                          @typescript-eslint/explicit-function-return-type
  17:10  warning  Forbidden non-null assertion                                                             @typescript-eslint/no-non-null-assertion
  24:1   warning  Missing return type on function                                                          @typescript-eslint/explicit-function-return-type
  31:8   warning  Missing return type on function                                                          @typescript-eslint/explicit-function-return-type
  42:27  error    'generateBlogPosts' was used before it was defined                                       @typescript-eslint/no-use-before-define
  69:18  error    'title' is already declared in the upper scope                                           no-shadow
  83:8   warning  Missing return type on function                                                          @typescript-eslint/explicit-function-return-type

/Users/stu/Workspace/docusaurus/packages/docusaurus-plugin-content-blog/src/index.ts
   13:1   error    '@docusaurus/types' should be listed in the project's dependencies, not devDependencies     import/no-extraneous-dependencies
   21:1   error    'webpack' should be listed in the project's dependencies. Run 'npm i -S webpack' to add it  import/no-extraneous-dependencies
   47:31  warning  Unexpected any. Specify a different type                                                    @typescript-eslint/no-explicit-any
   55:22  warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
   82:5   warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
   89:5   warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
  101:11  error    Assignment to property of function parameter 'blogPost'                                     no-param-reassign
  109:11  error    Assignment to property of function parameter 'blogPost'                                     no-param-reassign
  127:7   warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
  199:5   warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
  217:29  warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
  268:23  error    'metadata' is already declared in the upper scope                                           no-shadow
  351:5   warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
  377:35  warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
  399:5   warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
  429:5   warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
  453:30  error    Expected to return a value at the end of arrow function                                     array-callback-return
  460:22  error    'path' is already declared in the upper scope                                               no-shadow
  460:28  error    'title' is already declared in the upper scope                                              no-shadow

/Users/stu/Workspace/docusaurus/packages/docusaurus-plugin-content-blog/src/markdownLoader.ts
   8:1   error  'webpack' should be listed in the project's dependencies. Run 'npm i -S webpack' to add it  import/no-extraneous-dependencies
  11:34  error  Require statement not part of import statement                                              @typescript-eslint/no-var-requires

/Users/stu/Workspace/docusaurus/packages/docusaurus-plugin-content-docs/src/__tests__/index.test.ts
   9:1   error    'webpack' should be listed in the project's dependencies. Run 'npm i -S webpack' to add it  import/no-extraneous-dependencies
  23:27  warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
  29:15  warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
  32:17  warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
  34:9   error    Assignment to property of function parameter 'dataContainer'                                no-param-reassign

/Users/stu/Workspace/docusaurus/packages/docusaurus-plugin-content-docs/src/env.ts
  17:8  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type
  21:8  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type
  25:8  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type
  44:7  error    Use array destructuring          prefer-destructuring

/Users/stu/Workspace/docusaurus/packages/docusaurus-plugin-content-docs/src/index.ts
   18:1   error    '@docusaurus/types' should be listed in the project's dependencies, not devDependencies     import/no-extraneous-dependencies
   20:1   error    'webpack' should be listed in the project's dependencies. Run 'npm i -S webpack' to add it  import/no-extraneous-dependencies
   87:5   warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
  100:5   warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
  120:5   warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
  277:5   warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
  284:29  warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
  308:11  error    Do not nest ternary expressions                                                             no-nested-ternary
  312:28  warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
  386:9   error    Async method 'contentLoaded' expected no return value                                       consistent-return
  390:5   warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
  412:35  warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type

/Users/stu/Workspace/docusaurus/packages/docusaurus-plugin-content-docs/src/markdown/__tests__/linkify.test.ts
  27:19  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type

/Users/stu/Workspace/docusaurus/packages/docusaurus-plugin-content-docs/src/markdown/index.ts
  9:1  error  'webpack' should be listed in the project's dependencies. Run 'npm i -S webpack' to add it  import/no-extraneous-dependencies

/Users/stu/Workspace/docusaurus/packages/docusaurus-plugin-content-docs/src/markdown/linkify.ts
  13:16  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type
  57:31  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type

/Users/stu/Workspace/docusaurus/packages/docusaurus-plugin-content-docs/src/metadata.ts
   16:1   error    '@docusaurus/types' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
   74:31  warning  Forbidden non-null assertion                                                             @typescript-eslint/no-non-null-assertion
   97:10  error    Identifier 'sidebar_label' is not in camel case                                          @typescript-eslint/camelcase
   97:25  error    Identifier 'custom_edit_url' is not in camel case                                        @typescript-eslint/camelcase
  137:14  error    Identifier 'custom_edit_url' is not in camel case                                        @typescript-eslint/camelcase
  137:46  error    Identifier 'custom_edit_url' is not in camel case                                        @typescript-eslint/camelcase
  141:5   error    Identifier 'sidebar_label' is not in camel case                                          @typescript-eslint/camelcase
  141:5   error    Identifier 'sidebar_label' is not in camel case                                          @typescript-eslint/camelcase

/Users/stu/Workspace/docusaurus/packages/docusaurus-plugin-content-docs/src/order.ts
  18:24  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type
  20:9   error    Expected a default case          default-case

/Users/stu/Workspace/docusaurus/packages/docusaurus-plugin-content-docs/src/sidebars.ts
   23:42  warning  Unexpected any. Specify a different type      @typescript-eslint/no-explicit-any
   37:33  warning  Unexpected any. Specify a different type      @typescript-eslint/no-explicit-any
   51:28  warning  Unexpected any. Specify a different type      @typescript-eslint/no-explicit-any
   60:29  warning  Unexpected any. Specify a different type      @typescript-eslint/no-explicit-any
  137:32  error    Expected to return a value in arrow function  array-callback-return

/Users/stu/Workspace/docusaurus/packages/docusaurus-plugin-content-docs/src/types.ts
  63:22  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/stu/Workspace/docusaurus/packages/docusaurus-plugin-content-docs/src/version.ts
  18:1   error    Prefer default export                                              import/prefer-default-export
  18:8   warning  Missing return type on function                                    @typescript-eslint/explicit-function-return-type
  40:7   error    Unexpected control character(s) in regular expression: \x00, \x1f  no-control-regex
  40:13  error    Unnecessary escape character: \/                                   no-useless-escape

/Users/stu/Workspace/docusaurus/packages/docusaurus-plugin-content-pages/src/index.ts
  32:5  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type
  38:5  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type
  64:5  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type

/Users/stu/Workspace/docusaurus/packages/docusaurus-plugin-ideal-image/src/index.ts
   7:1   error    '@docusaurus/types' should be listed in the project's dependencies, not devDependencies     import/no-extraneous-dependencies
   8:1   error    'webpack' should be listed in the project's dependencies. Run 'npm i -S webpack' to add it  import/no-extraneous-dependencies
  13:16  warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
  18:5   warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type
  22:5   warning  Missing return type on function                                                             @typescript-eslint/explicit-function-return-type

/Users/stu/Workspace/docusaurus/packages/docusaurus-plugin-sitemap/src/__tests__/createSitemap.test.ts
  31:27  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  31:42  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/stu/Workspace/docusaurus/packages/docusaurus-plugin-sitemap/src/createSitemap.ts
  12:16  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type

/Users/stu/Workspace/docusaurus/packages/docusaurus-plugin-sitemap/src/index.ts
  20:16  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type
  29:5   warning  Missing return type on function  @typescript-eslint/explicit-function-return-type

/Users/stu/Workspace/docusaurus/packages/docusaurus-theme-classic/src/theme/DocItem/index.js
  46:13  warning  Dangerous property 'dangerouslySetInnerHTML' found  react/no-danger

/Users/stu/Workspace/docusaurus/packages/docusaurus-theme-classic/src/theme/Footer/index.js
  75:27  warning  Dangerous property 'dangerouslySetInnerHTML' found  react/no-danger

/Users/stu/Workspace/docusaurus/packages/docusaurus-types/src/index.d.ts
    8:1   error    'webpack' should be listed in the project's dependencies. Run 'npm i -S webpack' to add it  import/no-extraneous-dependencies
   25:20  warning  Unexpected any. Specify a different type                                                    @typescript-eslint/no-explicit-any
   28:20  warning  Unexpected any. Specify a different type                                                    @typescript-eslint/no-explicit-any
   34:24  warning  Unexpected any. Specify a different type                                                    @typescript-eslint/no-explicit-any
   41:24  warning  Unexpected any. Specify a different type                                                    @typescript-eslint/no-explicit-any
   55:52  warning  Unexpected any. Specify a different type                                                    @typescript-eslint/no-explicit-any
   86:19  warning  Unexpected any. Specify a different type                                                    @typescript-eslint/no-explicit-any
   91:34  warning  Unexpected any. Specify a different type                                                    @typescript-eslint/no-explicit-any
  122:52  warning  Unexpected any. Specify a different type                                                    @typescript-eslint/no-explicit-any
  162:22  warning  Unexpected any. Specify a different type                                                    @typescript-eslint/no-explicit-any

/Users/stu/Workspace/docusaurus/packages/docusaurus-utils/src/index.ts
   19:12  warning  Unexpected any. Specify a different type             @typescript-eslint/no-explicit-any
   54:8   warning  Missing return type on function                      @typescript-eslint/explicit-function-return-type
   54:57  warning  Unexpected any. Specify a different type             @typescript-eslint/no-explicit-any
  156:29  warning  Unexpected any. Specify a different type             @typescript-eslint/no-explicit-any
  156:76  warning  Unexpected any. Specify a different type             @typescript-eslint/no-explicit-any
  183:20  warning  Unexpected any. Specify a different type             @typescript-eslint/no-explicit-any
  190:7   error    Assignment to property of function parameter 'file'  no-param-reassign
  260:8   warning  Missing return type on function                      @typescript-eslint/explicit-function-return-type

✖ 198 problems (93 errors, 105 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by strtw** [comment]
Yes I'll certainly help out with that.

**Comment by yangshun** [comment]
Sure, go ahead. Let's try to rebase also as there are updates to some of the files since this PR was created and there are now conflicts.

**Comment by yangshun** [comment]
@lex111 can we try to take over this?

**Comment by fanny** [comment]
Just fix the conflicts, probably I'll need some help to change any for the types

**Comment by fanny** [comment]
I fixed the most part of the errors, @yangshun in some places it complain about  the `contentLoad` function return value, when in `@docusaurus/types` is no expected. Before I do any change, is there some reason? Also, if you have time to look my `eslint` config, I'll be grateful

**Comment by slorber** [comment]
hi

sorry didn't see this PR, but this is now fixed

**Pull request closed without merging**
