### PR TITLE
docs: add firelordjs to showcase

### PR DESCRIPTION
**Pull request by tylim88**
### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

No

## Related PRs

No

### CODE REVIEW

**Comment by tylim88** [comment]
the bot stuck again....

**Comment by Josh-Cena** [comment]
😥 I don't know what's going on... Do you want to wait for a few days and see if it kicks, or are you okay if I send the PR myself?

**Comment by tylim88** [comment]
@Josh-Cena I am ok with you sending the PR, thank you 👍

**Comment by Josh-Cena** [comment]
#7059

**Pull request closed without merging**
