### PR TITLE
Update Docusaurus v2 Showcase

### PR DESCRIPTION
**Pull request by ndom91**
## Motivation

Just wanted to add https://next-auth.js.org to the showcase as I believe it to be a particularly nice implementation of Docusaurus.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

Only changed docs / showcase.md page

## Related PRs

N/A

### CODE REVIEW

**Review by lex111 — APPROVED** [review]
Nice looking website!

**Comment by lex111** [comment]
@ndom91 could  you  please sign the required CLA please?

**Comment by ndom91** [comment]
@lex111 I just signed it after submitting the PR, according to that page it should update automatically shortly, right? I did signin with my Github account during the CLA signing flow.

**Comment by lex111** [comment]
@ndom91 thanks! But you are using an old (unsupported) version, so we recommend that you upgrade to the latest one.

**Comment by ndom91** [comment]
An old supported version of what?

**Comment by lex111** [comment]
Docusaurus, of course. We are still in the alpha stage, so we often release new versions that contain many different improvements and bug fixes. Therefore, it is important to update to the latest versions as soon as they become available.

**Comment by ndom91** [comment]
Ah gotcha, good call. I'll do that.

**Pull request merged**
