### PR TITLE
docs: update showcase data

### PR DESCRIPTION
**Pull request by Josh-Cena**
## Motivation

As noted in #6859, some sites' `source` is not pointing to the website.

The following websites have been removed due to unavailability:

- Amphora
- OCPeasy
- Wisdom

cc @xtellurian @dbrrt @jagracey If you could inspect this or provide an alternative URL we are open to add them back.

GraphQL inspector is removed because it's no longer using Docusaurus.

These websites don't seem to be open-source despite my best effort to find their sources.

- Aide Jeune
- Clutch
- Component Kit
- Gulp
- TRPG Engine
- Quickwit

cc @l0u1sg @danielhochman @fabiomassimo @phated @moonrailgun @fmassot If your website is actually open-source, you can open up a follow-up PR to update the source URL.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

**Comment by fmassot** [comment]
@Josh-Cena oh right, the new link is `https://github.com/quickwit-inc/quickwit` and we are open source, I will open the PR.

**Comment by Josh-Cena** [comment]
@fmassot I saw the repo, but I couldn't find your website's source...

**Comment by danielhochman** [comment]
@Josh-Cena the Clutch site source is available in the main repo: https://github.com/lyft/clutch/tree/main/docs/_website

**Comment by phated** [comment]
@danielhochman https://github.com/gulpjs/gulpjs.github.io is the gulp website source

**Comment by Josh-Cena** [comment]
Thanks @danielhochman @phated Sent https://github.com/facebook/docusaurus/pull/6871. Sorry that I missed them!

**Comment by moonrailgun** [comment]
Hi @Josh-Cena 
My website is under sub dir in my repo. 

Here is source code:
[https://github.com/TRPGEngine/Server/tree/master/services/Website](https://github.com/TRPGEngine/Server/tree/master/services/Website)

**Comment by Josh-Cena** [comment]
Thanks @moonrailgun mind sending a PR yourself?

**Comment by moonrailgun** [comment]
> 

Well, here is my repo #6875

**Pull request merged**
