### PR TITLE
Add  documentation for `onPageNav`

### PR DESCRIPTION
**Pull request by JoelMarcey**
## Motivation

Adds documentation for `onPageNav`, which enables secondary, page-specific navigation.

And enable this option for docusaurus.io

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Local site testing

## Related PRs

https://github.com/facebook/Docusaurus/pull/475/

### CODE REVIEW

**Comment by violabg** [comment]
is there a special syntax to enable onPageNav, beside to have onPageNav: "separate", on the siteConfig?
because I can't get the onPageNav sidebar to show.

**Comment by JoelMarcey** [comment]
@violabg Hi! You will need to make sure you are using the proper markdown heading markers, in the right order

If you go here: https://docusaurus.io/docs/en/site-creation.html and the look at the markdown https://github.com/facebook/docusaurus/edit/master/docs/getting-started-site-creation.md, you will see you want 

##
###

to display the headers in the nav.

**Comment by violabg** [comment]
I’m sorry, but I can’t find any documentation that explains what kind of markdown I need to implement, in order to have onPageNav displaying on the right sidebar. 
I have many headers on my page, I have added anchor tags to them, but nothing. 
I have also generated a TOC to see if would display on the right.

**Comment by JoelMarcey** [comment]
@violabg Hi. There is no documentation on the proper markdown format to support the `onPageNav` - only what is shown in here. We //should// document it 😄 .

But I wanted to see if you updated your headers to a format like:

```
#
##
##
###
##
###
##
##
###
```

does that solve your problem.

Basically, you need one and only one H1, multiple H2 and possibly multiple H3 under any H2.

**Comment by violabg** [comment]
I did. And have onPageNav: "separate", on the siteConfig. 
Just to be sure. Does the example file created with Docusaurus-init suppose to have the right sidebar onPageNav?

**Comment by violabg** [comment]
I went through the generated code, and I found that onPageNav is there, but has display:none.
I'm testi in Safari 11.1, then I have checked on Chrome and is working.
I guess Safari doesn't pass @supports(position: sticky)  on main.css, which is weird since they were the first to adopt it.

**Comment by endiliey** [comment]
https://github.com/facebook/Docusaurus/blob/a603aff193096195bd805b5755f662d981d0857e/lib/static/css/main.css#L1443

**Comment by violabg** [comment]
Thanks, but the browser window is definitely bigger then 1024px.
Even the main site doesn't show the onPageNav on Safari:
https://docusaurus.io/docs/en/site-creation.html
It does on Chrome and Firefox.
This is definitely a Safari bug

**Comment by endiliey** [comment]
Seems like it's a bug. Aftet some googling, found out that sticky in safari worked differently with chrome & firefox. Too bad that i don't have a mac to test this out & fix it.

Do you want to try submitting a PR for this ? ☺

**Pull request merged**
