### PR TITLE
fix(v2): remove trailing slash from router links

### LINKED ISSUE #2394: Hosting environments that add a trailing back slash break page links
## 🐛 Bug Report
Hosting setups that add a trailing back slash to urls break all inter-site links on the page.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Create a new site using `npx @docusaurus/init@next init test-site classic`
1. Create two new sub folders in docs called `a` and `b`
1. Add attached file `a.md` to `a` folder, and `b.md` to `b` folder.
    - [a.md.zip](https://github.com/facebook/docusaurus/files/4308600/a.md.zip)
    - [b.md.zip](https://github.com/facebook/docusaurus/files/4308601/b.md.zip)
1. Replace `sidebar.js` with attached version.
    - [sidebars.js.zip](https://github.com/facebook/docusaurus/files/4308602/sidebars.js.zip)
1. run `npm run build` to generate the flat site.
1. Load the site in any browser by navigating directly to the url of page `a`: `http://127.0.0.1:8080/docs/a/a`
1. Click the link `Link to page "b"`

## Expected behavior

Page `b` should load.

## Actual Behavior

`Page Not Found` page.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.48
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Safari 13.0.5 (15608.5.11), Chrome 80.0.3987.132, Firefox 73.0.1
- Operating system and version (desktop or mobile): macOS 10.15.3 (19D76)

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

http://littlespex.com/docusaurus/docs/a/a

[test-site.zip](https://github.com/facebook/docusaurus/files/4308603/test-site.zip)

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Resolves #2394

Some hosting providers automatically add a trailing slash to the website links, which leads to the fact that some functionality stops working correctly. For example, in such cases, relative links to other Markdown files do not work. Therefore, to avoid this, we can remove the trailing slash from the internal (_which are processed by the router_) links before they get to the router. This is safe operation, because we usually get links without a trailing slash, and we can safely delete it.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

1. Create a Markdown file in a new subdirectory so that it refers to the file in the parent directory OR follow instructions in To Reproduce section in the issue #2394

docs/main.md:

```
---
id: main
title: Main page
---

Some page...
```

docs/sub/index.md:

```
---
id: sub
title: Subcategory page
---

See [main page](../main).
```

sidebars.js

```js
module.exports = {
  docs: {
    Root: ['main', 'sub/sub']
  }
}
```

Now, when navigating to the `docs/sub/sub` path without a trailing slash and with it (`docs/sub/sub/`), the result should be the same:

```html
<p><a href="/docs/main">See main page</a>.</p>
```

Earlier, when navigating a path with a trailing slash, the result was as follows:

```html
<p><a href="/docs/sub/main">See main page</a>.</p>
```

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by yangshun** [comment]
Is this truly safe? What if users were doing `../../` to circumvent the issue and now that we strip the trailing slash, their path will be wrong.

But I agree we should try to normalize and either add trailing slashes to all or strip all the trailing slashes.

**Comment by lex111** [comment]
I do not quite understand what you mean, someone will have links like
`[link](../../)`?

In this PR, an extra (redundant) slash in the current path is removed if
the hosting provider has automatically added it (eg. Netlify). Therefore,
it should not break anything.

пт, 27 мар. 2020 г. в 21:44, Yangshun Tay <notifications@github.com>:

**Comment by lex111** [comment]
I checked this change with links of more than one nesting level (`[Link](../../id)`), it is works fine.

**Comment by yangshun** [comment]
Yeah, so what I was saying is if we merge this PR, users who did that will now have the incorrect URL.

**Comment by yangshun** [comment]
Oh great, I'll do more testing first.

**Comment by lex111** [comment]
What side effects do you see here? Removing the trailing  slash (which was added by the hosting provider), we process the page as originally "intended" (i.e. without a slash). Therefore, if you call working linking a side effect, then yes, in this case it is.
We only change the path of current location, just as if you opened this link without trailing slash.

**Comment by yangshun** [comment]
The side effect is that you're modifying `window.location` (which a a global environment) within a component. `window.location` is not owned by the component. What if there's another similar component in some part of the code base that adds trailing slashes to `window.location`? You can't guarantee yours will always "win".

Why don't we modify the `targetLink` instead and leave the `window.location` alone?

**Comment by lex111** [comment]
Not sure if this will help in the issue solution. Well then I close it, maybe later it will be resolved by someone else.

**Pull request closed without merging**
