### PR TITLE
docs: fix typo in script command of typescript-support.mdx

### PR DESCRIPTION
**Pull request by brightzoe**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Test Plan
This is not a code change,only fix typo.

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

### CODE REVIEW

**Comment by Josh-Cena** [comment]
`npm run` requires the extra `--` to pass extra arguments. Has this changed? This isn't required for Yarn though.

**Comment by brightzoe** [comment]
> `npm run` requires the extra `--` to pass extra arguments. Has this changed? This isn't required for Yarn though.

Yes, you're right about the behavior of npm run and yarn run; that was my oversight. 

But I'm useing pnpm. As for pnpm, after further testing, I can confirm that it behaves like yarn: there's no need for an extra -- to pass additional arguments. Just place the arguments directly after the command. 

References: [pnpm run docs](https://pnpm.io/cli/run#options)

image

image

On inspecting the code, I traced the issue back to a third-party package `npm-to-yarn`. 

The specific problem seems to be located in the path https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-remark-plugin-npm2yarn/src/index.ts, related to the `npm-to-yarn` package.

so the issue is with [npm-to-yarn](https://github.com/nebrelbug/npm-to-yarn) ,not the a typo in docusaurus. This pr should be closed.

**Comment by OzakIOne** [comment]
Indeed the old command fails on my end with pnpm and doesn't fail with the new syntax, npm and yarn seems to be working with both syntax

image

**Comment by slorber** [comment]
hmmm

I thought this had been fixed in npm-to-yarn by @armano2 a while ago, first in a fork and then in the official repo.

Hasn't this been backported in npm-to-yarn @armano2 ? (https://github.com/facebook/docusaurus/pull/6005)

Or maybe there it has but there is a bug?

**Comment by armano2** [comment]
this change is present in yarn but has not been added to pnpm, i missed that when i added support for it in https://github.com/nebrelbug/npm-to-yarn/pull/37

https://github.com/nebrelbug/npm-to-yarn/blob/master/src/npmToYarn.ts#L139C1-L142C4

https://github.com/nebrelbug/npm-to-yarn/blob/233ff640c635332bf754c86db7412a61c6686b24/src/npmToPnpm.ts#L124

**Comment by slorber** [comment]
Thanks

I created the npm-to-yarn bug report, let me know if anyone wants to contribute a fix:
https://github.com/nebrelbug/npm-to-yarn/issues/44

**Pull request closed without merging**
