### PR TITLE
fixed backToTopButton hook

### LINKED ISSUE #10135: the backtotopbutton only shows when scrolling up slightly after scrolling down
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

After scrolling down the back to top button doesn't show unless you scroll up slightly. 

### Reproducible demo

_No response_

### Steps to reproduce

1. Go to https://docusaurus.io/docs/next/api/themes/configuration
2. Scroll down
3. Scroll up slightly - note that the backtotopbutton appears.

### Expected behavior

The button should appear once scrolling down past the threshold without the need to scroll up slightly.

### Actual behavior

The button doesn't appear until you scroll up again slightly.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

### PR DESCRIPTION
**Pull request by Raj-Mandal-20**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [x] **If this is a new API or substantial change**: the PR has an accompanying issue (#10135 ) and the maintainers have approved on my working plan.

## Related issues/PRs
  Fixes #10135

### CODE REVIEW

**Review by slorber — COMMENTED** [review]
Thanks for the PR

I'll turn it as a draft for now because we are still unsure of what we want to implement exactly.

See discussions here: https://github.com/facebook/docusaurus/issues/10135#issuecomment-2115846822

**Comment by Raj-Mandal-20** [comment]
@slorber Apart from this do we have any Slack or Discord channel for communication?

**Comment by slorber** [comment]
> @slorber Apart from this do we have any Slack or Discord channel for communication?

We have a Discord server that you can find in the website footer

**Comment by slorber** [comment]
Thanks for your PR

Unfortunately we have decided to not implement this for now.
See https://github.com/facebook/docusaurus/issues/10135#issuecomment-2264860260

**Pull request closed without merging**
