### PR TITLE
test: add tests for gitUtils

### PR DESCRIPTION
**Pull request by Josh-Cena**
## Motivation

Added some basic tests so this file is at least test-covered.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Oh, read your reasoning in #6593. Honestly, continuously amending a commit doesn't sound like a terribly common practice, but I'm fine with this way.

**Comment by Josh-Cena** [comment]
Oops, forgot to check Windows status again...

**Comment by felipecrs** [comment]
The tests turned out great, by the way. :)

**Pull request merged**
