### PR TITLE
chore(v2): remove unused hooks from bootstrap theme

### PR DESCRIPTION
**Pull request by fanny**
## Motivation

Remove hooks related to dark theme
### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

yes
## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)
N\A

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by anshulrgoyal** [comment]
@fanny  can u provide some docs for the bootstrap theme. We are writing validation for all official plugin and themes. But I am unable to find docs for it. Here is the https://github.com/facebook/docusaurus/pull/2970

**Comment by fanny** [comment]
Opss.. I deleted the PR that made this, I'll upload again.

**Comment by anshulrgoyal** [comment]
@fanny I talking more about `themeConfig`.

**Comment by fanny** [comment]
It's here #2981

**Pull request merged**
