### PR TITLE
Make font-family as configurable parameter(#220)

### PR DESCRIPTION
**Pull request by cowlingj**
## Motivation

issue: #220

## Test Plan

1. Edit siteConfig.js to include fonts object with keys mapped to arrays of font names
```js
fonts: {
  myKey: [
    "Times New Roman",
    "Serif"
  ],
  myOtherKey: [
    "-apple-system",
    "system-ui"
  ]
},
```
2. add the corresponding keys as font-family variables in a css file in the form $<key>
```css
h1 {
  font-family: $myKey;
}
```
3. run server

### CODE REVIEW

**Comment by JoelMarcey** [comment]
@cowlingj Thank you very much for this PR to fix the currently hard coded `font-family` issue. 

Did you try, locally, using your new approach in `main.css` and see if the Docusaurus site, the test site that comes with running `docusaurus-init`, or any other site would load the same with the proper fonts?

**Comment by JoelMarcey** [comment]
@cowlingj Hi. Just pinging to see what site you tested this change on? Thanks!

**Comment by cowlingj** [comment]
I've tested both, first adding custom fonts in the `siteConfig.js` and `custom.css` of both, then the docusarus site by building and running with npm, and a site ran with `docusarus-init` by calling `start-server.js` directly.

**Comment by JoelMarcey** [comment]
My Prettier work here is becoming a bit funny. I will get it :)

**Pull request merged**
