### PR TITLE
Fixed Typo

### PR DESCRIPTION
**Pull request by dimaaac**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [x] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

### CODE REVIEW

**Comment by dimaaac** [comment]
literally, fixed typo. i will soon be contributing and adding documentations.

**Comment by dimaaac** [comment]
Why?

**Comment by slorber** [comment]
Why what?
You don't explain your changes so I assume it's fine to close without explaning why either

**Comment by dimaaac** [comment]
It's straight forward. I fixed a typo 💀

**Comment by Josh-Cena** [comment]
@dimaaac None of your changes are "typos". The examples aren't "scripts". They are actual project files that should be built by Docusaurus (something to be built is not a "script"). The capitalization doesn't really make a difference before or after.

In the future, please explain yourself even when fixing typos, because, for example, we don't find the change to "scripts" any convincing, and neither are the others. There are some legit copy edits such as adding the period and changing capitalization for the sake of consistency, but we don't think it warrants a PR on itself—we mostly welcome significant code or documentation contributions.

**Pull request closed without merging**
