### PR TITLE
fix(utils): allow partially backticked markdown h1 contentTitles

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [x] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

See https://github.com/facebook/docusaurus/discussions/8294 - I want h1s with inline code please 😄 

## Test Plan

I ... don't have one beyond unit tests.

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

## Related issues/PRs

https://github.com/facebook/docusaurus/discussions/8294 - would you like me to file an issue? Or can someone convert that to one?

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Fun, isn't this function only used for sanitizing metadata like browser tab title? Does it work when rendering?

**Comment by JoshuaKGoldberg** [comment]
Yeah, this is a start, but I want to try more. Just blocked on #8315 for testing page changes 😄

**Comment by JoshuaKGoldberg** [comment]
Or, I guess while that gets worked on, can we get this as a partial fix in the meantime? I think this will at least partially improve the situation?

**Comment by slorber** [comment]
👍 thanks

Looks like it's working as we want it to:

CleanShot 2022-11-17 at 11 35 49@2x

**Pull request merged**
