### PR TITLE
docs: fix more references to Discord channels

### PR DESCRIPTION
**Pull request by Josh-Cena**
## Motivation

Missed a few places in #5581 because I used case-sensitive global search🤦‍♂️

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

**Review by lex111 — APPROVED** [review]

**Comment by lex111** [comment]
@Josh-Cena thanks!

**Comment by Josh-Cena** [comment]
The production deployment has been failing for a while I believe, unable to see any new changes to the doc. Can someone inspect that?

**Comment by lex111** [comment]
Apparently this is due to the zh-CN translation.

image

**Comment by Josh-Cena** [comment]
Fixed that. Maybe we should set `onBrokenLinks: 'warn'` in production so that translation contributors don't crash the entire site?

**Comment by lex111** [comment]
I think @slorber will clarify this point.

**Comment by slorber** [comment]
I'd prefer to keep throwing until we have a way to report broken link errors, otherwise those could stay unnoticed (I don't think we often check for logs of successful deployments)

We could extend the system to accept a function to have CI build warnings being sent to a Discord channel or something

**Comment by Josh-Cena** [comment]
Is it possible to report production build status in the CI status? I have a project that uses Netlify and deployment is part of CI, so I can know if it fails through GitHub

**Comment by slorber** [comment]
We have an icon on the repo readme:

image


This is not visible enough though.

Netlify has a notification system, but afaik it reports ALL failures, not just for the production branch, and it's a bit annoying. Also no Discord integration.

**Pull request merged**
