### PR TITLE
fix(v2): tidy up Markdown page layout

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Quite strange looking now markdown page, I suppose it should be aligned to center like on all the other pages (see screenshots below).

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

| Before <br/> (https://docusaurus.io/examples/markdownPageExample)   | After <br/> (https://deploy-preview-4917--docusaurus-2.netlify.app/examples/markdownPageExample)    |
| -------- | -------- |
| image | image |

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by slorber** [comment]
I'm not a designer but find it better if the actual content remains centered.

I don't like too much the idea of having the TOC move the content to the left.

Also, wouldn't this lead to different md page layouts for pages with/without TOC?

Is the content of a page without TOC moved to the left (would be weird)? or in this case, the content is in the center?

 I'd rather keep them all looking the same so that it's not confusing when you navigate from a page with TOC to a page without TOC (ie the content remains at the same place)

**Comment by lex111** [comment]
I just implement the same behavior as on the doc page, `hide_table_of_contents=true` is useful if the user wants to expand the width of content part:

| Default ( `hide_table_of_contents=false`)   | With `hide_table_of_contents=true`    |
| -------- | -------- |
| image | image |

So I thought it would be helpful on regular pages as well.

**Comment by slorber** [comment]
Hmmm isn't it the same screenshot? Can't tell the differences.

@yangshun any opinion regarding how the content should be centered?

**Comment by lex111** [comment]
I wanted to show that if TOC is hidden, then the content column is stretched to container full width.

**Review by yangshun — APPROVED** [review]

**Pull request merged**
