### PR TITLE
Fix translation urls take 2

### PR DESCRIPTION
**Pull request by neilsutcliffe**
## Motivation

I wanted to improve the health of the codebase by ensuring that we end up defaulting to the English language less.

Then I noticed the code had to be changed in two places and that wasn't very DRY.

So now, I made this giant pull-request before I need to sleep to work tommorow. I'm already 3 hours overdue.

## Test Plan

I cannot get building to work on mine. Has building been tested on Windows?

This PR has been tested with the Docusaurus site itself, but I haven't tested versioning, or building. 

Ensure that pages get picked up, even if they are in the language subfolder.

## Related PRs

#322

### CODE REVIEW

**Comment by JoelMarcey** [comment]
@neilsutcliffe Hi! Could you pull out the vscode support into a separate PR?

I was just about to publish a PR with some stuff, but remembered you had stuff in this PR, so I figure you should be able to add that?

**Comment by neilsutcliffe** [comment]
Sure thing. One sec.

**Comment by JoelMarcey** [comment]
@neilsutcliffe Hi. Are you closing this in lieu of something else? Or you feel it is not needed any longer? Or something else?

**Comment by neilsutcliffe** [comment]
I heard you were taking Christmas off :)

It's all still in my repo if you want to check, but I'm working on a different more testable pull request for the build fix. The process to remove English as the default language is not so easy, and I think it needs to be something we gradually work towards.

It's dangerous to touch too many areas of the system in one swoop. So I'll be keeping the changes I made for this in my mind.

**Comment by neilsutcliffe** [comment]
I made another change to make the default json file default.json for example, and my refactoring work clarifies how we deal with languages. For example, there are no 'en' variables in any of the code i have locally.

A problem I have to worry about as well is that many of the sites deployed have got 'en' as a default language.

I'm learning a lot though :D

**Pull request closed without merging**
