### PR TITLE
fix(theme-classic): shrink title size on mobile

### PR DESCRIPTION
**Pull request by Pierre-Gilles**
## Motivation

Fix https://github.com/facebook/docusaurus/issues/7003, I noticed that the title on blog post are really big on mobile.

I change the current size from (left) to (right) on mobile: 

Docusaurus PR

Note: I didn't change anything on tablet size, it looked good to me.

I try with `1.5rem` too, but then the title of the page was smaller than the H2 in the page, so it looked weird.

Let me know if the value is fine 🙂

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Open one article and compare to the production documentation.

### CODE REVIEW

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
1. Can we port the same font size to docs?
2. Would this make h2 headings bigger than h1?

**Comment by Josh-Cena** [comment]
TBH, I can't say for sure either 😅 I would leave this to @slorber to review

**Comment by lex111** [comment]
If we want to set the headings sizing for mobiles, it is better to do this in the corresponding file in the Infima repository first https://github.com/facebookincubator/infima/blob/main/packages/core/styles/content/markdown.pcss

**Comment by slorber** [comment]
That looks good enough to me. Any concern merging this now @lex111 ?

**Comment by lex111** [comment]
@slorber I guess it's acceptable to merge.

**Pull request merged**
