### PR TITLE
bug: fixes docs sidebar to display without overlapping elements

### PR DESCRIPTION
**Pull request by r-lawrence**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
> tests were not written as changes were to CSS only.

## Motivation

[Issue #8370](https://github.com/facebook/docusaurus/issues/8370) indicates there is a layout issue when the anouncementBar is present.  After investigation, it appears the button with `title` `Collapse Sidebar` is causing the issue.  The `position` for this element is set to `sticky`.  When adjusting screen size this causes the button to start seeping into the `Sidebar Ad` element.

This PR removes the `sticky` positioning from the CSS file related to the `Collapse Sidebar` button.  This allows both the `SideBar Ad` and `Collapse Sidebar` button to display in all view ports without overlapping.
## Test Plan
**Verify the problem:**

1. navigate to https://docusaurus.io/tests/docs
2. using your browser developer tools in a responsive view, resize the window until you see the `Collapse Sidebar` button start overlapping with the `Sidebar Ad` element.

_image of problem:_
Screenshot 2022-11-25 at 1 54 55 PM

**verify the fix**

1. download this branch to your local or use the environment spun up to test changes.
2. navigate to `/tests/docs` <- start of URL will differ based on environment.  EX local would be - http://localhost:3000/tests/docs
4. using your browser developer tools in a responsive view, resize the height of the window again, this time notice that the `Collapse Sidebar` button does not start overlapping the `Sidebar Ad` element at any height.

_image of fix:_
Screenshot 2022-11-25 at 1 57 02 PM

### Test links
Deploy preview: https://deploy-preview-8377--docusaurus-2.netlify.app/tests/docs

## Related issues/PRs
[Issue #8370](https://github.com/facebook/docusaurus/issues/8370)

### CODE REVIEW

**Comment by slorber** [comment]
Thanks, will review this soon

By chance do you know if it also fixes https://github.com/facebook/docusaurus/issues/8374 ?

**Comment by r-lawrence** [comment]
> Thanks, will review this soon
> 
> By chance do you know if it also fixes #8374 ?

Hi @slorber I took a look at the related ticket and think I may have introduced a new bug.  I think im needing clarification on how this display should look.

When an announcement ad is present, the current functionality in prod  on page https://docusaurus.io/docs, renders the sidebar back button like this.

Screenshot 2022-11-30 at 3 08 54 PM


Looking at the deploy preview for this branch, its being rendered differently:

- with announcement add active:
Screenshot 2022-11-30 at 3 04 37 PM

- without announcement add active:
Screenshot 2022-11-30 at 3 13 30 PM

_it appears when the announcement is active with the change from the current branch, the back button gets pushed down and only a partial button appears.  When the announcement isn't present, the full back button appears _

Im wondering,

- On this branch, while the announcement is active it appears its not pushing down the sidebar back button and making it partially visible.  Is this ok?

or

- should the back button in the sidebar for the https://docusaurus.io/docs page be completely visible, regardless if the add is present or not?

**Comment by slorber** [comment]
Yes it's not working as we expect here

CleanShot 2022-12-08 at 16 37 06@2x


The collapse button is supposed to remain visible with/without the announcement bar, and the scrollbar position should also be correct

**Review by slorber — CHANGES_REQUESTED** [review]
Yes it's not working as we expect here

CleanShot 2022-12-08 at 16 37 06@2x


The collapse button is supposed to remain visible with/without the announcement bar, and the scrollbar position should also be correct.

Making this work probably requires a more complex refactor of our layouts. 

Not sure exactly what should be done, unfortunately, but my intuition think using this CSS var is not the correct solution:

```js
margin-bottom: var(--docusaurus-announcement-bar-height);
```

If you want to keep working on it, please let me know, otherwise you can close the PR and someone else will give it a try

**Comment by Djunnni** [comment]
@slorber Are Sidebar Ads variable height? Or is it fixed at 40px?
Can i try? because he was no answer 2 weeks over

**Comment by r-lawrence** [comment]
Hello @slorber, Ive been out of town the last few days and dont have my computer with me.  Im coming home today and was hoping between tonight/tomorrow I could give it another shot.  Thanks a bunch, Ill be updating the PR within the next 24-48 hours.

**Comment by r-lawrence** [comment]
I looked into the problem a bit deeper and I agree with you.  Looking at how the aside element that contains the sidebar is rendering on the page, it appears we would have to re-think how this sidebar is laid out, to create the correct display functionality with or without the add display. 

I'm going to continue to work on this, but am going to close the PR for now.  Because it may take me longer to think up a working solution, I'de like to give others a chance to give it a shot as well.  Thanks

**Comment by slorber** [comment]
Thanks for trying :)

> @slorber Are Sidebar Ads variable height? Or is it fixed at 40px? Can i try? because he was no answer 2 weeks over

If the height is fixed (I think it is), I'd prefer it to become dynamic in the future

**Pull request closed without merging**
