### PR TITLE
v1.7.3

### PR DESCRIPTION
**Pull request by jakebolam**
## Motivation
Release fixes

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Netlify.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by jakebolam** [comment]
We're trying to fix a violation with the algolia policy, and require a fix in master to be released. Any chance we can release this? (Relevant issue here: https://github.com/facebook/Docusaurus/pull/1240)

[Issue comment](https://github.com/facebook/Docusaurus/pull/1240#issuecomment-466770996)

**Comment by yangshun** [comment]
Deploy preview for *munseo-preview* ready!

Built with commit 1ffd9930cae330e63751c2615dc5b8d8c168e270

https://deploy-preview-1286--munseo-preview.netlify.com

**Comment by endiliey** [comment]
i will release 1.7.3 asap. most likely today

**Comment by jakebolam** [comment]
Thanks for all your great work on this project @yangshun, happy to help

**Pull request merged**
