### PR TITLE
Added support for anchors on sidebar

### PR DESCRIPTION
**Pull request by marcosvega91**
## Motivation

Hi, i like this project and so I have decided to improve the docusaurus functionality implementing the one suggested by @JoelMarcey. 

## Test Plan

I haven't completed the feature yet. It works now but I have to add support for i18n and add some styles. 
I have added an option key for each category into the sidebar.json called anchors. This key is an array of anchors. The anchors are saved as metadata inside metadata.js and then they will be rendered into sidebar as an ul list inside category (image below) .

image

### CODE REVIEW

**Comment by JoelMarcey** [comment]
@marcosvega91 Thank you very much for this pull request. I need to get a release out with some bug fixes, but I will review this right afterwards.

**Comment by marcosvega91** [comment]
Hi @JoelMarcey  thanks for your time. Today I have fixed a bug that caused the failing of tests. Now I would improve my code

**Comment by JoelMarcey** [comment]
@marcosvega91 Hi! Did you want me to review this PR as it is? Or were you planning any other changes/improvements?

**Comment by JoelMarcey** [comment]
I say we give this PR a go - we won't be in any worse shape than where we are now if it indeed does not actually publish, right? I would just be more confused as to why since I personally set this personal access token up myself. :)

**Comment by marcosvega91** [comment]
Hi @JoelMarcey I would like to add the support for translation for the anchors, but in these days I didn't have so much time

**Comment by microbouji** [comment]
Hi @marcosvega91! If you're still interested in working on this we now have autogenerated anchors from the document headings. Check out #474 and #475. You can use the `OnPageNav` component to display the list of anchors under the currently active list item when the new siteConfig.js option `onPageNav` is set to `'embed'`.

**Comment by JoelMarcey** [comment]
Hi @marcosvega91 @microbouji - Just to be clear - `embed` doesn't currently exist - it would have to be created as the option represented by this PR in combination with what @microbouji did.

**Comment by yangshun** [comment]
@marcosvega91 How is it going with the planned changes/improvements? Let us know how you can help! If you have less time these days to work on it, it's totally ok, just let us know and we can take it from here.

**Comment by yangshun** [comment]
Closing due to inactivity. Feel free to reopen.

**Pull request closed without merging**
