### PR TITLE
Refactor of Build Process

### PR DESCRIPTION
**Pull request by neilsutcliffe**
Progress towards #336 and #325 as we need to unify the render functions between the server and build process. ATM they are two completely parallel processes.

Whilst this PR doesn't actually solve that problem, it sets the render functions up nicely to be called from the server.

I've also commented some extra areas which need some attention.

The jest tests for build all pass on Windows, and I tried with multiple languages. One thing that did fail was setting English disabled and enabling another language. That may be an existing issue however.

Update: Build now succeeds on UNIX

### CODE REVIEW

**Comment by neilsutcliffe** [comment]
Can reproduce build error locally now, fixing it up.

**Comment by neilsutcliffe** [comment]
Woo! Tests are all working.

**Comment by neilsutcliffe** [comment]
I found a way to avoid having logic related to which document to link to in the HTML render function. It seems robust enough, but ultimately makes that area of the code far simpler. I think that's it for today though.

**Comment by JoelMarcey** [comment]
@neilsutcliffe Hi! I think I want to get this in the next release. Can you rebase?

**Comment by neilsutcliffe** [comment]
I'll get this rebased once I can get to a computer. I suggest getting it onto a release branch rather than merging straight into master however. That way if there are any issues you don't have to revert master and it keeps the history cleaner.

**Comment by neilsutcliffe** [comment]
Hi. I'm still alive, just hectic moving house and all.

**Comment by JoelMarcey** [comment]
@neilsutcliffe I know how much of a crazy time moving can be. Totally understand.

**Comment by neilsutcliffe** [comment]
https://xkcd.com/323/

I've rebased and made the CSS use the shared library. This makes the upcoming theme support easier.

**Comment by JoelMarcey** [comment]
@neilsutcliffe Hi Neil! I think it is time we start looking at bringing some of this refactor in soon. If you are still interested, can you do a clean rebase - there shouldn't be 59 changed files as it shows now. It is showing identical changes that have been merged already. I am thinking the number of changed files should be on the order of 10 or so -- basically only the ones you changed/deleted/added.

**Comment by neilsutcliffe** [comment]
The styles bit will also conflict with #422, however that PR doesn't merge the style file for the generate.js file as well.

**Comment by neilsutcliffe** [comment]
Feel free to use whatever you like from this, but I'm out. I have my own projects I've been putting off.

The main concerns I have are that English is considered the default language. i18n is the main distinction between this product and something like Jekyll, and good open source projects may come from anywhere across the globe.

If there the English translation is default, how would you get an English translation project that has Japanese as the "en" language.

Anyway, good luck.

**Comment by JoelMarcey** [comment]
@neilsutcliffe will do. My plan was to use at least some of this as part of an overall v2.0 launch and a blog post. 

I hope you weren’t putting off projects because of this particular PR. If so, my apologies. I appreciate the contributions you have provided to Docusaurus.

Good luck on your projects!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
