### PR TITLE
chore: update changelog

### PR DESCRIPTION
**Pull request by endiliey**
## Motivation

Some internal chores, updating changelog proactively

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

N/A

### CODE REVIEW

**Comment by JoelMarcey** [comment]
Hi @endiliey - is the idea here to update the changelog on every relevant commit moving forward? Or is this a one time thing?

**Comment by endiliey** [comment]
@joelmarcey

Actually i did this just to help the next person doing the release since there is a lot of commits this time.

But Ideally we can try updating changelog *just right before merging PR*. What do you think ?

**Comment by JoelMarcey** [comment]
So for every PR we merge, we update the changelog along with it? I like that in theory. We can use a template to put it in the right form. And then when we release we can rearrange things to make the log more like it is now when it is done manually.

**Comment by endiliey** [comment]
Yes. I think its much better to do small increment than big increment at once. Jest is doing it like this

I am not really sure on the template though.

**Pull request merged**
