### PR TITLE
ci: enable yarn install cache

### PR DESCRIPTION
**Pull request by armano2**
## Motivation

https://github.com/actions/cache/blob/main/examples.md#node---yarn
https://github.com/actions/cache/blob/main/examples.md#node---yarn-2

ci build time is now reduced per job by 30s~1min

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### CODE REVIEW

**Comment by slorber** [comment]
Hey, that's a cool idea

Was just wondering if there isn't a way to remove all that verbosity?

I've used this action recently and it worked great, can it be used instead?
https://github.com/bahmutov/npm-install

**Comment by armano2** [comment]
it can be used, and its your call if you think that's a good idea

**Comment by slorber** [comment]
yes I think `- uses: bahmutov/npm-install@v1` would be better.

Do you want to edit this PR or we close and I do another one?

**Comment by armano2** [comment]
i'm going to update this pr, do you think that we should apply this for windows machines to?

**Comment by slorber** [comment]
thanks, that looks fine

**Comment by slorber** [comment]
I think we can enable this on Windows too, do you see any reason not to?

**Comment by armano2** [comment]
generally caching on windows gh actions seem to be slow, i will try it out

**Comment by slorber** [comment]
didn't know that, is it documented or your personal experience? slower than no caching at all?

**Comment by slorber** [comment]
let's merge this for now and see if we can improve windows in another PR

**Pull request merged**
