### PR TITLE
misc: avoid using fs.realpathSync in website

### PR DESCRIPTION
**Pull request by Zamiell**
fixes `yarn start`, from @Josh-Cena

### CODE REVIEW

**Comment by Josh-Cena** [comment]
For context: this doesn't work on virtually every Windows machine. See https://github.com/facebook/docusaurus/issues/7052 for one.

`fs.realpathSync` is really not very useful because it just points to the original directory. We may well just use the original one, then.

**Review by Josh-Cena — APPROVED** [review]
Thanks!

**Comment by slorber** [comment]
I don't understand, how do we test for our symlinked dir support now?

**Comment by Josh-Cena** [comment]
How is `fs.realpathSync` testing anything in practice, though? It always evaluates to `"_dogfooding/_docs tests"`. On machines that don't support symlinks (i.e. all Windows machines), it always causes an error that I have to teach them to fix. Previously when we had `resolve.symlinks: false` for Webpack, it seems more worthwhile to test.

**Comment by slorber** [comment]
ok 👍 true

**Pull request merged**
