### PR TITLE
feat(docs): allow to configure noIndex per doc version

### PR DESCRIPTION
**Pull request by slorber**
## Motivation

You might want to prevent crawlers and google to index older versions of your docs

See also https://github.com/facebook/docusaurus/discussions/7960

## Test Plan

unit tests + local tests + dogfood on test docs instance (as it's not really useful to index it)

### Test links

Deploy preview: 
- https://deploy-preview-7963--docusaurus-2.netlify.app/tests/docs
- https://deploy-preview-7963--docusaurus-2.netlify.app/sitemap.xml

---

Limitation: the versioned docs tag pages won't be noIndexed. But a further refactor will fix it soon.

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
Question: how does this play with the sitemap? Over there, we only test `tag.props.name === 'robots' && tag.props.content === 'noindex'`. Maybe it should be `tag.props.content.includes("noindex")` instead?

**Comment by slorber** [comment]
> Question: how does this play with the sitemap? Over there, we only test `tag.props.name === 'robots' && tag.props.content === 'noindex'`. Maybe it should be `tag.props.content.includes("noindex")` instead?

Yes definitively! I thought it was already the case actually 😅 will send another PR and edited our sitemap plugin so that we can see the problem. Will merge a sitemap plugin fix before this PR, ensuring we can see the problem fixed here.

**Comment by slorber** [comment]
BTW I guess having a noIndex: true flag for plugin instances in a generic way could be useful 🤷‍♂️ we also want to have a label, wonder what else makes sense as a general option for a plugin instance.

Not going to implement this here, but let's keep this in mind

**Comment by slorber** [comment]
working fine now

those tag urls are still there in the sitemap and indexed, will do another refactor to fix that

```xml
<url>
<loc>https://docusaurus.io/tests/docs/tags/</loc>
<changefreq>weekly</changefreq>
<priority>0.5</priority>
</url>
<url>
<loc>https://docusaurus.io/tests/docs/tags/a/</loc>
<changefreq>weekly</changefreq>
<priority>0.5</priority>
</url>
<url>
<loc>https://docusaurus.io/tests/docs/tags/b/</loc>
<changefreq>weekly</changefreq>
<priority>0.5</priority>
</url>
<url>
<loc>https://docusaurus.io/tests/docs/tags/c/</loc>
<changefreq>weekly</changefreq>
<priority>0.5</priority>
</url>
<url>
<loc>https://docusaurus.io/tests/docs/tags/d-custom-permalink/</loc>
<changefreq>weekly</changefreq>
<priority>0.5</priority>
</url>
<url>
<loc>https://docusaurus.io/tests/docs/tags/e/</loc>
<changefreq>weekly</changefreq>
<priority>0.5</priority>
</url>
<url>
<loc>https://docusaurus.io/tests/docs/tags/some-tag/</loc>
<changefreq>weekly</changefreq>
<priority>0.5</priority>
</url>
```

**Pull request merged**
