### PR TITLE
docs: add a link to easily add your project with a form

### PR DESCRIPTION
**Pull request by ymschaap**
**Re: this discussion:** https://github.com/facebook/Docusaurus/issues/1080#issuecomment-440346187

### Why:
Adding a project to the users list now involves forking, editing a js file, uploading a logo, creating a PR, reviewing. Which can be made much simpler with a Github bot that transforms a form submission into the right Pull Request.

### What:
This PR links to a new web based submission form from the [users](https://docusaurus.io/en/users) page: https://build.amsterdam/your-company/docusaurus

### How:
* fill out the form
* submit
* backend creates a PR that updates the users.js and uploads the logo, and wraps it in a PR.

**As gif:**

### Example Bot PR:
How a bot PR looks like:
https://github.com/ymschaap/Docusaurus/pull/3

Let me know your thoughts if interested work on merging.

### CODE REVIEW

**Comment by JoelMarcey** [comment]
@ymschaap Hi. This is actually really cool 😄 

We definitely are interested in merging this, but we would need a few things first:

1. Rebase the PR
2. Can you make it so that new users are added alphabetically?
3. Add docs on how to use this?

Thanks!

**Comment by ymschaap** [comment]
Great.

@JoelMarcey
1. Rebase done
2. Fixed sorting bug when adding a new users (wasn't case-insensitive)
3. What kind of docs are you thinking of? To explain what happens when you submit the form? Or how the tool works?

@yangshun
1. I want to move the config for this form-to-PR tool to Github as well. Now I indeed make the change manually, but I want to open this up asap so maintainers can change it (and support all Docusaurus projects). But don't have a ETA yet.
2. Now it tags the person in the PR. I have to dive into the Github API to see if the commit can be easily made under the user's name. Imho if they value the commit under their name, the original route to manually do a PR remains and would be their choice, no?

**Comment by endiliey** [comment]
What is the blocker of this PR ?

**Comment by endiliey** [comment]
I think we are not going forward with this. Sorry. Thank you for the PR though 😉

**Pull request closed without merging**
