### PR TITLE
docs(v2): New doc page for math equations

### PR DESCRIPTION
**Pull request by pranabdas**
## Motivation

Rendering LaTeX math equations is an important feature for many documentation sites. Although, it is possible to write math equations using Docusaurus, it is not documented in the Docs. 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

I have created a new file `website/docs/guides/markdown-features/markdown-features-math-equations.mdx`, and made changes to  the sidebar configuration (`website/sidebars.js`) to include it in the sidebar. I have tested the doc website locally, and it works properly.

## Related PRs

- https://github.com/facebook/docusaurus/issues/4017

### CODE REVIEW

**Comment by slorber** [comment]
Hey, thanks for this doc

I've updated it a bit and enabled Katex on Docusaurus site for dogfooding and ensure this remains usable.

Helped me figure out some potential problems in versions (hast-util-is-element absolutely need to be 1.1.0 or it won't work)

**Comment by pranabdas** [comment]
Thank you for catching the dependencies. I did not test on Docusaurus website (was not sure if it would be good idea to change *package.json*). For me it worked fine on a cleanly built site:
```js
npm i @docusaurus/core@latest @docusaurus/preset-classic@latest
npm i remark-math@3 rehype-katex
```

**Comment by slorber** [comment]
rehype-katex has published v5 recently, I'm not sure it's compatible anymore. In any case I think it's preferable to lock to specific major versions as our doc may start failing other time when new incompatible majors are released

**Comment by pranabdas** [comment]
I updated some of my Doc sites to rehype-katex v5 along with docusaurus v2-beta0 couple of weeks ago. Have not noticed any glitch yet ([an example page with lots of math equations](https://pranabdas.github.io/qe-dft/dft)). But it make sense to lock major versions, and upgrade manually.

**Comment by slorber** [comment]
hey @pranabdas , was wondering how did you decide to use an external cdn URL for this asset.

As I'm having network issues, this resource is blocking and preventing me to work locally easily

So I'll move the docusaurus site to self-hosted CSS to unblock me, but we should probably recommend users to do the same 🤷‍♂️

**Comment by pranabdas** [comment]
Hello @slorber, I did not think about its pros and cons much. Probably there is not much of cons hosting `katex.min.css` locally, as it is only 23 KB and relatively low chance that it would be cached by the browser (because the user downloaded the same resource used in another website).

**Comment by pranabdas** [comment]
@slorber I also realise that we need to host required katex fonts alongside katex stylesheet. Total asset size is ~1.2MB. Is that much build size increase acceptable? If you like, I can create a PR with proposed changes. Thank you.

**Pull request merged**
