### PR TITLE
fix: docs sidebar layout issue when announcementBar visible

### PR DESCRIPTION
**Pull request by proke03**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

### Test links
https://deploy-preview-8567--docusaurus-2.netlify.app/tests/docs/toc/toc-_-5/
https://deploy-preview-8567--docusaurus-2.netlify.app/docs/sidebar/items

Deploy preview: https://deploy-preview-8567--docusaurus-2.netlify.app/

## Related issues/PRs
#8370

### CODE REVIEW

**Comment by proke03** [comment]
After submiting this PR, I signed the CLA.

**Review by slorber — CHANGES_REQUESTED** [review]
Thanks for trying but unfortunately it is not the kind of solution we are looking for.

We are not looking to solve the "Sidebar ad" problem only (something only displayed on our own site), but rather to find a generic solution that will not lead to issues for all docusaurus sites.

On your preview, the problem is still present for all other Docusaurus pages that do not present the sidebarAd component. Just scroll a few pixels of the main scrollbar to see the issue:

CleanShot 2023-01-25 at 17 56 45@2x

**Comment by proke03** [comment]
Reverted changes to Sidebar ad.
This is a problem caused by the length of the sidebar menu not changing when the Announcementbar disappears.
So when it checked the showAnnouncementBar variable, it referenced the length of the announcementBar. And I modified the height style value of the menu element in the sidebar.

**Comment by slorber** [comment]
Doesn't seem to work as I'd like it to:

CleanShot 2023-03-08 at 19 39 50@2x

**Comment by slorber** [comment]
Thanks for giving it a try.

For now I'm going to close all the pending PRs trying to solve this issue, see https://github.com/facebook/docusaurus/issues/8370#issuecomment-1500129085

**Pull request closed without merging**
