### PR TITLE
Add another text of Circle CI which is runnable

### LINKED ISSUE #671: The first build of Circle CI failed
1. Copy the text of Circle CI to my project in .circle/config.yml and push it to master.
2. Start building on Circle CI, but the result of building is failure .
The error message is as below:
image
3.But after that, when I push something again to master, it builds successfully! That is odd.

If not use workflow, The first build will always be successful. So I add another text of Circle CI.

### PR DESCRIPTION
**Pull request by ysyfff**
fix #671

### CODE REVIEW

**Comment by ysyfff** [comment]
@yangshun see #671

**Comment by JoelMarcey** [comment]
@ysyfff Hi! I am not sure we should have two sets of instructions for Circle. Last week, I added the config specified in the docs to the [Pyre repo](https://github.com/facebook/pyre-check/blob/master/.circleci/config.yml) and it worked right away.

So, in my opinion, either something got messed up with your copy and paste with what was currently in the docs or something was wrong with Circle at the time, maybe.

But we should just have one set of instructions that works -- not two.

**Comment by ysyfff** [comment]
@JoelMarcey **Hi!** I also think something was wrong with Circle. 
Maybe one set of instruction that works is better.

I recommend to use the set of of instruction of mine which is always right.

**Comment by JoelMarcey** [comment]
@ysyfff Hi! That's thing the thing. I am not sure that what is currently there is not right. We use it in a bunch of places and it works great. Like I said, I literally used that template in a project last week. And it also offers information about adding a bit of extra functionality in case you need it.

Even https://github.com/facebook/jest/blob/master/.circleci/config.yml uses the template and expands upon it.

**Comment by JoelMarcey** [comment]
@ysyfff Circle also just confirmed an outage yesterday. Maybe you tried running with the current instructions during that time?

**Comment by yangshun** [comment]
I'll try out the entire CircleCI flow on a fresh project this weekend to test.

**Comment by ysyfff** [comment]
I hope other people will not be confused with the same problem especially who is fresh with Circle.

**Pull request closed without merging**
