### PR TITLE
test(v2): add protocol relative uri validation test

### PR DESCRIPTION
**Pull request by moonrailgun**
## Motivation

I Wanna Support relative url like `//docusaurus.io` in footer link item in `href` field

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yep

## Test Plan

I append a test case for relative url in URISchema test case 

or manual modify `themeConfig-footer-links-items-href` field start with `//`(not `http://` or `https://`)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by tommilligan** [comment]
I've run into a similar issue already - I believe your issue will be solved by #3449 which is a more permissive implementation (will allow relative URIs such as `../<path>` as well as `//<path>`).

If you could take a look, I'm happy to merge in the unit tests for your case.

**Comment by moonrailgun** [comment]
> I've run into a similar issue already - I believe your issue will be solved by #3449 which is a more permissive implementation (will allow relative URIs such as `../<path>` as well as `//<path>`).
> 
> If you could take a look, I'm happy to merge in the unit tests for your case.

@tommilligan 
Well, I check your PR. I also use joi's `allowRelative` at first. But i think relative uri like a simple string is not a good URI schema check. Then i write it manual.

**Comment by moonrailgun** [comment]
For your case, why not use `to` field? I have no idea about the reason of need full reload

**Comment by tommilligan** [comment]
The reason for a full reload is I'm linking to an external, but relative path. In my case I'm linking from say, `example.com/docs` which is the root of our docusaurus app, to `example.com`, which is an independent static site. They do not share JS code, are not the same SPA etc.

A full reload is required, otherwise docusaurus simply interprets the relative link as requiring a `history.push(...)` call, which triggers an internal JS component load but not a full HTTP page reload. This leads to a 404 page.

To force the full reload, I set `href` and `target`, as this cannot be achieved with `to` as far as I'm aware.

**Comment by moonrailgun** [comment]
@tommilligan 

Its looks like `swizzle` can be helpful for your case.

try type in your cli
```bash
npx docusaurus swizzle @docusaurus/theme-classic Navbar
```
and modify your own navbar if your pull request not been approval. In my mind its should not a common way.

for offical document: https://v2.docusaurus.io/docs/cli/#docusaurus-swizzle

**Comment by tommilligan** [comment]
@moonrailgun actually, I've just tried setting both `to` and `target` as you suggested and it works - thanks! I guess in that case I'm confused as to why both `to` and `href` are allowed, but :shrug: 

Thanks for your help!

**Review by lex111 — APPROVED** [review]

**Comment by slorber** [comment]
Thanks,

Actually updated the PR but kept the test cases, because @tommilligan is right, // is included in the {relativeUri: true} option (that I merged).

**Comment by slorber** [comment]
BTW, it's worth nothing that relative protocol uris are considered an antipattern according to https://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by slorber** [comment]
> @moonrailgun actually, I've just tried setting both to and target as you suggested and it works - thanks! I guess in that case I'm confused as to why both to and href are allowed, but 🤷

This is a confusing part of this project, and is historically like this. Will try to improve that but it's not so easy to make changes without annoying users with breaking changes unfortunately

**Comment by moonrailgun** [comment]
@slorber Well, i just consider about should simple text should identified as a uri?

like `relativeURL`.

Maybe i am too prudent.

**Pull request merged**
