### PR TITLE
docs(v2): add documentation for prog nav API issue #2562

### PR DESCRIPTION
**Pull request by csfj87**
## Motivation

I was motivated to contribute, because I'm a beginner to open source and I wanted to work on something to get me started.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

I didn't change functionally code, but I did add CSS to document how to use the hook. The changes should work, because I copy and pasted the template of the hook above it, and changed what I needed to from there.

### CODE REVIEW

**Comment by csfj87** [comment]
Here is a screenshot of what it will look like.
useHistoryDocusaurus

**Comment by csfj87** [comment]
Here is a preview of the update.
useHistory

**Comment by csfj87** [comment]
Here is a preview of the u
useHistory
pdate.

**Comment by slorber** [comment]
Hi

That does not seem correct documentation, this hook has nothing to do with Algolia

**Pull request closed without merging**
