### PR TITLE
fix: do not hardcode siteConfig path

### PR DESCRIPTION
**Pull request by JoelMarcey**
## Motivation

Fix broken build

Fixes https://github.com/facebook/Docusaurus/issues/1149

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, I helped write them.

## Test Plan

Local Testing

## Related PRs

https://github.com/facebook/Docusaurus/pull/1143

### CODE REVIEW

**Comment by JoelMarcey** [comment]
@endiliey, @yangshun -- the v1 tests are failing, but I am wondering if the test itself is not write due to the faulty include in the first place.

**Comment by JoelMarcey** [comment]
Unless I am totally missing something here, this should be the proper fix to the path issue.

**Comment by endiliey** [comment]
This is because on test. process.cwd() is actually not `website`, it's the root project directory. That's why I dislike having `process.cwd()` on v1. We have to mock it during the test.

**Comment by endiliey** [comment]
I'm gonna patch this PR and make `server/utils` to be purely functional without side effect. Having require siteConfig made the utils functions having side effect.

**Comment by JoelMarcey** [comment]
@endiliey - I trust you 👍

**Pull request merged**
