### PR TITLE
Added Hashnode support site to showcase

### PR DESCRIPTION
**Pull request by iamshadmirza**
## Motivation

We built [Hashnode support](https://support.hashnode.com/) site using docusaurus and want to showcase that on the `/showcase` page

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

I updated the files inside `website/src/data/users` and tested them by running `yarn start`

## Related PRs

None
(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by slorber** [comment]
thanks for choosing docusaurus 👍 

just waiting for the CLA signature process to complete before being able to merge

**Comment by slorber** [comment]
@iamshadmirza can you please sign the FB CLA?

Unfortunately, I'm unable to merge this PR without it

**Comment by iamshadmirza** [comment]
Hey @slorber, the CLA is signed. You can merge the PR now. Sorry for the delay.

**Comment by lex111** [comment]
@iamshadmirza thanks!

**Pull request merged**
