### PR TITLE
feat(v2): bootstrap theme, preset, template, CI previews

### PR DESCRIPTION
**Pull request by fanny**
## Motivation

Document the bootstrap template, preset and theme 
### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes
## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by slorber** [comment]
🤪 just understood that is theme is for Bootstrap the CSS framework.

I thought it was about providing the basic theme structure to be able to render docs, blogs etc ^^

Is this PR ready for review or WIP?

**Comment by fanny** [comment]
> 🤪 just understood that is theme is for Bootstrap the CSS framework.
> 
> I thought it was about providing the basic theme structure to be able to render docs, blogs etc ^^
> 
> Is this PR ready for review or WIP?

Sorry for the delay, you're right. And Is Ready for review

**Comment by slorber** [comment]
@fanny what's your workflow to test the bootstrap theme btw? I've never seen it in action

**Comment by yangshun** [comment]
It should be just going into the Bootstrap template, run the site and visually inspect

**Comment by slorber** [comment]
I see thanks.

One idea I had was to make our deploy previews deploy D2 website in multiple variants, like theme classic, theme bootstrap etc... that would dogfood and ensure this theme keeps the feature parity with the classic theme and stays in sync over time

**Comment by yangshun** [comment]
That would be fantastic :)

**Comment by slorber** [comment]
@yangshun @fanny it's not perfect but got it running  :)

https://deploy-preview-2981--docusaurus-2.netlify.app/classic/
https://deploy-preview-2981--docusaurus-2.netlify.app/bootstrap/

Both will be deployed on each PR now! Will make it easier to iterate on the bootstrap theme.

Note: I disabled versioning for bootstrap previews, so that it does not increase too much the build time ;)

**Pull request merged**
