### PR TITLE
docs(deployment): add GITHUB_TOKEN permission info...

### PR DESCRIPTION
**Pull request by chillinPanda**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [x] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

When I set up a new docusaurus repo and following the GitHub Pages deployment guide with GitHub Actions, I ran into the issue, that the automatic token has read only access per default.

In order to help new users I added information to the guide, so other users don't have to figure it out on their own

## Test Plan

no code change, only mdx

### Test links

https://deploy-preview-9373--docusaurus-2.netlify.app/docs/deployment#triggering-deployment-with-github-actions

http://localhost:3000/docs/deployment#triggering-deployment-with-github-actions

New details box "GITHUB_TOKEN permissions"

### CODE REVIEW

**Comment by slorber** [comment]
https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-first-deployment-with-github_token

CleanShot 2023-10-05 at 12 35 36@2x

CleanShot 2023-10-05 at 12 36 07@2x

Are you sure that you followed our instructions properly?

If you did, please create a repro showing the GH pages deployment failing despite using the recommended config.

**Comment by chillinPanda** [comment]
Hi @slorber, 

thank you for taking the time to have a look into and answering with much details :) 👍

I used the deploy.yml from the current version (2.4.3) -> https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions

In the next / canary version I see indeed the permissions section like in your screenshot. In the 2.4.3 it is not there yet.

I reverted the token permissions to the default state and added the permissions section to my action yml and it is working.

So my issue is already solved in the next version and I close this PR.

**Comment by slorber** [comment]
Thanks

If you want you can add the Yaml permission to the v2.4.3 docs, didn't see it wasn't there and it would help others as well.

**Comment by chillinPanda** [comment]
Hi @slorber ,

Good idea! Will do.

I didn't know that it is ok to modify the current version.

But in this case the addition also works with 2.4.3, so it's a good idea to do.

**Comment by chillinPanda** [comment]
Hi @slorber ,

I created a new PR: #9377

**Pull request closed without merging**
