### PR TITLE
fix(website): resize images to width 640

### PR DESCRIPTION
**Pull request by slorber**
## Motivation

See also https://github.com/facebook/docusaurus/issues/5980

640 seems like a good baseline to resize showcase images and the smallest image size found atm. 

It's unlikely we'll render those images above 600px anyway even on Retina.

For favorite sites, we may need higher res screenshots later but we can easily redo them.

Using `mogrify -resize 640 website/src/data/showcase/*.png -quality 100%`

Not 100% sure it's a good way for now.

Quality seems worst (not sure? will see in preview) than before and some items are heavier than before 🤷‍♂️ 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

yes

## Test Plan

preview

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Seems some images have been _upscaled_? Or is it just because of deoptimisation...

**Comment by armano2** [comment]
biggest difference in metadata of those images is palette used, rn, you are encoding them in full rgb

**Comment by slorber** [comment]
yes it doesn't look good to merge 😅 

I don't think images are upscaled but the output does not seem optimized. If someone want to take a look let me know. CLI tools are not so good it seems (or I'm using the wrong options?) or we have to chain multiple of them to have a decent output 🤷‍♂️

**Comment by armano2** [comment]
what do you think about:

```sh
mogrify -filter Triangle -define filter:support=2 -resize 640 -unsharp 0.25x0.25+8+0.065 -dither None -posterize 136 -quality 100 -colors 255 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB -strip website/src/data/showcase/*.png
```

**Comment by slorber** [comment]
🤯 I have no idea :D If you want to open another PR we can see if the preview and diff size is good ;)

**Comment by armano2** [comment]
i opened new pr #6043

**Pull request closed without merging**
