### PR TITLE
feat(v1): strip html from TOC

### PR DESCRIPTION
**Pull request by ThisIsMissEm**
## Motivation

As a developer using [kafkajs](https://kafka.js.org), I was annoyed by their TOC links constantly being broken or formatted totally unreadably, so I decided to write a fix.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

yes, CLA signed.

## Test Plan

Added test cases to verify the output is correct; haven't yet run Docusaurus on itself, but the test cases cover what's changed.

```
$ jest packages/docusaurus-1.x/lib/core/__tests__/toc.test.js
```

## What changed

The approach here is to first strip the HTML from the heading's content, then rendered it with markdown to get the HTML content for the TOC entry, then to strip the HTML from the rendered content again, as to get the text for the TOC entry's link.

⚠️Adds an additional dependency of [striptags](https://npm.im/striptags) (MIT licensed)

closes issue #1703, https://github.com/tulios/kafkajs/issues/450

## Example Output

Given the heading of:

```markdown
## <a name="foo"></a> Foo
```

This change will now mean the TOC Entry for that heading will be:

```javascript
{
  hashLink: 'foo',
  rawContent: '<a name="foo"></a> _Foo_',
  content: '<em>Foo</em>',
  children: []
}
```

Previously it would have been:

```javascript
{
  hashLink: 'a-name-foo-a-_foo_',
  rawContent: '<a name="foo"></a> _Foo_',
  content: '&lt;a name=&quot;foo&quot;&gt;&lt;/a&gt; <em>Foo</em>',
  children: []
}
```

## Screenshots

<table>
  <tr>
    <th>Before</th>
    <th>After</th>
  </tr>
  <tr>
    <td>Screenshot 2019-08-18 at 04 35 36</td>
    <td>Screenshot 2019-08-18 at 04 35 26</td>
  </tr>
</table>

## Related PRs

https://github.com/facebook/docusaurus/pull/1740 — I looked at that PR first, but felt like it was removing functionality by just using `rawContent`, as this actually would result in, for instance, the `<a name="foo"></a>` from the above example to be outputted into the document twice, which isn't probably the intention.

### CODE REVIEW

**Comment by ThisIsMissEm** [comment]
It's also perhaps good to note that if the heading has markdown in the middle of it, e.g.,

```
## Using this _awesome_ tool
```

Then the hash link will be `using-this-awesome-tool`, i.e., markdown doesn't result in additional dashes in the URL

**Comment by ThisIsMissEm** [comment]
Also, should this have been a `feat` or a breaking change? It does mean permalinks to content before this change and after this change won't match.

**Comment by Nevon** [comment]
Fixes #1703 

Some context on why this is important for us, that was missing from the discussion in #1740: we manually create anchor tags in our headings because the software we ship contains links back to the documentation within error logs, so we need the links to stay the same even if we end up changing the wording of the heading. This broke with some update of Docusaurus.

The fix looks good to me, but I'm not overly familiar with the internals of Docusaurus.

**Comment by ThisIsMissEm** [comment]
@yangshun hey, can you let me know when the minor version bump is out, that way I can do an PR for the kafkajs project to upgrade us.

**Comment by yangshun** [comment]
@ThisIsMissEm We just published v1.13.0

**Pull request merged**
