### PR TITLE
docs: add OSS Insight to showcase

### PR DESCRIPTION
**Pull request by sykp241095**
## Motivation

We want to add https://ossinsight.io into showcases.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Great to see PingCAP using it—been following TiDB for a long time. 

Just remember to upload the image and sign the CLA so we can review & merge

**Review by Josh-Cena — APPROVED** [review]
Great, thanks!

**Comment by Josh-Cena** [comment]
Off-topic: half a year ago, Docusaurus was 29k stars and TiDB was 30k; now Docusaurus is 32k and TiDB is 31k :DDD

**Comment by slorber** [comment]
Cool oss features 👍

**Pull request merged**
