### PR TITLE
Enhancing Website Responsiveness with React 18 Selective Hydration 🚀

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
Hello,
This pull request introduces an enhancement in the hydration process by leveraging the new React 18 Selective Hydration feature. This improvement aims to make websites feel more responsive.

I noticed that this approach has been implemented in Vercel's official Next.js e-commerce template, which can be found at the following link: https://github.com/vercel/commerce/blob/2448f5201c06b629787544dc2c181d8def01a23c/app/layout.tsx#L39

For more information about Selective Hydration, you can refer to the following resources:
1) Official YouTube video: https://youtu.be/pj5N-Khihgc?si=mZRaovscAN0o4eaS&t=14m35s
2) GitHub Discussion: https://github.com/reactwg/react-18/discussions/37

Extremely sorry, if I made any mistakes :)

### CODE REVIEW

**Comment by sanjaiyan-dev** [comment]
> Hello, This pull request introduces an enhancement in the hydration process by leveraging the new React 18 Selective Hydration feature. This improvement aims to make websites feel more responsive.
> 
> I noticed that this approach has been implemented in Vercel's official Next.js e-commerce template, which can be found at the following link: https://github.com/vercel/commerce/blob/2448f5201c06b629787544dc2c181d8def01a23c/app/layout.tsx#L39
> 
> For more information about Selective Hydration, you can refer to the following resources:
> 
> 1. Official YouTube video: https://youtu.be/pj5N-Khihgc?si=mZRaovscAN0o4eaS&t=14m35s
> 2. GitHub Discussion: [New Suspense SSR Architecture in React 18 reactwg/react-18#37](https://github.com/reactwg/react-18/discussions/37)
> 
> Extremely sorry, if I made any mistakes :)

Additional Reference -: https://github.com/reactwg/react-18/discussions/130

**Comment by sanjaiyan-dev** [comment]
`<Suspense>` in React 18 introduces a powerful feature called Selective Hydration, which optimizes the hydration process of components. It allows React to progressively enhance sections of an application based on user interactions. Rather than requiring the entire codebase to be downloaded and executed upfront, Selective Hydration loads and hydrates only the components that users are actively engaging with. This not only improves the user experience by making the application more responsive but also conserves network bandwidth and system resources by loading code on demand. In summary, Selective Hydration in `<Suspense>` prioritizes and streamlines component hydration, offering a more efficient and user-friendly web application experience.

Additional Reference -: https://github.com/reactwg/react-18/discussions/130

**Comment by Josh-Cena** [comment]
I'll let @slorber decide, but I don't think this is useful, because you've basically suspended the main content of the website, without which the site is non-functional anyway. We are also building a fully static site with progressive enhancement, so this is an entirely different problem domain from an e-commerce site where content has to be rendered dynamically.

**Comment by slorber** [comment]
Hey

For now I'd rather not merge this PR, because I need to experiment more to be sure the behavior we implement, and eventually need to discuss a bit what Suspense could mean for static sites with the React team (because it's not super well documented currently, cf https://react.dev/reference/react-dom/server/renderToPipeableStream#waiting-for-all-content-to-load-for-crawlers-and-static-generation)


This is also why I added this danger admonition in our v3 blog post:

CleanShot 2023-11-26 at 23 07 53@2x

https://docusaurus.io/blog/releases/3.0#react-18

This also relates to `React.lazy` and the legacy `react-loadable` library that we are using.

---

Thanks for your work but please avoid sending PRs using such new React features. I am well aware of the new features and if I don't work on them it's usually because I'm not 100% sure of the behavior we want to adopt. Open an RFC/proposal first to see if a PR is welcome.

**Comment by sanjaiyan-dev** [comment]
> Hey
> 
> For now I'd rather not merge this PR, because I need to experiment more to be sure the behavior we implement, and eventually need to discuss a bit what Suspense could mean for static sites with the React team (because it's not super well documented currently, cf https://react.dev/reference/react-dom/server/renderToPipeableStream#waiting-for-all-content-to-load-for-crawlers-and-static-generation)
> 
> This is also why I added this danger admonition in our v3 blog post:
> 
> CleanShot 2023-11-26 at 23 07 53@2x
> https://docusaurus.io/blog/releases/3.0#react-18
> 
> This also relates to `React.lazy` and the legacy `react-loadable` library that we are using.
> 
> Thanks for your work but please avoid sending PRs using such new React features. I am well aware of the new features and if I don't work on them it's usually because I'm not 100% sure of the behavior we want to adopt. Open an RFC/proposal first to see if a PR is welcome.

I apologize for any inconvenience caused. OK, I understand your preference. I'll refrain from sending PRs with new React features and will consider opening an RFC/proposal first. Thank you for clarifying.

**Pull request closed without merging**
