### PR TITLE
fix(theme-translations): fix Turkish translation for aria label "Enter key"

### PR DESCRIPTION
**Pull request by LiberaTeMetuMortis**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [x] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

### CODE REVIEW

**Comment by slorber** [comment]
Thanks @LiberaTeMetuMortis, LGTM 👍 

I need you to sign the CLA, I can't merge without this

**Comment by LiberaTeMetuMortis** [comment]
> CLA



> Thanks @LiberaTeMetuMortis, LGTM +1
> 
> I need you to sign the CLA, I can't merge without this

I signed it.

**Comment by slorber** [comment]
> > CLA
> 
> > Thanks @LiberaTeMetuMortis, LGTM +1
> > I need you to sign the CLA, I can't merge without this
> 
> I signed it.

Thanks,

It is possible that our CLA bot is delayed to report your signature then.

We will have to wait until it validates your signature before being able to merge this PR

**Comment by LiberaTeMetuMortis** [comment]
> > > CLA
> > 
> > 
> > > Thanks @LiberaTeMetuMortis, LGTM +1
> > > I need you to sign the CLA, I can't merge without this
> > 
> > 
> > I signed it.
> 
> Thanks,
> 
> It is possible that our CLA bot is delayed to report your signature then.
> 
> We will have to wait until it validates your signature before being able to merge this PR

It added the CLA Signed flag.

**Pull request merged**
