### PR TITLE
chore: enable react/jsx-closing-bracket-location

### PR DESCRIPTION
**Pull request by nschonni**
## Motivation

This no longer appears to conflict with prettier

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

N/A

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by Josh-Cena** [comment]
But... if Prettier already checks it and fixes it, why do we need to enable it anyways?

**Comment by Josh-Cena** [comment]
@nschonni But... if Prettier already checks it and fixes it, why do we need to enable it anyways?

**Comment by nschonni** [comment]
Up to you, I just find it better to leave the defaults that are coming from the `extends` unless there is a conflict (like there used to be)

**Review by Josh-Cena — APPROVED** [review]
Sure, I clearly see the value in not disabling rules although enabling them don't change anything

**Pull request merged**
