### PR TITLE
feat(core, theme-classic): allow overriding htmlLang

### PR DESCRIPTION
**Pull request by noomorph**
## Motivation

1. I'm in the middle of building [a website](https://interslavic.fun) for Interslavic language which is available in multiple locales and scripts. The problem is that Interslavic language has quite a long BCP-47 language tag: `art-x-interslv`.[^1]
    
    
    
    Besides, since it supports equally the Latin and Cyrillic scripts, you ought[^2] to specify the script as well: `art-Latn-x-interslv` and `art-Cyrl-x-interslv` respectively. Also, the language has a for-internal-use script with extra etymological letters[^3], the so-called Etymological (or Scientific) alphabet, which we agreed to have under `art-Latn-x-interslv-etymolog`.
    
    [^1]: See ConLang Code Registry: https://www.kreativekorp.com/clcr/
    [^2]: See page 12: https://tools.ietf.org/search/bcp47
    [^3]: http://steen.free.fr/interslavic/orthography.html#etymological_alphabet

2. Docusaurus is too coupled at the moment to the language code – you have to maintain directory and URL structure accordingly to the code. I'd like to shorten my directory names and URLs to `.../sla-Latn/...` and `.../sla-Cyrl/...`, for example, but I'd still want to render the adopted BCP 47 language tag in the document markup.

   Without this feature, even the home page would have a URL like `https://interslavic.fun/art-Latn-x-interslv-etymolog`, which looks clumsy.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes, although some parts I skimmed. 🙏 

## Test Plan

In your `docusaurus.config.js`, try overriding your `i18n` section, e.g.:

```diff
   i18n: {
     defaultLocale: 'en',
+    localeConfig: {
+      en: { htmlLang: 'en-GB' }
+    }
```

After reloading the website, check that you see `<html lang="en-GB">` in the rendered HTML markup.

## Related PRs

* feat(v2): add support for RTL direction: https://github.com/facebook/docusaurus/pull/4140
* fix(v2): fix/enhance minor i18n issues reported: https://github.com/facebook/docusaurus/pull/4092

### CODE REVIEW

**Comment by slorber** [comment]
Thanks, LGTM 👍 

nice site, please add it to our showcase ;)

**Comment by Josh-Cena** [comment]
Oops, forgot about docs🤦‍♂️

**Comment by slorber** [comment]
😅 missed that too

**Comment by noomorph** [comment]
@slorber , @Josh-Cena , so what action is required? Please elaborate and I'll try to supplement what's missing.

**Comment by Josh-Cena** [comment]
No worries @noomorph I'll write some docs. I have long planned to renew the i18n docs, going to document this change as well.

**Comment by slorber** [comment]
It wouldn't harm to add it here quickly @noomorph : https://docusaurus.io/docs/api/docusaurus-config#i18n

This way we are sure to not forget when updating the i18n doc ;)

**Pull request merged**
