### PR TITLE
feat(v2): CodeBlock copy button

### LINKED ISSUE #1587: copy code button for Docusaurus 2
## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

Support copy codeblock button for Docusaurus 2

## Where to start

Start docusaurus 2 website
1. Clone this repository
2. Read https://github.com/facebook/Docusaurus/tree/master/website and start website
3. Go to any docs url with codeblock. maybe http://localhost:3000/docs/installation
image

Modify here to test in Docusaurus 2 to add the copy code button
https://github.com/facebook/Docusaurus/blob/1aa0ea1152b0133830d127d11b123fcea261deb4/packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js#L33-L53

Also make sure to duplicate the change to https://github.com/facebook/Docusaurus/blob/master/packages/docusaurus-theme-classic/src/theme/CodeBlock/index.js

Send PR !!

### PR DESCRIPTION
**Pull request by bvego**
## Motivation

Hi there. The motivation behind this was so many websites that don't have the copy button.
The design was pretty much eyeballed but is open for suggestions. I chose not to go with an icon here.

Attempts to close #1587 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

- bootstrap the dependencies with
- ```sh
   yarn
   ```
- Start the project with
- ```sh
   yarn start
   ```
- Navigate to any codeblock, i.e. `http://localhost:3000/docs/installation`
- Hover the codeblock
- Click the copy button

I've only wrapped the `pre` element with a `div` that acts as a wrapper and use it for anchoring the position of the copy button.

I've used the `clipboard` package for copying because I saw it elsewhere in the repo

Edit:
I also noticed that `packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/styles.module.css` and `packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css` are missing the copyright notice on the top.

Maybe it's indented but just wanted point it out if it slipped through.

### CODE REVIEW

**Comment by bvego** [comment]
Oh wow, what a blunder 😦 

Pushed a fix, works now

**Comment by endiliey** [comment]
cc @yangshun @wgao19 on UI feedback.

**Comment by endiliey** [comment]
> However, I wonder if there's a way we can avoid duplicating the buttons in theme-classic/CodeBlock and theme-live-codeblock. It's not really ideal to have so much duplication. WDYT @endilie

ideally if we want to avoid duplication we have to make one as another dependency. But i think its out of this PR scope.

**Comment by endiliey** [comment]
lets merge this out first ?

**Comment by endiliey** [comment]
Thanks a lot @bvego

you are awesome

**Pull request merged**
