### PR TITLE
docs: update showcase data for digital support notes

### PR DESCRIPTION
**Pull request by PatelN123**
## Motivation

The motivation to complete this change was because I felt that before the site had a standard look, and now it has a more modern look. The purpose of this PR is to keep the showcase up-to-date with images. 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

**Comment by PatelN123** [comment]
I should also mention that I have compressed the image down to 81KB, from the three hundred and something the old image had.

**Comment by Josh-Cena** [comment]
The old file was massive because I'm retina screen and I forgot to resize after taking the screenshot🤦‍♂️

**Comment by PatelN123** [comment]
@Josh-Cena Add your screenshot, if you think it'll look better. :)

**Comment by Josh-Cena** [comment]
The current one is fine. It's still large (1880px wide) but better

**Pull request merged**
