### PR TITLE
Move Verifying Installation section to Installation doc

### PR DESCRIPTION
**Pull request by gedeagas**
## Motivation
The verifying installation section on site preparation is not in the right place 
and I think maybe this should be in the installation section.

In (https://github.com/facebook/Docusaurus/issues/431) @JoelMarcey mentions about the first paragraph that will need to be updated but I didn't know what should be updated in there.

### CODE REVIEW

**Comment by JoelMarcey** [comment]
@gedeagas Hi. Did you want to make the update to this PR for the first paragraph in `getting-started-preparation` given the feedback in #431 ?

**Comment by JoelMarcey** [comment]
I am going to merge this. And then I can make another separate change as discussed in #431.

**Comment by gedeagas** [comment]
hey @JoelMarcey I am sorry that I can't make the change that we discussed here https://github.com/facebook/Docusaurus/issues/431 because I have been busy for the past week 😞.

**Comment by JoelMarcey** [comment]
@gedeagas No problem at all. Thank you for your PR. I was able to make that change. We worked together :D

**Pull request merged**
