### PR TITLE
docusaurus opencollective reminder #1527

### PR DESCRIPTION
**Pull request by jwandrews99**
## Motivation

Contribute to open source to grow my self.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Not quite sure how to test, willing to take tips

### CODE REVIEW

**Comment by jwandrews99** [comment]
Hi,

Thank you, I shall try that test and get some screenshots

**Comment by jwandrews99** [comment]
I need to start again, going to close this and re do as i know what i am doing with the pr. Open collective is working on install. Will have screenshots in the next pr

**Comment by yangshun** [comment]
@jwandrews99 You could update your branch and then the PR would be updated. But it's fine, you're free to restart. Please ensure you're working off the latest master branch. We had a bad commit and had to reset the master branch.

**Comment by endiliey** [comment]
It should be done after docusaurus install, not after installing this repo.

**Pull request closed without merging**
