### PR TITLE
feat(v2): only create one css file to avoid code-split css loading problem

### LINKED ISSUE #2006: The same CSS files are injected several times when switching pages
## 🐛 Bug Report

I noticed a strange bug when switching pages (Home -> Docs -> Blog) CSS styles are **duplicated** (re-injected as I understand it correctly).

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Open devtools and focus on styles (body eg)
1. Open Home page (https://v2.docusaurus.io/) and we can already see that the styles are duplicated!
image

1. Alright, go ahead, click on Docs (https://v2.docusaurus.io/docs/introduction) in navbar and check the styles in devtools again, now the styles are duplicated several times (**+3 new**)!
image

## Expected behavior

Styles should not be duplicated (re-injected) when moving to other pages.

## Actual Behavior

For some reason, the same styles are injected, which overridden the earlier ones.

## Reproducible Demo

See To Reproduce section.

### PR DESCRIPTION
**Pull request by endiliey**
## Motivation

Close #2006 

See issue for reasoning

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

yes

## Test Plan

- yarn build, only one css file is created
- netlify ???
- no css break on local build

caveat:
- dont know how big is our css 😭

### CODE REVIEW

**Comment by endiliey** [comment]
webpack bundle analyzer won't display css size. But before gzip, its 92kb in windows explorer
image

**Comment by yangshun** [comment]
It's 17kb after gzip based on the preview. I inspected the files and saw that the extra CSS is react-toggle, algolia search and some page-specific CSS modules. LGTM.

**Comment by endiliey** [comment]
As a side note it decreases web dev lighthouse performance by 10 
image

I wonder if we can somehow reduce the size

> This is fine considering previously it was 16.3kb split across 2 files.
Previously it wasn't the case, because the infima css is already loaded in main bundle. while the other css is code-splitted. So it's 10.2kb first and the rest is code-splitted

So going to https://v2.docusaurus.io/ is 10 + 6kb
image

Then going to https://v2.docusaurus.io/docs/introduction is probably another 6kb.

This is definitely better though long-term wise. Just wishing we can tree shake that css hehehe

**Comment by lex111** [comment]
What about something like critical CSS or a similar technique?

**Comment by endiliey** [comment]
Happy to accept PR on that :)

**Pull request merged**
