### PR TITLE
Add customize highlightjs support

### LINKED ISSUE #428: custom highlight.css url
### Is this a bug report?

No， This is a feature

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Environment

(OS, Node, npm, yarn)

### Steps to Reproduce

**Our users mostly locate in China，they not not freely visit  cloudflare**
I want to get control of the hightlight.js url, I wish you can‘t give the options to developer self

Thanks for yours attention

### Expected Behavior

Just give the `highlight` config in `siteConfig.js` the full url options

### PR DESCRIPTION
**Pull request by huang-x-h**
## Motivation

To fixed #428 - add customize highlight support

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Test ok on my local build

## Related PRs

N/A

### CODE REVIEW

**Comment by JoelMarcey** [comment]
@huang-x-h Hi. Just curious why you closed this. When I first looked at it, I had a few questions on it; just hadn’t gotten to commenting on it yet.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by huang-x-h** [comment]
@JoelMarcey Sorry, it doesn't work, and have some error on testing local. I don't want people to wonder, so i close it.

**Comment by huang-x-h** [comment]
And i have a question, `highlightjs` is import in `package.json`, why not just copy the theme file from `node_modules`?

**Comment by JoelMarcey** [comment]
@huang-x-h Sorry, I am not sure I understand your question. For us, `highlight.js` is a dependency for Docusaurus to function correctly when it comes to syntax highlighting. That's why it is in the `package.json`. What do you mean copy the theme file?

**Comment by huang-x-h** [comment]
@JoelMarcey Yes, `highlight.js` is a dependency, and `siteConfig.js` has a `highlight` option define

```js
highlight: {
  theme: 'solarized-dark',
},
```

it used to set theme path

```jsx
<link
      rel="stylesheet"
      href={`//cdnjs.cloudflare.com/ajax/libs/highlight.js/${highlightVersion}/styles/${highlightTheme}.min.css`}
/>
```

But in `node_modules/highlight.js/styles`, we have the all theme files, so we can copy this (`node_modules/highlight.js/styles/solarized-dark.css`) instead of use `cdnjs` and if the `theme` options has `'/'` like `/somepath/my-theme.css` which means custom theme path

**Comment by wulucxy** [comment]
@huang-x-h @JoelMarcey  did this PR merged？

**Comment by JoelMarcey** [comment]
Hi @wulucxy - There is a new PR for this - https://github.com/facebook/Docusaurus/pull/517

**Pull request closed without merging**
