### PR TITLE
feat(content-docs): new front matter options to customize pagination

### LINKED ISSUE #5688: Use doc front matter to customize pagination
## 🚀 Feature

An option to hide specific pagination buttons, and repoint pagination links to other doc pages.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Has this been requested on [Canny](https://docusaurus.io/feature-requests)?

https://docusaurus.io/feature-requests/p/allow-for-non-linear-navigation _kind of_ points to this

## Motivation

To allow for non-linear navigation; also related to #5686 because this will be used home pages where navigation doesn't make sense

## API Design

- `pagination_next: my-doc` (a doc ID)
- `pagination_prev: my-doc`
- `pagination_next: false` (disable pagination)
- `pagination_prev: false`

## Have you tried building it?

Yes, using swizzling and adding CSS to hide pagination; but repointing links would require editing on the plugin side

### PR DESCRIPTION
**Pull request by Josh-Cena**
## Motivation

Close #5688.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Refactoring that bulky `docs.ts` file is probably too much for this feature PR. If we are to further separate the code I'll do that in a separate refactor PR. On my list are `docs.ts`, `index.ts` and `versions.ts`, and my goal is to make each file 100~200 lines

**Comment by Josh-Cena** [comment]
> However I'm struggling with the syntax in the package.json to point to it. 

I don't really have much idea. I don't publish my fork, so I don't think it's in the NPM registry. If you are using Yarn berry, you can use [`patch`](https://yarnpkg.com/cli/patch) and manually incorporate my changes

**Comment by mbalex99** [comment]
Thanks! I tried all of that and didn't get anywhere. In particular tried https://gitpkg.vercel.app/

```json
"@docusaurus/core": "https://gitpkg.now.sh/Josh-Cena/docusaurus/packages/docusaurus?frontmatter-pagination",
"@docusaurus/preset-classic": "https://gitpkg.now.sh/Josh-Cena/docusaurus/packages/docusaurus-preset-classic?frontmatter-pagination",
```

However, I'm getting this error when running the app:

```
Error: Cannot find module '../lib'
Require stack:
- /Users/maxalex/ditto/docs/node_modules/@docusaurus/core/bin/docusaurus.js
```

Maybe I can just wait for this to land in a release. Any idea when this might happen? Again many thanks for this feature and PR!

**Comment by slorber** [comment]
👍 LGTM thanks ;)

**Pull request merged**
