### PR TITLE
misc: show only latest archive alpha/beta versions dropdown

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Currently versions dropdown on the site is quite long, I propose to reduce its items by showing only the latest archived versions, since all available versions already renders on the "Versions" page.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Preview.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by Josh-Cena** [comment]
What's the rationale to keep the last Alpha release? The alpha-beta cutoff was pretty arbitrary iirc, and beta.0 is not much different from alpha.75. From the [NPM stats](https://www.npmjs.com/package/@docusaurus/core) it doesn't seem alpha versions are very popular either

**Comment by slorber** [comment]
Agree that it's not so useful to keep the latest alphas. 
I'd rather keep the last 5 archived versions in the dropdown + 1.x.
Other versions remain available on the "All Versions" page anyway.
It's probably worth creating a `const ArchivedVersionsDropdownItems`

> Also, surprised to see such significant bundle size optimization👀

I don't understand either, would be interesting to investigate and see a diff

**Comment by lex111** [comment]
> I'd rather keep the last 5 archived versions in the dropdown + 1.x.

There won't be any alpha version in dropdown, alright then, but maybe we shouldn't create extra var for this?

**Comment by slorber** [comment]
Looks good enough for now thanks 👍

**Comment by slorber** [comment]
FYI about the file size diff: https://github.com/facebook/docusaurus/issues/5865

**Pull request merged**
