### PR TITLE
fix(theme-translations): add missing zh-Hans messages

### PR DESCRIPTION
**Pull request by chudongvip**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [x] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

It is not fix a bug, just help translate default translates of language zh-Hans.

## Test Plan

NO

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

### CODE REVIEW

**Comment by slorber** [comment]
Thanks. 

We need you to sign the CLA otherwise it's impossible to merge. (sometimes it can takes hours to report your signatures so we'll just have to wait)

**Comment by slorber** [comment]
@chudongvip can you sign the CLA please? 

Otherwise I'll have to close and let someone else submit a fix

**Comment by chudongvip** [comment]
> @chudongvip can you sign the CLA please?
> 
> Otherwise I'll have to close and let someone else submit a fix

Sure. I have signed the CLA just now. I'm sorry for not replying to you in time

**Comment by slorber** [comment]
Thanks 👍

**Pull request merged**
