### PR TITLE
chore(debug-plugin): migrate to a new maintained JSON Viewer

### LINKED ISSUE #9486: `npm install` on a freshly created project produces warnings for `Conflicting peer dependency`
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

`npm install` on a freshly created project produces warnings for `Conflicting peer dependency`.

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: flux@4.0.4
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.0.0" from the root project
npm WARN   31 more (@docsearch/react, @docusaurus/core, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^15.0.2 || ^16.0.0 || ^17.0.0" from flux@4.0.4
npm WARN node_modules/@microlink/react-json-view/node_modules/flux
npm WARN   flux@"~4.0.1" from @microlink/react-json-view@1.23.0
npm WARN   node_modules/@microlink/react-json-view
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^15.0.2 || ^16.0.0 || ^17.0.0" from flux@4.0.4
npm WARN   node_modules/@microlink/react-json-view/node_modules/flux
npm WARN     flux@"~4.0.1" from @microlink/react-json-view@1.23.0
npm WARN     node_modules/@microlink/react-json-view
```

### Reproducible demo

_No response_

### Steps to reproduce

* Create a new site

```sh
npx create-docusaurus@latest my-website classic 
```

* Run `npm install`
```sh
cd my-website
npm install
```

### Expected behavior

No warnings produced. The site seems to work fine, but it can be confusing.

### Actual behavior

Warnings produced.

### Your environment

- Public source code: (newly created Docusaurus 3.0 project)
- Public site URL:
- Docusaurus version used: 3.0.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): -
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): 18.14.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

### PR DESCRIPTION
**Pull request by mcrstudio**
## Pre-flight checklist

- [ x ] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behaviour.

## Motivation

There is currently a peer dependency issue due to the `react-json-view` library depending on `flux`, which is no longer maintained and deprecated. If somebody is using rules that require peer dependencies to have no conflict, this is blocking them from upgrading docusaurus.

I have migrated the JSON Viewer in the plugin-debug to use `react-json-view-lite` which, despite not having many features, does the job respectfully and has the benefit of working with SSR, which `react-json-view` did not. This has made the implementation a little tidier.

It will also be fairly easy to update `react-json-view` in the future if a similar issue happens and the code for that project is quite a bit simpler.

## Test Plan

I tested two sites, side by side. One site had the current version of Docusaurus and the other had the version containing my changes. I looked to see if the same properties were collapsed and expanded, which appeared to be the case. This library also appears to be more responsive that `react-json-view` when loading larger depths of expanded JSON content.

I'm not sure on how a dogfooding page would work when the task involved removing the old JSON Viewer.

### Test links

Deploy preview: [https://deploy-preview-9566--docusaurus-2.netlify.app/](https://deploy-preview-9566--docusaurus-2.netlify.app/)
## Related issues/PRs

Fixes #9486

### CODE REVIEW

**Comment by slorber** [comment]
Thanks for your work on this

I'm not super fan of the package you choose though, being maintained by a single person can lead to the same issue we are trying to fix right now 😅 

Have you tried this one? It's more heavy (but not a big deal for this usecase imho) but is much more likely to stay maintained over time: https://github.com/reduxjs/redux-devtools/tree/main/packages/react-json-tree

Also if possible I'd like to keep the amount of expanded items by default smaller. For example this page becomes less usable by default now:
- now: https://deploy-preview-9566--docusaurus-2.netlify.app/__docusaurus/debug/content/
- before: https://docusaurus.io/__docusaurus/debug/content

**Comment by mcrstudio** [comment]
@slorber I appreciate that, though I was choosing a library based on ease of implementation, as I'm very restricted for time. I have made an update that makes the new page behave almost identically to the old page.

I think a large benefit of a tiny package like this is that it's only peer dependency is React, there are no difficult dependencies. If this goes unmaintained in the future, then at least it can be updated to a later version of React whilst another solution is found with less urgency?

I'm not really able to make a commitment to switch out the library, as this was a quick fix I did over the weekend and I won't have much free time again for 2 weeks!

**Comment by Josh-Cena** [comment]
I'm +1 to merging this as-is—I don't think it's worth time at this point to find a perfect solution and spend time verifying that it works, when it is causing actual issues in user land.

**Comment by mcrstudio** [comment]
@Josh-Cena @slorber I can also note that aesthetically, it's not as pleasing. We can, however, add some styles to modify the look and appearance but the indentation isn't as readable as the existing library. For me, the most important factor was that there's no dependencies other than React.

My argument for why this should be merged despite the aesthetics is that it's an issue that users are facing, created by a transitive dependency of a deprecated library inside of a json viewer inside of a debugging plugin for Docusaurus configurations. It's quite a niche area of the website to be visited as it stands and I don't believe the aesthetics take precedence over dependency conflicts that users are facing in existing installations.

**Comment by mcrstudio** [comment]
I've updated the PR to match the styling of the existing JSON viewer. They look much the same now albeit some minor changes.

**Comment by Josh-Cena** [comment]
@mcrstudio Thanks for the work!

**Review by slorber — APPROVED** [review]
Agree, let's move on!
I'll figure out later how to improve if needed, but it's not high priority.
Thanks 👍

**Pull request merged**
