### PR TITLE
fix: check for lowercase TOC token

### LINKED ISSUE #1234: AUTOGENERATED_TABLE_OF_CONTENTS does not work with translations
## 🐛 Bug Report

AUTOGENERATED_TABLE_OF_CONTENTS does not work with translations enabled

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## To Reproduce

1. Enable translations
1. Add a doc page with some h3
1. Add AUTOGENERATED_TABLE_OF_CONTENTS 

# Expected behavior
Generated for all languages

(Write what you thought would happen.)

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

### PR DESCRIPTION
**Pull request by vikrantsinghthakur**
## Motivation

Fix #1234 
Placeholder tokens going through crowdin get converted to lowercase. This PR tries to check for both uppercase and lowercase placeholder token to be replaced with table.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

YES

## Test Plan

Use crowdin to generate translation and check if table of contents has been added correctly

### CODE REVIEW

**Comment by yangshun** [comment]
Deploy preview for *munseo-preview* ready!

Built with commit 0e841172ad323b1c4ba9cbf13c56a09d1cc9e3f3

https://deploy-preview-1288--munseo-preview.netlify.com

**Comment by vikrantsinghthakur** [comment]
Well I see the generated netlify build itself has the issue, even without translation. Let me take a look into it.

**Comment by jakebolam** [comment]
For sure @vikrantsinghthakur

**Comment by vikrantsinghthakur** [comment]
There were 2 builds generated for the PR with the same commit, [munseo-preview](https://deploy-preview-1288--munseo-preview.netlify.com) and [docusaurus-preview](https://deploy-preview-1288--docusaurus-preview.netlify.com).
Table of contents was **not** generated for the former, while it seems to be working fine for the latter. This looks like a non deterministic outcome and I wonder why it occurred. Can anyone with more information about this enlighten me?

**Comment by endiliey** [comment]
Ignore the munseo-preview, thats the v2 build and lot of stuff is still wip on v2.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
