### PR TITLE
infra: use native eslint enums for eslint rules

### PR DESCRIPTION
**Pull request by amilajack**
## Motivation

Simpler configuration

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Not yet

## Test Plan

Lint the project and check if anything broke. This will be caught by CI

### CODE REVIEW

**Comment by vikr01** [comment]
Could also now make the file a `json`.

**Comment by yangshun** [comment]
> Could also now make the file a json.

JSON format is not preferred because you can't have comments not trailing commas in them.

I'll leave this file as it is then. Thanks for the PR @amilajack but we prefer to use constants.

**Comment by vikr01** [comment]
@yangshun `eslint` actually parses comments out of `.eslintrc` (not sure about `.eslintrc.json` but I wouldn't expect it to be any different).

**Comment by yangshun** [comment]
> eslint actually parses comments out of .eslintrc

The config file with a JS extension will be read as a JS module. Why would comments matter and what's the benefit of parsing comments out of it?

> not sure about .eslintrc.json but I wouldn't expect it to be any different

This doesn't sound right. Comments make a JSON file invalid and it's weird that ESLint will have a non-standard parser to parse JSON.

@vikr01 Could you try to substantiate what you've said above? A repo with a repro would be great!

**Comment by vikr01** [comment]
@yangshun [Here](https://github.com/eslint/eslint/blob/caeb223c4f7b0b6fe35e5348ae0df4c6446b5bed/lib/config/config-file.js#L114)'s the source where `eslint` strips out comments

[Here](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/.eslintrc)'s an example from airbnb.

**Comment by yangshun** [comment]
> @yangshun Here's the source where eslint strips out comments

Thanks! Good to know that! That's cool. Stripping comment sounds more accurate than parses comments, which makes sense.

Regardless, `.js` extension is preferred because editors and GitHub will use the correct syntax highlighting from the file format. If you use JSON format and have comments within it, the code will not be syntax highlighted properly. If you use an `.eslintrc` file, no syntax highlighting takes place (that's also actually a legacy format).

**Comment by vikr01** [comment]
@yangshun Actually editors will usually have a `jsonc` format to recognize the syntax highlighting (VSCode by default already recognizes comments in `.eslintrc` and `.babelrc`).

Either one sounds good to me. Though from what I've seen, `json` filetypes generally have better support with intellisense from plugins.

**Pull request closed without merging**
