### PR TITLE
Reenable translations

### LINKED ISSUE #564: Broken links on site after translation
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

(OS, Node, npm, yarn)

### Steps to Reproduce

1. Load https://docusaurus.io/docs/en/site-preparation.html. Try to click on the "installing Docusaurus" link. It leads to a 404.
2. Load https://docusaurus.io/docs/en/publishing.html. The markdown links are broken.

The links are being translated to Spanish on the English page and that caused the behavior above.

### Reproducible Demo

Access the URLs above.

### PR DESCRIPTION
**Pull request by JoelMarcey**
## Motivation

We believe we sorted out some string issues we had on Crowdin. We are going to see if this works.

I also turned it on for versioned docs as well.

Fixes #564 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Local site testing

## Related PRs

N/A

### CODE REVIEW

**Comment by yangshun** [comment]
@JoelMarcey I'm getting an error when I change the language and click on "Docs". For example, changing the language to Espanol:

Works: https://deploy-preview-727--docusaurus-preview.netlify.com/es-es/

Doesn't work: https://deploy-preview-727--docusaurus-preview.netlify.com/docs/es-ES/installation.html

(Note that the language in the path have different case)

**Comment by JoelMarcey** [comment]
@yangshun I was chatting with @endiliey and I think that is because when we preview on Netlify, we have not gone through the Crowdin upload and download processes yet like we will when we publish via Circle (see our circle.yml file).

@ericnakagawa, is that right?

**Comment by JoelMarcey** [comment]
I just checked. It works locally. With all links correct, etc. I think we should just merge this and see what happens 😄

**Comment by JoelMarcey** [comment]
We still do not have 100% coverage on our translations for any language, so we definitely should try to push for that from the community.

**Pull request merged**
