### PR TITLE
feat: support reference-style linking in documents

### LINKED ISSUE #257: Support reference style linking
https://github.com/prettier/prettier/pull/3353/files#r153973850

https://daringfireball.net/projects/markdown/syntax#link

### PR DESCRIPTION
**Pull request by phated**
## Motivation

Needed reference link support for the gulp docusaurus website. Fixes #257 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yep.

## Test Plan

Create a page with a reference link that is described in #257 and generate a Docusaurus page. The link should be replaced correctly.

I wanted to submit this as a proposal for a fix because I'm using local changes currently.  If you need changes or tests added, just let me know. Thanks!

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by phated** [comment]
@endiliey before I add the tests, is this a passable solution?

**Comment by endiliey** [comment]
Seems so to me.

**Comment by yangshun** [comment]
@phated Do you have the Gulp Docusaurus website hosted somewhere for us to have a look?

**Comment by phated** [comment]
It's not available yet. We're putting some finishing touches on next week.

**Comment by yangshun** [comment]
@phated I'm interested in seeing the WIP too if possible. 

On a side note, I see that the unofficial Gulp docs - https://gulpjs.org/ is built using VuePress so I'm surprised that you're still going ahead with a Docusaurus version (you're welcome to of course).

**Comment by phated** [comment]
Like you said, it's the unofficial docs and has nothing to do with us. Our domain is gulpjs.com for the official project.

**Comment by phated** [comment]
@yangshun if you didn't catch the gulp announcement yesterday - our docusaurus website is live at https://gulpjs.com/docs/en/getting-started/quick-start

**Comment by yangshun** [comment]
@phated I didn't catch it. This is sweet! Would you mind submitting a PR to add Gulp has a *pinned* user to Docusaurus website? Congrats on the launch!

**Comment by phated** [comment]
@yangshun Thanks!  I plan to submit our logo in a PR once we land this because currently we have to publish from my laptop only.

@endiliey are my submitted tests sufficient?

**Comment by phated** [comment]
Could we get a 1.x release for this? I need our team members to have an installable version to publish with.

**Comment by yangshun** [comment]
@phated Sorry for the delay, we just released v1.5.1 on npm.

**Pull request merged**
