### PR TITLE
fix(v2): do not force terminate building if client bundle failed in development mode

### LINKED ISSUE #2390: Latest alpha version is less resilient to import errors
## 🐛 Bug Report

In version 44 a failed import reports an error but docusaurus continues to run and reload changes. In 48 the server terminates and has to be restarted after the error is fixed. This is quite inconvenient during the development/documentation cycle.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Note that the example project below is using Lerna. This is just to make the repro easier -- our actual project doesn't use Lerna but exhibits the same behaviour.

1. Download / clone https://github.com/jugglingcats/docusaurus-repro
2. `lerna bootstrap`
3. `cd docusaurus-site`
4. `npm start`
5. Notice that the server starts, albeit with an error
```
Starting the development server...

× Client
  Compiled with some errors in 8.43s

i ｢wds｣: Project is running at http://localhost:3001/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from D:\alfie\tmp\docusaurus-repro\packages\docusaurus-site
i ｢wds｣: 404s will fallback to /index.html


./docs/mdx.md
Module not found: Can't resolve '@theme/invalid' in 'D:\alfie\tmp\docusaurus-repro\packages\docusaurus-site\docs'
```
6. Kill the server
7. Edit `package.json` to upgrade to version 48. Re-run `lerna bootstrap`
7. Try to start docusaurus

## Expected behavior

Docusaurus should start and report the import error.

## Actual Behavior

Docusaurus reports the error and terminates.
```
Starting the development server...

* Client █████████████████████████ after emitting (98%)


i ｢wds｣: Project is running at http://localhost:3000/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from D:\alfie\tmp\docusaurus-repro\packages\docusaurus-site
i ｢wds｣: 404s will fallback to /index.html
Client bundle compiled with errors therefore further build is impossible.
```

## Your Environment

- Docusaurus version used: 2.0.0-alpha.48
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
- Operating system and version (desktop or mobile):

## Reproducible Demo

https://github.com/jugglingcats/docusaurus-repro

See above for detailed steps.

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Resolve #2390

This is really inconvenient during development (and therefore degrades DX) and should only be enabled at building.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

- In a MDX file try to import unresolvable dependency e.g.:

```md
---
id: mdx
title: MDX page
---

import Blah from 'Blah';

Heading...
```

When executing the `yarn start` command, an error should be displayed and the process go to idle. But during the build (`yarn build` command), the process should force terminate along with the error display.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by AfolabiOlaoluwa** [comment]
I am on version [2.0.0-rc.1](https://docusaurus.io/docs) and I couldn't get past this problem. It terminates when I run `yarn build`. How do you solve it?

**Comment by Josh-Cena** [comment]
@AfolabiOlaoluwa It's expected to terminate during build, because it's impossible to further build with errors. Please don't necropost—perfect way to get your question unnoticed.

**Comment by AfolabiOlaoluwa** [comment]
@Josh-Cena Necroposting? Do you prefer I open another issue? I saw there was a discussion and I asked how it is solved. Besides, I am not npm/yarn/js dev, I am just using this code for the first time. Your last sentence was not necessary. The first sentence informed me better.

**Comment by Josh-Cena** [comment]
It's basic etiquette when engaging with an open-source project to not comment on an already resolved issue/PR. It's the very reason a lot of projects automatically lock old threads. We are trying our best to help you—not just this incident, but to ensure you keep being helped into the future. Please assume good faith of everyone who interacts with you. You can always ask in GitHub discussions or Discord if something is not working—see https://docusaurus.io/community/support

**Comment by AfolabiOlaoluwa** [comment]
I do think the etiquette in open-source in this case is "subjective". I have been in other communities that will actually point you to resolved issues/PR instead of opening another issue. But thank you for your opinion and a little lecture on the opinions of this project. I will proceed with your suggestion. Of course, I assume good faith with all interactions!

**Comment by Josh-Cena** [comment]
Oh well, maybe it's also an ecosystem thing? The vast majority of JS/TS repos that I've engaged with definitely encourage you to open new issues to ensure visibility. Well, something to uphold into the future...

**Comment by AfolabiOlaoluwa** [comment]
I really do not think it is an ecosystem thing. Some just prefer the first good you can do not to stress anyone in the community is to look at resolved issues rather than opening another one which may end up violating DRY principles to them and answering the same thing over and over. That's why I said that etiquette is subjective, and people can rationalize it in diverse ways. 

I personally believe if I answer a question 2 weeks ago and it is not deleted, just look through that discussion and append solutions there.

**Pull request merged**
