### PR TITLE
fix: set routeBasePath into '/' in plugin-content-pages preset options

### PR DESCRIPTION
**Pull request by Niko030303**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [x] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

### CODE REVIEW

**Comment by Niko030303** [comment]
#8255

**Comment by Niko030303** [comment]
issue: #8254

**Comment by slorber** [comment]
Hey

This is likely not just a doc issue, as explained in https://github.com/facebook/docusaurus/issues/8254#issuecomment-1293232646

(and if it were you would have to update all the docs, including in particularly inside the `./docs` folder)

**Comment by Niko030303** [comment]
> Hey
> 
> This is likely not just a doc issue, as explained in [#8254 (comment)](https://github.com/facebook/docusaurus/issues/8254#issuecomment-1293232646)
> 
> (and if it were you would have to update all the docs, including in particularly inside the `./docs` folder)

Du you mean I have to replace all `routeBasePath: ''` to `routeBasePath: '/'` ?

**Comment by slorber** [comment]
I mean the validation logic of all 3 content plugins is incorrect (or at least does not give a good developer experience) and must be adjusted accordingly, as described in my linked comment.

If you don't feel comfortable to handle this (+ unit tests to ensure it works), you can close the PR and someone else will work on it

**Pull request closed without merging**
