### PR TITLE
Await site configuration

### PR DESCRIPTION
**Pull request by LightDiscord**
## Motivation

I wish I could return an asynchronous configuration, in my case `users` is a list I get from the internet so I need to use async functions.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

**Comment by LightDiscord** [comment]
My configuration file (`siteConfig.js`) is in my project, but inside it I make asynchronous calls, but return a Promise with `module.exports` doesn't work.

So the await met my need perfectly.

**Comment by JoelMarcey** [comment]
Would using `await` cause any unintended consequences for sites that don't require async?

**Comment by yangshun** [comment]
Makes sense! We'll think about this a while more first 😄 

One concern is that officially, Docusaurus supports Node 6+ but `async` is only fully supported in Node 8+

**Comment by LightDiscord** [comment]
> Would using await cause any unintended consequences for sites that don't require async?

It doesn't change anything, you can try with the code below

```js
async function context (config) {
  console.log(await config)
}

context(new Promise((resolve, reject) => resolve('A')))
context('B')
```

> One concern is that officially, Docusaurus supports Node 6+ but `async` is only fully supported in Node 8+

Damn, I didn't think of that ^^

I saw [you were using an async below](https://github.com/facebook/Docusaurus/blob/d4df35c8b85ec3867bf0b8762225a24612fc0d81/lib/server/generate.js#L413) and I didn't think about it.

**Comment by yangshun** [comment]
> I saw you were using an async below and I didn't think about it.

I think I forgot about Node compatibility when I wrote that 😓 

Maybe we can increase official support to Node 8? Node 8 is backward compatible with Node 6 I think. @JoelMarcey

**Comment by JoelMarcey** [comment]
@yangshun and I discussed this internally and let's do it. We will have to probably call this a breaking change insofar as people using CI may have their node version coded to 6 or 7, but that should probably be ok. We can bump up the version of Docusaurus to 1.1 as a result.

**Comment by yangshun** [comment]
@LightDiscord How is your siteConfig like during development? Since you only changed the require in `server/generate.js` but not in `server/server.js` I wonder how your set up behaves/works during development.

Ideally if we were to move the require in `generate`, we would want to move everywhere to async. Unfortunately the current code is not quite ready to support that :/

**Comment by yangshun** [comment]
@LightDiscord I don't think we will get to this anytime soon as it requires far too much effort to refactor so I'm closing this first. As a workaround, you could:

1. Add a generate command that fetches the data and runs just before the build step.
2. Dynamically fetch the contents upon page load.

This way, requiring siteConfig does not have to be async. Let me know if that doesn't work and we can think of alternatives.

**Pull request closed without merging**
