### PR TITLE
fix(v2): Resolve IE11 compatibility issues (Fixes  #1784)

### LINKED ISSUE #1784: react-loadable module in v2.0, failed in ie11 with Object doesn't support property or method 'assign'
## 🐛 Bug Report

(A clear and concise description of what the bug is)

react-loadable module in docusaurus V2.0 failed in ie11 with exception:
Object doesn't support property or method 'assign'

image

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. create a project with docusauras
2. start the project and visit the index page

## Expected behavior
the index page is rendered properly
image

## Actual Behavior
the index page was not rendered, and there is a exception report in debug console.

image

## Reproducible Demo
online demo:  https://www.10studio.tech
which is power by docusaurus V2.0

## Question
There are some package to provide ie compatibility such like `core-js`, but I don't know how to properly add it in docusaurus v2.0

### PR DESCRIPTION
**Pull request by andresmanelli**
## Motivation

I need to create a site that is compatible with IE11 and I like the simplicity of this project.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

I just ran `yarn test` and had the same result than `v2.0.0-alpha.25` (I think because of Windows paths)

This is a screenshot of the website in IE11 (not perfect, but ok)

Capture

## Related PRs

None

**Disclaimer**: I am no web developer :) so all reviews are welcome. Thanks!

### CODE REVIEW

**Comment by andresmanelli** [comment]
I will try that, although I found other issues when only importing that specific method from core-js.

I'll let you know asap

**Comment by endiliey** [comment]
ie11 polyfill from cra https://github.com/facebook/create-react-app/blob/master/packages/react-app-polyfill/ie11.js

naturally it will be best if we can utilize it like babel preset env browserslist integration because importing "core-js" loads polyfills for every possible ECMAScript feature: what if you know that you only need some of them?

**Comment by endiliey** [comment]
Currently our babel-preset-env use the default options
https://github.com/facebook/docusaurus/blob/d5ca17ffea204359c4359741fbaaa1ed2708e7de/packages/docusaurus/src/webpack/utils.ts#L91

Maybe can utilize https://babeljs.io/docs/en/babel-preset-env#usebuiltins 'usage'
so that polyfills will be added automatically when the usage of some feature is unsupported in target environment

**Comment by endiliey** [comment]
the error is not related to #1782

**Comment by andresmanelli** [comment]
I can confirm the addition of the `useBuiltIns` option makes the build crash. I don't really know a good workaround. Should I close this PR or do you have any ideas ? Thank you !

**Comment by endiliey** [comment]
polyfill features that are missing to ie11 only without importing whole corejs ?

**Pull request closed without merging**
