### PR TITLE
clarify valid children for Tabs element.

### PR DESCRIPTION
**Pull request by homotechsual**
## Pre-flight checklist

- [X] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

### CODE REVIEW

**Comment by homotechsual** [comment]
@Josh-Cena any idea why the husky lint step is messing up the first admonition example here?

image

Losing the will to live trying to get it to leave it alone 🤣

**Comment by Josh-Cena** [comment]
@homotechsual https://docusaurus.io/docs/markdown-features/admonitions#usage-with-prettier?

**Comment by homotechsual** [comment]
Aha - thanks!

**Comment by homotechsual** [comment]
> @homotechsual https://docusaurus.io/docs/markdown-features/admonitions#usage-with-prettier?

Hmm, unfortunately it doesn't work in this context - I added blank lines before and after the opening `:::tip` line and the closing `:::` and it just puts it back to the inline format 🤣

**Pull request closed without merging**
