### PR TITLE
feat(v2): minify injected inline JavaScript code

### PR DESCRIPTION
**Pull request by lex111**
# Motivation

Perhaps this is what is called preliminary optimization, but it seems to me that this certainly will not hurt and does not bear any negative consequences, right?

For example, before and after:

```js
<script type="text/javascript">(function() {
  function setDataThemeAttribute(theme) {
    document.querySelector('html').setAttribute('data-theme', theme);
  }
  
  var preferDarkQuery = '(prefers-color-scheme: dark)';
  var mql = window.matchMedia(preferDarkQuery);
  var supportsColorSchemeQuery = mql.media === preferDarkQuery;
  var localStorageTheme = null;
  try {
    localStorageTheme = localStorage.getItem('theme');
  } catch (err) {}
  var localStorageExists = localStorageTheme !== null;

  if (localStorageExists) {
    setDataThemeAttribute(localStorageTheme);
  } else if (supportsColorSchemeQuery && mql.matches) {
    setDataThemeAttribute('dark');
  }
})();</script>
```

```js
<script type="text/javascript">(function(){function a(a){document.querySelector("html").setAttribute("data-theme",a)}var b=window.matchMedia("(prefers-color-scheme: dark)"),c=b.media==="(prefers-color-scheme: dark)",d=null;try{d=localStorage.getItem("theme")}catch(a){}var e=null!==d;e?a(d):c&&b.matches&&a("dark")})();</script>
```

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

See HTML markup.

### CODE REVIEW

**Comment by endiliey** [comment]
image

Above is the thread. Minify is kinda abandoned.

On another note, html will also be compressed by default (on netlify for example), so the actual gain might not be that much. HTML gzip compression is also very efficient unlike JS. Can we compare this netlify preview HTML gzipped size vs before this PR ?

Thoughts ?

**Comment by yangshun** [comment]
My two cents - Passing the code through Babel is not just about minifying, there's also conversion of syntax as well. In v1 we had a few instances where our scripts were written in ES6 syntax, resulting in the page being broken for older browsers.

**Comment by endiliey** [comment]
Hmm i guess you are right at that point, but isnt the point of this PR is more on the minifying ? ``My concern is more on the fact that babel minify seems to be unmaintained and can broke someone else code. Like I’d prefer terser if we want to minify and that seems to be the standard nowadays. 

Terser>UglifyES>Babel minify

On another note, do we want all this magic in core ? 


This is kinda similar to how we optimize image in v1. Sometimes optipng or imagemin seems to break someone’s else image (or corrupt it).

What if user dont want to minify for sake of debuggability in production. Minification isnt perfect as well, some things might break.

Maybe its better to just minify it in the plugin itself. In this case the theme-classic plugin. This keeps core lean and simple.

Its not the case in v1 because we try to handle everything, but in v2 we can try to shift more responsibility to user.

**Comment by endiliey** [comment]
Another example that I can think of

What if user purposefully use es modules in the injected html ? we dont want to transform that right. We need a check as well.

Its called differential loading

<script type="module">let foo = “test”;</script>
<script nomodule>var foo = “test”;script>

**Comment by lex111** [comment]
That's right, I did not take into account all these things, I wanted to minify inline scripts, but there are a lot of pitfalls here, which is a pity! :(
What about *minifying HTML*? Maybe it can be done completely during the build (regardless of the use of static hosting provider)?

image

**Comment by endiliey** [comment]
I think we can actually minify html with compression webpack plugin.

https://github.com/webpack/compression-webpack-plugin

Our html renderer (static site generator webpack plugin) is compatible with it.
See https://github.com/endiliey/static-site-generator-webpack-plugin/blob/cd502af2291b950d67fb247175046961b3356c1f/test/success-cases/compression/webpack.config.js#L23

**Comment by endiliey** [comment]
On another thought, there seems to be two things
1. minify the html
2. gzip the html

Almost forgot minify and gzip is different.
But of course this all has a cost, such as build time and more memory used. So maybe its better done as a plugin. Actually if user is adventurous enough, they can always use the postBuild hook to do their own minifying thing

**Comment by lex111** [comment]
I do not think this is so critical, because the website is build via CI, that is, not on the user's local machine (in most cases).
I just want Docusaurus out of the box to be or present means for better performance. Ideally, I think we need to provide for the ability to compress images during build website...

**Comment by endiliey** [comment]
. For html we can do it with https://github.com/DanielRuf/html-minifier-terser (its used by htmlwebpackplugin). 

We can modify https://github.com/facebook/docusaurus/blob/1f0eb37e1941ef626e3e6cc9fe2cbf99c1776177/packages/docusaurus/src/client/serverEntry.js#L71 and return minified html string instead

As for images, its considered best practice that if they want to optimize it, they should do it through webpack loader (so its on demand optimization) or do it on their own. See docusaurus plugin ideal image for example.

We should not touch anything in /static folder. Its been quite proven from maintaining v1 for a year+ that if we try to optimize all image, many times it broke someone else image and usually will lower the image quality, so thats why I dont think it should be in core. Optimizing image is all about lowering quality anyway.

Another thing is that its not a matter whether its build in CI/not, The thing is image processing consumes lot of memory, and time. Most people are on free plan CI and it has timeout, if they have 500 images and we optimize it all, it can most likely cause NODEJS heap out of memory. Better let them do it on demand

**Comment by lex111** [comment]
Fine, although I would prefer to minify HTML as a plugin, which is enabled by default, and mention in docs about image optimization (something like recipe).

**Comment by endiliey** [comment]
I think its fine to minify HTML in core, since minifying text is so much much faster (negligible) than optimizing images. Also note that `minifying !== syntax transform` (what babel/env does).

wdyt ?

For image optimization, PR always welcome for docs 😉 Though I dont know where to put it also. @wgao19 is the boss for docs.

**Comment by lex111** [comment]
> I think its fine to minify HTML in core, since minifying text is so much much faster (negligible) than optimizing images. Also note that minifying !== syntax transform (what babel/env does).

~~Will try implement this.~~ Oh you already did, cool! I will look at the result.

**Comment by lex111** [comment]
@endiliey this works fine! Also, besides this, we have a minified inline JS code! :clap:

**Comment by wgao19** [comment]
#1640 recipe for image optimization

**Pull request closed without merging**
