### PR TITLE
updated the link

### PR DESCRIPTION
**Pull request by balnarendrasapa**
the link was broken. it wasn't my-markdown-page. it was markdown-page

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
Hi! This file is called `my-markdown-page.md`, so the path is `/my-markdown-page`.

**Comment by balnarendrasapa** [comment]
I installed the docusaurus on my pc. I did not make any changes and was exploring the project. the link pointed `/my-markdown-page`  but the default install had markdown-page.md which should pointed to by  `/markdown-page`. sorry for not explaining that clearly

**Comment by Josh-Cena** [comment]
Yes, but this page is about creating an extra page at my-markdown-page.md ^^

**Comment by balnarendrasapa** [comment]
This is default install and this is how the pages directory looks like 
image

when i click the link `https://localhost:3000/my-markdown-page` , the browser shows that the page is not found like the below image
image
image

Now, when i type `https://localhost:3000/markdown-page` in the url of the browser. the markdown-page.md from the pages directory is rendered. 
image

what I am trying to say is, either the link in the page should be `https://localhost:3000/markdown-page` or the markdown-page.md should be renamed as `my-markdown-page.md`

**Comment by balnarendrasapa** [comment]
got it. thanks 😊

**Pull request closed without merging**
