### PR TITLE
Adding scrollbar to header when it overflows

### LINKED ISSUE #441: Header links on mobile get cutoff
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Environment

Chrome development tools

### Steps to Reproduce

https://github.com/babel/website/issues/1556

### Expected Behavior

All header links shown

### Actual Behavior

https://github.com/babel/website/issues/1556

### Reproducible Demo

https://github.com/babel/website/issues/1556

### PR DESCRIPTION
**Pull request by maaz93**
## Motivation

Fixes #441 

## Test Plan

1. Add many dummy entries into the `siteConfig.js`.
2. Use the Chrome devtools' ["Toggle Device Mode"](https://developers.google.com/web/tools/chrome-devtools/device-mode/) to simulate various responsive sizes. Note: Just make sure you refresh the page once when you switch to mobile mode. This guarantees that the page is loaded in the simulated mobile mode and any old CSS effects from the desktop mode are not into play.

scroll_doc

cc @JoelMarcey

### CODE REVIEW

**Comment by JoelMarcey** [comment]
This is great @maaz93. Thanks so much!

**Comment by maaz93** [comment]
Awesome! Will wait for the next release to update the Babel website.

**Comment by JoelMarcey** [comment]
@maaz93 Hi. I commented on #445 that I had to revert this :( It broke Algolia search. I am thinking we can only overflow when the header links are on their own row like in your original screenshot here? So we just need to put the overflow in the `@media only` place.

**Comment by maaz93** [comment]
Oops. That's a bit weird. I put a `overflow-x` and there's a vertical scroll. I'll look at it. Can we re-open the issue?

**Comment by JoelMarcey** [comment]
Issue is reopened.

**Pull request merged**
