### PR TITLE
Add more static classes to Classic Theme components.

### PR DESCRIPTION
**Pull request by sambauers**
## Motivation

During my own attempt to implement customisations to the Classic Theme, I found it very difficult to modify some of the styles due to them being given different scopes in hot reload development as opposed to during a build, where they are appended with hashes.

My current solution has been to create a very hacky swizzle of the `ThemeProvider` component, which injects a style tag into the HTML body with the classes added which I want to over-ride. A reduction of that solution is below (only look if you appreciate "creative" programming):

```js
import React from 'react';
import cssesc from 'cssesc';

import ThemeProvider_Original from '../../../node_modules/@docusaurus/theme-classic/src/theme/ThemeProvider';
import styles_DocPage from '../../../node_modules/@docusaurus/theme-classic/src/theme/DocPage/styles.module.css';

const esc = name => cssesc(name, {isIdentifier: true});

const styles = `
.${esc(styles_DocPage.docSidebarContainer)} {
  border-right: none;
}
`;

export default function(props) {
  return (
    <>
      <style dangerouslySetInnerHTML={{__html: styles}} />
      <ThemeProvider_Original {...props} />
    </>
  );
}
```

So that's what it took just to remove the border on the left-side docs menu.

This PR proposes to ease the simple use of the standard `custom.css` instead, by providing more static classes to the Classic Theme components. These will not be scoped by Webpack/CSS Loader, and so will be more easily overridden in `custom.css` (albeit sometimes using `!important` - can the load order be fixed so `custom.css` is always last?).

I have done my best to identify all the potential points where a user might want to hook in with their own styles. I am not attached to the class names themselves, I was trying to understand the logic of underscores, hyphens, camels, and kebabs but it was really not clear.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, Facebook now has the right to claim my first born son.

## Test Plan

These are non-breaking changes that are 100% backward compatible. I ran all the tests and linters though. Works a treat on my local development env and I can do away with my magical swizzled component at this point.

## Related PRs

None. No docs about the standard styles exist AFAIK, so I guess they don't need updating.

### CODE REVIEW

**Comment by sambauers** [comment]
That was just for my example. I have had this occur on many other components. There are just not enough static class names for someone to hook into using standard `custom.css`. And diving down anonymous Dom elements is not great either. I selected a few places where I thought adding predictable class names would be helpful. I need about half of these myself.

Happy to call the classes whatever, but I need guidance there as I can't decipher the pattern - actually I suspect there isn't really a pattern.

**Comment by lex111** [comment]
I am against such a "messy" adding of classes. I'd rather do it on demand
when someone really needs it.

ср, 13 мая 2020 г. в 12:58, Sam Bauers <notifications@github.com>:

**Comment by yangshun** [comment]
Sorry, we will not go back to using static classes. To save yourself time in future, please raise an issue to discuss before spending the time to implement the changes which isn't aligned with what we want/need.

**Comment by oriooctopus** [comment]
@yangshun @lex111 
I understand the desire not to have a bunch of static classes when using css modules, but it is still pretty inconvenient to swizzle a component just to implement basic styling. 

What if the user could, instead of swizzling the whole component, create a component specific css modules file that would combine with the pre-existing css module file?

https://github.com/css-modules/css-modules/blob/master/docs/import-multiple-css-modules.md

**Comment by yangshun** [comment]
> What if the user could, instead of swizzling the whole component, create a component specific css modules file that would combine with the pre-existing css module file?

That sounds interesting. I do agree swizzling is not ideal. We'll look into allowing for more customization via outlets (injecting your React components into certain slots) and class name props are possible additions. Please add more of your swizzling use cases here so we know how why people are swizzling components and what APIs we can add such that you can customize your components without swizzling.

**Comment by yangshun** [comment]
I started a discussion on #2790, feel free to chime in there!

**Pull request closed without merging**
