### PR TITLE
fix: Support tsx with prism syntax highlighter

### PR DESCRIPTION
**Pull request by ntucker**
## Motivation

TSX and any other compositionally defined language (Prism.languages.extend) in prism will not work with the current system because of how language loading works.

Basically the other languages tsx is composed from (jsx and typescript) won't always be loaded first (I don't even have JSX examples so it can never get to that point). If that's the case it won't be able to create the composition properly.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

yes

## Test Plan

I simply did this modification in my usage where I have lots of tsx (https://resthooks.io). Before I was getting `TypeError: Cannot read property 'rest' of undefined.` and it would fallback to highlight.js, which of course doesn't support tsx. 

Here's it working:
tsx

## Related PRs

Inspiration for this fix comes from workarounds in: https://github.com/PrismJS/prism/issues/972

### CODE REVIEW

**Comment by endiliey** [comment]
Deploy preview for *docusaurus-2* failed.

Built with commit cb33742add11eb211e1a32f43e9974f188e5987b

https://app.netlify.com/sites/docusaurus-2/deploys/5cc15c527de8d7000854286b

**Comment by endiliey** [comment]
Deploy preview for *docusaurus-2* failed.

Built with commit afe481081c15ebaabad55d56a89dc6d1a631fb8f

https://app.netlify.com/sites/docusaurus-2/deploys/5cc15df8d0ea56000a46bf63

**Comment by ntucker** [comment]
Can you release a version with this fix?

**Comment by endiliey** [comment]
I'll release next v1 version along with #1369 

For now, you can use `master` version with `@next` tag

https://www.npmjs.com/package/docusaurus
image

Don't worry, there is no breaking changes for that,  Docusaurus 2 itself is renamed to another package called '@docusaurus/core'

**Pull request merged**
