### PR TITLE
Make sure the sitemap in footer is left aligned

### PR DESCRIPTION
**Pull request by ryzokuken**
Fixes: https://github.com/facebook/Docusaurus/issues/485

This had been claimed 5 days ago, but there had been no response so I decided to submit a PR. This is my first one, so let me know if I made any errors, I'll make sure to take care of them.

Preview:

screen shot 2018-03-17 at 7 02 08 pm

### CODE REVIEW

**Comment by JoelMarcey** [comment]
@ryzokuken Thanks for the PR!

**Comment by ryzokuken** [comment]
@JoelMarcey I did and the footer didn't shit to the right any longer on mobile view, but I just checked in desktop view and realized that the footer looks a little shifted towards the left on non-mobile. Making that fix in a minute.

**Comment by ryzokuken** [comment]
@JoelMarcey I realized that there was a media query for smaller devices inside the file and it changed how the footer looked (thus making the broken transition). I made the change there and now it looks perfect.

Thanks for pointing out the error, I had totally missed it.

**Comment by ryzokuken** [comment]
Screenshots
screenshot-2018-3-19 adding a blog docusaurus
screenshot-2018-3-19 docusaurus easy to maintain open source documentation websites

**Comment by ryzokuken** [comment]
Okay, I just found out that there's a horizontal scrollbar problem (even on the original site). Should I make a new PR for that?

**Comment by JoelMarcey** [comment]
> Okay, I just found out that there's a horizontal scrollbar problem (even on the original site). Should I make a new PR for that?

@ryzokuken Would love a new PR for that fix, thanks!

**Comment by cheercroaker** [comment]
I have tested in isolation the "not yet released" fix from commits e0f4671b34e6ae9dc20726c5d762ca4dcd495598 & 6e08ae284d656bf56235d703126e4ab81ad65c40 that respectively fix #518 right after #485 and it works like a charm on mobile and desktop: footer does not shift to the right any longer and no problem with horizontal scrollbar anymore.

@ryzokuken Well done :+1: , thanks!

**Pull request merged**
