### PR TITLE
docs: fix a typo in CHANGELOG

### PR DESCRIPTION
**Pull request by KonstHardy**
Hello,
I've found some minor typos in the documentation, solved with this PR.

Fix typo:
the the -> the

### CODE REVIEW

**Review by Josh-Cena — APPROVED** [review]
Thanks

Didn't think someone would actually read through the change log🤷‍♂️

**Comment by KonstHardy** [comment]
> Thanks
> 
> Didn't think someone would actually read through the change log🤷‍♂️

**Comment by Josh-Cena** [comment]
I approved it though :P Didn't say I won't merge, just surprised by this contribution

**Comment by KonstHardy** [comment]
> > Thanks
> > Didn't think someone would actually read through the change log🤷‍♂️

I think so too, but decided to fix the typo by adding changes for the crowding-v2.yaml file and CHANGELOG

**Pull request merged**
