### PR TITLE
docs: docusaurus-plugin-sass need npm install sass-loader

### PR DESCRIPTION
**Pull request by hoishing**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).

## Motivation

`sass-loader` has to be installed, otherwise docusaurus will fail to run with the following error:

```
Compiled with problems:

ERROR in ./.docusaurus/client-modules.js 1:492-548

Module not found: Error: Can't resolve 'sass-loader'
```

### CODE REVIEW

**Comment by slorber** [comment]
Hey

this sass plugin is a third-party dependency and we only copied the install instructions: https://github.com/rlamana/docusaurus-plugin-sass

Maybe you can submit a PR to that repo, and if merged, we'll just sync the updated instructions and merge this PR?

I'd rather avoid having different instructions from the official third-party repo

**Comment by slorber** [comment]
Any opinion @rlamana?

**Comment by rlamana** [comment]
@slorber The `sass-loader` is already defined as a "hard" dependency on my package, not as a peer dependency (https://github.com/rlamana/docusaurus-plugin-sass/blob/ea853a4539bc44925c03a3afd7679e589914ae0c/package.json#L7), npm/yarn should have installed the dependency without needing to add it in the `npm install`, or what am I missing?

**Comment by hoishing** [comment]
I just found that the issue maybe caused by `pnpm`, because the error I encountered only appear when I use `pnpm`. Using `npm` works just fine. Closing the PR for now. Thanks for looking into the issue :)

**Comment by slorber** [comment]
Thanks :)

**Comment by hoishing** [comment]
FYI, when using `pnpm`, if I add `--shamefully-hoist` flag to make all dependencies as a direct sub-directory in `node_module`, it works fine. Otherwise it can't find the `sass-loader`

**Pull request closed without merging**
