### PR TITLE
docs: Adding ReactSeals logo

### PR DESCRIPTION
**Pull request by RosaryDarling**
## Motivation

Just adding a company's logo here since we are using docusaurus 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Could not properly test it

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Review by slorber — CHANGES_REQUESTED** [review]
Thanks for your PR

the infoLink should target a Docusaurus v1 site, do you have a better link?

**Comment by lex111** [comment]
As I understand it, the company uses Docusaurus internally, so it cannot show actual site built with Docusaurus.

All the same, this is a public showcase, and we have to show sites made with Docusaurus. So I think we shouldn't include this company in the users list.

**Comment by RosaryDarling** [comment]
Yes, sorry, we currently use this internally and for client projects, so this is probably not the time yet,

**Comment by lex111** [comment]
I get it, but nevertheless, we are glad that you have chosen our project and are using it, but this public showcase is designed to show sites built with Docusaurus. And it was weird to include a link to the site that is built with Nuxt.js :)

**Comment by slorber** [comment]
Let's close this then ;)

**Pull request closed without merging**
