### PR TITLE
blog: add a sneak-peek post about Docusaurus v2

### PR DESCRIPTION
**Pull request by endiliey**
## Motivation

Add a blog post talking about the plan & work for Docusaurus 2.0.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

https://deploy-preview-952--docusaurus-preview.netlify.com/blog/2018/09/11/towards-docusaurus-2

### CODE REVIEW

**Comment by endiliey** [comment]
We definitely need revision on the content 😭 / wording wise. Appreciate it if you guys could give some suggestion !! @yangshun @JoelMarcey

**Comment by endiliey** [comment]
Hmm.. i was thinking that maybe more details should be put in the actual Docusaurus 2 release post. This blog post aims to
1. Point user to RFC issue
2. Give an overview of planned v2
3. Informing user that we are working on v2, so less features/ changes on v1

Wdyt ?

Is this good for you @joelmarcey ?

**Comment by endiliey** [comment]
@yangshun added a 'frequently asked questions'. Please see it once again. 👍

**Comment by notjaril** [comment]
Just two spelling improvements:

* Howver, one thing that I'll highlight > However ...
* Crowdin for translations,so >> translations, so ...
* we do noot want to make Docusaurus better > we do not want ...

Other than those, it looks good! 👍

**Comment by yangshun** [comment]
Merging this since @JoelMarcey has proodread it too 😄

**Comment by yangshun** [comment]
Are there any other changes you want to make? If not I'll just add that line in.

**Comment by JoelMarcey** [comment]
Not at this time -- I can make any further changes if I come up with any.

**Pull request merged**
