### PR TITLE
fix(theme-classic): fix announcement bar height cutting off text

### LINKED ISSUE #7815: Announcement bar text being cut off
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Announcement bar text is being cut off on some display sizes if the announcement is long enough.

[View demo on codesandbox.](https://codesandbox.io/s/blissful-currying-nqeocf?file=/docusaurus.config.js&resolutionWidth=997&resolutionHeight=675) In this example the bug will occur at a screen size of 997px.
image

### Reproducible demo

https://codesandbox.io/s/blissful-currying-nqeocf?file=/docusaurus.config.js&resolutionWidth=997&resolutionHeight=675

### Steps to reproduce

1. Add an announcement that is sufficiently long
2. Shrink the window size down and the issue should appear when the announcement occupies more than 1 line.

### Expected behavior

The announcement bar should resize to fit the whole message.

### Actual behavior

The announcement bar is too small to fit the whole message. It clips the message vertically.

image

### Your environment

_No response_

### Self-service

- [ ] I'd be willing to fix this bug myself.

### PR DESCRIPTION
**Pull request by andrewsemchism**
## Pre-flight checklist

- [X] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [X] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [X] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Closes #7815 

### Test links

Deploy preview: https://deploy-preview-7820--docusaurus-2.netlify.app/

## Related issues/PRs

Related PR: #5430

### CODE REVIEW

**Review by slorber — CHANGES_REQUESTED** [review]
Unfortunately, this leads to unwanted side-effects 

CleanShot 2022-07-25 at 11 48 42

However, I do agree that we shouldn't need to constrain it to a fixed height, and there's probably some things that we can change in our docs sidebar layout to ensure it is possible.

**Comment by andrewsemchism** [comment]
Thanks for pointing that out. I will try to find a solution. I noticed that issue still occurs sometimes regardless of the change I made. If you visit the [docs page](https://docusaurus.io/docs/category/guides), **_scroll down just a few pixels_**, you will see the same problem.

Introduction

**Comment by slorber** [comment]
yes, apparently we have a larger problem 😅 we'll look into it

**Comment by azeek21** [comment]
#7815 states that this will fix announcement bar height cutting off the text. But no this bug still exists and it comes from this line

https://github.com/facebook/docusaurus/blob/985a64ad222694b9987d0283705703b420e01bff/packages/docusaurus-theme-classic/src/theme/AnnouncementBar/styles.module.css#L55

I still don't get why a fixed height of 30px is needed in this media query.
Sites affected by this: [AuthJs](https://authjs.dev/)
Screenshot: [Imgur link](https://imgur.com/vZLi70T) 

As far as I am concerned this can be easily fixed by removing fixed 30px height inside media query, no ?

**Comment by azeek21** [comment]
any updates on this PR ? 
affected site: [https://authjs.dev/](AuthJs)

**Pull request closed without merging**
