### PR TITLE
docs: fix example plugin implementation

### PR DESCRIPTION
**Pull request by gabrielcsapo**
## Pre-flight checklist

- [X] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Tried to run docs example and found a failure in the basic implementation

## Test Plan

N/A

### Test links

N/A

## Related issues/PRs

N/A

### CODE REVIEW

**Review by Josh-Cena — APPROVED** [review]
Thanks! Could you update the versioned docs as well?

**Comment by gabrielcsapo** [comment]
@Josh-Cena I will do that now.

**Comment by gabrielcsapo** [comment]
@Josh-Cena I have updated the versioned files.

**Comment by Josh-Cena** [comment]
Thanks

**Pull request merged**
