### PR TITLE
fix grammar

### PR DESCRIPTION
**Pull request by thadguidry**
## Motivation

improve grammar about inline SVGs

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

YES

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by slorber** [comment]
thanks ;:)

**Comment by maksnester** [comment]
@slorber @thadguidry I guess fixes like that should be applied to the next version by default. Now that typo is fixed in .63 docs, but not in .64 or next docs. 

I was just curious how do you guys handle versioned documentation fixes and found this PR.

**Comment by slorber** [comment]
@maksnester this is a merge mistake, thanks for reporting it. We generally ask the contributor to update the upstram docs, not a specific version.

I've ported the changes here: https://github.com/facebook/docusaurus/pull/3493

**Comment by thadguidry** [comment]
@slorber it's not clear enough then on the CONTRIBUTING.md file.  https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md

**Comment by slorber** [comment]
@thadguidry this doc is quite old and we should also consider that there is v1 and v2 in the same repo. We'll likely update it in the future once v2 is officially released

In the meantime, if you have ideas on how we could improve this doc, PRs are welcome

**Comment by thadguidry** [comment]
@slorber I don't know what the best context would be to put into the CONTRIBUTING.md document, but I would suggest that perhaps since v1 and v2 are in the same repo, then mention that in the document and then have someone on your team type up a separate paragraph about "Contributing to Docs for v2" which is the critical point for many using and helping test v2 at this point in time.

**Comment by slorber** [comment]
@thadguidry we are a small team (basically only me fulltime) and I should focus on shipping i18n support. If you really think something is important, submitting a PR is the most effective way. I agree this is important, but can't do a full docs and contributing docs review right now, as shipping i18n is even more important, and I'm coming back from holidays I have like 100th issues opened in my todolist :)

**Pull request merged**
