### PR TITLE
fix(module-type-aliases): fix type def for translate params

### PR DESCRIPTION
**Pull request by Josh-Cena**
## Motivation

Fix a bad typedef.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

**Comment by slorber** [comment]
🤯 what does it fix exactly?

**Comment by Josh-Cena** [comment]
1. `TranslateParam` should not contain `values` in its first param.
2. The current generic actually doesn't narrow according to the `Str` generic arg. I fixed the type in #6399 and made TS able to extract all `{}` enclosed text labels form the `message` / `children` and use them to create the `values` type.

**Comment by slorber** [comment]
oh yes I remember seeing something weird regarding the extra values

We have a test that still fails to typecheck as I'd like, let me know if you figure out how to fix it and make it fail compilation, I couldn't figure out why this happens

image

**Comment by Josh-Cena** [comment]
It's because the test files aren't checked using any tsconfig (they are excluded by our project-level tsconfigs), so they don't have access to the declaration files. The fix is probably to add another tsconfig specifically for the test files, but up to this point... there hasn't been a significant push yet. I would inspect this later.

**Pull request merged**
