### PR TITLE
docs(v2): Add Buddy to deployment doc

### PR DESCRIPTION
**Pull request by tomekpapiernik**
## Motivation

I want to show the public an option to automate their deployments with a very user-friendly tool that can be handled 100% through the UI. Setup is extremely easy and there's no `.yml` magic involved which tends to scare people away. 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

no

## Related PRs

none

### CODE REVIEW

**Comment by slorber** [comment]
Thanks 👍 Used Buddy before and liked it

**Comment by tomekpapiernik** [comment]
@slorber thanks! Shouldn't it be visible on the website now? It's not there in the preview for this PR either - just noticed that. Did I break something? "Works on my machine" :D

**Comment by slorber** [comment]
https://docusaurus.io/docs/next/deployment#triggering-deployment-with-buddy

**Comment by tomekpapiernik** [comment]
@slorber Sorry, I removed my comment bc I realized that I should be looking at the `next` version. It's all good, thanks!

**Comment by slorber** [comment]
FYI, we are going to clean up our existing Docusaurus docs deployment page in favor of a GitHub discussions category. 

This means your platform won't appear anymore on this page: https://docusaurus.io/docs/deployment

If you want your hosting / CI / CDN platform to remain documented for Docusaurus users, please submit an entry at: https://github.com/facebook/docusaurus/discussions/categories/deployment-platforms

This will be your responsibility to keep it up to date over time.

**Pull request merged**
