### PR TITLE
docs: add Overwolf to users

### PR DESCRIPTION
**Pull request by eransharv**
adding our overwolf project

## Motivation

request to Add our project to the list. We love Docusaurus! 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Related PRs

Yes - the PR for the logo SVG: #1727

### CODE REVIEW

**Comment by yangshun** [comment]
@eransharv ping in case you didn't see my reply 😄

**Comment by eransharv** [comment]
HI. 

You said, "However you need to combine the SVG from #1727 into this PR also".

How can I do that? Can you please tell me if there is any action item from my end?

**Comment by yangshun** [comment]
@eransharv Can you add that file to this branch and update the branch? The PR will be updated.

**Comment by eransharv** [comment]
@yangshun sorry for the dumb question.. but how can I do that? I tried several options and couldn't find a way to add to this PR some other commit.
Sorry for the hassle. I'm entirely new to GIT.

**Comment by eransharv** [comment]
@yangshun sorry for the dumb question. but how can I do that? I tried several options and couldn't find a way to add to this PR some other commit.
Sorry for the hassle. I'm entirely new to GIT.

**Comment by wgao19** [comment]
@eransharv you don't have to mess with the other branch. You can commit again to this branch and add the file in.

**Comment by eransharv** [comment]
@wgao19  thanks for the help! 
@yangshun I added the SVG to this PR. hopes that's good enough.

thanks.

**Pull request merged**
