### PR TITLE
docs: add Kinsta to deployment page

### PR DESCRIPTION
**Pull request by palmiak**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).

## Motivation

It adds a small guide about how to deploy Docusaurus on Kinsta Application Hosting.

### Test links

Deploy preview: https://deploy-preview-8375--docusaurus-2.netlify.app/

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Please see the big red warning at the top of the doc:

> For the same concern of up-to-datedness, we have stopped accepting PRs adding new hosting options. You can, however, publish your writeup on a separate site (e.g. your blog, or the provider's official website), and ask us to include a link to your writeup.

**Comment by palmiak** [comment]
@Josh-Cena - I just pushed the fixed version. Sorry that I missed it.

**Comment by palmiak** [comment]
I see that PR is failing, but I'm unsure if I can do something about it.

**Comment by slorber** [comment]
Thanks 👍 

Our spell-checker didn't know the word "kinsta" 😄

**Comment by palmiak** [comment]
Shame :D  
Thanks for adding it and for such a quick reaction.

**Pull request merged**
