### PR TITLE
docs(v2): wrap all plugin imports in require.resolve()

### PR DESCRIPTION
**Pull request by TomBrien**
## Motivation

(Write your motivation here.)

As per the breaking change in 2.0.0-alpha56 plugin call need to be wrapped in `require.resolve(...)`. Add this to the examples.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by slorber** [comment]
Thanks @TomBrien 

Do you mind updating as well the /docs folder? otherwise on next release your docs changes will be reverted. The `versioned_docs` folder is for already released versions, and will not be used for next releases.

**Comment by TomBrien** [comment]
My bad just hit the edit on GitHub button. Sure will move that over now

**Comment by SamChou19815** [comment]
> I think this only serves as a workaround due to a bug in the current version, and will not be necessary after we release the next alpha version is that right?. cc @SamChou19815

Yes, but I think it makes sense to make the change _only_ in alpha-56 versioned docs.

**Comment by TomBrien** [comment]
Will revert the second commit :)

**Comment by yangshun** [comment]
Thank you very much @TomBrien!

**Pull request merged**
