### PR TITLE
docs: add Tremor website to showcase page

### PR DESCRIPTION
**Pull request by skoech**
Signed-off-by: Sharon Koech <sharonkoech5147@gmail.com>

## Motivation

A few months ago, we decided to redesign our [website](https://www.tremor.rs/) using a framework that unified all of our content forms (www, docs, rfcs and courseware) under a single consolidated theme and design. After [a lot of deliberation](https://github.com/skoech/framework-comparison), Docusaurus was our clear answer! We loved it then, and we still love it now.
We would be very happy and honoured if you would consider adding our website to your showcase page, along with the other absolutely fantastic sites.
Thanks!

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

Run `npm run start`.

## Related PRs

None.

### CODE REVIEW

**Comment by slorber** [comment]
Thanks!

We'd be happy to do so

Can you send a screenshot with a little more height? This is important so that card headers are not cropped:

image

**Comment by skoech** [comment]
Ah, I see. On it!

**Comment by skoech** [comment]
How cool. Thank you so much for having us! :)

**Comment by Josh-Cena** [comment]
Thanks for the detailed writeup as well @skoech decent field research

**Comment by skoech** [comment]
Much obliged. :)

**Pull request merged**
