### PR TITLE
docs: update Kent C. Dodds Twitter avatar

### PR DESCRIPTION
**Pull request by DharsanB**
## Pre-flight checklist

- [ ] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

### CODE REVIEW

**Comment by DharsanB** [comment]
@Josh-Cena, Please verify and let me know

**Comment by Josh-Cena** [comment]
Change looks good—once the CLA status gets updated (provided you did sign it) we can merge 👍

**Comment by slorber** [comment]
having a similar problem on my newsletter landing page 😅 wonder if there's a reliably way to get a twitter avatar URL

https://thisweekinreact.com/subscribe

**Comment by Josh-Cena** [comment]
This works: https://unavatar.io/twitter/SidaChen63

**Comment by DharsanB** [comment]
> Change looks good—once the CLA status gets updated (provided you did sign it) we can merge 👍

Done @Josh-Cena

**Pull request merged**
