### PR TITLE
docs: add Blogasaurus to showcase

### PR DESCRIPTION
**Pull request by BattleOfPlassey**
## Motivation

I created a personal blog using Docusaurus 2 so I thought of adding it to the showcase section.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

No changes in code

## Related PRs

No related PR

### CODE REVIEW

**Comment by BattleOfPlassey** [comment]
@lex111 @slorber  Am i missing something here? The preview build is failing for some reason. Pls advise if some change is needed in the PR.

**Comment by Josh-Cena** [comment]
@BattleOfPlassey Check the deploy log, you should use `.png` extension instead of `.PNG`. I know it sounds too strict (and probably due to inconsiderate settings), but at least for the sake of uniformity you should change it

**Comment by BattleOfPlassey** [comment]
@Josh-Cena Thank you !!
fixed the png error.

**Review by lex111 — APPROVED** [review]

**Comment by lex111** [comment]
@BattleOfPlassey thanks!

**Pull request merged**
