### PR TITLE
chore: typo colocation -> collocation

### PR DESCRIPTION
**Pull request by nschonni**
## Motivation

(Write your motivation here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Actually, that was what @yangshun changed it to. Now I have no idea which one is more correct🧐

**Comment by nschonni** [comment]
I'm going by the previous discussion https://github.com/facebook/docusaurus/pull/6324#discussion_r783658526

**Comment by Josh-Cena** [comment]
I know, this is more of a question for @yangshun 😁

**Review by yangshun — APPROVED** [review]
Seems legit. Colocation is more for businesses. TIL and thanks :)

**Comment by slorber** [comment]
🤷‍♂️ I have never seen this written this way personally, but I've seen colocation and co-located used widely by the tech community for CSS-in-JS, state, typedefs, proptypes or GraphQL queries

https://kentcdodds.com/blog/colocation
https://egghead.io/lessons/react-lifting-and-colocating-react-state
https://relay.dev/docs/guides/compiler/#running-the-compiler

I'd rather follow what everyone else is doing

**Comment by Josh-Cena** [comment]
I had _just_ been reading this thread. https://github.com/airbnb/javascript/pull/2512 Seems some people do use `collocation`, and if the spell checker likes one to the other, I'm fine with it.

**Pull request merged**
