### PR TITLE
docs: clarify MDX version used

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

See https://github.com/facebook/docusaurus/issues/4029#issuecomment-920468413

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Preview

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by Josh-Cena** [comment]
The link still directs to v2. Shouldn't the v1 link be used?

**Comment by lex111** [comment]
Does MDX have site designed for the current v1? https://v1.mdxjs.com/ is very outdated site.

**Comment by Josh-Cena** [comment]
Hmm, this link you posted in the other issue seems good for now? https://mdx-git-renovate-babel-monorepo-mdx.vercel.app/

**Comment by lex111** [comment]
This is actually preview deploy from one of PR from mdxjs repo. I'm not sure if it  should be used for this link, but it might be worth using for MDX playground link on 26 line.

**Comment by Josh-Cena** [comment]
I see, interesting that the deploy preview link is so human readable🧐

**Pull request merged**
