### PR TITLE
feat(v2): add support for key,cert in https

### PR DESCRIPTION
**Pull request by ThakurKarthik**
## Motivation

Adding support for https with key and cert files in docusaurus

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

1.Install [mkcert](https://github.com/FiloSottile/mkcert) anywhere to create certificates for local testing
2.In the root folder of docusaurus run `mkcert localhost 127.0.0.1 ::1`. mkcert will generate two files, one is key file and other cert file for testing.Move these two files to `website` folder.
3.Run `HTTPS=true SSL_CRT_FILE=localhost+2.pem  SSL_KEY_FILE=localhost+2-key.pem yarn start`

**Note** please replace `localhost+2.pem` and `localhost+2-key.pem` with the files you will get from mkcert.

Screenshot from 2020-10-16 01-15-28
Screenshot from 2020-10-16 01-15-43
Screenshot from 2020-10-16 01-00-55

Hey @slorber @lex111 can you Please review these changes, Thanks !

Ref: #3445

### CODE REVIEW

**Review by lex111 — COMMENTED** [review]
@ThakurKarthik could you please add some docs about using this feature?

**Comment by ThakurKarthik** [comment]
Sure @lex111 , you want me to document this in the website right? I will add that !

**Comment by lex111** [comment]
@ThakurKarthik yes please, and resolve conflict too.

**Comment by slorber** [comment]
LGTM

Yeah basically we need the docs to know how to run Docusaurus on https locally so that our users know how to do it too. Basically it's adding your test plans to the docs somewhere (maybe on the start command doc?)

Need to resolve the merge conflict


I know from source issue (https://github.com/facebook/docusaurus/issues/3445) that CRA use env variables. Wonder how they made the choice of env variables VS cli options. Any idea?

**Comment by ThakurKarthik** [comment]
Hey @slorber I will add the steps to enable https in docs soon, as for your question of choice between env vs cli options, I am not that sure I tracked the original implementation in CRA https://github.com/facebook/create-react-app/pull/5845 , sadly i can't find the reasoning behind the choice and here is a comment about moving env vars to a config file https://github.com/facebook/create-react-app/pull/5845#issuecomment-580716984

**Comment by slorber** [comment]
Hi @andriijas or @alexbrazier, wonder if you can give us some insights regarding this feature? 
How did you choose between env variables, cli options or config file?

**Comment by slorber** [comment]
@ThakurKarthik do you want me to complete the PR, and write some docs? We can keep the env variables for now, that should be fine (HTTPS is already an env variable anyway)

**Comment by ThakurKarthik** [comment]
Hey @slorber sorry for delay,I can update them by today evening if you won't mind.
Thanks !

**Comment by slorber** [comment]
sure, no hurry, just wanted to be sure this pr won't become stale :)

**Comment by ThakurKarthik** [comment]
Hey @slorber @lex111 I have added docs for using https, please review it and feel free to suggest any changes !

**Comment by alexbrazier** [comment]
> Thanks @ThakurKarthik
> 
> Hi @andriijas or @alexbrazier, wonder if you can give us some insights regarding this feature?
> How did you choose between env variables, cli options or config file?

Hi @slorber, there wasn't really much of a discussion around the decision, it just happened to be how we had setup our fork of cra and it had been working well for our team for over 2 years. I think part of the original decision would have been because `HTTPS=true` was also set using an env var so it made sense to set all of the https config via an env var.

**Comment by slorber** [comment]
Thanks, LGTM, just made the docs simpler.

Thanks @alexbrazier , as we already have env.HTTPS I guess we should do the same :)

**Pull request merged**
