### PR TITLE
fix: h3 topics with Markdown formatting causes a glitch on mobile

### LINKED ISSUE #1254: h3 topics with Markdown formatting causes a glitch on mobile
## 🐛 Bug Report

Found this while investigating a Jest issue: https://github.com/facebook/jest/issues/7856
When navigating a "topics" (?) menu on a mobile screen size, clicking an h3 header that has Markdown formatting does not closes the menu. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

Note: I'm using a local Jest repository using Docusaurus 1.7.2 to reproduce this

1. Add some Markdown formatting (such as bold, italics or code) to a h3 header on a document.

2. Use a responsive website size small enough to have this UI:
issue_23_first

3. Click the vertical three dots button to see all references:
issue_23_second

4. Attempting to navigate to a h3 section formatted with Markdown will not hide the page, although it correctly redirects the URL:
issue_23_third

## Expected behavior

The open menu should have closed.

## Actual Behavior

URL changes but the menu isn't closed.
Removing the backticks from the h3 makes it function properly.
Adding other formatting such as bold and italics generate the same issue.

### PR DESCRIPTION
**Pull request by shakcho**
## Motivation

we are adding click listener on ".toc-headings" and removing toActive class if the target is "A" tag, Where in case of this issue the target is actually Code tag. 
Look at the below code.
```html
<li><a href="#docusaurus-build"><code>docusaurus-build</code></a></li>
```
Because of this "toActive" class is not getting removed.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

I have done Yarn test, and every test cases passed. 
For verification of the code, I tried the following URL  https://docusaurus.io/docs/en/commands/#docusaurus-build
and it's working as per expectation.

## Edit from maintainer:

Close #1254
Close #1485

### CODE REVIEW

**Comment by endiliey** [comment]
Deploy preview for *docusaurus-2* failed.

Built with commit 35debbc7321edd58ab4f173c28ca1e70e8a17619

https://app.netlify.com/sites/docusaurus-2/deploys/5cddb4f9b84c0a0007dc3700

**Comment by endiliey** [comment]
Related is #1254 

@yangshun you might want to take a look at it. There is a CSS proposed fix and JS proposed fix (although it still fails for me after trying it on my iphone)

**Comment by shakcho** [comment]
@endiliey @yangshun Should I changed the PR to use the CSS approach?

**Comment by endiliey** [comment]
@shakcho you can try to send another PR with another solution. We will merge and close one of it

**Comment by endiliey** [comment]
🚀 Ship it .... 

shipit

**Pull request merged**
