### PR TITLE
Add nteract project as a user

### PR DESCRIPTION
**Pull request by willingc**
## Motivation

As suggested by @yangshun in PR #888, I've submitted the nteract project as a user.

We :heart: Docusaurus.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### CODE REVIEW

**Comment by yangshun** [comment]
@willingc Thanks for the PR! Do you happen to know why the test are failing? The CI output doesn't tell me much. Could you run the test command locally and see if it passes?

**Comment by willingc** [comment]
Sorry about that @yangshun. I had an extra line feed in one of the lines. 😊

**Comment by yangshun** [comment]
Thanks for your contribution @willingc !

**Comment by JoelMarcey** [comment]
Thank you for using Docusaurus, @willingc 😄

**Pull request merged**
