### PR TITLE
test(e2e): dogfood Yarn with enableGlobalCache

### PR DESCRIPTION
**Pull request by ylemkimon**
## Motivation
Test for #3324.

~I'm not sure this is worth testing in the e2e test.~

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?
Yes

## Test Plan
Check GitHub Actions pass.

## Related PRs
N/A

### CODE REVIEW

**Comment by slorber** [comment]
LGTM, seems to be passing.
Do you plan to include more commits?

**Comment by ylemkimon** [comment]
@slorber No, but I'm not sure it's worth adding these configurations. Using the official Yarn release and `enableGlobalCache: false` would be more common.

**Comment by slorber** [comment]
Is it more likely to fail with this setting = true? Does it have any drawback?

I'm in favor to dogfood advanced options in our own CI, to ensure it keeps working over time, even if it's kind of useless

**Comment by ylemkimon** [comment]
@slorber 
> Is it more likely to fail with this setting = true?

Yes, due to the limitation of PnP. This would've failed with Yarn<2.3.0.

> Does it have any drawback?

I cannot think of any drawbacks for now, as CI currently doesn't use cache. However if the cache were to be added, extra configuration might be needed.

> I'm in favor to dogfood advanced options in our own CI, to ensure it keeps working over time, even if it's kind of useless

I'll mark this PR ready for review. Thank you!

**Comment by slorber** [comment]
thanks, seems safe to merge :)

**Pull request merged**
