### PR TITLE
fix(theme-common): docs breadcrumbs not working with baseUrl

### PR DESCRIPTION
**Pull request by slorber**
## Motivation

fix bug reported here: https://github.com/facebook/docusaurus/pull/6749#issuecomment-1051471026

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

yes

## Test Plan

unit tests

### CODE REVIEW

**Comment by pranabdas** [comment]
@slorber So the home icon in breadcrumbs is not supposed to show up for docs-only sites? The breadcrumb looks bit empty in this case if there is only one item. Is it possible to have home icon in this case linking to `logo.href`? Thank you.

**Comment by slorber** [comment]
yes it's showing for docs-only sites if there's a doc with slug: /

For breadcrumbs improvements, I suggest giving your opinion here: https://github.com/facebook/docusaurus/discussions/6786

I don't know if `logo.href` is such a good fallback.

Maybe it would be better to always ensure/force that a docs site has a home 🤷‍♂️

**Comment by pranabdas** [comment]
Maybe there is a bug then, the home icon is not showing up in the breadcrumb in docs-only mode. Steps to reproduce: 
1. Create a new site: `npx create-docusaurus@latest website classic` 
3. `cd website`
2. Update to latest canary: `npm i --save-exact @docusaurus/core@canary @docusaurus/preset-classic@canary`
4. Remove index page `rm src/pages/index.js`
5. Add `routeBasePath` for docs in `docusaurus.config.js`:
```
module.exports = {
  // ...
  presets: [
    '@docusaurus/preset-classic',
    {
      docs: {
        routeBasePath: '/', 
      },
    },
  ],
};
```
6. Add slug to `docs/intro.md`:
```
slug: /
```
7. `npm start` and this is what I see:
Screenshot 2022-03-03 at 5 47 37 PM

**Comment by Josh-Cena** [comment]
Indeed, it's because the version route that the doc plugin doesn't specify `exact: true` or `false` so it isn't recognized as a home parent route... @slorber Is it intended to only match `exact === false`?

**Comment by slorber** [comment]
hmmm weird, I tested this locally and it worked 😅 

Will fix this asap

**Comment by slorber** [comment]
https://github.com/facebook/docusaurus/pull/6824

**Pull request merged**
