### PR TITLE
feat(v2): add pt-PT translations for docusaurus-theme-classic

### PR DESCRIPTION
**Pull request by tiago-rr**
## Motivation

Following this [comment ](https://github.com/facebook/docusaurus/pull/4525#issuecomment-809456499) asking if it was possible to also have the translation for pt-PT translations, I wanted to help.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Since I only added a new translation JSON, there is no test plan, the existing tests should do fine.

## Related PRs

None

### CODE REVIEW

**Comment by slorber** [comment]
thanks!

**Comment by slorber** [comment]
Was wondering, if a user choose locale = "pt", should we apply PT or BR translations by default?

**Comment by tiago-rr** [comment]
That is actually a good question! If you think with maths, it would probably be better to use pt-BR, since there are waaaay more brazilian people than portuguese people, however pt-PT is the "original" ahahah 

If I had to choose only one, maybe pt-BR, since it more probable that someone would brazilian rather than portuguese.

**Comment by slorber** [comment]
I see
But if you want a Docusaurus site in Brazilian, would you try using "pt" instead of using directly "pt-BR"?

Maybe we should have `pt.json` (for `pt` + `pt-PT`) and `pt-BR.json`?

**Comment by tiago-rr** [comment]
Yeah, that's probably the best approach, since I believe most brazilian people are more used to seeing "pt-BR" than simply "pt".

**Comment by slorber** [comment]
Apparently, it's pt-BR :)

https://twitter.com/sebastienlorber/status/1376825837417340931

image

**Comment by tiago-rr** [comment]
Fair enough then, we learn things every day ahahah

**Comment by slorber** [comment]
"pt" -> "pt-BR"  implemented in https://github.com/facebook/docusaurus/pull/4581

**Pull request merged**
