### PR TITLE
feat(logger): new "url" format, add double quotes around paths

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

The paths in a command output are better placed in quotes, they were correctly identified as paths. For example, if there is a "dot" at the end of line with path, VS Code will not find that path if you click by it from output:

```
[INFO] 158 translations will be written at i18n/fr/code.json.
[INFO] 6 translations will be written at i18n/fr/docusaurus-theme-classic/navbar.json.
```

image

Also, quoted paths  make it easier to copy-pasting from terminal, for example currently when trying to copy the path below, a "dot" char will also be selected:

image

After:

image

## Test Plan

Try to run cli command contains paths in the output, eg `yarn run write-translations -- --locale fr`

### CODE REVIEW

**Comment by lex111** [comment]
@Josh-Cena perhaps we should explicitly separate paths and links in the logger by introducing a new `link` formatter, what do you think about this?

**Comment by Josh-Cena** [comment]
I also thought about that. There seems to be libs that support actual URL formatting; do you want to try one out?

**Comment by lex111** [comment]
Yes, but I don't really know what kind of libs you mean. Do we still leave the current `path` formatter for formatting links or do we create a new one specifically for them?

**Comment by Josh-Cena** [comment]
Oh yeah, about the `link` formatter, I definitely think we should. `url` sounds like a better name

**Comment by lex111** [comment]
I remember trying to use `terminal-link` once, but it didn't work for me either.

> Are HTTPS URLs directly clickable even when there's a trailing period?

Yes, the current issue relates to paths only.

**Review by Josh-Cena — APPROVED** [review]
Thanks!

**Pull request merged**
