### PR TITLE
style: UI improvements to searchbar

### PR DESCRIPTION
**Pull request by alkshendra**
## Motivation

Wanted to make this already awesome project a lil better! 🍺

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes!

## Test Plan

1. Open the application in chrome/firefox and reduce the browser width
2. Type anything in the search bar
3. Resize to smaller sizes and test 

GIFs:
*Tablet sizes*

Before:

After:

*Mobile sizes*

Before:

After:

### CODE REVIEW

**Comment by endiliey** [comment]
Thanks a lot @alkshendra 

shipped

**Comment by Haroenv** [comment]
I like it! there's a little too much padding at the bottom of the logo IMO, but could be fixed in another PR

**Comment by endiliey** [comment]
Kinda true. It seems like a "good first issue". Do you mind helping to file an issue for that ? A PR is fine too, but we'd love getting more contributors 😈

**Comment by alkshendra** [comment]
@Haroenv @endiliey  Actually, that extra padding issue has been fixed in this PR, I had recorded the GIFs before fixing that! 😅

Here's the fix LOC from my PR:

```
.navigationSlider .slidingNav .navSearchWrapper .algolia-docsearch-footer a {
  height: auto;
}
```

**Pull request merged**
