### PR TITLE
feat(v2): allow to use array of files in customCss field

### PR DESCRIPTION
**Pull request by Simek**
## Motivation

This small PR fixes the issue with server build when array of files was specified in `customCss` field in the theme classic preset configuration.

CC @slorber 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Successful server build of React Native website with multiple files in `customCss`.

## Related PRs

* https://github.com/react-native-website-migration/react-native-website/issues/23

### CODE REVIEW

**Comment by lex111** [comment]
@Simek your PR resolves #3416?

**Comment by Simek** [comment]
@lex111 Yup, this PR should fix the mentioned by you issue too, but I have not added the Joi validator as Sebastien suggested.

**Comment by lex111** [comment]
@Simek will you do that? Also we need to update the docs.

**Comment by Simek** [comment]
@lex111 I'm not sure how to do this correctly, since `customCss` field is a part of `presets.theme` config, not `themeConfig`. 

Also it looks like an additional schema will be needed in `docusaurus-utils-validation`, but to be honest I'm not that familiar with Joi.

**Comment by lex111** [comment]
I'm not very good at this either, alright, so let's wait until Sebastien comes back from vacation.

**Comment by anshulrgoyal** [comment]
For Joi validation add it in the classic theme option validation.

**Comment by slorber** [comment]
Hey, I've added the validation. Also fixed a bug because using concat instead of push was no-op :)

**Pull request merged**
