### PR TITLE
docs(v2): fix migration command

### PR DESCRIPTION
**Pull request by BogdanDor**
## Motivation
Fix incorrect command.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?
Yes.

## Test Plan

Go to https://v2.docusaurus.io/docs/migrating-from-v1-to-v2/#migration-command.
This section contains incorrect command.

### CODE REVIEW

**Comment by teikjun** [comment]
@BogdanDor thanks for fixing it! I've made the same changes for the earlier versions in PR #3251

**Comment by slorber** [comment]
Thanks, but not needed anymore :)

**Comment by teikjun** [comment]
@slorber I think this PR is still needed. I assumed that this PR would be merged, so I did not make the same changes for the latest docs in #3251. Sorry for the confusion 😅

**Comment by slorber** [comment]
ah :) ok

**Pull request merged**
