### PR TITLE
chore: bump npm-to-yarn

### PR DESCRIPTION
**Pull request by nebrelbug**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

I'm a maintainer of https://npmjs.com/package/npm-to-yarn, which is used by `docusaurus-remark-plugin-npm2yarn`.

Previously, `npm-to-yarn` didn't work correctly with NodeNext module resolution. The newest version fixes that.

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

## Related issues/PRs

See https://github.com/nebrelbug/npm-to-yarn/issues/33

### CODE REVIEW

**Comment by nebrelbug** [comment]
Not sure if I should push `yarn.lock` or not.

**Comment by Josh-Cena** [comment]
> Not sure if I should push `yarn.lock` or not.

Yes, please

**Comment by nebrelbug** [comment]
@Josh-Cena just pushed it.

**Comment by armano2** [comment]
fixes #5861

**Comment by nebrelbug** [comment]
I just updated the PR to require `npm-to-yarn@2.0.0`, which includes https://github.com/nebrelbug/npm-to-yarn/pull/36 as well as https://github.com/nebrelbug/npm-to-yarn/pull/37

**Comment by slorber** [comment]
Closing in favor of https://github.com/facebook/docusaurus/pull/8690

**Pull request closed without merging**
