### PR TITLE
fix(v2): remove extra top margin of tab item

### LINKED ISSUE #2738: Wrong margin-top in inactive tabs
## 🐛 Bug Report

Right now, all tabs of a tabbar (excluding first one) are receiving a margin-top of 0.25rem, from Infima `markdown.css` file. This makes tabs uneven.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Go to https://v2.docusaurus.io/docs/installation#running-the-development-server
2. Inspect **Yarn** tab

## Expected behavior

To tabs do not have a margin-top.

## Actual Behavior

Tabs from a tabbar (except first one) have a margin-top.

Screen Shot 2020-05-12 at 07 31 46

## Your Environment

v2.0.0.-alpha54 online docs

## Reproducible Demo

Go to https://v2.docusaurus.io/docs/markdown-features#tabs

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Resolve #2738.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

| Before   | After    |
| -------- | -------- |
| image | image |

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by lex111** [comment]
Maybe it will but I am not sure about that.

**Comment by yangshun** [comment]
A CSS reset won't help here because `.markdown li+li` is the class responsible for that margin. Maybe we should just use divs instead of ul/li and add aria roles to preserve the semantic-ness.

**Comment by lex111** [comment]
@yangshun will you add reset styles to Infima today?

**Comment by yangshun** [comment]
Nope, not today

**Comment by lex111** [comment]
But what about the new Docusaurus release tomorrow? I mean, should we release a new version of Infima now in order to apply the new changes in the upcoming version of Docusaurus?

**Comment by yangshun** [comment]
Yes I wanna fix some issue first - docs h2 size same as docs title on mobile

**Comment by lex111** [comment]
Alright, I hope you fix it asap.

**Pull request merged**
