### PR TITLE
fix: properly sanitize HTML tags

### PR DESCRIPTION
**Pull request by Josh-Cena**
## Motivation

Clear CodeQL errors. The current code doesn't handle HTML tags 100% correctly either, because a `<` has to be followed by a latin character to be considered an HTML tag.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

CI

### CODE REVIEW

**Review by lex111 — COMMENTED** [review]
No need "fix" this, there is no security risk here, it is false positive from CodeQL.

**Comment by Josh-Cena** [comment]
Yeah, part of the reason is because the sanitization is incorrect anyways. I'll try a few more times and if I don't find a way to both clear the error and make it work gracefully I'm going to close this

**Comment by lex111** [comment]
Alright, but it's not worth the effort now. Don't want to complicate this code, introducing extra regexs, so that just CI is was successful.

**Comment by Josh-Cena** [comment]
Going to close this, and probably follow up by a new excerpt creation method.

**Pull request closed without merging**
