### PR TITLE
fix(v2): make search bar not lose focus after clicking on it after initial load

### LINKED ISSUE #2175: bug(v2): search bar loses focus after clicking on it after initial load
## 🐛 Bug Report

On a side note, loading the JS + style when user clicks on the search bar causes a re-render and the focus is lost. It has happened to me a few times on laptop but I didn't know why. But because of this PR I tried the search bar on mobile and it became very obvious what is happening.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Load page (load on mobile to make it even more obvious)
1. Click on search bar
1. See that focus is lost and you have to reclick on the search bar

## Expected behavior

Search bar stays in focus.

## Actual Behavior

Search bar loses focus.

demo)

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

### PR DESCRIPTION
**Pull request by yangshun**
## Motivation

Fixes #2175 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

1. Load Netlify preview (try on mobile too)
1. Click on the search bar
1. See that it doesn't lose focus

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by lex111** [comment]
Hmm, but I can **not** reproduce this issue on the current version of v2.docusaurus.io. :thinking: 

Record from https://v2.docusaurus.io/ (with cleared cache)

screencast-nimbus-capture-2020 01 03-00_25_55

I also did not identify this issue on my phone (Android).

**Comment by yangshun** [comment]
On website it's harder to reproduce because of `onMouseOver`. On mobile it's much easier to reproduce.

**Comment by yangshun** [comment]
Unfortunately this PR doesn't fix the issue on mobile (I'll have to debug why).

**Comment by yangshun** [comment]
I've updated #2175 with the screen recording. See that the cursor was only on the input field for a while and it's gone.

**Comment by lex111** [comment]
Yeah, now I see, but in preview this issue also remains.

**Pull request merged**
