### PR TITLE
docs(v2): showcase user Clutch

### PR DESCRIPTION
**Pull request by danielhochman**
## Motivation

Adding another example of a Docusaurus v2 user to the showcase.

https://clutch.sh

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Validate CI + Preview

## Related PRs

N/A

### CODE REVIEW

**Comment by slorber** [comment]
thanks

**Comment by slorber** [comment]
will have to wait for the "CLA signed" bot before merging this PR :)

**Comment by danielhochman** [comment]
thanks @slorber! we (Lyft) have an existing corp CLA signed, working to get myself added to it.

**Comment by slorber** [comment]
great thanks,  not sure how this corp CLA works but as long as the bot says cla signed I can merge ^^

**Comment by slorber** [comment]
wonder if you shouldn't sign both individually and with the corp

@JoelMarcey any idea?

**Pull request merged**
