### PR TITLE
fix(ideal-image): do not pass down `img` prop

### PR DESCRIPTION
**Pull request by lex111**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [x] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Screenshot below speaks for itself:

image

## Test Plan

Preview

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

### CODE REVIEW

**Comment by Josh-Cena** [comment]
In this case we don't need to destructure `className` or `alt` since they aren't overridden

**Comment by slorber** [comment]
LGTM

Couldn't reproduce the extra img attribute on prod, is this only happening in dev mode?

**Comment by Josh-Cena** [comment]
We only use a plain `` tag in dev. In prod the actual ideal image component takes care of the prop.

**Review by Josh-Cena — APPROVED** [review]

**Comment by lex111** [comment]
> We only use a plain  tag in dev.

This is also used in the production site see https://github.com/facebook/docusaurus/blob/97c9710ce332cfa722fcec31f84fbdbc4a275fd0/website/src/pages/showcase/_components/ShowcaseCard/index.tsx#L64

**Comment by slorber** [comment]
ah I see, only the ones with a serverless image, can repro now thanks 👍 

CleanShot 2022-10-26 at 20 04 28@2x

**Pull request merged**
