### PR TITLE
feat(core): throw error when official docusaurus dependencies use different versions

### PR DESCRIPTION
**Pull request by JorensM**
## Pre-flight checklist
  - [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
  - [x] If this is a code change: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
  - [ ] If this is a new API or substantial change: the PR has an accompanying issue (closes https://github.com/facebook/docusaurus/issues/9342 ) and the maintainers have approved on my working plan.
## Related issues/PRs

https://github.com/facebook/docusaurus/issues/9342

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Please, check for existing PRs before sending one. https://github.com/facebook/docusaurus/pull/9380

**Comment by Josh-Cena** [comment]
Sorry, I see you actually claimed the issue first!

**Comment by Josh-Cena** [comment]
Could you respect the PR template? Most importantly it asks you to link to the issue to intend to address because it will be automatically closed if you include text like "closes #xxxx".

**Comment by JorensM** [comment]
@Josh-Cena Thanks for noticing haha. But if you think the other PR is better in some way, you can merge that one. Also I was using Gitpod to make this PR, and I think there should've been some extra info in the PR description that I should've added like a checklist.

**Comment by JorensM** [comment]
@Josh-Cena The tests seem to have failed, but I'm not sure why. Could you take a look and explain why they're not passing?

**Comment by Josh-Cena** [comment]
The test logs are public and you can click on them. For example: https://github.com/facebook/docusaurus/actions/runs/6445635746/job/17499918105#step:5:1

The reason is because we have a test that expects mismatching plugins to log a message but run completely nontheless, while it now throws an error. You may take inspiration from the other PR to modify the test.

**Comment by JorensM** [comment]
@Josh-Cena Thanks for explaining! I updated the test

**Comment by slorber** [comment]
Thanks 👍

**Pull request merged**
