### PR TITLE
chore: upgrade to Husky 7

### PR DESCRIPTION
**Pull request by nschonni**
## Motivation

Newer husky changed the need moved the post-install to `prepare` script, so a few other packages could now be dropped

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Thank you! As soon as the CLA check passes we can merge.

**Review by Josh-Cena — APPROVED** [review]
Thank you! As soon as the CLA check passes we can merge.

**Comment by nschonni** [comment]
I signed it, so the bot is probably just sneaker-netting it somewhere

**Comment by Josh-Cena** [comment]
I have a question: last time I investigated, it seems `prepare` is executed at the end of virtually every script. However, it seems we currently don't install husky during CI (hence `is-ci || husky install`). Is there any reason for removing that check?

Husky is now installed for CI. Compare:
https://github.com/facebook/docusaurus/runs/4758213712?check_suite_focus=true
https://github.com/facebook/docusaurus/runs/4757919573?check_suite_focus=true

**Comment by Josh-Cena** [comment]
Yeah, it can take a while for the CLA check to come through, no worries😉

**Comment by nschonni** [comment]
Looks like they do still talk about it in https://typicode.github.io/husky/#/?id=disable-husky-in-cidocker. I thought it fully wasn't needed because they had dropped the old env variables to skip the install.
I can add it back if you want

**Comment by Josh-Cena** [comment]
I have no idea why we had that check in the first place since we don't git commit in CI, but I'm fine with removing it since it probably only saves a few seconds of installation. Any value you can see in not installing for CI?

**Comment by nschonni** [comment]
Not really. I could see it maybe tripping up on repos that use semantic-relaese plugins and commitlint, but I don't think it should matter here

**Comment by Josh-Cena** [comment]
Okay, let's go!

**Pull request merged**
