### PR TITLE
Fix  tags

### PR DESCRIPTION
**Pull request by redhat123456**

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Already fixed. Please don't open duplicate PRs. I hope this is a mistake.

**Comment by redhat123456** [comment]
额，这并不是一个错误，我想修改一下Tag，我们的网站不是个人网站是一个团体网站

**Comment by redhat123456** [comment]
😂

**Comment by Josh-Cena** [comment]
It's "personal" as opposed to "product"/"company"/"commercial" etc. We don't have a dedicated "private organization" tag for now, so "personal" is the way to go for now :P

**Comment by redhat123456** [comment]
好吧，我懂了

**Pull request closed without merging**
