### PR TITLE
fix(v2): doc path special char (space or other) should lead to a valid slug

### PR DESCRIPTION
**Pull request by slorber**
## Motivation

Fixes https://github.com/facebook/docusaurus/issues/3223

## Test Plan

tests

### CODE REVIEW

**Comment by banli17** [comment]
Error: Unable to resolve valid document slug. Maybe your slug frontmatter is incorrect? Doc id=node原理与解析 / dirName=node / frontmatterSlug=undefined => bad result slug=/node/node原理与解析

**Comment by slorber** [comment]
Hi @banli17 

Can you open another issue for that?

I don't know much about chars like 原理与解析, are theese valid pathname characters? What do you expect the slug to be according to this id/filename?

As an escape hatch  you can write your own slug with the slug frontmatter

**Comment by slorber** [comment]
Note @banli17 this PR is not yet released. Please tell me if the upcoming release does not fix your issue, but I think it will.

Probably releasing next week

**Comment by MaHe666** [comment]
There is a bug when I use character #

**Pull request merged**
