### PR TITLE
fix(v2): update postcss to 8.x and adapt custom plugins

### LINKED ISSUE #4378: [v2.0.0-alpha.71] Error: PostCSS plugin autoprefixer requires PostCSS 8.
## 🐛 Bug Report

I upgraded our internal documentation site to v2.0.0-alpha.71 (from alpha.69) and started receiving several errors along the lines of:

```
./node_modules/@docusaurus/core/lib/client/nprogress.css
Error: PostCSS plugin autoprefixer requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
 @ ./node_modules/@docusaurus/core/lib/client/PendingNavigation.js 6:261-285
 @ ./node_modules/@docusaurus/core/lib/client/App.js
 @ ./node_modules/@docusaurus/core/lib/client/clientEntry.js
 @ multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./node_modules/@docusaurus/core/lib/client/clientEntry.js./node_modules/@docusaurus/core/lib/client/baseUrlIssueBanner/styles.module.css
...
```

I _believe_ it's related to the upgrade to `autoprefixer@10` from #4355 (as `autoprefixer@10` requires postcss 8). Checking my package-lock.json's (I run a similar monorepo to this official docusaurus monorepo) `@docusaurus/core` correctly pulls in `autoprefixer@10` and `postcss@8`. However it looks like `@docusaurus/cssnano-preset` and `@docusaurus/theme-classic` all want `postcss@7`

I _think_ the solution is to coordinate the postcss upgrades across the other packages e.g. https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-cssnano-preset/package.json#L17

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

I believe part of my issue is I'm using `npm` and _not_ `yarn`, so it might be possible to reproduce by setting up a Docusaurus website using npm. I don't have time _right now_ to build a reproduction use case.

## Expected behavior

Clean build.

## Actual Behavior

Build errors.

## Your Environment

- Public source code: **n/a**
- Public site url: **n/a**
- Docusaurus version used: **2.0.0-alpha.71**
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): **node 12.18.2, npm 6.14.11, lerna 3.22.1**
- Operating system and version (desktop or mobile): **macOS 11.2.3**

## Reproducible Demo

n/a, see above "To Reproduce"

### PR DESCRIPTION
**Pull request by armano2**
## Motivation

Update postcss and all packages that depends on it to version 8. 
this change is applied only to v2

This PR is not finished yet as its currently blocked by 
- [x] postcss-preset-env - csstools/postcss-preset-env#191 - removed #4506
- [ ] stylelint - https://github.com/stylelint/stylelint/issues/4942

```
=> Found "postcss@7.0.35"
info Has been hoisted to "postcss"
info Reasons this module exists
   - "workspace-aggregator-3f5d2bd0-33dc-4456-980d-55f4af3e0882" depends on it
   - Hoisted from "_project_#docusaurus#postcss"
   - Hoisted from "_project_#stylelint#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#postcss"
   - Hoisted from "_project_#stylelint#postcss-less#postcss"
   - Hoisted from "_project_#stylelint#sugarss#postcss"
   - Hoisted from "_project_#stylelint#postcss-sass#postcss"
   - Hoisted from "_project_#stylelint#postcss-safe-parser#postcss"
   - Hoisted from "_project_#@docusaurus#migrate#@mapbox#hast-util-to-jsx#postcss"
   - Hoisted from "_project_#docusaurus#autoprefixer#postcss"
   - Hoisted from "_project_#stylelint#autoprefixer#postcss"
   - Hoisted from "_project_#stylelint#postcss-scss#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss"
   - Hoisted from "_project_#@docusaurus#migrate#@mapbox#hast-util-to-jsx#postcss-js#postcss"
   - Hoisted from "_project_#netlify-cli#precinct#detective-postcss#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#cssnano-util-raw-cache#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-colormin#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-convert-values#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-discard-comments#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-discard-duplicates#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-discard-empty#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-discard-overridden#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-merge-longhand#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-merge-rules#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-minify-font-values#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-minify-gradients#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-minify-params#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-minify-selectors#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-normalize-charset#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-normalize-display-values#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-normalize-positions#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-normalize-repeat-style#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-normalize-string#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-normalize-timing-functions#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-normalize-unicode#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-normalize-url#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-normalize-whitespace#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-ordered-values#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-reduce-initial#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-reduce-transforms#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-svgo#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-unique-selectors#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#css-declaration-sorter#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-calc#postcss"
   - Hoisted from "_project_#docusaurus#cssnano#cssnano-preset-default#postcss-merge-longhand#stylehacks#postcss"
info Disk size without dependencies: "332KB"
info Disk size with unique dependencies: "1.29MB"
info Disk size with transitive dependencies: "1.41MB"
info Number of shared dependencies: 7
=> Found "@docusaurus/cssnano-preset#postcss@8.2.8"
info This module exists because "_project_#@docusaurus#cssnano-preset" depends on it.
=> Found "@docusaurus/theme-classic#postcss@8.2.8"
info This module exists because "_project_#@docusaurus#theme-classic" depends on it.
=> Found "@docusaurus/core#postcss@8.2.8"
info This module exists because "_project_#@docusaurus#core" depends on it.
=> Found "rtlcss#postcss@8.2.8"
info This module exists because "_project_#@docusaurus#theme-classic#rtlcss" depends on it.
=> Found "css-loader#postcss@8.2.8"
info This module exists because "_project_#@docusaurus#core#css-loader" depends on it.
```

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

yes

## Test Plan

validate if new plugin is working by creating rtl version in preview
check if styles still work correctly

### CODE REVIEW

**Comment by ludofischer** [comment]
Have you considered getting rid of `preset-env`? I could be wrong, but I have the impression that nowadays only IE11 needs most of the `preset-env` transforms. I could not find in the docs what browsers Docusaurus targets, but it is possible that it does not actually use most of the transforms any more.

**Comment by lex111** [comment]
@ludofischer yep, we don't actually support IE11, so previously I [replaced postcss-preset-env with autoprefixer](https://github.com/facebook/docusaurus/pull/4355/files#diff-0c33a9be9b9aca4b4536266cc9c2b8db8131f03a7bc2cec8c5ccf27ea63cbc82). So if preset-env is not needed for CSS optimization (in advanced preset), then we can get rid of it, I guess.

**Comment by ludofischer** [comment]
>  So if preset-env is not needed for CSS optimization (in advanced preset), then we can get rid of it, I guess.
Looking at the list of plugins in `preset-env`, I see only support for CSS features, no optimizations. I am in favor of getting rid of it, then this pull request won't be blocked any more.

**Comment by ludofischer** [comment]
>  So if preset-env is not needed for CSS optimization (in advanced preset), then we can get rid of it, I guess.
Looking at the list of plugins in `preset-env`, I see only support for CSS features, no optimizations. I am in favor of getting rid of it, then this pull request won't be blocked any more.

**Comment by armano2** [comment]
there seem to be an issue with a build or github 

image


https://github.com/facebook/docusaurus/pull/4404/checks?check_run_id=2174386786

**Comment by armano2** [comment]
postponed until #4089 is merged

**Comment by slorber** [comment]
@armano2 going to merge the webpack5 migration soon early next week, and would like to have postcss8 asap once it's merged, do you want to re-open your PR next week or I do it myself based on your suggestions?

**Comment by slorber** [comment]
Nevermind, actually had to support postcss8 in https://github.com/facebook/docusaurus/pull/4089

**Pull request closed without merging**
