### PR TITLE
docs(v2): add taro to users

### PR DESCRIPTION
**Pull request by honlyHuang**
## Motivation

Showcasing a open source project that uses docusaurus v2 for documentation

### CODE REVIEW

**Review by lex111 — COMMENTED** [review]
Hi @honlyHuang, please sign the CLA, otherwise we unable to merge your PR.

**Review by lex111 — APPROVED** [review]
:+1:

**Comment by lex111** [comment]
@honlyHuang thanks! BTW you are using an outdated version of Docusaurus, we recommend that you upgrade to stable latest one.

**Comment by honlyHuang** [comment]
> @honlyHuang thanks! BTW you are using an outdated version of Docusaurus, we recommend that you upgrade to stable latest one.

Thank you very much, we have upgraded.

**Pull request merged**
